# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RX007SDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RX007SDK

  target 'RX007SDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RX007SDKUITests' do
    # Pods for testing
  end

end
