platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'



##工作台名称
workspace 'RXLBSKit.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    pod 'AMapSearch'
    pod 'AMapLocation'

end

##SDK
target 'RXLBSKit' do
    ##项目在工作台下的目录名称
    project 'RXLBSKit.xcodeproj'

    commonPods
end

target 'RXLBSKitDemo' do
    ##项目在工作台下的目录名称
    project 'RXLBSKitDemo/RXLBSKitDemo.xcodeproj'
    
#    use_frameworks!

    commonPods
end

