plugins {
    id 'com.android.library'
}
project.group 'com.ruixue'
apply from: "${rootDir}/maven.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        buildConfigField("String", "BUILD_TIME", "\"${getTimestamp()}\"")
        buildConfigField("String", "COMMIT_ID", "\"${getGitCommit()}\"")
    }

    buildTypes {
        release {
            aaptOptions {
                ignoreAssetsPattern '!supplierconfig.json:'
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        packagingAAR(project, android)
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

}

dependencies {
    // common:游戏高光时刻服务基础SDK，必须集成
    api 'com.huawei.game.replay:common:14.1.1.301'
    // replayrecord:游戏高光时刻服务录屏模块，实现录制视频功能时集成（可选）
    api 'com.huawei.game.replay:replayrecord:14.1.1.301'
    // replaytemplate:游戏高光时刻服务模板模块，实现使用模板导出视频功能时集成（可选）
    api 'com.huawei.game.replay:replaytemplate:14.1.1.301'

    api project(path: ':rxsdk_base')
}