platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXAdjustSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    pod 'Adjust'

end

target 'RXAdjustSDKDemo' do
  project 'RXAdjustSDKDemo/RXAdjustSDKDemo.xcodeproj'
  commonPods
end



target 'RXAdjustSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'RXAdjustSDK.xcodeproj'

  commonPods

end
