platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXUniPinSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
#    pod 'RXSDK_Pure'
    pod 'RXLanguageKit'
    pod 'RXPublicToolKit'
end

target 'RXUniPinSDKDemo' do
  project 'RXUniPinSDKDemo/RXUniPinSDKDemo.xcodeproj'
  commonPods
end

target 'RXUniPinSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'RXUniPinSDK.xcodeproj'

  commonPods

end
