# 瑞雪 SDK Unity 接入流程指南
# Generated by MCP

# ==================== 完整接入步骤 ====================
guide: |
  ## 瑞雪 SDK Unity 接入流程

  ### 第一步：安装 SDK

  #### 方式 A：UPM 安装（推荐）
  1. 打开 Packages/manifest.json
  2. 添加 scopedRegistries 和依赖：
     ```json
     {
       "scopedRegistries": [
         {
           "name": "RuiXue SDK",
           "url": "http://60.205.123.114:4873",
           "scopes": ["com.ruixue"]
         }
       ],
       "dependencies": {
         "com.ruixue.unitysdk.base": "{{.Version}}",
         "com.ruixue.unitysdk.share": "{{.Version}}",
         "com.ruixue.unitysdk.login": "{{.Version}}",
         "com.ruixue.unitysdk.pay": "{{.Version}}"
       }
     }
     ```

  #### 方式 B：.unitypackage 安装
  1. 获取 RuiXueSDK.unitypackage 文件
  2. Unity 菜单：Assets → Import Package → Custom Package...
  3. 选择文件并导入

  ### 第二步：初始化 SDK
  ```csharp
  using RuiXue;

  var config = new RXSdkInitConfig
  {
      cpId = "your_cpid",
      productId = "your_product_id",
      channelId = "your_channel_id",
      baseUrlList = new List<string> { "https://api1.ruixueyun.com" }
  };

  RXSDK.Initialize(config, result =>
  {
      if (result.IsSuccess) Debug.Log("初始化成功");
      else Debug.LogError("初始化失败: " + result.Error);
  });
  ```

  ### 第三步：设置全局回调
  ```csharp
  RuiXueSdk.SetSdkCallback(
      publicDelegate: (int type, string jsonDicData) => { Debug.Log($"事件: {type}, {jsonDicData}"); },
      onLogout: (code, msg) => { /* 处理登出 */ },
      onSwitchAccount: (code, data) => { return true; }
  );
  ```

  ### 第四步：接入登录
  ```csharp
  using RuiXue.Login;

  var loginConfig = new LoginConfig { loginType = LoginMethod.Guest };
  RXSDK.Login(loginConfig, result =>
  {
      if (result.IsSuccess) Debug.Log("登录成功: " + result.Data);
      else Debug.LogError("登录失败: " + result.Error);
  });
  ```

  ### 第五步：接入支付（按需）
  ```csharp
  var payParams = new Dictionary<string, object>
  {
      { "goods_tag", "diamond_100" },
      { "trade_no", System.Guid.NewGuid().ToString() },
      { "amount", 100 }
  };
  RXSDK.Pay(payParams, result => { /* 处理支付结果 */ });
  ```

  ### 第六步：打包配置
  - **Android**：Player Settings → Minimum API Level 21，建议 IL2CPP
  - **iOS**：Player Settings → Target minimum iOS Version 11.0，架构 ARM64

  ### 接入检查清单
  - [ ] SDK 安装完成（UPM 或 .unitypackage）
  - [ ] 初始化代码已添加到游戏启动场景
  - [ ] 全局回调已配置（登出、切换账号）
  - [ ] 登录功能已接入
  - [ ] 支付功能已接入（如需要）
  - [ ] Android/iOS 平台配置已完成
  - [ ] 真机测试通过
