# 瑞雪 SDK Unity Android 原生依赖接入
# Generated by MCP

summary: |
  本功能用于 Unity Android 完整工程配置，包括 API Level、Manifest、UnityPlayerActivity 生命周期、Gradle 属性、Maven 仓库、原生依赖和 Proguard。

inputs:
  workspacePath: "{{.WorkspacePath}}"
  applicationId: "{{.ApplicationID}}"
  region: "{{.Region}}"
  channel: "{{.Channel}}"
  androidVersion: "{{.AndroidVersion}}"
  components:
{{range .Components}}
    - "{{.}}"
{{else}}
    []
{{end}}
  pushPlatforms:
{{range .PushPlatforms}}
    - "{{.}}"
{{else}}
    []
{{end}}

player_settings:
  - "Minimum API Level: Android 5.1 / API 22"
  - "Target API Level: Android 12.0 / API 31"
  - "勾选 Player Settings > Publishing Settings > Custom Main Manifest"
  - "勾选 Player Settings > Publishing Settings > Custom Main Gradle Template"
  - "勾选 Player Settings > Publishing Settings > Custom Gradle Properties Template"
  - "勾选 Player Settings > Publishing Settings > Custom Gradle Settings Template"
  - "勾选 Player Settings > Publishing Settings > Custom Proguard File"
  - "MCP 会在可安全修改 ProjectSettings.asset 时自动配置 API Level 并启用上述模板"

android_manifest:
  path: "{{.WorkspacePath}}/Assets/Plugins/Android/AndroidManifest.xml"
  package: "{{.ApplicationID}}"
  application: "com.ruixue.openapi.RXApplication"
  activity: "{{.ApplicationID}}.UnityPlayerActivity"

unity_player_activity:
  path: "{{.WorkspacePath}}/Assets/Plugins/Android/UnityPlayerActivity.java"
  package: "{{.ApplicationID}}"
  lifecycle:
    - "onCreate/onStart/onRestart/onResume/onPause/onStop"
    - "onNewIntent/onActivityResult/onConfigurationChanged/onRequestPermissionsResult"
  missing_file: "如果文件不存在，先导出 Android 工程，将 unityLibrary/src/main/java/<包名>/UnityPlayerActivity.java 复制到 Assets/Plugins/Android 后重新调用。"

gradle_properties:
  path: "{{.WorkspacePath}}/Assets/Plugins/Android/gradleTemplate.properties"
  common:
    - "android.useAndroidX=true"
    - "android.enableJetifier=true"
  channel_specific:
    - "rxsdk_ysdk: android.useNewApkCreator=false"
    - "rxsdk_vivo/rxsdk_oppo: android.injected.testOnly=false"

maven_repositories:
  path: "{{.WorkspacePath}}/Assets/Plugins/Android/settingsTemplate.gradle"
  notes:
    - "自动添加 google、mavenCentral、阿里云 jcenter 镜像和瑞雪 Maven 主地址。"
    - "备用私有仓库凭证不得硬编码；如需启用，请通过 RUIXUE_MAVEN_USERNAME/RUIXUE_MAVEN_PASSWORD 环境变量配置。"

main_template_gradle:
  path: "{{.WorkspacePath}}/Assets/Plugins/Android/mainTemplate.gradle"
  dependency_block: |
{{.GradleDependencyBlock}}

proguard:
  path: "{{.WorkspacePath}}/Assets/Plugins/Android/proguard-user.txt"
  config: |
    {{.ProguardConfig}}

channel_libraries:
{{range .ChannelNames}}
  - "{{.}}"
{{end}}

component_libraries:
{{range .ComponentNames}}
  - "{{.}}"
{{end}}

preflight:
  checked: {{.Preflight.Checked}}
  satisfied: {{.Preflight.Satisfied}}
  modified:
{{range .Preflight.Modified}}
    - "{{.}}"
{{else}}
    []
{{end}}
  missing:
{{range .Preflight.Missing}}
    - "{{.}}"
{{else}}
    []
{{end}}
  warnings:
{{range .Preflight.Warnings}}
    - "{{.}}"
{{else}}
    []
{{end}}
  nextSteps:
{{range .Preflight.NextSteps}}
    - "{{.}}"
{{else}}
    []
{{end}}

notes:
  - "渠道库必须让用户从 channel_libraries 中单选一个，组件库可多选。"
  - "接入推送时必须先让用户从 pushPlatforms 中选择至少一个平台；MCP 不得按渠道或地区自行猜测。"
  - "即使 region=overseas，MCP 也不会自动选择 rxsdk_overseas；如果缺少 channel，请先询问用户要接入哪个渠道库。"
  - "androidVersion 为 Android 原生 SDK 版本；不要使用 Unity UPM 包版本替代。"
  - "如需自动更新最新 Android 原生 SDK 版本，可传 androidVersion=+。"
  - "applicationId 优先读取 params.applicationId；未传时尝试从 ProjectSettings.asset 的 applicationIdentifier.Android 获取。"
  - "配置完成后请使用 Unity 重新导出或构建 Android 工程验证。"
