# 瑞雪 SDK Unity 公告/邮件
# Generated by MCP

# ==================== 获取公告 ====================
get_announcement:
  method: "RXSDK.GetAnnouncement(int limit, SdkCallback callback)"
  code: |
    using RuiXue;

    RXSDK.GetAnnouncement(10, result =>
    {
        if (result.IsSuccess) Debug.Log("公告列表: " + result.Data);
        else Debug.LogError("获取公告失败: " + result.Error);
    });

# ==================== 获取临时维护公告 ====================
get_temp_notice:
  method: "RuiXueSdk.GetTempNotice(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  min_unity_sdk_version: ">= 1.6.28"
  code: |
    using RuiXue;
    using UnityEngine;

    // Unity SDK 版本需 >= 1.6.28。调用 MCP 时传入 workspacePath 可自动升级 Packages/manifest.json。
    RuiXueSdk.GetTempNotice(
        data =>
        {
            Debug.Log("临时维护公告: " + data);
        },
        error =>
        {
            Debug.LogError("获取临时维护公告失败: " + error);
        });

# ==================== 获取邮件列表 ====================
get_email_list:
  method: "RXSDK.GetEmailList(string userId, SdkCallback callback)"
  code: |
    RXSDK.GetEmailList("user_id", result =>
    {
        if (result.IsSuccess) Debug.Log("邮件列表: " + result.Data);
    });

# ==================== 获取邮件详情 ====================
get_email_detail:
  method: "RXSDK.GetEmailDetail(string userId, int mailId, SdkCallback callback)"
  code: |
    RXSDK.GetEmailDetail("user_id", 12345, result =>
    {
        if (result.IsSuccess) Debug.Log("邮件详情: " + result.Data);
    });

# ==================== 获取附件/领取道具 ====================
get_email_award:
  method: "RXSDK.GetEmailAward(string userId, int type, int mailId, SdkCallback callback)"
  code: |
    RXSDK.GetEmailAward("user_id", 1, 12345, result =>
    {
        if (result.IsSuccess) Debug.Log("领取道具成功: " + result.Data);
    });

# ==================== 删除邮件 ====================
delete_email:
  method: "RXSDK.DeleteEmail(string userId, int type, int mailId, SdkCallback callback)"
  code: |
    RXSDK.DeleteEmail("user_id", 1, 12345, result =>
    {
        if (result.IsSuccess) Debug.Log("删除邮件成功");
    });

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"

{{template "unity_native_dependency_upgrade" .NativeDependencyUpgrade}}
