# 瑞雪 SDK Unity v1 验证码
# Generated by MCP

send_captcha:
  method: "RXLogin.SendCaptcha(CaptchaType type, string target, string purpose, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    using RuiXue;
    using RuiXue.Login;

    RXLogin.SendCaptcha(CaptchaType.Phone, "13800000000", "login",
        data => Debug.Log("验证码发送成功: " + data),
        error => Debug.LogError("验证码发送失败: " + error)
    );

verify_captcha:
  method: "RXLogin.VerifyCaptcha(CaptchaType type, string target, string purpose, string captcha_code, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    RXLogin.VerifyCaptcha(CaptchaType.Phone, "13800000000", "login", "123456",
        data => Debug.Log("验证码校验成功: " + data),
        error => Debug.LogError("验证码校验失败: " + error)
    );

imports:
  - "using RuiXue;"
  - "using RuiXue.Login;"
