# 瑞雪 SDK Unity 设备信息与配置
# Generated by MCP

# ==================== 获取设备码 ====================
get_device_code:
  method: "RuiXueSdk.GetDeviceCode(RequestResponseDelegate onResponse)"
  code: |
    using RuiXue;
    using UnityEngine;

    RuiXueSdk.GetDeviceCode(data =>
    {
        Debug.Log("设备码: " + data);
    });

# ==================== 配置类 API ====================
config_apis:
  set_log:
    method: "RuiXueSdk.SetLogEnable(bool enabled)"
    code: |
      RuiXueSdk.SetLogEnable(true);  // 开启日志

  set_language:
    method: "RuiXueSdk.SetLanguage(string language)"
    code: |
      RuiXueSdk.SetLanguage("zh-Hans");    // 简体中文
      RuiXueSdk.SetLanguage("en");         // 英文

  set_sub_channel:
    method: "RuiXueSdk.SetSubChannelId(string subChannelId)"
    code: |
      RuiXueSdk.SetSubChannelId("sub_channel_001");

  set_game_info:
    method: "RuiXueSdk.SetGameInfo(string roleId, string regionTag)"
    code: |
      RuiXueSdk.SetGameInfo("role_001", "server_001");

  set_area:
    method: "RuiXueSdk.SetArea(string area)"
    code: |
      RuiXueSdk.SetArea("CN");

  set_screen_capture:
    method: "RuiXueSdk.SetScreenCaptureDisable(bool disable)"
    code: |
      RuiXueSdk.SetScreenCaptureDisable(true);  // 禁止截屏

  set_password_strength:
    method: "RuiXueSdk.SetPasswordStrength(RXPasswordStrength type)"
    code: |
      RuiXueSdk.SetPasswordStrength(RXPasswordStrength.Strong);

  set_pwd_pattern:
    method: "RuiXueSdk.SetPwdPattern(string pattern)"
    code: |
      RuiXueSdk.SetPwdPattern(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$");

  config_error_msg:
    method: "RuiXueSdk.configErrorMsg(Dictionary<string, object> errorMsgMap)"
    code: |
      var errorMsgMap = new Dictionary<string, object>
      {
          { "10001", new Dictionary<string, string>
              {
                  { "zh-Hans", "自定义错误信息" },
                  { "en", "Custom error message" }
              }
          }
      };
      RuiXueSdk.configErrorMsg(errorMsgMap);

  disable_sensitive_info:
    method: "RuiXueSdk.DisableReadSensitiveInfo(bool disabled)"
    code: |
      RuiXueSdk.DisableReadSensitiveInfo(true);  // 关闭敏感信息采集

# ==================== 状态查询 ====================
status_apis:
  login_openid_expire:
    method: "RuiXueSdk.LoginOpenidExpireInvalid()"
    code: |
      bool expired = RuiXueSdk.LoginOpenidExpireInvalid();
      Debug.Log("login_openid 是否失效: " + expired);

  is_agreed_privacy:
    method: "RuiXueSdk.IsAgreedPrivacy()"
    code: |
      bool agreed = RuiXueSdk.IsAgreedPrivacy();

  search_game_account:
    method: "RuiXueSdk.SearchGameAccount(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
    code: |
      RuiXueSdk.SearchGameAccount(
          data => Debug.Log("游戏账号信息: " + data),
          error => Debug.LogError("查询游戏账号失败: " + error)
      );

# ==================== 网络请求 ====================
create_request:
  method: "RuiXueSdk.CreateRequest(string url, Dictionary<string, string> header, Dictionary<string, string> body, HttpMethod method, bool needLogin, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    var header = new Dictionary<string, string>
    {
        { "Content-Type", "application/json" }
    };
    var body = new Dictionary<string, string>
    {
        { "key", "value" }
    };

    RuiXueSdk.CreateRequest(
        "https://api.example.com/custom",
        header,
        body,
        HttpMethod.POST,
        true,   // needLogin: 是否需要登录态
        data => Debug.Log("请求成功: " + data),
        error => Debug.LogError("请求失败: " + error)
    );

# ==================== 三方渠道初始化 ====================
init_third_sdk:
  method: "RuiXueSdk.InitThirdSdk(Dictionary<string, object> map, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    var initParams = new Dictionary<string, object>
    {
        { "channel", "rxsdk_weile" }
    };

    RuiXueSdk.InitThirdSdk(
        initParams,
        data => Debug.Log("三方渠道初始化成功: " + data),
        error => Debug.LogError("三方渠道初始化失败: " + error)
    );

# ==================== 绑定第三方账号 ====================
bind_account:
  method: "RuiXueSdk.BindAccount(Dictionary<string, object> ext, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  min_unity_sdk: "1.6.22"
  min_android_sdk: "4.0.8"
  min_ios_pods:
    RXSDK_Pure: "4.0.2"
    RXFacebookSDK: "4.0.0"
    RXGoogleSDK: "4.0.0"
  code: |
    // 版本要求：
    // - UnitySDK >= 1.6.22
    // - Android 原生 SDK >= 4.0.8（检查 mainTemplate.gradle 中 rxVersion）
    // - iOS RXSDK_Pure >= 4.0.2
    // - 若 method 为 facebook/google，RXFacebookSDK/RXGoogleSDK 需 >= 4.0.0
    // - 若版本过低，请先自动升级：Unity 改 Packages/manifest.json，Android 改 mainTemplate.gradle rxVersion，iOS 改 Podfile 后执行 pod update
    var ext = new Dictionary<string, object>
    {
        { "method", "wechat" },
        { "scene", "authorization" }
    };

    RuiXueSdk.BindAccount(
        ext,
        data => Debug.Log("绑定第三方账号成功: " + data),
        error => Debug.LogError("绑定第三方账号失败: " + error)
    );

# ==================== 检查免密支付 ====================
check_quick_ap:
  method: "RuiXueSdk.CheckQuickAp(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    RuiXueSdk.CheckQuickAp(
        data => Debug.Log("免密支付检查结果: " + data),
        error => Debug.LogError("免密支付检查失败: " + error)
    );

# ==================== 退出应用 ====================
exit_app:
  method: "RuiXueSdk.ExitApp(ExitConfirmDelegate onExitConfirm, ExitCancelDelegate onExitCancel)"
  code: |
    RuiXueSdk.ExitApp(
        res => Debug.Log("渠道确认退出: " + res),
        () => Debug.Log("渠道取消退出")
    );

# ==================== 导入语句 ====================
imports:
  - "using System.Collections.Generic;"
  - "using RuiXue;"
  - "using UnityEngine;"
