# 瑞雪 SDK Unity v1 好友管理
# Generated by MCP

add_friends:
  method: "RXSocial.AddFriends(string target, string target_remarks, string user_remarks, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    using RuiXue;
    using RuiXue.Social;

    RXSocial.AddFriends("target_open_id", "对方备注", "我的备注", data => Debug.Log("添加好友成功"), error => Debug.LogError(error));

remove_friends:
  method: "RXSocial.RemoveFriends(string target, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    RXSocial.RemoveFriends("target_open_id", data => { }, error => Debug.LogError(error));

relation_friends:
  method: "RXSocial.RelationFriends(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    RXSocial.RelationFriends(data => Debug.Log("好友列表: " + data), error => Debug.LogError(error));

is_friend:
  method: "RXSocial.IsFriend(string target, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    RXSocial.IsFriend("target_open_id", data => Debug.Log("是否好友: " + data), error => Debug.LogError(error));

update_friend_remarks:
  method: "RXSocial.UpdateFriendRemarks(string target, string target_remarks, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    RXSocial.UpdateFriendRemarks("target_open_id", "新备注", data => { }, error => Debug.LogError(error));

imports:
  - "using RuiXue;"
  - "using RuiXue.Social;"
