# 瑞雪 SDK Unity v1 法务
# Generated by MCP

get_legal:
  method: "RXLegal.Legal(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    using RuiXue;
    using RuiXue.Legal;

    RXLegal.Legal(
        data => Debug.Log("法务配置: " + data),
        error => Debug.LogError("获取法务配置失败: " + error)
    );

privacy:
  method: "RuiXueSdk.SetPrivacyAgree(Action<bool> callback) / RuiXueSdk.IsAgreedPrivacy()"
  code: |
    RuiXueSdk.SetPrivacyAgree(agreed => Debug.Log("隐私授权状态: " + agreed));
    bool agreedPrivacy = RuiXueSdk.IsAgreedPrivacy();

imports:
  - "using RuiXue;"
  - "using RuiXue.Legal;"
