# 瑞雪 SDK Unity 微信小游戏（WebGL）
# Generated by MCP

# ==================== 适用范围 ====================
overview: |
  微信小游戏专属能力，来自包 com.ruixue.unitysdk.minigame.weixin（目录 com.ruixue.unitysdk.webgl.weixin）。
  - 命名空间：RuiXue.MiniGame.WeiXin，入口类：RXMiniGameWeiXin（静态类）。
  - 仅在 WebGL 平台生效，所有调用需包裹在 #if UNITY_WEBGL 中。
  - 依赖 com.ruixue.unitysdk.base，且运行时依赖内嵌的瑞雪 JS SDK
    （Plugins/WebGL/RXJsSdk_WeiXin/channelSDK/index.js，由 RXSDK-JS 的 build:wegame 产物同步）。
  - 通用登录/支付/社交/排行榜等仍走 RuiXue 主命名空间（RuiXueSdk/RXLogin/RXPay 等），本模块只覆盖微信小游戏特有接口。

# ==================== 导入语句 ====================
imports:
  - "using System.Collections.Generic;"
  - "using RuiXue.MiniGame.WeiXin; // 需包裹在 #if UNITY_WEBGL"

# ==================== 内容安全 ====================
content_security: |
  ## 文本内容安全识别
  ```csharp
  var dic = new Dictionary<string, object>
  {
      ["content"] = "待检测文本",
      ["scene"] = 2
  };
  RXMiniGameWeiXin.MsgSecCheck(dic, OnResponse, OnError);
  ```

  ## 异步校验图片
  ```csharp
  var dic = new Dictionary<string, object>
  {
      ["mediaUrl"] = "https://example.com/img.png",
      ["mediaType"] = 2
  };
  RXMiniGameWeiXin.MediaCheckAsync(dic, OnResponse, OnError);
  ```

# ==================== 客服与设备 ====================
customer_service: |
  ## 打开客服会话
  ```csharp
  var dic = new Dictionary<string, object>();
  RXMiniGameWeiXin.OpenCustomerServiceConversation(dic, OnResponse, OnError);
  ```

  ## 获取用户设备码
  ```csharp
  RXMiniGameWeiXin.GetUserDeviceCode(OnResponse, OnError);
  ```

# ==================== 补单 ====================
compensate_pay: |
  ## 查询是否需要补单
  ```csharp
  RXMiniGameWeiXin.CheckHasCompensatePayOrder(OnResponse, OnError);
  ```

  ## 补单
  ```csharp
  var dic = new Dictionary<string, object>
  {
      ["orderNo"] = "订单号"
  };
  RXMiniGameWeiXin.CompensatePayOrder(dic, OnResponse, OnError);
  ```

# ==================== 开放数据域 / 云存储 ====================
open_data: |
  说明：部分 GetXxx 接口（GetUserCloudStorage/GetUserCloudStorageKeys/GetFriendCloudStorage/GetPotentialFriendList）
  被标记为 [Obsolete]，只能在开放数据域调用，主域调用会返回错误，请谨慎使用。

  ## 写入用户托管数据
  ```csharp
  var data = new[]
  {
      new RXMiniGameWeiXin.CloudStorageKVData { key = "gold", value = "3000" },
      new RXMiniGameWeiXin.CloudStorageKVData { key = "score", value = "100" }
  };
  RXMiniGameWeiXin.SetUserCloudStorage(data, OnResponse, OnError);
  ```

  ## 删除用户托管数据
  ```csharp
  RXMiniGameWeiXin.RemoveUserCloudStorage(new[] { "score" }, OnResponse, OnError);
  ```

  ## 获取互动型托管数据
  ```csharp
  RXMiniGameWeiXin.GetUserInteractiveStorage(new[] { "1", "2" }, OnResponse, OnError);
  ```

  ## 获取游戏圈数据
  ```csharp
  var dataTypeList = new[]
  {
      new RXMiniGameWeiXin.GameClubDataType { type = 1, subKey = "" }
  };
  RXMiniGameWeiXin.GetGameClubData(dataTypeList, OnResponse, OnError);
  ```

# ==================== 同玩游戏好友列表 ====================
relation_friend: |
  ## 获取同玩游戏好友列表 GetRelationFriendList
  版本要求：unitysdk >= 1.6.32、jssdk >= 4.0.1；需微信基础库 3.16.2 及以上，低版本会走失败回调。
  ```csharp
  // dic 全部可选，无参数时传空字典 new Dictionary<string, object>()
  var dic = new Dictionary<string, object>
  {
      ["guideAuthWhenDeny"] = true,   // 拒绝授权时是否自动弹窗引导去设置页开启，默认 true
      ["authModalTitle"] = "授权提示",
      ["authModalContent"] = "需要获取互动好友信息，请在设置中开启授权"
  };
  RXMiniGameWeiXin.GetRelationFriendList(dic, OnResponse, OnError);
  ```
  说明：调用 JSSDK 同名方法 getRelationFriendList，结果通过 OnResponse 回调返回同玩互动好友列表。

# ==================== 分享 ====================
share: |
  ## 发起分享
  ```csharp
  var dic = new Dictionary<string, dynamic>
  {
      ["title"] = "分享标题",
      ["imageUrl"] = "https://example.com/share.png"
  };
  RXMiniGameWeiXin.Share(dic, OnResponse, OnError);
  ```

  ## 调度分享（分享 / 广告混合调度）
  ```csharp
  RXMiniGameWeiXin.SchedulingAction(dic, OnResponse, OnError);
  ```

  ## 其他分享能力
  - ShowShareImageMenu(dic, ...): 打开分享图片弹窗
  - ShareMessageToFriend(dic, ...): 给指定好友分享
  - CreateActivityId(dic, ...) / GetDynamicShareActivityId(...): 动态消息 activity_id
  - DynamicShare(dic, ...): 分享动态消息

# ==================== 订阅消息 ====================
subscribe_message: |
  ```csharp
  var dic = new Dictionary<string, dynamic>
  {
      ["tmplIds"] = new[] { "模板ID1", "模板ID2" }
  };
  RXMiniGameWeiXin.RequestSubscribeMessage(dic, OnResponse, OnError);
  ```

# ==================== 广告 ====================
ad: |
  ## 激励视频广告
  ```csharp
  var dic = new Dictionary<string, dynamic>
  {
      ["adUnitId"] = "广告位ID"
  };
  RXMiniGameWeiXin.RewardedVideoAd(dic, OnResponse, OnError);
  ```

  ## 原生模板广告
  ```csharp
  RXMiniGameWeiXin.CreateCustomAd(dic, OnResponse, OnError);
  ```

# ==================== 公告与邮件 ====================
announcement_mail: |
  ## 获取公告列表
  ```csharp
  RXMiniGameWeiXin.GetAnnouncement(10, OnResponse, OnError);
  ```

  ## 邮件
  - GetEmailList(dic, ...): 邮件列表
  - GetEmailDetail(dic, ...): 邮件详情
  - ReceiveEmail(dic, ...): 领取邮件
  - DelEmail(dic, ...): 删除邮件

# ==================== 玩家反馈 ====================
feedback: |
  - AddFeedback(dic, ...): 创建玩家反馈
  - GetFeedbackList(dic, ...): 反馈列表
  - GetFeedbackDetail(dic, ...): 反馈详情

# ==================== 达人福利 ====================
promo: |
  ```csharp
  RXMiniGameWeiXin.GetPromoDisplayKey(OnResponse, OnError);
  RXMiniGameWeiXin.ExchangePromoCdKey("福利码", OnResponse, OnError);
  RXMiniGameWeiXin.CollectProps(dic, OnResponse, OnError); // 领取道具
  ```

# ==================== 账号（换绑手机号）====================
account: |
  - GetPhoneNumber(dic, ...): 绑定手机号（iOS）
  - ChangePhone(dic, ...) / ChangePhoneNumber(dic, ...): 换绑手机号
  - ValidateUnbindCode(dic, ...): 校验解绑验证码

# ==================== 数据上报 ====================
report: |
  ```csharp
  RXMiniGameWeiXin.ReportCreateRole("roleId");            // 创角
  RXMiniGameWeiXin.ReportPurchase(6, needReportMidas: true); // 付费
  RXMiniGameWeiXin.ReportUpdateLevel(dic);                // 等级提升
  RXMiniGameWeiXin.ReportTutorialFinish();                // 完成指引
  RXMiniGameWeiXin.ReportViewContent("item");             // 浏览
  RXMiniGameWeiXin.SetGameInfo("roleId", "regionTag");    // 设置区服角色
  RXMiniGameWeiXin.SearchGameAccount(OnResponse, OnError);// 查询区服角色
  ```

# ==================== 回调签名 ====================
callback: |
  ```csharp
  void OnResponse(string data) { Debug.Log($"success: {data}"); }
  void OnError(string data) { Debug.LogError($"error: {data}"); }
  ```

# ==================== 注意事项 ====================
note: |
  - 全部接口只在 WebGL（微信小游戏）平台可用，Editor/其他平台不会执行原生桥接。
  - 运行时 JS（channelSDK/index.js）必须与 SDK 版本匹配：使用 RXSDK-JS 的 `npm run build:wegame`
    产物覆盖 Plugins/WebGL/RXJsSdk_WeiXin/channelSDK/index.js，切勿使用 wegame.full 全量包。
  - 通用能力（初始化 RuiXueSdk.Initialize、登录 RXLogin、支付 RXPay 等）用 unity 工具的对应 feature 获取。
