# 瑞雪 SDK Unity 支付
# Generated by MCP

# ==================== 方法签名 ====================
signature:
  method: "RXPay.Pay(Dictionary<string, object> dic, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  android_product_info: "RXGoogle.QueryProductDetailsAsync(List<string> skusList, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  ios_product_info: "RXPay.IOS_GetProductInfos(List<string> productIds, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"

# ==================== 支付参数 ====================
pay_params:
  - name: goods_tag
    type: string
    required: true
    description: 商品标识
  - name: trade_no
    type: string
    required: true
    description: 订单号（需唯一）
  - name: amount
    type: int
    required: true
    description: 支付金额（单位：分）
  - name: hq_type
    type: string
    required: false
    description: 支付方式（如 wechat、alipay）
  - name: product_name
    type: string
    required: false
    description: 商品名称
  - name: product_desc
    type: string
    required: false
    description: 商品描述

# ==================== 样板代码 ====================
code: |
  using System.Collections.Generic;
  using RuiXue;
  using RuiXue.Google;
  using RuiXue.Pay;
  using UnityEngine;

  // ========== 发起支付 ==========
  private void DoPay()
  {
      var payParams = new Dictionary<string, object>
      {
          { "goods_tag", "diamond_100" },                          // 商品标识
          { "trade_no", System.Guid.NewGuid().ToString() },       // 订单号
          { "amount", 100 },                                      // 金额（分）
          { "product_name", "100钻石" },                           // 商品名称
          { "product_desc", "购买100颗钻石" },                     // 商品描述
      };

      RXPay.Pay(payParams, OnPayResponse, OnPayError);
  }

  private void OnPayResponse(string data)
  {
      Debug.Log("支付成功: " + data);
      // TODO: 发放道具
  }

  private void OnPayError(string error)
  {
      Debug.LogError("支付失败: " + error);
      // TODO: 处理支付失败
  }

  // ========== 获取商品信息 ==========
  private void QueryProductInfo()
  {
      var productIds = new List<string> { "com.game.diamond100", "com.game.diamond500" };
  #if UNITY_ANDROID
      // Android Google 商品详情查询
      RXGoogle.QueryProductDetailsAsync(productIds, OnAndroidProductInfoResponse, OnAndroidProductInfoError);
  #elif UNITY_IOS
      // iOS App Store 商品信息查询
      RXPay.IOS_GetProductInfos(productIds, OnIOSProductInfoResponse, OnIOSProductInfoError);
  #else
      Debug.LogWarning("当前平台暂不支持获取商品信息");
  #endif
  }

  private void OnAndroidProductInfoResponse(string data)
  {
      Debug.Log("Android 商品信息: " + data);
  }

  private void OnAndroidProductInfoError(string error)
  {
      Debug.LogError("Android 商品信息查询失败: " + error);
  }

  private void OnIOSProductInfoResponse(string data)
  {
      Debug.Log("iOS 商品信息: " + data);
  }

  private void OnIOSProductInfoError(string error)
  {
      Debug.LogError("iOS 商品信息查询失败: " + error);
  }

# ==================== 导入语句 ====================
imports:
  - "using System.Collections.Generic;"
  - "using RuiXue;"
  - "using RuiXue.Google;"
  - "using RuiXue.Pay;"
  - "using UnityEngine;"
