# 瑞雪 SDK Unity v1 推送
# Generated by MCP

platform_selection:
  parameter_platform: "platform"
  default_platform: "android"
  parameter: "pushPlatforms"
  required: "platform=android 或 platform=both 时必填"
  rule: "Android/Unity Android 接入推送前必须询问用户选择平台，不得根据地区、渠道或设备品牌自动猜测；platform=ios 时不需要 pushPlatforms。"
  supported:
    - firebase
    - huawei
    - honor
    - xiaomi
    - oppo
    - vivo
    - meizu
  native_setup: "选择后调用 unity feature=android_native_setup，并原样传入 pushPlatforms；MCP 只写入对应平台组件，组件会传递引入 rxsdk_push_base。"

ios_notification_service:
  minimum_upm_version: "4.0.8"
  package: "com.ruixue.unitysdk.push"
  generated_on: "Unity 导出 iOS Xcode 工程时自动创建"
  target_name: "NotificationService"
  bundle_id: "主应用 Bundle ID + .NotificationService"
  minimum_ios_version: "12.0"
  report_method: "[[RXPushService sharedSDK] pushReceivedWithUserInfo:self.bestAttemptContent.userInfo]"
  behavior:
    foreground: "RXPushSDK 自动执行消息接收统计。"
    background_or_terminated: "NotificationService Extension 调用 pushReceivedWithUserInfo: 执行消息接收统计。"
  payload:
    required: true
    json_path: "aps.mutable-content"
    value: 1
    note: "缺少 mutable-content=1 时，iOS 不会唤起 Notification Service Extension。"
  generated_configuration:
    - "自动生成 NotificationService.h、NotificationService.m 和 Info.plist"
    - "自动为 NotificationService Target 添加 RXPushSDK Pod"
    - "自动配置 UserNotifications.framework、Keychain Sharing 和签名继承"
  verification:
    - "重新导出 iOS 工程并确认 NotificationService Target 存在"
    - "确认 Bundle ID 后缀为 .NotificationService"
    - "使用真机验证 App 后台和退出状态的接收统计；不以模拟器作为验证结论"

init:
  method: "RXPush.Init() / RXPush.Init(string productId, string channelId, string cpid, List<string> urls)"
  code: |
    using System.Collections.Generic;
    using RuiXue.Push;

    RXPush.Init();
    RXPush.Init("product_id", "channel_id", "cpid", new List<string> { "https://push.ruixueyun.com" });

register_token:
  method: "RXPush.RegisterToken()"
  code: |
    RXPush.RegisterToken();

unregister_token:
  method: "RXPush.UnRegisterToken()"
  code: |
    RXPush.UnRegisterToken();

get_device_token:
  method: "string RXPush.GetDeviceToken()"
  code: |
    string token = RXPush.GetDeviceToken();

alias:
  bind:
    method: "RXPush.BindAlias(string alias)"
    code: |
      RXPush.BindAlias("player_001");
  unbind:
    method: "RXPush.UnBindAlias(string alias)"
    code: |
      RXPush.UnBindAlias("player_001");

imports:
  - "using System.Collections.Generic;"
  - "using RuiXue.Push;"
