# 瑞雪 SDK Unity 实名认证 / 支付宝 IIFAA
# Generated by MCP
#
# 接入前必须先询问用户:
# - 是否使用瑞雪实名认证 UI？
# - 使用：接入 RXLoginUI.RealAuthUI
# - 不使用：接入 IIFAA 支付宝授权跳转地址和认证结果查询

decision_prompt:
  question: "是否使用瑞雪实名认证 UI？"
  use_ruixue_ui: "使用瑞雪实名认证 UI 时，调用 RXLoginUI.RealAuthUI，并确保 Unity UI 包和原生 UI 依赖版本满足要求。"
  custom_ui: "不使用瑞雪实名认证 UI 时，自动接入获取 IIFAA 支付宝授权跳转地址和查询 IIFAA 认证结果。"

iifaa_config_notice:
  message: "请按照文档确认配置"
  document_url: "https://doc.ruixueyun.com/main/#/view?path=ba910252-aff4-440d-8f78-31f25d19c271"
  response_rule: "用户询问 IIFAA 配置文档时，只返回 document_url，不解析文档内容。"

# ==================== 瑞雪实名认证 UI ====================
real_auth_ui:
  method: "RXLoginUI.RealAuthUI(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  min_unity_sdk: "1.6.25"
  code: |
    // ========== 瑞雪 SDK 实名认证 UI ==========
    // 使用此方式前请确认已接入 com.ruixue.unitysdk.ui，且版本与 base 保持一致
    using RuiXue.LoginUI;
    using UnityEngine;

    private void ShowRealAuthUI()
    {
        RXLoginUI.RealAuthUI(
            data => Debug.Log("实名认证 UI 成功: " + data),
            error => Debug.LogError("实名认证 UI 失败: " + error)
        );
    }

# ==================== 普通实名认证 ====================
real_auth:
  method: "RXLogin.RealAuth(string realname, string idcard, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    // ========== 瑞雪 SDK 普通实名认证 ==========
    using RuiXue.Login;
    using UnityEngine;

    private void DoRealAuth(string realname, string idcard)
    {
        RXLogin.RealAuth(
            realname,
            idcard,
            data => Debug.Log("实名认证成功: " + data),
            error => Debug.LogError("实名认证失败: " + error)
        );
    }

# ==================== IIFAA 支付宝实名认证（自定义 UI） ====================
iifaa_alipay_real_auth:
  description: "不使用瑞雪实名认证 UI 时使用：获取 IIFAA 支付宝授权跳转地址，读取 data[\"url\"] 并通过 scheme 跳转；App 回到前台后 retryCount=3 查询认证结果。"
  min_unity_sdk: "1.6.31"
  min_android_sdk: "4.0.14"
  min_ios_pods:
    RXSDK_Pure: "4.0.6"
    RXUIKit: "4.0.4"
  code: |
    // ========== Unity IIFAA 支付宝实名认证 ==========
    // 版本要求：
    // - UnitySDK >= 1.6.31
    // - Android 原生 SDK >= 4.0.14
    // - iOS RXSDK_Pure >= 4.0.6；使用瑞雪实名认证 UI 时 RXUIKit >= 4.0.4
    // - 若版本过低，请先按 native_version_check.auto_upgrade 自动升级对应依赖
    // - IIFAA 配置确认只返回文档地址：https://doc.ruixueyun.com/main/#/view?path=ba910252-aff4-440d-8f78-31f25d19c271，不解析文档内容
    //
    // 重要逻辑：
    // 1. 获取 IIFAA 支付宝授权跳转地址
    // 2. 从返回数据中读取 data["url"] 并 Application.OpenURL(url)
    // 3. 设置 isIifaaRealAuthInProgress = true
    // 4. 监听 App 进入前台，仅当 isIifaaRealAuthInProgress 为 true 时查询认证结果
    // 5. 查询 IIFAA 认证结果 retryCount 固定传 3
    using RuiXue;
    using RuiXueLitJson;
    using UnityEngine;

    public class RuiXueIifaaRealAuth : MonoBehaviour
    {
        private bool isIifaaRealAuthInProgress;

        public void StartIifaaRealAuth(string appName, string scheme)
        {
            RuiXueSdk.GetIIFAARedirectURL(
                appName,
                scheme,
                data =>
                {
                    string url = GetUrlFromIifaaResponse(data);
                    if (string.IsNullOrEmpty(url))
                    {
                        Debug.LogError("IIFAA 授权地址为空: " + data);
                        return;
                    }

                    isIifaaRealAuthInProgress = true;
                    Application.OpenURL(url);
                },
                error => Debug.LogError("获取 IIFAA 授权地址失败: " + error)
            );
        }

        private void OnApplicationFocus(bool hasFocus)
        {
            if (!hasFocus || !isIifaaRealAuthInProgress)
            {
                return;
            }

            QueryIifaaResult();
        }

        private void QueryIifaaResult()
        {
            // source 传 deregister 表示注销场景，传空表示正常认证逻辑
            RuiXueSdk.GetIIFAAResultWithSource(
                "",
                3,
                data =>
                {
                    isIifaaRealAuthInProgress = false;
                    Debug.Log("IIFAA 认证成功: " + data);
                },
                error =>
                {
                    isIifaaRealAuthInProgress = false;
                    Debug.LogError("IIFAA 认证结果查询失败: " + error);
                }
            );
        }

        private static string GetUrlFromIifaaResponse(string json)
        {
            JsonData root = JsonMapper.ToObject(json);
            JsonData data = root.ContainsKey("data") ? root["data"] : root;
            return data.ContainsKey("url") ? data["url"].ToString() : "";
        }

    }

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"
  - "using RuiXue.Login;"
  - "using RuiXueLitJson;"
  - "using UnityEngine;"

{{template "unity_native_dependency_upgrade" .NativeDependencyUpgrade}}
