# 瑞雪 SDK Unity v1 应用商店评分
# Generated by MCP

jump_to_app_store:
  method: "RXReview.JumpToAppStore()"
  return: bool
  code: |
    using RuiXue.Review;
    using UnityEngine;

    bool success = RXReview.JumpToAppStore();
    Debug.Log("跳转应用商店: " + success);

imports:
  - "using RuiXue.Review;"
  - "using UnityEngine;"
