# 瑞雪 SDK Unity 自动化接入
# Generated by MCP

# ==================== UPM 安装指令 ====================
setup_upm: |
  【你现在必须执行以下操作 - UPM 方式】

  项目路径: {{.WorkspacePath}}
  SDK 版本: {{.Version}}（未传入 version 时使用 MCP 内置默认版本）

  1. 编辑 manifest.json
     - 文件路径: {{.WorkspacePath}}/Packages/manifest.json
     - 在 JSON 根对象中添加 scopedRegistries 配置（如已存在则追加）：
       ```json
       "scopedRegistries": [
         {
           "name": "RuiXue SDK",
           "url": "http://60.205.123.114:4873",
           "scopes": ["com.ruixue"]
         }
       ]
       ```
     - 在 dependencies 中添加：
       ```json
{{.DefaultDependencies}}
       ```

  2. 保存文件后 Unity 会自动下载并导入 SDK

  3. 默认接入范围
     - com.ruixue.unitysdk.base：基础初始化与公共能力
     - com.ruixue.unitysdk.share：分享能力
     - com.ruixue.unitysdk.login：登录、通行证、账号相关能力
     - com.ruixue.unitysdk.pay：支付能力

  4. 按需补充组件库
     - 当用户调用的接口/类型不存在时，先判断接口所属功能，再在 `Packages/manifest.json` 的 `dependencies` 追加对应组件库
     - 追加组件库的版本号必须与 com.ruixue.unitysdk.base 保持一致，即 {{.Version}}
     - 例如排行榜功能追加 `"com.ruixue.unitysdk.rank": "{{.Version}}"`，广告功能追加 `"com.ruixue.unitysdk.ad": "{{.Version}}"`

  5. 验证安装
     - Unity 菜单：Window → Package Manager
     - 确认 RuiXue Base、Share、Login、Pay 出现在已安装列表中

  6. 完成后提醒用户：
     - 创建一个 MonoBehaviour 脚本用于 SDK 初始化
     - 调用 unity feature=init 获取初始化代码

# ==================== .unitypackage 安装指令 ====================
setup_unitypackage: |
  【你现在必须执行以下操作 - .unitypackage 方式】

  项目路径: {{.WorkspacePath}}

  1. 确认 .unitypackage 文件
     - 检查用户是否已有 RuiXueSDK.unitypackage 文件
     - 如果没有，提示用户从瑞雪技术支持获取

  2. 导入步骤（告知用户手动操作）
     - 打开 Unity 编辑器
     - 菜单栏：Assets → Import Package → Custom Package...
     - 选择 RuiXueSDK.unitypackage 文件
     - 在弹出的导入窗口中勾选所有文件
     - 点击 "Import" 按钮

  3. 验证导入
     - 检查 Assets 目录下是否出现 RuiXue 相关文件夹
     - 检查 Console 是否有编译错误

  4. 完成后提醒用户：
     - 创建一个 MonoBehaviour 脚本用于 SDK 初始化
     - 调用 unity feature=init 获取初始化代码
