# 瑞雪 SDK Unity 银联综合支付
# Generated by MCP

overview:
  feature: unifypay
  supported_target: Android
  unsupported_target: iOS
  upm_package: "com.ruixue.unitysdk.pay"
  minimum_upm_version: "4.0.0"
  android_dependency: "com.ruixue:rxsdk_unifypay:4.0.17"
  android_direct_api: "UPPaySdkWrapper.getInstance().doPay"

example_csharp: |
  using System.Collections.Generic;
  using RuiXue.Pay;
  using UnityEngine;

  var ext = new Dictionary<string, object>
  {
      ["hq_type"] = "uac",
      ["supportBank"] = "CCB",
      ["invokeType"] = "APP"
  };

  var payParams = new Dictionary<string, object>
  {
      ["hq_type"] = "aums",
      ["goods_tag"] = "YOUR_GOODS_TAG",
      ["trade_no"] = "YOUR_TRADE_NO",
      ["ext"] = ext
  };

  RXPay.Pay(
      payParams,
      data => Debug.Log("银联支付成功: " + data),
      error => Debug.LogError("银联支付失败: " + error)
  );

requirements:
  - "仅支持 Unity Android 构建目标；iOS 不生成伪调用。"
  - "调用前必须完成 RuiXueSdk.Initialize。"
  - "Packages/manifest.json 需要 com.ruixue.unitysdk.pay >= 4.0.0。"
  - "mainTemplate.gradle 需要当前已验证的 com.ruixue:rxsdk_unifypay >= 4.0.17，minSdkVersion >= 22。"
  - "Unity 通过 RXPay.Pay 进入支付链路，Android 原生银联插件使用 UPPaySdkWrapper.getInstance().doPay。"
