# 瑞雪 SDK Unity 版本检查 v2
# Generated by MCP
# 最低版本：Unity UPM >= 1.6.39，Android 原生 >= 4.0.13，iOS RXSDK_Pure >= 4.0.8

# ==================== 接入前强制检查 ====================
preflight_check:
  must_do_before_insert_code: true
  minimum_sdk:
    unity: ">= 1.6.39"
    android: ">= 4.0.13"
    ios:
      RXSDK_Pure: ">= 4.0.8"
  checks:
    - "检查 Packages/manifest.json 中 com.ruixue.unitysdk.versioncheck 与 com.ruixue.unitysdk.base 是否 >= 1.6.39"
    - "检查 Unity 项目中是否已完成 RuiXueSdk.Initialize 初始化"
    - "如果存在 Assets/Plugins/Android/mainTemplate.gradle，检查 com.ruixue:* 或 rxVersion 是否 >= 4.0.13"
    - "如果存在 Podfile / PodfileTemplate，检查 RXSDK_Pure 是否 >= 4.0.8"
    - "只生成 v2 RXVersionCheck.UpdateGameVersion 接入，不再返回旧 UpdateApp/CheckUpdateApp/UpdateGame/UpdateActivity 版本检查代码"
  failure_action:
    - "如果 preflight.satisfied=false，先按 preflight.missing / preflight.nextSteps 补齐基础接入和版本升级"
    - "版本不足且 MCP 已修改 manifest/Gradle/Podfile 时，先让 Unity Package Manager resolve，并重新构建原生工程"
  agent_rule:
    - "用户说“接入瑞雪版本检查”“Unity 版本检查”“检查更新”时，直接返回本 v2 RXVersionCheck.UpdateGameVersion 接入"
    - "不得再生成旧版 UpdateApp、CheckUpdateApp、UpdateGame、UpdateActivity 版本检查接口"

{{template "unity_native_dependency_upgrade" .}}

# ==================== 响应数据 ====================
response_data:
  schema:
    code: "Number，接口状态码；0 表示请求正常，非 0 表示请求失败"
    data:
      type: Object
      description: 业务数据
      fields:
        modules:
          type: Array<ModuleResponse>
          description: 模块检查结果数组
          item_fields:
            module_tag: "String，模块标识"
            category_tag: "String，分类标识"
            version: "Number，最新版本；大于 0 表示有新版本，0 表示无最新版本"
            uri: "String，版本包下载地址"
  example: |
    {
      "data": {
        "modules": [
          {
            "module_tag": "dsa",
            "category_tag": "dass",
            "uri": "https://rxfile-test.ruixueyun.com/release/pkg/25031110GjPuOV0TkITessHcdWpgyWn3Tb3T2U.zip",
            "version": 88
          },
          {
            "module_tag": "_nNNN",
            "category_tag": "default",
            "uri": "https://rxfile-test.ruixueyun.com/release/pkg/25031110jCFrdMrEvsqRMDnMEC7vMoJO7EinKp.zip",
            "version": 99
          }
        ]
      },
      "code": 0
    }

# ==================== 版本检查 v2 ====================
update_game_version_v2:
  method: "RXVersionCheck.UpdateGameVersion(string moduleTag, string categoryTag, int clientVersion, int checkVersion, string type, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  description: 瑞雪版本检查 v2，统一检查模块版本
  module_fields:
    module_tag: "String，必填，模块标识"
    category_tag: "String，必填，分类标识"
    clientversion: "Number，必填，客户端当前版本；0 表示首次接入或当前无相关版本"
    checkversion: "Number，必填，优先检查版本；不指定时传 0"
  code: |
    using RuiXue;
    using RuiXue.VersionCheck;
    using UnityEngine;

    public void CheckVersionV2()
    {
        RXVersionCheck.UpdateGameVersion(
            "@test",  // moduleTag：必填，替换为实际模块标识
            "@test",  // categoryTag：必填，替换为实际分类标识
            0,        // clientVersion：必填；0 表示首次接入或当前无相关版本
            0,        // checkVersion：必填；不指定优先检查版本时传 0
            "u3d",    // type：脚本类型
            data =>
            {
                Debug.Log("版本检查 v2 成功: " + data);
                // TODO: 解析 data，按服务端返回处理模块更新
            },
            error =>
            {
                Debug.LogError("版本检查 v2 失败: " + error);
            });
    }

update_game_version_v2_multi_modules:
  method: "RXVersionCheck.UpdateGameVersion(List<VersionCheckModule> modules, string type, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  description: 多模块版本检查 v2
  code: |
    using System.Collections.Generic;
    using RuiXue;
    using RuiXue.VersionCheck;
    using UnityEngine;

    public void CheckMultiModuleVersionV2()
    {
        List<VersionCheckModule> modules = new List<VersionCheckModule>
        {
            new VersionCheckModule("@test", "@test", 0, 0),
            new VersionCheckModule("@test", "@test", 0, 0)
        };

        RXVersionCheck.UpdateGameVersion(
            modules,
            "u3d",
            data => Debug.Log("版本检查 v2 成功: " + data),
            error => Debug.LogError("版本检查 v2 失败: " + error));
    }

# ==================== 导入语句 ====================
imports:
  - "using System.Collections.Generic;"
  - "using RuiXue;"
  - "using RuiXue.VersionCheck;"
  - "using UnityEngine;"

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "接入瑞雪版本检查"
    - "Unity 版本检查"
    - "检查更新"
    - "版本检查 v2"
  actions:
    - "固定使用 RXVersionCheck.UpdateGameVersion v2 代码片段"
    - "插入前先确认 preflight.satisfied=true"
    - "不要回退到旧版本检查 MCP 或旧 API"
