platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RxRedditSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
#    暂时在demo本地添加了此SDK，后续正式使用时需要打开
#    pod 'RXSDK_Pure'
#    pod 'RXPublicToolKit'
#     RXLanguageKit要删除
     pod "RXLanguageKit"
end

target 'RxRedditSDKDemo' do
  project 'RxRedditSDKDemo/RxRedditSDKDemo.xcodeproj'
  commonPods
end

target 'RXRedditSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'RXRedditSDK.xcodeproj'

  commonPods

end
