platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'RXASAKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'RXSDK_Pure', '3.4.5'

end
