platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'


workspace 'RXAddressBookSDK.xcworkspace'

def commonPods
  
  use_frameworks!
  
end

target 'RXAddressBookSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

  commonPods

end

target 'RXAddressBookSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXAddressBookSDKDemo/RXAddressBookSDKDemo.xcodeproj'
    commonPods

end
