# 瑞雪 SDK 微信小游戏 GDT 接入规范
# Generated by MCP

overview:
  feature: gdt
  minimum_jssdk_version: "4.0.2"
  required_artifacts:
    - index.js
    - tencent-sdk.js
  note: |
    发布前必须在微信后台配置 https://api.datanexus.qq.com 安全域名。
    MCP preflight 会检查 JSSDK 版本、初始化、腾讯 SDK 注入、GDT 上报及直玩接口。

bootstrap:
  code_javascript: |
    import { SDK } from './tencent-sdk'
    SDK.setDebug(false)
    wx.TencentSDK = SDK

    const sdk = new RxSdk({
      productId: 'YOUR_PRODUCT_ID',
      channelId: 'YOUR_CHANNEL_ID',
      cpid: 'YOUR_CP_ID',
      baseUrlList: ['https://YOUR_API_HOST'],
    })

required_events:
  code_javascript: |
    sdk.reportGdt('LOAD_FINISH', {})
    sdk.reportCreateRole('role-id')
    sdk.reportUpdateLevel({ level: 10 })
    sdk.reportGdt('SUBSCRIBE', {})
    sdk.reportGdt('TUTORIAL_START', {})
    sdk.reportGdt('QUEST', { outer_action_id: 'quest-1001' })
    sdk.reportViewContent('Mall')

direct_game:
  code_javascript: |
    const status = sdk.getDirectAdStatusSync()
    sdk.onDirectAdStatusChange((nextStatus) => {
      console.log(nextStatus.isInDirectGameAd, nextStatus.isInMask, nextStatus.isEndByAbnormal)
    })

menu_events:
  note: 收藏和右上角分享监听不会自动注册，CP 应在 SDK 初始化成功后自行处理。
  code_javascript: |
    wx.onAddToFavorites(() => {
      sdk.reportAddToFavorites('default')
    })
    wx.onShareAppMessage(() => {
      sdk.reportShareAppMessage('APP_MESSAGE')
    })
    wx.onShareTimeline(() => {
      sdk.reportShareAppMessage('TIME_LINE')
    })

automatic_events:
  note: |
    启动、注册、沉默唤起由 JSSDK 自动上报。
    JSSDK 4.0.2 会查询公众号支付缓存订单并自动补报，不要调用废弃的 reportPurchase。

preflight_check:
  required:
    - JSSDK 构建产物版本 >= 4.0.2
    - tencent-sdk.js 存在且 wx.TencentSDK 已赋值
    - RxSdk / channelSDK 初始化参数存在
    - reportGdt、创角/升级/浏览 API 存在
    - getDirectAdStatusSync 与 onDirectAdStatusChange 存在
