/**
 * 瑞雪 SDK 小游戏初始化
 * Generated by MCP
 *
 * 适用平台：微信小游戏、QQ 小游戏等
 */

// ============================================================
// 步骤 1: 安装 SDK
// ============================================================

// 将构建产物 dist/ 中的 SDK 文件复制到小游戏项目目录
// 在 game.js 或入口文件中引入：
import RxSdk from './lib/channel-sdk'

// ============================================================
// 步骤 2: 初始化 SDK
// ============================================================

const sdk = new RxSdk({
    productId: 'your_product_id',    // 必填：应用 ID
    channelId: 'your_channel_id',    // 必填：渠道 ID
    cpid: 'your_cpid',              // 必填：CP 唯一 ID
    baseUrlList: [                   // 必填：域名列表
        'https://api1.ruixueyun.com',
        'https://api2.ruixueyun.com'
    ]
})

// ============================================================
// 步骤 3: 设置子渠道（可选）
// ============================================================

sdk.setSubChannelId('sub_channel_001')

// ============================================================
// 步骤 4: 登录
// ============================================================

sdk.login({}, {
    complete(res) {
        if (res.code === 0) {
            console.log('登录成功', res.data)
            // res.data.token - 登录 Token
            // res.data.openid - 用户 OpenID
            // res.data.tid - 用户 TID
        } else {
            console.error('登录失败', res.code, res.msg)
        }
    }
})

// ============================================================
// 注意事项
// ============================================================

// 1. productId、channelId、cpid、baseUrlList 为必须参数
// 2. 必须在微信开放平台配置服务器域名（request 合法域名）
// 3. SDK 初始化后自动调用 wx.login 获取 code 进行登录
// 4. 所有 API 调用采用 callback 模式：{ complete(res) { ... } }
// 5. 返回值统一格式：{ code: number, msg: string, data?: any }
// 6. code === 0 表示成功，其他值表示失败
