/**
 * 瑞雪 SDK 小游戏 - 用户通行证
 * Generated by MCP
 */

// ============================================================
// 0. 接入前强制检查
// ============================================================

// 在生成 sdk.getUserInfoByField 业务代码前，必须先确认：
// 1. 小游戏项目已引入瑞雪 JSSDK 构建产物（例如 dist/lib/channel-sdk 或项目内约定路径）。
// 2. 入口文件已 import / require 瑞雪 SDK，并完成 new RxSdk({...}) 实例化。
// 3. 初始化参数 productId、channelId、cpid、baseUrlList 已配置。
// 4. 当前 JSSDK 构建产物包含 getUserInfoByField / getUserInfoByFieldApi；如果不存在，先升级或重新替换 SDK 构建产物。
// 5. 微信/小游戏后台已配置 request 合法域名。
// 6. 必须在 SDK 初始化和登录成功后再调用 getUserInfoByField。
//
// 如果以上任一项不满足，不要只插入 sdk.getUserInfoByField 调用；
// 应先调用 minigame feature=init 生成初始化代码，或先替换到包含 getUserInfoByFieldApi 的 JSSDK 构建产物。

// ============================================================
// 1. 获取指定用户信息（getUserInfoByFieldApi）
// ============================================================

sdk.getUserInfoByField({
    // user/login/current/aas/current_account/account 六个分组均为可选，至少传一个
    user: ['openid', 'cp_user_id', 'nickname', 'avatar', 'phone', 'email', 'real_auth_name'],
    login: ['product_id', 'channel_id', 'login_time', 'last_login_time', 'method'],
    current: ['product_id', 'channel_id', 'devicecode', 'ip', 'os', 'os_version'],
    aas: ['flag', 'limit', 'aas', 'suitable_age', 'trip'],
    current_account: ['user_id', 'method', 'username', 'add_time'],
    account: ['user_id', 'method', 'username', 'add_time'],
    // Accesstoken 调用时无需传 openid/cp_user_id；服务端签名调用时二选一
    // openid: 'rxuxxxx',
    // cp_user_id: '10001'
}, {
    complete(res) {
        if (res.code === 0) {
            console.log('指定用户信息', res.data)
            // res.data.user             - 用户注册信息
            // res.data.login            - 上次登录信息
            // res.data.current          - 本次请求信息
            // res.data.aas              - 防沉迷信息
            // res.data.current_account  - 当前登录凭证信息
            // res.data.account          - 当前应用下全部登录凭证列表
        } else {
            console.error('获取指定用户信息失败', res)
        }
    }
})

// ============================================================
// 1.1 常见需求参数组合
// ============================================================

// 获取用户实名信息 + 用户绑定的登录方式信息
// 注意：“用户绑定的登录方式信息 / 查询用户绑定信息” 对应 account 当前应用下全部登录凭证列表字段。
// 如果只需要知道绑定了哪些登录方式，参数必须使用 account: ['method']。
sdk.getUserInfoByField({
    user: ['real_auth_id', 'real_auth_name', 'real_auth_id_card', 'real_auth_time', 'age', 'sex'],
    account: ['method']
}, {
    complete(res) {
        if (res.code === 0) {
            console.log('实名信息', res.data.user)
            console.log('绑定登录方式', res.data.account)
        }
    }
})

// 仅查询用户绑定信息 / 绑定的登录方式
sdk.getUserInfoByField({
    account: ['method']
}, {
    complete(res) {
        if (res.code === 0) {
            console.log('绑定登录方式', res.data.account)
        }
    }
})

// 获取基础资料 + 本次请求环境
sdk.getUserInfoByField({
    user: ['openid', 'nickname', 'avatar', 'phone', 'email'],
    current: ['ip', 'os', 'os_version']
}, {
    complete(res) {
        if (res.code === 0) {
            console.log('用户基础资料', res.data.user)
            console.log('本次请求环境', res.data.current)
        }
    }
})

// ============================================================
// 2. 修改用户信息
// ============================================================

sdk.updateInfo({
    nickname: '新昵称',
    avatar: 'https://example.com/avatar.png'
}, {
    complete(res) {
        if (res.code === 0) {
            console.log('修改成功')
        }
    }
})

// ============================================================
// 3. 获取详细用户信息（内部接口，兼容旧版）
// ============================================================

sdk._getInfo({
    complete(res) {
        if (res.code === 0) {
            console.log('详细用户信息', res.data)
        }
    }
})

// ============================================================
// 4. 获取短链接
// ============================================================

sdk.getShortUrl({ url: 'https://example.com/share?param=value' }, {
    complete(res) {
        if (res.code === 0) {
            console.log('短链接', res.data)
        }
    }
})

// ============================================================
// 注意事项
// ============================================================

// 1. 所有用户通行证接口必须在登录成功后调用
// 2. updateInfo 仅可修改昵称和头像等基本信息
// 3. 手机号和邮箱变更请使用 account_binding 相关接口
// 4. getUserInfoByField 参数参考：
//    - user: openid/cp_user_id/nickname/avatar/phone/email/real_auth_name 等
//    - login: devicecode/product_id/channel_id/login_ip/login_time/last_login_time/method
//    - current: product_id/channel_id/devicecode/ip/os/os_version
//    - aas: flag/limit/aas/suitable_age/trip
//    - current_account/account: user_id/add_time/product_id/channel_id/username/method/devicecode
// 5. 自然语言映射：
//    - “获取用户实名信息”：user: ['real_auth_id', 'real_auth_name', 'real_auth_id_card', 'real_auth_time', 'age', 'sex']
//    - “获取用户绑定的登录方式信息 / 查询用户绑定信息”：account: ['method']
//    - “获取当前登录凭证信息”：current_account: ['method', 'username']
//    - “获取防沉迷信息”：aas: ['limit', 'aas', 'flag', 'suitable_age', 'trip']
