server {
    listen 80;
    server_name res.weileapp.com;
    charset utf-8;
    expires -1;
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers *;
    add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
    if ($request_method = 'OPTIONS') {
        return 204;
    }
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Remote_addr $remote_addr;
    proxy_set_header X-Real_IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-CROS true;  # 自定义，有做跨域的时候需要加，后端会做判断
    proxy_redirect off;
    proxy_http_version 1.1;

    location ~ ^/file/(\w+) {
        root /usr/share/nginx/;
        set $file channel-sdk.$1.v$arg_version.umd.js;
        if ($arg_dev = 1) {
            set $file channel-sdk.$1.v$arg_version.dev.umd.js;
        }
        index $file;
        try_files $uri $uri/ /$file;
    }

    location ~ ^/privacy-policy/(\w+).html {
        root /usr/share/nginx/file;
        index $1.html;
    }
}
