platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXTecentCloudDNSSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    pod 'MSDKDns_C11'
end

target 'RXTecentCloudDNSSDKDemo' do
  project 'RXTecentCloudDNSSDKDemo/RXTecentCloudDNSSDKDemo.xcodeproj'
  commonPods
end

target 'RXTecentCloudDNSSDK' do
  project 'RXTecentCloudDNSSDK.xcodeproj'
  commonPods
end
