platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXVKSDK.xcworkspace'

def commonPods

  use_frameworks!
  
  pod 'VKID', '~> 2.9'
  pod 'RXLanguageKit'
#  pod 'RXSDK_Pure'
#  pod 'RXFirebaseSDK'
  
end

target 'RXVKSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

  commonPods

end

target 'RXVKSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXVKSDKDemo/RXVKSDKDemo.xcodeproj'
    commonPods

end
