// @keepTs
// @ts-nocheck
import { o9 } from "../b1/c1";
import { o2 } from "./u";
export type p13 = string | o2;
export declare class o13 {
    protected readonly d11: string;
    constructor(j15: string);
    execute(): void;
    protected e11(): void;
    protected o10(): Promise<p13>;
    protected q10(result: string): void;
    protected r10(error: o2): void;
}
export declare function t13(i15: o9): p13;
export declare function b10(h15: o9): void;
