plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ruixue.rxsdkdemo.overseas'
    compileSdk 34

    defaultConfig {
        applicationId "com.ruixue.rxsdkdemo.overseas"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        manifestPlaceholders.put("FACEBOOK_APP_ID", "7472805502731255")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    buildFeatures {
        viewBinding true
    }
}

configurations.all {
    resolutionStrategy {
        cacheChangingModulesFor 0, 'seconds'
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'com.google.android.libraries.identity.googleid:googleid:1.1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.cardview:cardview:1.0.0'
    
    // 瑞雪 SDK - 海外渠道（changing = true 表示每次都检查更新）
    implementation('com.ruixue:rxsdk_overseas:3.7.36-beta1') {
        changing = true
    }

    implementation('com.ruixue:rxsdk_base:3.7.36-beta1') {
        changing = true
    }
    
    // 瑞雪 SDK - UI 模块
    implementation('com.ruixue:rxsdk_base_ui:3.7.36-beta1') {
        changing = true
    }
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
