platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

##工作台名称
workspace 'RXGameCenterSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!

    pod 'RXSDK_Pure'
end

target 'RXGameCenterSDK' do
    ##项目在工作台下的目录名称
    project 'RXGameCenterSDK.xcodeproj'

    commonPods
end


target 'RXGameCenterSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXGameCenterSDKDemo/RXGameCenterSDKDemo.xcodeproj'
    
    use_frameworks!

    commonPods
end


