plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}
project.group 'com.ruixue'
apply from: "${rootDir}/maven.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        buildConfigField("String", "BUILD_TIME", "\"${getTimestamp()}\"")
        buildConfigField("String", "COMMIT_ID", "\"${getGitCommit()}\"")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        packagingAAR(project, android)
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

}

dependencies {
    api project(path: ':rxsdk_base')
    api project(path: ':rxsdk_base_ui')
    implementation libs.appcompat

    implementation 'io.github.lucksiege:pictureselector:v3.11.2'
    implementation "com.google.android.exoplayer:exoplayer:2.18.0"
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.18.0'


}