// @keepTs
// @ts-nocheck
export declare class r4 {
    static readonly u3: string;
    static readonly v3: string;
    static readonly w3: string;
    static readonly x3: string;
    static readonly y3: string;
    static readonly z3: string;
    static readonly a4: string;
    static readonly b4: string;
    static readonly c4: string;
    static readonly d4: string;
    static readonly e4: string;
    static readonly f4: string;
    static readonly g4: string;
    static readonly h4: string;
    static readonly i4: string;
    static readonly j4: string;
    static readonly l4: string;
    static readonly m4: string;
    static readonly s4: string;
    static readonly t4 = "dfvg";
    static readonly u4: string;
    static readonly v4: string;
    static readonly w4: string;
    static readonly x4: string;
    static readonly y4: string;
    static readonly z4: string;
    static readonly a5: string;
    static readonly b5: string;
    static readonly c5: string;
    static readonly d5: string;
    static readonly e5: string;
    static readonly f5: string;
    static readonly g5: string;
    static readonly h5: string;
    static readonly i5: string;
    static readonly j5: string;
}
