// @keepTs
// @ts-nocheck
import common from '@ohos.app.ability.common';
import { k5 } from "../b1/c1";
import { OpInitConfig } from "../e";
export declare class h1 {
    private constructor();
    private static n1;
    static getInstance(): h1;
    private l5;
    set context(value: Nullable<common.ApplicationContext>);
    get context(): Nullable<common.ApplicationContext>;
    private m5;
    set t1(value: Nullable<string>);
    get t1(): Nullable<string>;
    private n5;
    set v1(value: Nullable<OpInitConfig>);
    get v1(): Nullable<OpInitConfig>;
    private o5;
    set q1(value: Nullable<k5>);
    get q1(): Nullable<k5>;
}
