# 瑞雪 Go 服务端 SDK — Agent 接入指南
# Generated by MCP
# SDK: github.com/ruixueyun/ruixuego@v0.1.57

placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数。"

overview:
  description: |
    供 AI Agent / 开发者按固定顺序接入 ruixuego，避免漏 Init、漏 Close、漏替换 @test。
    调用业务 feature 后，按返回文档中的字段说明与示例代码落地，不要凭记忆编造签名。

recommended_flow:
  - step: 1
    action: "ruixuego feature=dependency"
    goal: 写入 go.mod 依赖
  - step: 2
    action: "ruixuego feature=init"
    goal: 生成 Init/Close 代码并写入进程入口
  - step: 3
    action: 向用户索取 APIDomain / CPID / CPKey / ProductID / ChannelID / AppKey
    goal: 替换全部 @test 与示例 CPID
  - step: 4
    action: "ruixuego feature=<业务模块> workspacePath=<Go 模块根>"
    goal: 按需生成 social / rank / bigdata / ims 等
  - step: 5
    action: 阅读返回文档中的字段约束、校验与示例
    goal: 按约束填参并复制对应示例段落
  - step: 6
    action: 编译与联调
    goal: 用 ErrTraceID 排查失败请求

agent_rules:
  - 必须实际调用 MCP 工具获取模板，禁止仅凭记忆编造 API 签名
  - 写入工程前扫描输出中的 "@test"，缺参则先问用户
  - 使用 BigData 时必须生成 defer ruixuego.Close()
  - 业务 API 优先选用 *V2 方法
  - workspacePath 传入后若 preflight 失败，先修 dependency/init
  - 数字字段（CPID、Lon/Lat、Score）禁止用字符串 "@test"
  - AES AppKey 长度必须为 16/24/32 字节

checklist:
  - go.mod 含 github.com/ruixueyun/ruixuego
  - 存在 ruixuego.Init(
  - Config 中无残留 @test
  - CPID 已改为真实数字
  - 埋点场景有 Close
  - 敏感信息未硬编码进公开仓库
  - 支付查单 OrderNo 以 v1 结尾（若使用 pay）

troubleshooting:
  - symptom: 签名错误 / 401
    fix: 检查 CPID、CPKey、AppKeys；检查系统时间
  - symptom: 埋点丢失
    fix: 确认 BigData 配置与进程退出前 Close
  - symptom: OpenID 解密失败
    fix: AppKey 长度必须 16/24/32，且 product/channel 匹配
  - symptom: ErrInvalidParam（支付查单）
    fix: OrderNo 非空且必须以 v1 结尾

code_go: |
  // Agent 落地检查伪代码（勿原样提交）
  // 1) 确认 go.mod
  // 2) 确认 Init 后：
  //    client := ruixuego.GetDefaultClient()
  // 3) 从对应 feature 返回的示例中复制业务调用
  // 4) 所有字符串业务参数来自用户真实配置，禁止留下 "@test"

notes:
  - 优先 V2 API
  - 不要跳过返回文档中的字段约束直接凭记忆写请求结构体
