# 瑞雪 Go 服务端 SDK — 角色上报 CP Role
# Generated by MCP
# SDK: github.com/ruixueyun/ruixuego@v0.1.57

placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数。"

overview:
  description: |
    CP 角色上报：新增、更新、删除、按 OpenID 列表查询。
  keywords:
    - CPRoleAdd
    - CPRoleUpdate
    - CPRoleDel
    - CPRoleListByOpenID

prerequisites:
  - ruixuego.Init 已完成
  - 已知 RxOpenID、RegionTag、CPRoleID

recommended_flow:
  - 创角 → CPRoleAdd
  - 角色信息变更 → CPRoleUpdate
  - 查询 → CPRoleListByOpenID
  - 删角 → CPRoleDel

apis:
  - name: CPRoleAdd
    signature: 'func (c *Client) CPRoleAdd(args *CPRoleInfo) error'
    when_to_use: 新增角色上报
  - name: CPRoleUpdate
    signature: 'func (c *Client) CPRoleUpdate(args *CPRoleInfo) error'
    when_to_use: 更新角色上报
  - name: CPRoleDel
    signature: 'func (c *Client) CPRoleDel(args *CPRoleInfoDel) error'
    when_to_use: 删除角色上报
  - name: CPRoleListByOpenID
    signature: 'func (c *Client) CPRoleListByOpenID(args *CPRoleList) ([]*CPRoleRes, error)'
    when_to_use: 按 OpenID 查询角色列表

api_details:
  - name: CPRoleAdd
    signature: 'func (c *Client) CPRoleAdd(args *CPRoleInfo) error'
    when_to_use: 玩家创角后上报角色
    request_fields:
      - name: RxOpenID
        type: string
        required: true
        desc: 瑞雪 openid
      - name: RegionTag
        type: string
        required: true
        desc: 区服 id
      - name: CPRoleID
        type: string
        required: true
        desc: 角色 id
      - name: Extension
        type: "map[string]interface{}"
        required: false
        desc: 扩展字段（JSON 对象）
    response_fields:
      - name: "(error)"
        type: error
        desc: 成功 nil
    validation:
      - RxOpenID / RegionTag / CPRoleID 必填业务语义字段
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func cpRoleAdd() {
      	err := ruixuego.GetDefaultClient().CPRoleAdd(&ruixuego.CPRoleInfo{
      		RxOpenID:  "@test",
      		RegionTag: "@test",
      		CPRoleID:  "@test",
      		Extension: map[string]interface{}{"@test": "@test"},
      	})
      	if err != nil {
      		log.Printf("CPRoleAdd failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      	}
      }

  - name: CPRoleUpdate
    signature: 'func (c *Client) CPRoleUpdate(args *CPRoleInfo) error'
    when_to_use: 角色信息变更后更新上报
    request_fields:
      - name: RxOpenID
        type: string
        required: true
        desc: 瑞雪 openid
      - name: RegionTag
        type: string
        required: true
        desc: 区服 id
      - name: CPRoleID
        type: string
        required: true
        desc: 角色 id
      - name: Extension
        type: "map[string]interface{}"
        required: false
        desc: 扩展字段
    response_fields:
      - name: "(error)"
        type: error
        desc: 成功 nil
    validation:
      - 与 Add 相同关键标识字段
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func cpRoleUpdate() {
      	err := ruixuego.GetDefaultClient().CPRoleUpdate(&ruixuego.CPRoleInfo{
      		RxOpenID:  "@test",
      		RegionTag: "@test",
      		CPRoleID:  "@test",
      		Extension: map[string]interface{}{"nickname": "@test"},
      	})
      	if err != nil {
      		log.Printf("CPRoleUpdate failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      	}
      }

  - name: CPRoleDel
    signature: 'func (c *Client) CPRoleDel(args *CPRoleInfoDel) error'
    when_to_use: 删除角色上报记录
    request_fields:
      - name: RxOpenID
        type: string
        required: true
        desc: 瑞雪 openid
      - name: RegionTag
        type: string
        required: true
        desc: 区服 id
      - name: CPRoleID
        type: string
        required: true
        desc: 角色 id
    response_fields:
      - name: "(error)"
        type: error
        desc: 成功 nil
    validation:
      - 三字段标识唯一角色
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func cpRoleDel() {
      	err := ruixuego.GetDefaultClient().CPRoleDel(&ruixuego.CPRoleInfoDel{
      		RxOpenID:  "@test",
      		RegionTag: "@test",
      		CPRoleID:  "@test",
      	})
      	if err != nil {
      		log.Printf("CPRoleDel failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      	}
      }

  - name: CPRoleListByOpenID
    signature: 'func (c *Client) CPRoleListByOpenID(args *CPRoleList) ([]*CPRoleRes, error)'
    when_to_use: 按 OpenID 拉取角色列表
    request_fields:
      - name: RxOpenID
        type: string
        required: true
        desc: 瑞雪 openid
      - name: Extension
        type: string
        required: false
        desc: '字段过滤："*" 全部；"nickname,avatar,sex" 指定；空忽略'
    response_fields:
      - name: "[].RxOpenID"
        type: string
        desc: 瑞雪 openid
      - name: "[].RegionTag"
        type: string
        desc: 区服 id
      - name: "[].CPRoleID"
        type: string
        desc: 角色 id
      - name: "[].ReportTime"
        type: int64
        desc: 上报时间
      - name: "[].Extension"
        type: "map[string]interface{}"
        desc: 扩展字段（若请求拉取）
    validation:
      - RxOpenID 必填
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"fmt"
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func cpRoleList() {
      	list, err := ruixuego.GetDefaultClient().CPRoleListByOpenID(&ruixuego.CPRoleList{
      		RxOpenID:  "@test",
      		Extension: "*", // * 全部；或 nickname,avatar,sex；空忽略
      	})
      	if err != nil {
      		log.Printf("CPRoleListByOpenID failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      		return
      	}
      	for _, r := range list {
      		fmt.Printf("role=%s region=%s time=%d\n", r.CPRoleID, r.RegionTag, r.ReportTime)
      	}
      }

notes:
  - RegionTag / CPRoleID 与游戏内角色体系保持一致
  - Extension 查询过滤语义见 CPRoleList.Extension 注释
