# 瑞雪 Go 服务端 SDK — IMS 即时通讯
# Generated by MCP
# SDK: github.com/ruixueyun/ruixuego@v0.1.57

placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数；示例 CPID 1000000 也必须替换。"

overview:
  description: |
    IMS 服务端能力包括登录令牌、消息发送与历史消息、会话 CRUD、成员管理和频道人数查询。
    包级 helper 用于校验用户 ID，以及生成或解析消息 ID、会话 ID；这些 helper 仅做本地计算。
  keywords: [IMSLogin, IMSSendMessage, IMSGetHistory, IMSCreateConversation, IMSChannelUsersCountV2, IMSParseConversationID]

prerequisites:
  - ruixuego.Init 已完成，并配置真实 CPID、ProductID、ChannelID 与密钥
  - 通过 ruixuego.GetDefaultClient() 获取 Client
  - UserID、群 ID、自定义会话 ID 满足 '^[a-zA-Z0-9_-]{1,32}$'
  - 已按单聊、群聊、自定义单聊或频道选择正确 ConversationID
  - AccessToken、RefreshToken、AESKey 按敏感凭据存储，不写普通日志

recommended_flow:
  - 先用 IMSVerifyUserID 校验用户 ID，再用对应 helper 生成 ConversationID
  - 客户端接入前调用 IMSLogin 获取令牌和 AESKey
  - 群聊等显式会话先 IMSCreateConversation，再 Join/Leave/Update
  - 发送消息前校验 ConversationID；发送后保存 IMSMessageAck.MsgID
  - 用 IMSGetHistory 按 MsgID 分页拉取历史，用 IMSParseMsgID 做本地解析
  - 频道监控使用 IMSChannelUsersCountV2，失败记录 err 与 ruixuego.ErrTraceID(err)

common_req_header:
  description: |
    IMS 请求结构体均嵌入 ReqHeader（Header map[string]string）；通常留空并使用 Client 默认配置。
    IMS helper 不发网络请求，无 ReqHeader。IMSSendMessage 会用 Init 配置中的 CPID 覆盖 req.CPID。

# ==================== API 目录（全量） ====================
apis:
  - {name: IMSLogin, signature: 'func (c *Client) IMSLogin(req *IMSLoginReq) (*IMSLoginResp, error)', when_to_use: 登录 IMS 并获取连接与刷新凭据}
  - {name: IMSSendMessage, signature: 'func (c *Client) IMSSendMessage(req *IMSMessage) (*IMSMessageAck, error)', when_to_use: 向合法会话发送消息}
  - {name: IMSGetHistory, signature: 'func (c *Client) IMSGetHistory(req *IMSHistoryReq) (*IMSHistoryResp, error)', when_to_use: 分页获取会话历史消息}
  - {name: IMSCreateConversation, signature: 'func (c *Client) IMSCreateConversation(req *IMSCreateConvReq) error', when_to_use: 创建群聊、频道等显式会话}
  - {name: IMSUpdateConversation, signature: 'func (c *Client) IMSUpdateConversation(req *IMSUpdateConvReq) error', when_to_use: 更新会话选项、创建者或扩展数据}
  - {name: IMSDeleteConversation, signature: 'func (c *Client) IMSDeleteConversation(req *IMSConvDeleteReq) error', when_to_use: 删除指定会话}
  - {name: IMSGetConversation, signature: 'func (c *Client) IMSGetConversation(req *IMSGetConversationReq) (*IMSConversation, error)', when_to_use: 获取指定用户视角的会话详情}
  - {name: IMSJoinConversation, signature: 'func (c *Client) IMSJoinConversation(req *IMSJoinConversationReq) error', when_to_use: 将用户加入会话}
  - {name: IMSLeaveConversation, signature: 'func (c *Client) IMSLeaveConversation(req *IMSLeaveConversationReq) error', when_to_use: 将用户批量移出会话}
  - {name: IMSUpdateConversationUserData, signature: 'func (c *Client) IMSUpdateConversationUserData(req *IMSUpdateConvUserDataReq) error', when_to_use: 更新用户在会话内的选项和扩展数据}
  - {name: IMSConversationUserList, signature: 'func (c *Client) IMSConversationUserList(req *IMSConversationUserListReq) ([]*IMSConversation, error)', when_to_use: 查询用户加入的会话列表}
  - {name: IMSChannelUsersCount, signature: 'func (c *Client) IMSChannelUsersCount(channelConvIds []string) (map[string]int64, error)', when_to_use: 旧版查询频道会话人数, deprecated: true, prefer: IMSChannelUsersCountV2}
  - {name: IMSChannelUsersCountV2, signature: 'func (c *Client) IMSChannelUsersCountV2(count *ReqIMSChannelUsersCount) (map[string]int64, error)', when_to_use: 推荐：批量查询频道会话人数}
  - {name: IMSVerifyUserID, signature: 'func IMSVerifyUserID(userID string) bool', when_to_use: 本地校验用户或会话数据 ID}
  - {name: IMSParseMsgID, signature: 'func IMSParseMsgID(msgID string) (msgSeqID int64, convType int32, conversationID string, ok bool)', when_to_use: 本地解析服务端消息 ID}
  - {name: IMSParseConversationID, signature: 'func IMSParseConversationID(conversationID string) (convType int32, conversationIDData string, ok bool)', when_to_use: 本地解析并校验会话 ID}
  - {name: IMSGetSingleConversationID, signature: 'func IMSGetSingleConversationID(sender, receiver string) string', when_to_use: 本地生成稳定的单聊会话 ID}
  - {name: IMSGetGroupConversationID, signature: 'func IMSGetGroupConversationID(groupID string) string', when_to_use: 本地生成群聊会话 ID}
  - {name: IMSGetCustomSingleConversationID, signature: 'func IMSGetCustomSingleConversationID(customID string) string', when_to_use: 本地生成自定义单聊会话 ID}
  - {name: IMSParseSingleConversationIDData, signature: 'func IMSParseSingleConversationIDData(data string) (minUserID, maxUserID string, ok bool)', when_to_use: 本地解析单聊会话数据}

# ==================== 详细说明（推荐/唯一 API） ====================
api_details:
  - name: IMSLogin
    signature: 'func (c *Client) IMSLogin(req *IMSLoginReq) (*IMSLoginResp, error)'
    when_to_use: 为用户获取 IMS Entry 连接令牌、刷新令牌和 AES 密钥
    request_fields:
      - {name: UserID, type: string, required: true, desc: CP 下唯一用户 ID, constraint: 建议先通过 IMSVerifyUserID}
      - {name: ProductID, type: string, required: true, desc: 产品 ID, constraint: 使用真实产品配置}
      - {name: ChannelID, type: string, required: true, desc: 渠道 ID, constraint: 使用真实渠道配置}
      - {name: DeviceCode, type: string, required: true, desc: 设备唯一标识, constraint: 不得固定写死或跨用户复用}
      - {name: CPID, type: uint32, required: true, desc: CP 数字 ID, constraint: 必须替换示例值}
      - {name: ClientType, type: int32, required: true, desc: 客户端类型, constraint: 按 IMS 约定枚举传值}
    response_fields:
      - {name: AccessToken, type: string, desc: Entry 连接令牌}
      - {name: AccessTokenExpire, type: int64, desc: 连接令牌过期时间，毫秒}
      - {name: RefreshToken, type: string, desc: 刷新令牌}
      - {name: RefreshTokenExpire, type: int64, desc: 刷新令牌过期时间，毫秒}
      - {name: AESKey, type: string, desc: 64 位十六进制字符串，解析后为 32 Byte 密钥}
    validation: [v0.1.57 SDK 不做本地字段校验，调用方必须校验 UserID 和必填配置]
    errors: [令牌和 AESKey 不得写入日志, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("fmt"; "log"; "github.com/ruixueyun/ruixuego")
      func imsLogin() {
          req := &ruixuego.IMSLoginReq{UserID: "@test", ProductID: "@test", ChannelID: "@test", DeviceCode: "@test", CPID: 1000000, /* 【必须替换】 */ ClientType: 1}
          res, err := ruixuego.GetDefaultClient().IMSLogin(req); if err != nil { log.Printf("ims login: %v trace=%s", err, ruixuego.ErrTraceID(err)); return }; fmt.Println("access expires:", res.AccessTokenExpire)
      }

  - name: IMSSendMessage
    signature: 'func (c *Client) IMSSendMessage(req *IMSMessage) (*IMSMessageAck, error)'
    when_to_use: 服务端向单聊、群聊、自定义单聊或频道发送消息
    request_fields:
      - {name: MilliTS, type: int64, required: false, desc: 消息毫秒时间戳, constraint: 0 时 SDK 自动取当前时间}
      - {name: UUID, type: string, required: false, desc: 客户端消息唯一 ID, constraint: 空时 SDK 自动生成；重试幂等应自行持久化}
      - {name: Sender, type: string, required: true, desc: 发送者 UserID, constraint: 应通过 IMSVerifyUserID}
      - {name: Receivers, type: '[]string', required: false, desc: 接收者列表, constraint: 按会话类型使用}
      - {name: ConversationID, type: string, required: true, desc: 会话 ID, constraint: 必须能被 IMSParseConversationID 解析}
      - {name: ConvType, type: int32, required: false, desc: 会话类型, constraint: 0 时 SDK 从 ConversationID 推导}
      - {name: CPID, type: uint32, required: false, desc: 请求字段会被 Init 的 CPID 覆盖；以全局配置为准}
      - {name: ProductID, type: string, required: true, desc: 产品 ID, constraint: 非空}
      - {name: ChannelID, type: string, required: true, desc: 渠道 ID, constraint: 非空}
      - {name: Content, type: string, required: true, desc: 消息正文, constraint: 长度与编码按服务端规则}
      - {name: Attr/Option/Status/ClientType/Type/SubType/InboxID/UnreadCount/ReceiverNum, type: integer, required: false, desc: 消息控制字段, constraint: 按 IMS 协议枚举和位定义传值}
      - {name: Ext/IMSExt, type: 'map[string]string', required: false, desc: CP/IMS 扩展字段, constraint: IMSExt 不应由 CP 任意修改}
    response_fields:
      - {name: MsgID, type: string, desc: 服务端消息 ID}
      - {name: UUID, type: string, desc: 对应请求 UUID}
      - {name: InboxID, type: int64, desc: 收件箱 ID}
      - {name: MilliTS, type: int64, desc: 服务端消息时间戳}
    validation: [ConversationID 非法返回 ErrInvalidIMSConversationID, UUID/MilliTS 为空时由 SDK 填充, CPID 强制取全局配置]
    errors: [重试复用同一 UUID 防止重复消息, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("fmt"; "log"; "github.com/ruixueyun/ruixuego")
      func imsSendMessage() {
          convID := ruixuego.IMSGetSingleConversationID("@test", "@test")
          req := &ruixuego.IMSMessage{UUID: "@test", Sender: "@test", ConversationID: convID, ProductID: "@test", ChannelID: "@test", Content: "@test", Type: 1}
          // CPID 由 SDK 用 Init 配置覆盖，无需在请求中依赖填写
          ack, err := ruixuego.GetDefaultClient().IMSSendMessage(req); if err != nil { log.Printf("send: %v trace=%s", err, ruixuego.ErrTraceID(err)); return }; fmt.Println(ack.MsgID)
      }

  - name: IMSGetHistory
    signature: 'func (c *Client) IMSGetHistory(req *IMSHistoryReq) (*IMSHistoryResp, error)'
    when_to_use: 按起始消息 ID 分页读取指定会话历史
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 会话 ID, constraint: 应先用 IMSParseConversationID 校验}
      - {name: StartMsgID, type: string, required: false, desc: 分页起始消息 ID, constraint: 非空时应能被 IMSParseMsgID 解析}
      - {name: FetchCount, type: int32, required: true, desc: 本次获取条数, constraint: 使用正数并限制批量大小}
    response_fields:
      - {name: Messages, type: '[]*IMSMessage', desc: 历史消息数组}
      - {name: Count, type: int32, desc: 本页消息数}
      - {name: Done, type: bool, desc: 是否已拉取完毕}
    validation: [v0.1.57 SDK 不做本地参数校验，调用方校验 ConversationID、StartMsgID 和 FetchCount]
    errors: [分页应以服务端返回和 Done 驱动，避免死循环, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("fmt"; "log"; "github.com/ruixueyun/ruixuego")
      func imsGetHistory() {
          req := &ruixuego.IMSHistoryReq{ConversationID: "@test", StartMsgID: "@test", FetchCount: 50}
          res, err := ruixuego.GetDefaultClient().IMSGetHistory(req); if err != nil { log.Printf("history: %v trace=%s", err, ruixuego.ErrTraceID(err)); return }; fmt.Printf("count=%d done=%v\n", res.Count, res.Done)
      }

  - name: IMSCreateConversation
    signature: 'func (c *Client) IMSCreateConversation(req *IMSCreateConvReq) error'
    when_to_use: 创建群聊、频道或业务管理的会话及初始成员
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 会话 ID, constraint: 使用 helper 生成或按合法格式构造}
      - {name: ConvType, type: int32, required: true, desc: 会话类型, constraint: 1 单聊、2 群聊、3 自定义单聊、4 频道}
      - {name: Creator, type: string, required: true, desc: 会话创建者 UserID, constraint: 应通过 IMSVerifyUserID}
      - {name: Members, type: '[]*MemberInfo', required: false, desc: 初始成员, constraint: MemberInfo.UserID 必须合法}
      - {name: Option, type: int64, required: false, desc: 会话选项, constraint: 按 IMS 位定义}
      - {name: Ext/IMSExt, type: 'map[string]string', required: false, desc: CP/IMS 会话扩展, constraint: IMSExt 不可由 CP 任意更改}
    response_fields: [{name: error, type: error, desc: nil 表示创建成功}]
    validation: [SDK 不做本地校验；调用前校验 ConversationID、ConvType、Creator 和成员]
    errors: [重复创建与成员上限由服务端判定, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("log"; "github.com/ruixueyun/ruixuego")
      func imsCreateConversation() {
          id := ruixuego.IMSGetGroupConversationID("@test")
          members := []*ruixuego.MemberInfo{
          	{UserID: "@test"},
          	{UserID: "@test"},
          }
          req := &ruixuego.IMSCreateConvReq{
          	ConversationID: id,
          	ConvType:       ruixuego.IMSConvTypeGroup,
          	Creator:        "@test",
          	Members:        members,
          	Ext:            map[string]string{"title": "@test"},
          }
          if err := ruixuego.GetDefaultClient().IMSCreateConversation(req); err != nil { log.Printf("create conv: %v trace=%s", err, ruixuego.ErrTraceID(err)) }
      }

  - name: IMSUpdateConversation
    signature: 'func (c *Client) IMSUpdateConversation(req *IMSUpdateConvReq) error'
    when_to_use: 更新会话选项、创建者或 CP 扩展信息
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 会话 ID, constraint: 必须合法且已存在}
      - {name: Option, type: int64, required: false, desc: 会话选项, constraint: 按 IMS 位定义}
      - {name: Creator, type: string, required: false, desc: 新创建者, constraint: 非空时应为合法 UserID}
      - {name: Ext, type: 'map[string]string', required: false, desc: CP 会话扩展, constraint: 明确覆盖/合并语义}
      - {name: IMSExt, type: 'map[string]string', required: false, desc: IMS 扩展, constraint: SDK 注释标明不可更改}
    response_fields: [{name: error, type: error, desc: nil 表示更新成功}]
    validation: [SDK 不做本地校验；不要尝试修改 IMSExt]
    errors: [无权限或会话不存在由服务端返回, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("log"; "github.com/ruixueyun/ruixuego")
      func imsUpdateConversation() {
          req := &ruixuego.IMSUpdateConvReq{ConversationID: "@test", Creator: "@test", Ext: map[string]string{"title": "@test"}}
          if err := ruixuego.GetDefaultClient().IMSUpdateConversation(req); err != nil { log.Printf("update conv: %v trace=%s", err, ruixuego.ErrTraceID(err)) }
      }

  - name: IMSDeleteConversation
    signature: 'func (c *Client) IMSDeleteConversation(req *IMSConvDeleteReq) error'
    when_to_use: 由有权限的操作人删除会话
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 要删除的会话 ID, constraint: 必须合法且已存在}
      - {name: UserID, type: string, required: true, desc: 操作人用户 ID, constraint: 应通过 IMSVerifyUserID 且具备权限}
    response_fields: [{name: error, type: error, desc: nil 表示删除成功}]
    validation: [SDK 不做本地校验；调用方校验两个字段及操作权限]
    errors: [删除可能不可逆，应先做业务确认和审计, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("log"; "github.com/ruixueyun/ruixuego")
      func imsDeleteConversation() {
          req := &ruixuego.IMSConvDeleteReq{ConversationID: "@test", UserID: "@test"}
          if err := ruixuego.GetDefaultClient().IMSDeleteConversation(req); err != nil { log.Printf("delete conv: %v trace=%s", err, ruixuego.ErrTraceID(err)) }
      }

  - name: IMSGetConversation
    signature: 'func (c *Client) IMSGetConversation(req *IMSGetConversationReq) (*IMSConversation, error)'
    when_to_use: 获取用户视角的会话元数据、成员与扩展信息
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 会话 ID, constraint: 必须合法}
      - {name: UserID, type: string, required: true, desc: 查询用户 ID, constraint: 应通过 IMSVerifyUserID}
    response_fields:
      - {name: ConversationID, type: string, desc: 会话 ID}
      - {name: Attr/Option/UserAttr/UserOption, type: int64, desc: 会话及用户属性/选项}
      - {name: CreateMilliTS/UpdateMilliTS/JoinMilliTS, type: int64, desc: 毫秒时间戳}
      - {name: Creator, type: string, desc: 创建者 UserID}
      - {name: UserExt/Ext, type: 'map[string]string', desc: 用户/会话扩展}
      - {name: Members, type: '[]string', desc: 成员 UserID 列表}
      - {name: Type/Status, type: int8, desc: 会话类型与状态}
    validation: [SDK 不做本地参数校验]
    errors: [用户不可见或会话不存在由服务端返回, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("fmt"; "log"; "github.com/ruixueyun/ruixuego")
      func imsGetConversation() {
          res, err := ruixuego.GetDefaultClient().IMSGetConversation(&ruixuego.IMSGetConversationReq{ConversationID: "@test", UserID: "@test"})
          if err != nil { log.Printf("get conv: %v trace=%s", err, ruixuego.ErrTraceID(err)); return }; fmt.Printf("type=%d creator=%s members=%v\n", res.Type, res.Creator, res.Members)
      }

  - name: IMSJoinConversation
    signature: 'func (c *Client) IMSJoinConversation(req *IMSJoinConversationReq) error'
    when_to_use: 将一个用户加入群聊或频道并设置会话内属性
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 目标会话 ID, constraint: 必须合法且已存在}
      - {name: UserID, type: string, required: true, desc: 加入用户 ID, constraint: 应通过 IMSVerifyUserID}
      - {name: Option, type: int64, required: false, desc: 用户会话选项, constraint: 按 IMS 位定义}
      - {name: Ext, type: 'map[string]string', required: false, desc: 用户扩展信息, constraint: 避免放敏感信息}
      - {name: ClientType, type: int32, required: false, desc: 用户客户端类型, constraint: 按 IMS 枚举}
    response_fields: [{name: error, type: error, desc: nil 表示加入成功}]
    validation: [SDK 不做本地参数校验]
    errors: [重复加入与容量限制由服务端判定, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("log"; "github.com/ruixueyun/ruixuego")
      func imsJoinConversation() {
          req := &ruixuego.IMSJoinConversationReq{ConversationID: "@test", UserID: "@test", ClientType: 1, Ext: map[string]string{"role": "@test"}}
          if err := ruixuego.GetDefaultClient().IMSJoinConversation(req); err != nil { log.Printf("join conv: %v trace=%s", err, ruixuego.ErrTraceID(err)) }
      }

  - name: IMSLeaveConversation
    signature: 'func (c *Client) IMSLeaveConversation(req *IMSLeaveConversationReq) error'
    when_to_use: 让用户一次离开一个或多个会话
    request_fields:
      - {name: ConversationIDs, type: '[]string', required: true, desc: 要离开的会话 ID 列表, constraint: 非空且每项合法}
      - {name: UserID, type: string, required: true, desc: 离开用户 ID, constraint: 应通过 IMSVerifyUserID}
      - {name: ClientType, type: int32, required: false, desc: 用户客户端类型, constraint: 按 IMS 枚举}
    response_fields: [{name: error, type: error, desc: nil 表示批量离开成功}]
    validation: [SDK 不做本地参数校验；调用方限制批量大小]
    errors: [批量请求的部分成功语义以服务端为准, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("log"; "github.com/ruixueyun/ruixuego")
      func imsLeaveConversation() {
          req := &ruixuego.IMSLeaveConversationReq{ConversationIDs: []string{"@test", "@test"}, UserID: "@test", ClientType: 1}
          if err := ruixuego.GetDefaultClient().IMSLeaveConversation(req); err != nil { log.Printf("leave conv: %v trace=%s", err, ruixuego.ErrTraceID(err)) }
      }

  - name: IMSUpdateConversationUserData
    signature: 'func (c *Client) IMSUpdateConversationUserData(req *IMSUpdateConvUserDataReq) error'
    when_to_use: 更新用户在指定会话内的选项、扩展或客户端类型
    request_fields:
      - {name: ConversationID, type: string, required: true, desc: 会话 ID, constraint: 必须合法且已存在}
      - {name: UserID, type: string, required: true, desc: 用户 ID, constraint: 应通过 IMSVerifyUserID}
      - {name: Option, type: int64, required: false, desc: 用户会话选项, constraint: 按 IMS 位定义}
      - {name: Ext, type: 'map[string]string', required: false, desc: 用户扩展信息, constraint: 明确覆盖/合并语义}
      - {name: ClientType, type: int32, required: false, desc: 客户端类型, constraint: 按 IMS 枚举}
    response_fields: [{name: error, type: error, desc: nil 表示更新成功}]
    validation: [SDK 不做本地参数校验]
    errors: [用户不在会话中或无权限由服务端返回, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("log"; "github.com/ruixueyun/ruixuego")
      func imsUpdateConversationUserData() {
          req := &ruixuego.IMSUpdateConvUserDataReq{ConversationID: "@test", UserID: "@test", Option: 1, Ext: map[string]string{"role": "@test"}, ClientType: 1}
          if err := ruixuego.GetDefaultClient().IMSUpdateConversationUserData(req); err != nil { log.Printf("update conv user: %v trace=%s", err, ruixuego.ErrTraceID(err)) }
      }

  - name: IMSConversationUserList
    signature: 'func (c *Client) IMSConversationUserList(req *IMSConversationUserListReq) ([]*IMSConversation, error)'
    when_to_use: 查询某用户已加入的会话及其用户视角数据
    request_fields:
      - {name: UserID, type: string, required: true, desc: 用户 ID, constraint: 应通过 IMSVerifyUserID}
    response_fields:
      - {name: conversations, type: '[]*IMSConversation', desc: 用户会话列表}
      - {name: IMSConversation, type: object, desc: 会话 ID、属性、时间、创建者、扩展、成员、类型与状态}
    validation: [SDK 不做本地参数校验]
    errors: [空列表不是错误, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("fmt"; "log"; "github.com/ruixueyun/ruixuego")
      func imsConversationUserList() {
          list, err := ruixuego.GetDefaultClient().IMSConversationUserList(&ruixuego.IMSConversationUserListReq{UserID: "@test"})
          if err != nil { log.Printf("user conv list: %v trace=%s", err, ruixuego.ErrTraceID(err)); return }; for _, c := range list { fmt.Println(c.ConversationID, c.Type, c.Status) }
      }

  - name: IMSChannelUsersCountV2
    signature: 'func (c *Client) IMSChannelUsersCountV2(count *ReqIMSChannelUsersCount) (map[string]int64, error)'
    when_to_use: 批量查询频道类型会话的当前玩家数量
    request_fields:
      - {name: ChannelConvIds, type: '[]string', required: true, desc: 频道 ConversationID 列表, constraint: 非空；每项应解析为 IMSConvTypeChannel}
      - {name: ReqHeader.Header, type: 'map[string]string', required: false, desc: 请求头覆盖, constraint: 通常留空}
    response_fields:
      - {name: counts, type: 'map[string]int64', desc: ConversationID 到玩家数量的映射}
    validation: [SDK 不做本地参数和会话类型校验；count 不可为 nil]
    errors: [返回映射可能不包含无数据 ID，读取时需检查 key, 网络/签名/业务失败需记录 trace ID]
    code_go: |
      package example
      import ("fmt"; "log"; "github.com/ruixueyun/ruixuego")
      func imsChannelUsersCountV2() {
          req := &ruixuego.ReqIMSChannelUsersCount{ChannelConvIds: []string{"$4$@test"}}
          res, err := ruixuego.GetDefaultClient().IMSChannelUsersCountV2(req); if err != nil { log.Printf("channel count: %v trace=%s", err, ruixuego.ErrTraceID(err)); return }; fmt.Printf("%+v\n", res)
      }

  - name: IMSVerifyUserID
    signature: 'func IMSVerifyUserID(userID string) bool'
    when_to_use: 生成会话 ID 或调用 IMS 网络 API 前做快速本地校验
    request_fields:
      - {name: userID, type: string, required: true, desc: 待校验 ID, constraint: '正则 ^[a-zA-Z0-9_-]{1,32}$'}
    response_fields: [{name: valid, type: bool, desc: true 表示格式合法}]
    validation: [空串、超过 32 字符或含其他字符返回 false]
    errors: [仅校验格式，不证明用户存在或有权限]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsVerifyUserID() { fmt.Println(ruixuego.IMSVerifyUserID("@test")) }

  - name: IMSParseMsgID
    signature: 'func IMSParseMsgID(msgID string) (msgSeqID int64, convType int32, conversationID string, ok bool)'
    when_to_use: 从服务端 MsgID 提取消息序号、会话类型和会话 ID
    request_fields:
      - {name: msgID, type: string, required: true, desc: IMS 消息 ID, constraint: '格式为非零十进制序号.ConversationID'}
    response_fields:
      - {name: msgSeqID, type: int64, desc: 非零消息序号}
      - {name: convType, type: int32, desc: 会话类型 1/2/3/4}
      - {name: conversationID, type: string, desc: 完整会话 ID}
      - {name: ok, type: bool, desc: 是否解析成功}
    validation: [空串、缺少点号、序号为 0 或会话 ID 非法时 ok=false]
    errors: [无 error 返回值，必须检查 ok 后再使用其余结果]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsParseMsgID() { seq, typ, id, ok := ruixuego.IMSParseMsgID("@test"); if !ok { return }; fmt.Println(seq, typ, id) }

  - name: IMSParseConversationID
    signature: 'func IMSParseConversationID(conversationID string) (convType int32, conversationIDData string, ok bool)'
    when_to_use: 校验 ConversationID 并拆出类型与数据部分
    request_fields:
      - {name: conversationID, type: string, required: true, desc: 会话 ID, constraint: '$<type>$<data>；type 仅 1/2/3/4'}
    response_fields:
      - {name: convType, type: int32, desc: 1 单聊、2 群聊、3 自定义单聊、4 频道}
      - {name: conversationIDData, type: string, desc: 会话数据部分}
      - {name: ok, type: bool, desc: 是否格式合法}
    validation: [单聊 data 必须是两个合法 UserID 以冒号连接, 其他类型 data 必须匹配 1 到 32 位字母数字下划线横线]
    errors: [无 error 返回值，必须检查 ok]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsParseConversationID() { typ, data, ok := ruixuego.IMSParseConversationID("@test"); if !ok { return }; fmt.Println(typ, data) }

  - name: IMSGetSingleConversationID
    signature: 'func IMSGetSingleConversationID(sender, receiver string) string'
    when_to_use: 为两个用户生成与传入顺序无关的稳定单聊 ConversationID
    request_fields:
      - {name: sender, type: string, required: true, desc: 一方 UserID, constraint: 必须通过 IMSVerifyUserID}
      - {name: receiver, type: string, required: true, desc: 另一方 UserID, constraint: 必须通过 IMSVerifyUserID}
    response_fields: [{name: conversationID, type: string, desc: '$1$较小UserID:较大UserID；非法时为空串'}]
    validation: [任一 ID 非法返回空串, SDK 按字符串字典序固定双方顺序]
    errors: [生成后仍应检查结果非空]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsGetSingleConversationID() { id := ruixuego.IMSGetSingleConversationID("@test", "@test"); if id == "" { return }; fmt.Println(id) }

  - name: IMSGetGroupConversationID
    signature: 'func IMSGetGroupConversationID(groupID string) string'
    when_to_use: 从业务群 ID 生成群聊 ConversationID
    request_fields:
      - {name: groupID, type: string, required: true, desc: 群唯一 ID, constraint: 必须匹配 1 到 32 位合法字符}
    response_fields: [{name: conversationID, type: string, desc: '$2$groupID；非法时为空串'}]
    validation: [groupID 未通过 IMSVerifyUserID 时返回空串]
    errors: [仅生成格式，不创建远端会话]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsGetGroupConversationID() { id := ruixuego.IMSGetGroupConversationID("@test"); if id == "" { return }; fmt.Println(id) }

  - name: IMSGetCustomSingleConversationID
    signature: 'func IMSGetCustomSingleConversationID(customID string) string'
    when_to_use: 业务已有稳定自定义标识并需要自定义单聊类型时生成 ID
    request_fields:
      - {name: customID, type: string, required: true, desc: 自定义单聊 ID 数据, constraint: 必须匹配 1 到 32 位合法字符}
    response_fields: [{name: conversationID, type: string, desc: '$3$customID；非法时为空串'}]
    validation: [customID 未通过 IMSVerifyUserID 时返回空串]
    errors: [customID 唯一性由业务保证；仅生成格式，不创建远端会话]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsGetCustomSingleConversationID() { id := ruixuego.IMSGetCustomSingleConversationID("@test"); if id == "" { return }; fmt.Println(id) }

  - name: IMSParseSingleConversationIDData
    signature: 'func IMSParseSingleConversationIDData(data string) (minUserID, maxUserID string, ok bool)'
    when_to_use: 已取得单聊 ConversationIDData 后解析双方 UserID
    request_fields:
      - {name: data, type: string, required: true, desc: 单聊会话数据部分, constraint: 两个合法 UserID 以冒号连接}
    response_fields:
      - {name: minUserID, type: string, desc: 字典序较小的 UserID}
      - {name: maxUserID, type: string, desc: 字典序较大的 UserID}
      - {name: ok, type: bool, desc: 是否解析成功}
    validation: [缺少冒号或任一 UserID 非法时 ok=false, 返回值总按字典序重排]
    errors: [传完整 ConversationID 会失败，应先用 IMSParseConversationID 获取 data]
    code_go: |
      package example
      import ("fmt"; "github.com/ruixueyun/ruixuego")
      func imsParseSingleConversationIDData() { minID, maxID, ok := ruixuego.IMSParseSingleConversationIDData("@test:@test"); if !ok { return }; fmt.Println(minID, maxID) }

notes:
  - CPID 示例统一使用 1000000 并标注【必须替换】；生产值应来自真实配置
  - IMSSendMessage 会把 req.CPID 覆盖为 ruixuego.Init 配置中的 CPID，必须确保全局配置正确
  - UserID、groupID、customID 仅允许 1 到 32 位字母、数字、下划线和横线
  - 会话类型常量：IMSConvTypeSingle=1、IMSConvTypeGroup=2、IMSConvTypeCustomSingle=3、IMSConvTypeChannel=4
  - 频道会话不支持离线消息、已读、撤回等能力
  - AccessToken、RefreshToken、AESKey、消息正文及扩展字段均按敏感数据处理
  - IMSChannelUsersCount 仅兼容旧代码；新代码使用 IMSChannelUsersCountV2
