# 瑞雪 Go 服务端 SDK — 运营工具 Operation
# Generated by MCP
# SDK: github.com/ruixueyun/ruixuego@v0.1.57

placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数。"

overview:
  description: |
    CDKey 兑换（ExtensionExchange）与主播游戏内显示码（ExtensionGameDisplayV2）。
  keywords:
    - ExtensionExchange
    - ExtensionGameDisplayV2
    - CdKey

prerequisites:
  - ruixuego.Init 已完成
  - 持有合法 CDKey / GameID

recommended_flow:
  - 玩家提交 CDKey → ExtensionExchange → 按返回道具发奖
  - 需要主播福利码展示 → ExtensionGameDisplayV2

apis:
  - name: ExtensionExchange
    signature: 'func (c *Client) ExtensionExchange(arg *ExtensionExchangeReq) ([]*ExtensionProp, error)'
    when_to_use: CDKey 兑换道具
  - name: ExtensionGameDisplay
    signature: 'func (c *Client) ExtensionGameDisplay(gameID string) (*GameDisplayWelfareCodeInfoExp, error)'
    when_to_use: 旧版主播显示码
    deprecated: true
    prefer: ExtensionGameDisplayV2
  - name: ExtensionGameDisplayV2
    signature: 'func (c *Client) ExtensionGameDisplayV2(req *ReqExtensionGameDisplay) (*GameDisplayWelfareCodeInfoExp, error)'
    when_to_use: 推荐：查询主播游戏内显示码

api_details:
  - name: ExtensionExchange
    signature: 'func (c *Client) ExtensionExchange(arg *ExtensionExchangeReq) ([]*ExtensionProp, error)'
    when_to_use: 玩家兑换 CDKey，返回道具列表
    request_fields:
      - name: CdKey
        type: string
        required: true
        desc: 兑换码
      - name: OpenID
        type: string
        required: false
        desc: 瑞雪 openid（建议填写；SDK 本地仅强制校验 CdKey、CpUserID）
      - name: CpUserID
        type: string
        required: true
        desc: CP 用户 ID
        constraint: 空则 ErrInvalidParam
    response_fields:
      - name: "[].PropID"
        type: string
        desc: 道具 ID
      - name: "[].PropName"
        type: string
        desc: 道具名称
      - name: "[].PropNum"
        type: string
        desc: 道具数量
    validation:
      - CdKey 或 CpUserID 为空 → ErrInvalidParam
      - OpenID 本地不强制，但业务上建议一并传入
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"fmt"
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func extensionExchange() {
      	props, err := ruixuego.GetDefaultClient().ExtensionExchange(&ruixuego.ExtensionExchangeReq{
      		CdKey:    "@test",
      		OpenID:   "@test", // 建议填写
      		CpUserID: "@test",
      	})
      	if err != nil {
      		log.Printf("exchange failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      		return
      	}
      	for _, p := range props {
      		fmt.Printf("prop id=%s name=%s num=%s\n", p.PropID, p.PropName, p.PropNum)
      	}
      }

  - name: ExtensionGameDisplayV2
    signature: 'func (c *Client) ExtensionGameDisplayV2(req *ReqExtensionGameDisplay) (*GameDisplayWelfareCodeInfoExp, error)'
    when_to_use: 按 GameID 获取主播福利/显示码信息
    request_fields:
      - name: GameID
        type: string
        required: true
        desc: 游戏 ID
    response_fields:
      - name: PromoterID
        type: string
        desc: 主播 id
      - name: PromoID
        type: string
        desc: 福利码 ID
      - name: RefreshPeriod
        type: int
        desc: 刷新周期（分钟）
      - name: PromoName
        type: string
        desc: 福利码名称
      - name: GiftName
        type: string
        desc: 礼包名称
      - name: PromoValidStart
        type: string
        desc: 有效开始时间
      - name: PromoValidEnd
        type: string
        desc: 有效结束时间
      - name: PromoCode
        type: string
        desc: 福利码
      - name: RefreshPeriodExp
        type: int64
        desc: 刷新周期过期时间
      - name: Polling
        type: int
        desc: 客户端轮询时间（秒）
    validation:
      - GameID 不可为空
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"fmt"
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func extensionGameDisplayV2() {
      	info, err := ruixuego.GetDefaultClient().ExtensionGameDisplayV2(&ruixuego.ReqExtensionGameDisplay{
      		GameID: "@test",
      	})
      	if err != nil {
      		log.Printf("display failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      		return
      	}
      	fmt.Printf("promo_code=%s gift=%s polling=%d\n", info.PromoCode, info.GiftName, info.Polling)
      }

notes:
  - CDKey 兑换成功后按 Prop 列表发奖，注意幂等
  - 显示码优先 ExtensionGameDisplayV2
