# 瑞雪 Go 服务端 SDK — 通行证 Passport
# Generated by MCP
# SDK: github.com/ruixueyun/ruixuego@v0.1.57

placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数。"

overview:
  description: |
    将瑞雪 OpenID 与 CP 侧 UserID 建立/更新映射（UpdateCPuserIDV2）。
    常见于登录成功后、账号绑定、或 CP 侧改号同步。
  keywords:
    - UpdateCPuserIDV2
    - OpenID
    - CPUserID

prerequisites:
  - ruixuego.Init 已完成
  - 已拿到用户瑞雪 OpenID 与 CP UserID

recommended_flow:
  - 客户端登录成功，服务端解密/校验 OpenID
  - 调用 UpdateCPuserIDV2 写入映射
  - 失败时打印 ErrTraceID 后重试或告警

common_req_header:
  description: V2 请求嵌入 ReqHeader；一般可留空。

apis:
  - name: UpdateCPuserID
    signature: 'func (c *Client) UpdateCPuserID(openID, cpUserID string) error'
    when_to_use: 旧版更新 CP UserID 映射
    deprecated: true
    prefer: UpdateCPuserIDV2
  - name: UpdateCPuserIDV2
    signature: 'func (c *Client) UpdateCPuserIDV2(req *UpdateCPUserIDRequest) error'
    when_to_use: 推荐：更新 OpenID ↔ CPUserID 映射

api_details:
  - name: UpdateCPuserIDV2
    signature: 'func (c *Client) UpdateCPuserIDV2(req *UpdateCPUserIDRequest) error'
    when_to_use: 登录或绑定时把瑞雪 OpenID 与 CP 用户 ID 关联
    request_fields:
      - name: OpenID
        type: string
        required: true
        desc: 瑞雪 openid
        constraint: 替换 @test 为真实 OpenID
      - name: CPUserID
        type: string
        required: true
        desc: CP 侧用户唯一 ID
        constraint: 替换 @test
      - name: ReqHeader.Header
        type: "map[string]string"
        required: false
        desc: 可选请求头
    response_fields:
      - name: "(error)"
        type: error
        desc: 成功返回 nil；失败返回 error
    validation:
      - OpenID / CPUserID 为空可能导致服务端参数错误（以返回为准）
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func updateCPUserIDV2() {
      	err := ruixuego.GetDefaultClient().UpdateCPuserIDV2(&ruixuego.UpdateCPUserIDRequest{
      		OpenID:   "@test", // 瑞雪 openid
      		CPUserID: "@test", // CP 侧 user_id
      	})
      	if err != nil {
      		log.Printf("UpdateCPuserIDV2 failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      		return
      	}
      }

notes:
  - OpenID / CPUserID 必须全部替换 @test
  - 优先 V2；勿在新代码使用 UpdateCPuserID
