# 瑞雪 Go 服务端 SDK — 推送 Pusher
# Generated by MCP
# SDK: github.com/ruixueyun/ruixuego@v0.1.57

placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数。"

overview:
  description: |
    服务端推送（PusherPushV2）：按 OpenID / CPUserID 等目标下发通知。
  keywords:
    - PusherPushV2
    - PusherPushReq
    - Target

prerequisites:
  - ruixuego.Init 已完成
  - 已知 ProductID / ChannelID 与推送目标

recommended_flow:
  - 组装 PushInfo（标题/内容/payload）与 Target
  - 调用 PusherPushV2
  - 测试通道可查看 DeviceTypeMap

apis:
  - name: PusherPush
    signature: 'func (c *Client) PusherPush(req *PusherPushReq, productID, channelID string) (*PusherPushRes, error)'
    when_to_use: 旧版推送
    deprecated: true
    prefer: PusherPushV2
  - name: PusherPushV2
    signature: 'func (c *Client) PusherPushV2(req *ReqPusher) (*PusherPushRes, error)'
    when_to_use: 推荐：服务端推送

api_details:
  - name: PusherPushV2
    signature: 'func (c *Client) PusherPushV2(req *ReqPusher) (*PusherPushRes, error)'
    when_to_use: 向指定用户下发推送通知
    request_fields:
      - name: ProductID
        type: string
        required: true
        desc: 产品 ID
      - name: ChannelID
        type: string
        required: true
        desc: 渠道 ID
      - name: Req.PushInfo.Title
        type: string
        required: true
        desc: 推送标题
      - name: Req.PushInfo.Content
        type: string
        required: true
        desc: 推送正文
      - name: Req.PushInfo.Payload
        type: string
        required: false
        desc: 自定义 payload
      - name: Req.PushInfo.Action
        type: uint8
        required: false
        desc: 动作类型（以业务/平台约定为准）
      - name: Req.PushInfo.Classification
        type: uint8
        required: false
        desc: 消息分类（以平台约定为准）
      - name: Req.Target.Type
        type: uint8
        required: true
        desc: 目标类型（以平台约定为准）
      - name: Req.Target.Openid
        type: "[]string"
        required: false
        desc: 瑞雪 openid 列表
      - name: Req.Target.CPUserID
        type: "[]string"
        required: false
        desc: CP 用户 ID 列表
      - name: Req.Target.Tag
        type: string
        required: false
        desc: 标签
      - name: Req.Target.Alias
        type: "[]string"
        required: false
        desc: 别名列表
      - name: Req.TargetUserType
        type: int32
        required: false
        desc: "推送通道：0 正式；1 测试（vivo/honor/huawei/苹果等厂商支持）"
    response_fields:
      - name: DeviceTypeMap
        type: "map[string]string"
        desc: 仅测试通道返回，标记厂商状态
    validation:
      - Req 不可为 nil；目标需按 Type 填对应字段
    errors:
      - 打印 err 与 ruixuego.ErrTraceID(err)
    code_go: |
      package example

      import (
      	"fmt"
      	"log"

      	"github.com/ruixueyun/ruixuego"
      )

      func pusherPushV2() {
      	res, err := ruixuego.GetDefaultClient().PusherPushV2(&ruixuego.ReqPusher{
      		ProductID: "@test",
      		ChannelID: "@test",
      		Req: &ruixuego.PusherPushReq{
      			PushInfo: ruixuego.PusherPushReqInfo{
      				Title:   "@test",
      				Content: "@test",
      				Payload: "@test",
      			},
      			Target: ruixuego.PusherPushReqTarget{
      				Type:     0, // 【按业务替换】目标类型
      				Openid:   []string{"@test"},
      				CPUserID: []string{"@test"},
      			},
      			TargetUserType: 0, // 0 正式；1 测试
      		},
      	})
      	if err != nil {
      		log.Printf("push failed: %v trace=%s", err, ruixuego.ErrTraceID(err))
      		return
      	}
      	fmt.Printf("device_type_map=%v\n", res.DeviceTypeMap)
      }

notes:
  - 正式环境 TargetUserType 用 0；联调厂商可用 1
  - OpenID / CPUserID 按目标类型填写，勿混用无关用户
  - 优先 V2
