source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXBDASignalSDK.xcworkspace'

def commonPods
  use_frameworks!
  
  pod 'BDASignalSDK'
  pod 'Protobuf'
  pod 'RXLanguageKit'
  
end

target 'RXBDASignalSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

  commonPods

end

target 'RXBDASignalSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXBDASignalSDKDemo/RXBDASignalSDKDemo.xcodeproj'
    
    commonPods

end

