platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'


workspace 'RXPushSDK.xcworkspace'


target 'RXPushSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXPushSDK
#  pod 'RXSDK_Pure'
#  pod 'RXLanguageKit'
#  pod 'SocketRocket'

  
end

target 'RXPushSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXPushSDKDemo/RXPushSDKDemo.xcodeproj'
    
    use_frameworks!

#pod 'WechatOpenSDK'
#pod 'AFNetworking'
#pod 'YYCache'
#pod 'YYModel'
#pod 'MJExtension'
#pod 'TYAttributedLabel'
#pod 'YYWebImage'
#pod 'SVProgressHUD', '~> 2.2.5'
#pod 'RXShareKit'
#pod 'RXSDK_Pure'
pod 'RXLanguageKit'
pod 'SocketRocket'
pod 'Toast' #不依赖于Toast，只是用Toast来写demo

end

target 'NotificationService' do
    ##项目在工作台下的目录名称
    project 'RXPushSDKDemo/RXPushSDKDemo.xcodeproj'
    
    use_frameworks!

#pod 'WechatOpenSDK'
#pod 'AFNetworking'
#pod 'YYCache'
#pod 'YYModel'
#pod 'MJExtension'
#pod 'TYAttributedLabel'
#pod 'YYWebImage'
#pod 'SVProgressHUD', '~> 2.2.5'
#pod 'RXShareKit'
#pod 'RXSDK_Pure'
#pod 'RXLanguageKit'

end
