source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXZaloSDK.xcworkspace'

def commonPods
#  pod 'ZaloSDK', :path => '../'
#  pod 'ZaloSDK'
#  pod 'RXZaloSDK_official'
pod 'ZaloSDK'
#  pod 'RXSDK_Pure'
  
end

target 'RXZaloSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'RXZaloSDK/RXZaloSDK.xcodeproj'
#  pod 'ZaloSDK', :path => '../'
  commonPods

end

target 'RXZaloSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXZaloSDKDemo/RXZaloSDKDemo.xcodeproj'
#    pod 'ZaloSDK', :path => '../'
    commonPods

end
