# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

##工作台名称
workspace 'RXWXSDK.xcworkspace'

target 'RXWXSDK' do
  
  project 'RXWXSDK.xcodeproj'
  
  use_frameworks!

  pod 'WechatOpenSDK'
#  pod 'RXSDK_Pure'
#pod 'SocketRocket'
  pod 'RXLanguageKit'

end

target 'RXWXSDKDemo' do
  
  project 'RXWXSDKDemo/RXWXSDKDemo.xcodeproj'
  
  use_frameworks!

  pod 'WechatOpenSDK'
#  pod 'RXSDK_Pure'
#pod 'SocketRocket'
  pod 'RXLanguageKit'
#  pod 'ZaloSDK'

end
