# 瑞雪 SDK Cocos2dx GDT 接入规范
# Generated by MCP

overview:
  feature: gdt
  bridge: ruixue::RuixueBridge
  native_dependencies:
    android: "com.ruixue:rxsdk_gdt:4.0.16"
    ios:
      RXGDTSDK: "1.0.2"
      RXSDK_Pure: "4.0.8"
  note: |
    C++ API 通过 RuixueBridge 分发到 Android GDTSdkWrapper 与 iOS RXGDTService。
    iOS 应在 RuixueBridge::init 前调用 gdtRegisterSdk；Android 该方法为空操作。

initialization:
  code_cpp: |
    #include "RuixueSDK/RuixueBridge.h"

    auto bridge = ruixue::RuixueBridge::getInstance();
    bridge->gdtRegisterSdk(); // iOS 必须先于 bridge->init；Android 为空操作
    bridge->gdtInitialize("YOUR_ACTION_SET_ID", "YOUR_SECRET_KEY", "tencent", "tencent");

required_events:
  code_cpp: |
    auto bridge = ruixue::RuixueBridge::getInstance();
    bridge->gdtReportCreateRole("role-id");
    bridge->gdtReportCheckout("item", "礼包", "sku-1", 1, false, "", "CNY", true);
    // valueInCents 的金额单位为分。
    bridge->gdtReportPurchase("item", "礼包", "sku-1", 1, "wechat", "CNY", 600, true);

complete_bridge_api:
  methods:
    - gdtRegisterSdk
    - gdtInitialize
    - gdtReportRegister
    - gdtReportLogin
    - gdtReportCreateRole
    - gdtReportCheckout
    - gdtReportPurchase
    - gdtReportQuestFinish
    - gdtReportShare
    - gdtReportUpdateLevel
    - gdtReportRateApp
    - gdtReportViewContent
    - gdtReportAddToCart

preflight_check:
  required:
    - RuixueBridge.h 声明完整 GDT API
    - Android/iOS 桥接实现存在
    - 基础 init 与 GDT 注册/初始化顺序存在
    - Android rxsdk_gdt 4.0.16
    - iOS RXGDTSDK 1.0.2 与 RXSDK_Pure 4.0.8
