platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXTopOnSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    
    pod 'TPNiOS','6.3.50'
    pod 'TraminiSDK','6.3.50'
    pod 'TPNMaioSDKAdapter','6.3.50'
    pod 'TPNStartAppSDKAdapter','6.3.50'
    pod 'TPNBaiduSDKAdapter','6.3.50.2'
    #Baidu--4.80 SDK,podfile文件顶部增加 source 'https://github.com/CocoaPods/Specs.git'
    pod 'TPNNendSDKAdapter','6.3.50.2'
    pod 'TPNKuaiShouSDKAdapter','6.3.50.4'
    pod 'TPNSigmobSDKAdapter','6.3.50'
    pod 'TPNVungleSDKAdapter','6.3.50.2'
    pod 'TPNUnityAdsSDKAdapter','6.3.50.2'
    pod 'TPNIronSourceSDKAdapter','6.3.50.2'
    pod 'TPNTapjoySDKAdapter','6.3.50'
    pod 'TPNTTSDKAdapter','6.3.50.2'
    pod 'TPNBigoSDKAdapter','6.3.50.2'
    pod 'TPNAdColonySDKAdapter','6.3.50'
    pod 'TPNPubNativeSDKAdapter','6.3.50.2'
    pod 'TPNKlevinSDKAdapter','6.3.50'
    pod 'TPNPangleSDKAdapter','6.3.50.4'
    pod 'TPNKwaiSDKAdapter','6.3.50'
    pod 'TPNIMASDKAdapter','6.3.50'
    pod 'TPNKidozSDKAdapter','6.3.50'
#后续本地添加FBSDK
    pod 'RXFacebookADSDK_official'
#    pod 'TPNFacebookSDKAdapter','6.3.50'
    
    pod 'TPNAdmobSDKAdapter','6.3.50.2'
    pod 'TPNInmobiSDKAdapter','6.3.50'
    pod 'TPNApplovinSDKAdapter','6.3.50.2'
    pod 'TPNMintegralSDKAdapter','6.3.50.2'
    pod 'TPNGDTSDKAdapter','6.3.50.4'
    pod 'TPNChartboostSDKAdapter','6.3.50'
    pod 'TPNMyTargetSDKAdapter','6.3.50'
    pod 'TPNYandexSDKAdapter','6.3.50'
    pod 'TPNFyberSDKAdapter','6.3.50'
    pod 'TPNOgurySDKAdapter','6.3.50'
    
    #这是辅助用库，实际应用时用不到
    pod 'Toast'
end

target 'RXTopOnSDKDemo' do
  project 'RXTopOnSDKDemo/RXTopOnSDKDemo.xcodeproj'
  commonPods
end

target 'RXTopOnSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  project 'RXTopOnSDK.xcodeproj'

  commonPods

end
