##工作台名称
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXInstagramSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    pod 'RXLanguageKit'

end

target 'RXInstagramSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXInstagramSDKDemo/RXInstagramSDKDemo.xcodeproj'
    
    commonPods

end

target 'RXInstagramSDK' do
    ##项目在工作台下的目录名称
    project 'RXInstagramSDK.xcodeproj'

    commonPods
    
end
