# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RXSDKDemo-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXSDKDemo-iOS
  
  # 瑞雪 SDK 核心库
  pod 'RXSDK_Pure'
  
  # 瑞雪 SDK UI 组件（国内版）
  pod 'RXUIKit'

  target 'RXSDKDemo-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RXSDKDemo-iOSUITests' do
    # Pods for testing
  end

end
