// @keepTs
// @ts-nocheck
/**
 * Use these variables when you tailor your ArkTS code. They must be of the const type.
 */
export declare const m = "2.2.1";
export declare const o = "release";
export declare const DEBUG = false;
export declare const t = "default";
export declare const u = true;
/**
 * BuildProfile Class is used only for compatibility purposes.
 */
export default class a1 {
    static readonly m = "2.2.1";
    static readonly o = "release";
    static readonly DEBUG = false;
    static readonly t = "default";
    static readonly u = true;
}
