export enum PLATFORM {
  WECHAT = 'wechat',
  QQ = 'qq',
  FACEBOOK = 'facebook',
  DOUYIN = 'douyin',
  MINIGAMEHUAWEI = 'minigame_huawei',
  VIVO = 'minigame_vivo',
  OPPO = 'minigame_oppo',
  ALIPAY = 'minigame_alipay',
  TAOBAO = 'minigame_taobao',
  KS = 'minigame_kuaishou',
  UC = 'minigame_uc',
  H54399 = 'h5_4399',
  MINIGAMEXIAOMI = 'minigame_xiaomi',
  MINIGAME4399 = 'minigame_4399',
  MEITUAN = 'meituan',
  MINIGAMEBAIDU = 'minigame_baidu',
  MINIGAMEBILIBILI = 'minigame_bilibili',
}
