source 'https://github.com/CocoaPods/Specs.git'

##工作台名称
workspace 'RXLineSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
#    pod 'LineSDKSwift'
pod 'RXLineSDK_official'
#pod 'RXSDK_Pure'
end

target 'RXLineSDK' do
  ##项目在工作台下的目录名称
  project 'RXLineSDK.xcodeproj'
  
  commonPods

end

target 'RXLineSDKDemo' do
  ##项目在工作台下的目录名称
  project 'RXLineSDKDemo/RXLineSDKDemo.xcodeproj'
  
  commonPods

end
