# 瑞雪 SDK Unity v2 接入流程指南
# Generated by MCP

# ==================== 完整接入步骤 ====================
guide: |
  ## 瑞雪 SDK Unity v2 接入流程

  ### 第一步：安装 SDK（UPM）

  1. 打开 `Packages/manifest.json`
  2. 添加 scopedRegistries 与依赖：
     ```json
     {
       "scopedRegistries": [
         {
           "name": "RuiXueUnitySdk",
           "url": "http://60.205.123.114:4873",
           "scopes": ["com.ruixue"]
         }
       ],
       "dependencies": {
         "com.ruixue.unitysdk": "{{.Version}}"
       }
     }
     ```

  ### 第二步：初始化 SDK（v2）
  ```csharp
  using System.Collections.Generic;
  using RuiXue;

  var config = new RXSdkInitConfig
  {
      cpId = "your_cpid",
      productId = "your_product_id",
      channelId = "your_channel_id",
      baseUrlList = new List<string> { "https://api1.ruixueyun.com" }
  };

  RXSDK.Initialize(config, result =>
  {
      if (result.IsSuccess) Debug.Log("初始化成功: " + result.Data);
      else Debug.LogError("初始化失败: " + result.Error);
  });
  ```

  ### 第三步：设置全局回调
  ```csharp
  RXSDK.SetSdkCallback(
      (type, json) => Debug.Log($"事件: {type}, {json}"),
      (code, msg) => Debug.Log($"登出: {code}, {msg}"),
      (code, data) =>
      {
          Debug.Log($"切换账号: {code}, {data}");
          return true;
      }
  );
  ```

  ### 第四步：接入登录
  ```csharp
  using RuiXue.Login;

  var loginConfig = new LoginConfig { loginType = LoginMethod.Guest };
  RXLogin.Login(loginConfig, result =>
  {
      if (result.IsSuccess) Debug.Log("登录成功: " + result.Data);
      else Debug.LogError("登录失败: " + result.Error);
  });
  ```

  ### 第五步：接入支付（按需）
  ```csharp
  using RuiXue.Pay;

  var payParams = new Dictionary<string, object>
  {
      { "goods_tag", "diamond_100" },
      { "trade_no", System.Guid.NewGuid().ToString() },
      { "amount", 100 }
  };

  RXPay.Pay(payParams, result =>
  {
      if (result.IsSuccess) Debug.Log("支付请求成功: " + result.Data);
      else Debug.LogError("支付请求失败: " + result.Error);
  });
  ```

  ### 接入检查清单
  - [ ] 已安装 `com.ruixue.unitysdk`
  - [ ] 初始化代码已添加到启动场景
  - [ ] 全局回调已配置（登出、切换账号）
  - [ ] 登录功能已接入（`RXLogin`）
  - [ ] 支付功能已接入（如需要，`RXPay`）
  - [ ] 真机测试通过
