# 瑞雪 SDK Unity v2 依赖配置
# Generated by MCP

# ==================== 安装方式 ====================

# 方式一：Unity Package Manager (UPM) 安装（推荐）
install_upm: |
  ## UPM 安装步骤（v2）

  1. 打开 Unity 项目的 `Packages/manifest.json` 文件
  2. 在 `scopedRegistries` 中添加瑞雪 Registry：

  ```json
  {
    "scopedRegistries": [
      {
        "name": "RuiXueUnitySdk",
        "url": "http://60.205.123.114:4873",
        "scopes": ["com.ruixue"]
      }
    ],
    "dependencies": {
      "com.ruixue.unitysdk": "{{.Version}}"
    }
  }
  ```

  3. 保存后 Unity 会自动下载并导入 SDK

# 方式二：.unitypackage 安装（仅兼容旧项目）
install_unitypackage: |
  ## .unitypackage 方式说明

  Unity SDK v2 推荐 UPM 接入。若项目仍使用 `.unitypackage`，请确认该包由瑞雪技术支持提供且版本与 v2 对齐。

  建议优先改为 UPM，以便版本管理与持续升级。

# ==================== 注意事项 ====================
note: |
  1. v2 统一包名为 `com.ruixue.unitysdk`
  2. 新项目建议仅使用 UPM，不建议维护 `.unitypackage` 双轨
