# 瑞雪 SDK Unity v2 游戏区服
# Generated by MCP
# 注意：Unity SDK 的游戏区服/角色功能通过 RXSDK 底层 API 或自定义请求实现

# ==================== 说明 ====================
description: |
  Unity SDK 中游戏区服相关功能通过 RXSDK.CreateRequest 自定义请求接口实现，
  或通过原生 Android/iOS SDK 桥接调用。

# ==================== 通过 CreateRequest 实现 ====================
code: |
  using System.Collections.Generic;
  using RuiXue;

  // ========== 查询区服信息 ==========
  private void SearchGameAreaInfo(string areaId)
  {
      var header = new Dictionary<string, string>();
      var body = new Dictionary<string, string>
      {
          { "area_id", areaId }
      };

      RXSDK.CreateRequest(
          "/game/area/info",
          header, body,
          HttpMethod.POST,
          true,
          result =>
          {
              if (result.IsSuccess)
              {
                  Debug.Log("区服信息: " + result.Data);
              }
          }
      );
  }

  // ========== 查询区服列表 ==========
  private void SearchGameAreaList()
  {
      RXSDK.CreateRequest(
          "/game/area/list",
          new Dictionary<string, string>(),
          new Dictionary<string, string>(),
          HttpMethod.POST,
          true,
          result =>
          {
              if (result.IsSuccess) Debug.Log("区服列表: " + result.Data);
          }
      );
  }

# ==================== 导入语句 ====================
imports:
  - "using System.Collections.Generic;"
  - "using RuiXue;"
