# 瑞雪 SDK Unity LBS（高德定位）
# Generated by MCP

important_note: |
  瑞雪定位功能基于高德定位 SDK，Unity 命名空间为 RuiXue.LBS。
  本功能用于从 Android/iOS 设备获取定位信息，不是 RXSDK.LbsUpdate/LbsRadius/LbsDelete 社交 LBS 接口。

dependencies:
  unity_upm: "com.ruixue.unitysdk.lbs（版本需与 com.ruixue.unitysdk.base 保持一致）"
  android_native: "com.ruixue:rxsdk_gaode:${rxVersion}"
  ios_native: "RXLBSKit（依赖 AMapLocation / AMapSearch；导出 Xcode 工程后检查 Podfile.lock，缺失时执行 pod install）"

android_setup:
  app_key: |
    1. 在 AndroidManifest.xml 的 application 标签内添加：
       <meta-data android:name="com.amap.api.v2.apikey" android:value="${AMAP_APIKEY}" />
    2. 在 launcherTemplate.gradle 的 defaultConfig 中配置：
       manifestPlaceholders = [AMAP_APIKEY: "your_amap_android_key"]
    3. 可调用 unity feature=android_native_setup，并在 components 中选择 rxsdk_gaode，以补齐 Android 原生依赖。
  permissions: |
    高德组件会声明定位相关权限；Android 6.0+ 仍需由宿主在运行时申请定位权限。
    Android 10+ 如需后台定位，还需申请 ACCESS_BACKGROUND_LOCATION。
  init:
    method: "RXLBSAndroid.InitLocation()"
    code: |
      using RuiXue.LBS;

      #if UNITY_ANDROID && !UNITY_EDITOR
      RXLBSAndroid.InitLocation();
      #endif
  start_location:
    method: "RXLBSAndroid.StartLocation(bool cbAddress, bool cbGpsFirst, bool cbCacheAble, bool cbOnceLocation, bool cbOnceLastest, bool cbSensorAble, long interval, long timeout, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
    code: |
      #if UNITY_ANDROID && !UNITY_EDITOR
      RXLBSAndroid.StartLocation(
          true, true, true, true, true, true,
          10000L, 10000L,
          data => Debug.Log("高德定位成功: " + data),
          error => Debug.LogError("高德定位失败: " + error)
      );
      #endif
  timed_report:
    method: "RXLBSAndroid.StartLocation(string[] types, int duration, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
    note: "duration 必须大于 30 秒；该重载会定时定位并自动调用瑞雪 lbsUpdate 上报坐标。"
    code: |
      #if UNITY_ANDROID && !UNITY_EDITOR
      RXLBSAndroid.StartLocation(
          new[] { "game" },
          60000,
          data => Debug.Log("定位并上报成功: " + data),
          error => Debug.LogError("定位并上报失败: " + error)
      );
      #endif
  stop_location:
    method: "RXLBSAndroid.StopLocation()"
    code: |
      #if UNITY_ANDROID && !UNITY_EDITOR
      RXLBSAndroid.StopLocation();
      #endif
  other_methods:
    - "RXLBSAndroid.GetGPSStatusString(int statusCode)"
    - "RXLBSAndroid.ResetOption(...)"
    - "RXLBSAndroid.WGSLat/WGSLon（GCJ-02 转 WGS84）"
    - "RXLBSAndroid.TransformLon/TransformLat"

ios_setup:
  permissions: |
    在 Info.plist 中按实际使用场景添加定位用途描述：
    - NSLocationWhenInUseUsageDescription
    - NSLocationAlwaysAndWhenInUseUsageDescription
    - NSLocationAlwaysUsageDescription
    如需后台定位，在 Xcode Signing & Capabilities 中开启 Background Modes > Location updates。
  init:
    method: "RXLBSIOS.Init(string appKey)"
    code: |
      using RuiXue.LBS;

      #if UNITY_IOS && !UNITY_EDITOR
      RXLBSIOS.Init("your_amap_ios_key");
      #endif
  request_permission:
    methods:
      - "RXLBSIOS.IsEnableLocation()"
      - "RXLBSIOS.RequestLocationAuthorization(RequestLocationAuthorizationDelegate callback)"
    code: |
      #if UNITY_IOS && !UNITY_EDITOR
      if (!RXLBSIOS.IsEnableLocation())
      {
          RXLBSIOS.RequestLocationAuthorization(
              authorized => Debug.Log("定位权限: " + authorized)
          );
      }
      #endif
  get_location:
    method: "RXLBSIOS.GetLocationInfo(RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
    code: |
      #if UNITY_IOS && !UNITY_EDITOR
      RXLBSIOS.SetLocationTimeout(2);
      RXLBSIOS.GetLocationInfo(
          data => Debug.Log("高德定位成功: " + data),
          error => Debug.LogError("高德定位失败: " + error)
      );
      #endif
  background_location:
    method: "RXLBSIOS.SetAllowsBackgroundLocationUpdates(bool allow)"

ios_response_fields:
  - "formattedAddress, country, province, city, district"
  - "citycode, adcode, street, number"
  - "POIName, AOIName, longitude, latitude"

imports:
  - "using RuiXue;"
  - "using RuiXue.LBS;"
