# 瑞雪 SDK Unity v2 登录功能
# Generated by MCP

# ==================== 方法签名 ====================
signature:
  class: RXLogin
  method_name: "RXLogin.Login"
  parameters:
    - name: config
      type: LoginConfig
      required: true
    - name: callback
      type: SdkCallback
      required: true

# ==================== 样板代码 ====================
code: |
  // ========== 瑞雪 SDK Unity v2 登录 ==========
  using UnityEngine;
  using RuiXue;
  using RuiXue.Login;

  // ---------- 游客登录 ----------
  private void LoginAsGuest()
  {
      var config = new LoginConfig
      {
          loginType = LoginMethod.Guest
      };

      RXLogin.Login(config, result =>
      {
          if (result.IsSuccess)
          {
              Debug.Log("游客登录成功: " + result.Data);
          }
          else
          {
              Debug.LogError($"游客登录失败 [{result.Code}]: {result.Error}");
          }
      });
  }

  // ---------- 账号密码登录 ----------
  private void LoginWithPassword(string username, string password)
  {
      var config = new LoginConfig
      {
          loginType = LoginMethod.Username,
          username = username,
          password = password
      };

      RXLogin.Login(config, result =>
      {
          if (result.IsSuccess) Debug.Log("账号登录成功: " + result.Data);
          else Debug.LogError("账号登录失败: " + result.Error);
      });
  }

  // ---------- 退出登录 ----------
  private void Logout()
  {
      RXLogin.Logout(result =>
      {
          if (result.IsSuccess) Debug.Log("退出登录成功");
          else Debug.LogError("退出登录失败: " + result.Error);
      });
  }

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"
  - "using RuiXue.Login;"

# ==================== 注意事项 ====================
note: |
  1. v2 推荐使用 SdkCallback 回调，统一通过 result.IsSuccess 判断结果
  2. 旧的 onResponse/onError 双回调仍可用，但仅用于兼容
