# 瑞雪 SDK Unity v2 密码管理
# Generated by MCP

# ==================== 修改密码 ====================
change_password:
  method: "RXSDK.ChangePassword(string oldPassword, string newPassword, SdkCallback callback)"
  code: |
    using RuiXue;

    RXSDK.ChangePassword("oldPassword", "newPassword", result =>
    {
        if (result.IsSuccess) Debug.Log("修改密码成功");
        else Debug.LogError("修改密码失败: " + result.Error);
    });

# ==================== 重置密码 ====================
reset_password:
  method: "RXSDK.ResetPassword(string username, string password, string captchaCode, object migrateArgs, SdkCallback callback)"
  code: |
    // 通过验证码重置密码
    RXSDK.ResetPassword("13800138000", "newPassword123", "123456", null, result =>
    {
        if (result.IsSuccess) Debug.Log("重置密码成功");
        else Debug.LogError("重置密码失败: " + result.Error);
    });

# ==================== 密码强度配置 ====================
password_strength:
  method: "RXSDK.SetPasswordStrength(RXPasswordStrength type)"
  values:
    - "RXPasswordStrength.Default   // 默认 6-32 位任意字符"
    - "RXPasswordStrength.Custom    // 自定义密码正则"
    - "RXPasswordStrength.Average   // 简易密码 6-32 位"
    - "RXPasswordStrength.Strong    // 强密码 6-32 位 数字+字母+特殊符号"
  code: |
    // 设置密码强度
    RXSDK.SetPasswordStrength(RXPasswordStrength.Strong);

    // 自定义密码正则
    RXSDK.SetPwdPattern(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$");

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"
