# 瑞雪 SDK Unity v2 用户通行证
# Generated by MCP

# ==================== 用户信息管理 ====================

# 获取用户信息
get_user_info:
  method: "RXSDK.GetUserInfo(SdkCallback callback)"
  async: "RXSDK.GetUserInfoAsync()"
  code: |
    RXSDK.GetUserInfo(result =>
    {
        if (result.IsSuccess)
        {
            Debug.Log("获取用户信息成功: " + result.Data);
            // result.Data 包含 nickname, avatar, region, sex 等
        }
    });

# 修改用户信息
update_user_info:
  method: "RXSDK.UpdateUserInfo(string nickname, string avatarUrl, string region, int sex, SdkCallback callback)"
  code: |
    RXSDK.UpdateUserInfo(
        "新昵称",           // nickname
        "https://xxx.png",  // avatarUrl
        "CN",               // region
        1,                  // sex: 0=女, 1=男
        result =>
        {
            if (result.IsSuccess) Debug.Log("修改用户信息成功");
        }
    );

# ==================== 登录/注册/登出 ====================

login:
  method: "RXSDK.Login(LoginConfig config, SdkCallback callback)"
  description: "详见 login 功能模块"

register:
  method: "RXSDK.Register(string username, string password, string captchaCode, Dictionary<string, object> ext, SdkCallback callback)"
  code: |
    RXSDK.Register("user@example.com", "password123", "123456", null, result =>
    {
        if (result.IsSuccess) Debug.Log("注册成功");
        else Debug.LogError("注册失败: " + result.Error);
    });

logout:
  method: "RXSDK.Logout(SdkCallback callback)"
  async: "RXSDK.LogoutAsync()"
  code: |
    RXSDK.Logout(result =>
    {
        if (result.IsSuccess) Debug.Log("退出登录成功");
    });

# ==================== 全局回调 ====================

set_sdk_callback:
  method: "RXSDK.SetSdkCallback(EventCallback onEvent, Action<int, string> onLogout, SwitchAccountCallback onSwitchAccount)"
  code: |
    RXSDK.SetSdkCallback(
        onEvent: (type, json) =>
        {
            Debug.Log($"SDK 事件: type={type}, data={json}");
        },
        onLogout: (code, msg) =>
        {
            Debug.Log($"被动登出: code={code}, msg={msg}");
            // 返回登录页面
        },
        onSwitchAccount: (code, data) =>
        {
            Debug.Log($"切换账号: code={code}");
            return true; // 返回 true 表示处理成功
        }
    );

# ==================== 查询绑定账号 ====================

search_binding_accounts:
  method: "RXSDK.SearchBindingAccounts(SdkCallback callback)"
  code: |
    RXSDK.SearchBindingAccounts(result =>
    {
        if (result.IsSuccess)
        {
            Debug.Log("绑定账号列表: " + result.Data);
        }
    });

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"
  - "using RuiXue.Login;"
