# 瑞雪 SDK Unity v2 排行榜
# Generated by MCP

# ==================== 增加分数 ====================
add_score:
  method: "RXSDK.AddScore(string rank_id, int score, SdkCallback callback)"
  code: |
    using RuiXue;

    RXSDK.AddScore("rank_001", 100, result =>
    {
        if (result.IsSuccess) Debug.Log("增加分数成功");
        else Debug.LogError("增加分数失败: " + result.Error);
    });

# ==================== 设置分数 ====================
set_score:
  method: "RXSDK.SetScore(string rank_id, int score, SdkCallback callback)"
  code: |
    RXSDK.SetScore("rank_001", 500, result =>
    {
        if (result.IsSuccess) Debug.Log("设置分数成功");
    });

# ==================== 查询用户排名 ====================
query_user_rank:
  method: "RXSDK.QueryUserRank(string rank_id, string open_id, SdkCallback callback)"
  code: |
    RXSDK.QueryUserRank("rank_001", "user_open_id", result =>
    {
        if (result.IsSuccess) Debug.Log("用户排名: " + result.Data);
    });

# ==================== 获取排行榜列表 ====================
get_rank_list:
  method: "RXSDK.GetRankList(string rank_id, int start_rank, int end_rank, SdkCallback callback)"
  code: |
    // 获取排行榜前 100 名
    RXSDK.GetRankList("rank_001", 1, 100, result =>
    {
        if (result.IsSuccess) Debug.Log("排行榜: " + result.Data);
    });

# ==================== 好友排行榜 ====================
friends_rank:
  method: "RXSDK.FriendsRank(string rank_id, SdkCallback callback)"
  code: |
    RXSDK.FriendsRank("rank_001", result =>
    {
        if (result.IsSuccess) Debug.Log("好友排行榜: " + result.Data);
    });

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"
