# 瑞雪 SDK Unity v2 分享
# Generated by MCP

# ==================== 分享调度初始化 ====================
share_scheduling_init:
  method: "RXSDK.ShareSchedulingInit(string[] funcs, SdkCallback callback)"
  code: |
    using RuiXue;

    RXSDK.ShareSchedulingInit(new string[] { "func1", "func2" }, result =>
    {
        if (result.IsSuccess) Debug.Log("分享调度初始化成功");
    });

# ==================== 获取分享调度 ====================
get_share_scheduling:
  method: "string RXSDK.GetShareScheduling(string[] func)"
  code: |
    string scheduling = RXSDK.GetShareScheduling(new string[] { "func1" });
    Debug.Log("分享调度: " + scheduling);

# ==================== 分享结果上报 ====================
share_scheduling_report:
  method: "RXSDK.ShareSchedulingReport(...)"
  code: |
    RXSDK.ShareSchedulingReport(
        "func1",                    // func
        "wechat",                   // platform
        "CN",                       // region
        true,                       // scheduling_event
        "share",                    // scheduling_type
        "transmit_data",            // transmits
        null,                       // properties
        result => { }
    );

# ==================== 获取分享数据 ====================
get_share_data:
  method: "RXSDK.GetShareData(RXShareConfig shareConfig, SdkCallback callback)"
  code: |
    using RuiXue.Share;

    var shareConfig = new RXShareConfig
    {
        func = "share_func",
        platform = "wechat",
        region = "CN",
        title = "分享标题",
        desc = "分享描述",
        imageUrl = "https://example.com/image.png"
    };

    RXSDK.GetShareData(shareConfig, result =>
    {
        if (result.IsSuccess) Debug.Log("分享数据: " + result.Data);
    });

# ==================== 发起分享 ====================
share:
  method: "RXSDK.Share(RXShareConfig shareConfig, SdkCallback callback)"
  code: |
    var shareConfig = new RXShareConfig
    {
        func = "share_func",
        platform = "wechat",
        region = "CN",
        title = "分享标题",
        desc = "分享描述",
        imageUrl = "https://example.com/image.png",
        auto_report = true,
        useShortUrl = false
    };

    RXSDK.Share(shareConfig, result =>
    {
        if (result.IsSuccess) Debug.Log("分享成功");
        else Debug.LogError("分享失败: " + result.Error);
    });

# ==================== 自定义分享 ====================
share_custom:
  method: "RXSDK.ShareCustom(RXCustomShareConfig shareConfig, SdkCallback callback)"
  code: |
    // 自定义数据分享
    RXSDK.ShareCustom(customShareConfig, result =>
    {
        if (result.IsSuccess) Debug.Log("自定义分享成功");
    });

# ==================== 获取短链接 ====================
get_short_url:
  method: "RXSDK.GetShortUrl(string url, SdkCallback callback)"
  code: |
    RXSDK.GetShortUrl("https://example.com/long-url", result =>
    {
        if (result.IsSuccess) Debug.Log("短链接: " + result.Data);
    });

# ==================== RXShareConfig 字段说明 ====================
share_config_fields:
  - name: func
    type: string
    description: 埋点标识
  - name: platform
    type: string
    description: 分享平台
  - name: region
    type: string
    description: 地区码
  - name: title
    type: string
    description: 分享标题
  - name: desc
    type: string
    description: 分享描述
  - name: imageUrl
    type: string
    description: 分享图片 URL
  - name: auto_report
    type: bool
    description: 是否自动上报（默认 true）
  - name: useShortUrl
    type: bool
    description: 是否使用短链接
  - name: channel
    type: string
    description: 渠道
  - name: transmits
    type: string
    description: 透传参数，原样返回

# ==================== 导入语句 ====================
imports:
  - "using RuiXue;"
  - "using RuiXue.Share;"
