# 瑞雪 SDK Unity v2 版本检查
# Generated by MCP

# ==================== 自定义版本检查 ====================
check_update_app:
  method: "RXVersionCheck.CheckUpdateApp(string version, string region, string type, Dictionary<string, int> games, Dictionary<string, int> activities, RequestResponseDelegate onResponse, RequestErrorDelegate onError)"
  code: |
    var games = new Dictionary<string, int> { { "game_001", 1 } };
    var activities = new Dictionary<string, int> { { "activity_001", 1 } };

    RXVersionCheck.CheckUpdateApp(
        "1.0.0",
        "CN",
        "hot",
        games,
        activities,
        data => Debug.Log("检查结果: " + data),
        error => Debug.LogError("检查失败: " + error));

# ==================== 游戏更新检查 ====================
update_game:
  method: "RXSDK.UpdateGame(string gameId, string gameVersion, string gameCheckVersion, string type, SdkCallback callback)"
  code: |
    RXSDK.UpdateGame("game_001", "1.0.0", "1.0.0", "hot", result =>
    {
        if (result.IsSuccess) Debug.Log("游戏更新: " + result.Data);
    });

# ==================== 活动更新检查 ====================
update_activity:
  method: "RXSDK.UpdateActivity(string activityShortname, string activityVersion, string activityCheckVersion, string type, SdkCallback callback)"
  code: |
    RXSDK.UpdateActivity("spring_event", "1.0.0", "1.0.0", "hot", result =>
    {
        if (result.IsSuccess) Debug.Log("活动更新: " + result.Data);
    });

# ==================== 导入语句 ====================
imports:
  - "using System.Collections.Generic;"
  - "using RuiXue;"
  - "using RuiXue.VersionCheck;"
