// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "Control.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(ClientInfo);
GPBObjCClassDeclaration(Connect);
GPBObjCClassDeclaration(ConnectAck);
GPBObjCClassDeclaration(Error);

#pragma mark - ControlRoot

@implementation ControlRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ControlRoot_FileDescriptor

static GPBFileDescriptor *ControlRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"domain"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Error

@implementation Error

@dynamic option;
@dynamic clientUuid;
@dynamic content;
@dynamic code;
@dynamic ext, ext_Count;

typedef struct Error__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  NSString *clientUuid;
  NSString *content;
  NSMutableDictionary *ext;
  int64_t option;
} Error__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "option",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Option,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Error__storage_, option),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "clientUuid",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_ClientUuid,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Error__storage_, clientUuid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Content,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Error__storage_, content),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Code,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Error__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "ext",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Ext,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Error__storage_, ext),
        .flags = (GPBFieldFlags)(GPBFieldMapKeyString | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Error class]
                                     rootClass:[ControlRoot class]
                                          file:ControlRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Error__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001F\000\002Gc\000\003G\000\004D\000\nC\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ClientInfo

@implementation ClientInfo

@dynamic cpid;
@dynamic clientType;
@dynamic productId;
@dynamic channelId;
@dynamic deviceCode;
@dynamic userId;
@dynamic language;

typedef struct ClientInfo__storage_ {
  uint32_t _has_storage_[1];
  uint32_t cpid;
  int32_t clientType;
  NSString *productId;
  NSString *channelId;
  NSString *deviceCode;
  NSString *userId;
  NSString *language;
} ClientInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "cpid",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_Cpid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, cpid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "clientType",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_ClientType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, clientType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "productId",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_ProductId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, productId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "channelId",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_ChannelId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, channelId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceCode",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_DeviceCode,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, deviceCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_UserId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "language",
        .dataTypeSpecific.clazz = Nil,
        .number = ClientInfo_FieldNumber_Language,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(ClientInfo__storage_, language),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ClientInfo class]
                                     rootClass:[ControlRoot class]
                                          file:ControlRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ClientInfo__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\001d\000\002J\000\003HA\000\004HA\000\005J\000\006EA\000\007H\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Connect

@implementation Connect

@dynamic hasClientInfo, clientInfo;
@dynamic option;
@dynamic milliTs;
@dynamic token;
@dynamic sign;
@dynamic ext, ext_Count;

typedef struct Connect__storage_ {
  uint32_t _has_storage_[1];
  ClientInfo *clientInfo;
  NSString *token;
  NSString *sign;
  NSMutableDictionary *ext;
  int64_t option;
  int64_t milliTs;
} Connect__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "clientInfo",
        .dataTypeSpecific.clazz = GPBObjCClass(ClientInfo),
        .number = Connect_FieldNumber_ClientInfo,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Connect__storage_, clientInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "option",
        .dataTypeSpecific.clazz = Nil,
        .number = Connect_FieldNumber_Option,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Connect__storage_, option),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "milliTs",
        .dataTypeSpecific.clazz = Nil,
        .number = Connect_FieldNumber_MilliTs,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Connect__storage_, milliTs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "token",
        .dataTypeSpecific.clazz = Nil,
        .number = Connect_FieldNumber_Token,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Connect__storage_, token),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sign",
        .dataTypeSpecific.clazz = Nil,
        .number = Connect_FieldNumber_Sign,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Connect__storage_, sign),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ext",
        .dataTypeSpecific.clazz = Nil,
        .number = Connect_FieldNumber_Ext,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Connect__storage_, ext),
        .flags = (GPBFieldFlags)(GPBFieldMapKeyString | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Connect class]
                                     rootClass:[ControlRoot class]
                                          file:ControlRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Connect__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\006\001J\000\002F\000\003FA\000\004E\000\005D\000\nC\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ConnectAck

@implementation ConnectAck

@dynamic content;
@dynamic code;
@dynamic pingIntervalMilli;
@dynamic discontinuousInboxIddelayMilliTs;
@dynamic ext, ext_Count;

typedef struct ConnectAck__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  int32_t pingIntervalMilli;
  int32_t discontinuousInboxIddelayMilliTs;
  NSString *content;
  NSMutableDictionary *ext;
} ConnectAck__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "content",
        .dataTypeSpecific.clazz = Nil,
        .number = ConnectAck_FieldNumber_Content,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ConnectAck__storage_, content),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = ConnectAck_FieldNumber_Code,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ConnectAck__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "pingIntervalMilli",
        .dataTypeSpecific.clazz = Nil,
        .number = ConnectAck_FieldNumber_PingIntervalMilli,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ConnectAck__storage_, pingIntervalMilli),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "discontinuousInboxIddelayMilliTs",
        .dataTypeSpecific.clazz = Nil,
        .number = ConnectAck_FieldNumber_DiscontinuousInboxIddelayMilliTs,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ConnectAck__storage_, discontinuousInboxIddelayMilliTs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "ext",
        .dataTypeSpecific.clazz = Nil,
        .number = ConnectAck_FieldNumber_Ext,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ConnectAck__storage_, ext),
        .flags = (GPBFieldFlags)(GPBFieldMapKeyString | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ConnectAck class]
                                     rootClass:[ControlRoot class]
                                          file:ControlRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ConnectAck__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001G\000\002D\000\003Q\000\004Sb\nA\000\nC\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
