// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RXIMChatServiceP.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - JximservicePRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface JximservicePRoot : GPBRootObject
@end

#pragma mark - ArgUserID

typedef GPB_ENUM(ArgUserID_FieldNumber) {
  ArgUserID_FieldNumber_UserId = 1,
};

/**
 * ArgUserID 通用请求参数
 **/
GPB_FINAL @interface ArgUserID : GPBMessage

@property(nonatomic, readwrite) int64_t userId;

@end

#pragma mark - LoginData

typedef GPB_ENUM(LoginData_FieldNumber) {
  LoginData_FieldNumber_UserId = 1,
  LoginData_FieldNumber_Aeskey = 2,
};

/**
 * LoginData 用户登陆数据结构
 * 由 data 服务存于 redis (with expire). entry 会经由 data 服务获取使用
 **/
GPB_FINAL @interface LoginData : GPBMessage

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *aeskey;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
