// @keepTs
// @ts-nocheck
export declare class y8 {
    readonly deviceType: string;
    readonly brand: string;
    readonly model: string;
    readonly v7: string;
    readonly b8: string;
    readonly c8: string;
    constructor(deviceType: string, brand: string, model: string, g9: string, h9: string, i9: string);
}
declare class z8 {
    private d8;
    getDeviceInfo(): y8;
    e8(): string;
    private f8;
}
declare const l15: z8;
export default l15;
