platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'


workspace 'RXOpeninstallOSSDK.xcworkspace'

def commonPods
  
  use_frameworks!
  
  pod 'RXLanguageKit'
#  pod 'libOpenInstallSDK'
  pod 'WechatOpenSDK'
  pod 'RXAuthSDK_official'

end

target 'RXOpeninstallOSSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

#  commonPods

end

target 'RXOpeninstallOSSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXOpeninstallOSSDKDemo/RXOpeninstallOSSDKDemo.xcodeproj'
    commonPods

end
