platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXGPMSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    
    pod 'RXLanguageKit'
end

target 'RXGPMSDKDemo' do
  project 'RXGPMSDKDemo/RXGPMSDKDemo.xcodeproj'
  commonPods
end

target 'RXGPMSDK' do
  project 'RXGPMSDK.xcodeproj'
  commonPods
end
