# 瑞雪 SDK 账号绑定功能
# Generated by MCP
# 包含：绑定第三方账号、绑定手机、解绑手机、修改手机、绑定邮箱、解绑邮箱、修改邮箱
#
# 版本要求:
# - BindAccount 需要 Android SDK 4.0.8 及以上版本
# - 如果当前 SDK 版本过低，不支持自动升级，请先手动升级 Gradle 依赖后再接入

# ==================== 绑定第三方账号 ====================
bindAccount:
  method_name: "RXSdkApi.getInstance().bindAccount"
  description: 绑定第三方账号
  min_android_sdk: "4.0.8"
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: map
      type: Map<String, Object>
      required: true
      description: 绑定参数，包含 method、scene 等字段
    - name: callback
      type: RXJSONCallback / RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 绑定第三方账号 ==========
    // 版本要求：Android SDK >= 4.0.8；低版本不支持自动升级，请先手动升级 Gradle 依赖
    // 参数说明：
    // - method: wechat / facebook / google / apple 等三方登录方式
    // - scene: authorization（三方账号绑定，默认）或 bind（红包绑定微信账号场景）
    Activity activity = this; // 如果不在 Activity 中，请传入当前页面 Activity
    Map<String, Object> map = new HashMap<>();
    map.put("method", "wechat");
    map.put("scene", "authorization");

    RXSdkApi.getInstance().bindAccount(activity, map, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "第三方账号绑定成功: " + jsonObject);
            } else {
                Log.e("RXSDK", "第三方账号绑定失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 绑定手机 ====================
bindPhone:
  method_name: "RXSDK.getInstance().bindPhone"
  description: 绑定手机号
  parameters:
    - name: phone
      type: String
      required: true
      description: 手机号
    - name: password
      type: String
      required: true
      description: 密码
    - name: captchaCode
      type: String
      required: true
      description: 验证码
    - name: migrateArgs
      type: Object
      required: false
      description: 迁移参数（可选）
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 绑定手机 ==========
    // 前置条件：需要先调用 sendCaptcha 发送验证码
    String phone = "13800138000";      // 必填，手机号，类型 String
    String password = "your_password"; // 必填，密码，类型 String
    String captchaCode = "123456";     // 必填，短信验证码，类型 String

    RXSDK.getInstance().bindPhone(phone, password, captchaCode, null, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "手机绑定成功");
                // TODO: 更新 UI 显示已绑定状态
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "手机绑定失败: " + msg);
                // 常见错误：手机号已被其他账号绑定
            }
        }
    });

# ==================== 解绑手机 ====================
unBindPhone:
  method_name: "RXSDK.getInstance().unBindPhone"
  description: 解绑手机号
  parameters:
    - name: phone
      type: String
      required: true
      description: 手机号
    - name: captchaCode
      type: String
      required: true
      description: 验证码
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 解绑手机 ==========
    // 前置条件：需要先调用 sendCaptcha 发送验证码
    String phone = "13800138000";  // 必填，当前绑定的手机号，类型 String
    String captchaCode = "123456"; // 必填，短信验证码，类型 String

    RXSDK.getInstance().unBindPhone(phone, captchaCode, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "手机解绑成功");
                // TODO: 更新 UI 显示未绑定状态
            } else {
                Log.e("RXSDK", "手机解绑失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 修改手机号 ====================
changePhone:
  method_name: "RXSDK.getInstance().changePhone"
  description: 修改手机号
  parameters:
    - name: newPhone
      type: String
      required: true
      description: 新手机号
    - name: newPhoneCaptcha
      type: String
      required: true
      description: 新手机号验证码
    - name: oldPhoneCaptcha
      type: String
      required: true
      description: 旧手机号验证码
    - name: migrateArgs
      type: Object
      required: false
      description: 迁移参数（可选）
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 修改手机号 ==========
    // 前置条件：需要先给新旧手机都发送验证码
    String newPhone = "13900139000";     // 必填，新手机号，类型 String
    String newPhoneCaptcha = "654321";   // 必填，新手机验证码，类型 String
    String oldPhoneCaptcha = "123456";   // 必填，旧手机验证码，类型 String

    RXSDK.getInstance().changePhone(newPhone, newPhoneCaptcha, oldPhoneCaptcha, null, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "手机号修改成功");
                // TODO: 更新显示的手机号
            } else {
                Log.e("RXSDK", "手机号修改失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 绑定邮箱 ====================
bindEmail:
  method_name: "RXSDK.getInstance().bindEmail"
  description: 绑定邮箱
  parameters:
    - name: email
      type: String
      required: true
      description: 邮箱地址
    - name: password
      type: String
      required: true
      description: 密码
    - name: captchaCode
      type: String
      required: true
      description: 验证码
    - name: migrateArgs
      type: Object
      required: false
      description: 迁移参数（可选）
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 绑定邮箱 ==========
    // 前置条件：需要先调用 sendCaptcha 发送验证码
    String email = "user@example.com";   // 必填，邮箱地址，类型 String
    String password = "your_password";   // 必填，密码，类型 String
    String captchaCode = "123456";       // 必填，邮箱验证码，类型 String

    RXSDK.getInstance().bindEmail(email, password, captchaCode, null, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "邮箱绑定成功");
                // TODO: 更新 UI 显示已绑定状态
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "邮箱绑定失败: " + msg);
            }
        }
    });

# ==================== 解绑邮箱 ====================
unBindEmail:
  method_name: "RXSDK.getInstance().unBindEmail"
  description: 解绑邮箱
  parameters:
    - name: email
      type: String
      required: true
      description: 邮箱地址
    - name: captchaCode
      type: String
      required: true
      description: 验证码
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 解绑邮箱 ==========
    // 前置条件：需要先调用 sendCaptcha 发送验证码
    String email = "user@example.com"; // 必填，当前绑定的邮箱，类型 String
    String captchaCode = "123456";     // 必填，邮箱验证码，类型 String

    RXSDK.getInstance().unBindEmail(email, captchaCode, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "邮箱解绑成功");
                // TODO: 更新 UI 显示未绑定状态
            } else {
                Log.e("RXSDK", "邮箱解绑失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 修改邮箱 ====================
changeEmail:
  method_name: "RXSDK.getInstance().changeEmail"
  description: 修改邮箱
  parameters:
    - name: newEmail
      type: String
      required: true
      description: 新邮箱
    - name: newEmailCaptcha
      type: String
      required: true
      description: 新邮箱验证码
    - name: oldEmailCaptcha
      type: String
      required: true
      description: 旧邮箱验证码
    - name: migrateArgs
      type: Object
      required: false
      description: 迁移参数（可选）
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 修改邮箱 ==========
    // 前置条件：需要先给新旧邮箱都发送验证码
    String newEmail = "new@example.com";   // 必填，新邮箱，类型 String
    String newEmailCaptcha = "654321";     // 必填，新邮箱验证码，类型 String
    String oldEmailCaptcha = "123456";     // 必填，旧邮箱验证码，类型 String

    RXSDK.getInstance().changeEmail(newEmail, newEmailCaptcha, oldEmailCaptcha, null, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "邮箱修改成功");
                // TODO: 更新显示的邮箱
            } else {
                Log.e("RXSDK", "邮箱修改失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.util.Log;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"
  - "import com.ruixue.openapi.RXSdkApi;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"

# 检查指南 (给 AI 的指令)
check_guide:
  - BindAccount 需要 Android SDK 4.0.8 及以上；低版本不支持自动升级，请先手动升级依赖
  - 检查绑定/解绑/修改方法的调用是否正确
  - 验证验证码参数是否已通过 sendCaptcha 获取
  - 修改手机/邮箱时，验证是否同时传递了新旧验证码
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "绑定手机"
    - "绑定第三方账号"
    - "绑定微信账号"
    - "绑定 Facebook 账号"
    - "绑定 Google 账号"
    - "解绑手机"
    - "修改手机号"
    - "绑定邮箱"
    - "解绑邮箱"
    - "修改邮箱"
  actions:
    - 根据用户需求选择对应的代码片段
    - 提醒用户先发送验证码
    - 确保必要的 import 语句已添加
