# 瑞雪 SDK 验证码功能
# Generated by MCP
# 包含：发送验证码、验证验证码

# ==================== 发送验证码 ====================
sendCaptcha:
  method_name: "RXSDK.getInstance().sendCaptcha"
  description: 发送验证码
  parameters:
    - name: type
      type: CaptchaType
      required: true
      description: 验证码类型（PHONE 手机 或 EMAIL 邮箱）
    - name: target
      type: String
      required: true
      description: 手机号或邮箱地址
    - name: purpose
      type: String
      required: true
      description: 用途（register/login/bindPhone/resetPassword/changePhone 等）
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  return_type: boolean
  return_description: 是否成功发起请求
  code: |
    // ========== 瑞雪 SDK 发送手机验证码 ==========
    // purpose 用途说明:
    //   - register: 注册
    //   - login: 登录
    //   - bindphone: 绑定手机
    //   - unbindphone: 解绑手机
    //   - resetpwd: 重置密码
    //   - changepwd: 修改密码
    //   - setpwd: 设置密码
    
    String phone = "xxxxxx";           // 必填，手机号，类型 String
    String purpose = "login";          // 必填，用途，类型 String

    boolean result = RXSDK.getInstance().sendCaptcha(
            CaptchaType.PHONE,     // 验证码类型：手机
            phone,                  // 手机号
            purpose,                // 用途
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "验证码发送成功");
                        // TODO: 开始 60 秒倒计时，禁用发送按钮
                    } else {
                        String msg = jsonObject.optString("msg");
                        Log.e("RXSDK", "验证码发送失败: " + msg);
                    }
                }
            }
    );

    if (!result) {
        Log.e("RXSDK", "发送验证码请求失败，请检查参数");
    }

    // ========== 瑞雪 SDK 发送邮箱验证码 ==========
    // purpose 用途说明:
    //   - bindemail: 绑定邮箱
    //   - unbindemail: 解绑邮箱
    
    String email = "xxxxxx";           // 必填，邮箱地址，类型 String
    String emailPurpose = "bindemail"; // 必填，用途，类型 String

    RXSDK.getInstance().sendCaptcha(
            CaptchaType.EMAIL,     // 验证码类型：邮箱
            email,                  // 邮箱地址
            emailPurpose,           // 用途
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "邮箱验证码发送成功");
                    } else {
                        Log.e("RXSDK", "邮箱验证码发送失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 验证验证码 ====================
verifyCaptcha:
  method_name: "RXSDK.getInstance().verifyCaptcha"
  description: 验证验证码
  parameters:
    - name: type
      type: CaptchaType
      required: true
      description: 验证码类型（PHONE 或 EMAIL）
    - name: target
      type: String
      required: true
      description: 手机号或邮箱地址
    - name: purpose
      type: String
      required: true
      description: 用途
    - name: captchaCode
      type: String
      required: true
      description: 用户输入的验证码
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  return_type: boolean
  return_description: 是否成功发起请求
  code: |
    // ========== 瑞雪 SDK 验证手机验证码 ==========
    // purpose 用途说明:
    //   - register: 注册
    //   - login: 登录
    //   - bindphone: 绑定手机
    //   - unbindphone: 解绑手机
    //   - resetpwd: 重置密码
    //   - changepwd: 修改密码
    //   - setpwd: 设置密码
    
    String phone = "xxxxxx";           // 必填，手机号，类型 String
    String captchaCode = "xxxxxx";     // 必填，用户输入的验证码，类型 String
    String purpose = "login";          // 必填，用途，类型 String

    boolean result = RXSDK.getInstance().verifyCaptcha(
            CaptchaType.PHONE,      // 验证码类型
            phone,                   // 手机号
            purpose,                 // 用途
            captchaCode,             // 用户输入的验证码
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "验证码验证成功");
                        // TODO: 继续后续业务逻辑（如完成注册、绑定手机等）
                    } else {
                        String msg = jsonObject.optString("msg");
                        Log.e("RXSDK", "验证码验证失败: " + msg);
                    }
                }
            }
    );

    if (!result) {
        Log.e("RXSDK", "验证码验证请求失败");
    }

    // ========== 瑞雪 SDK 验证邮箱验证码 ==========
    // purpose 用途说明:
    //   - bindemail: 绑定邮箱
    //   - unbindemail: 解绑邮箱
    
    String email = "xxxxxx";           // 必填，邮箱地址，类型 String
    String emailCaptcha = "xxxxxx";    // 必填，用户输入的验证码，类型 String
    String emailPurpose = "bindemail"; // 必填，用途，类型 String

    RXSDK.getInstance().verifyCaptcha(
            CaptchaType.EMAIL,
            email,
            emailPurpose,
            emailCaptcha,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "邮箱验证码验证成功");
                    } else {
                        Log.e("RXSDK", "邮箱验证码验证失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# 验证码类型常量
captcha_types:
  - name: PHONE
    value: CaptchaType.PHONE
    description: 手机验证码
  - name: EMAIL
    value: CaptchaType.EMAIL
    description: 邮箱验证码

# 验证码用途常量
captcha_purposes:
  - name: register
    description: 注册
  - name: login
    description: 登录
  - name: bindphone
    description: 绑定手机
  - name: unbindphone
    description: 解绑手机
  - name: resetpwd
    description: 重置密码
  - name: changepwd
    description: 修改密码
  - name: bindemail
    description: 绑定邮箱
  - name: unbindemail
    description: 解绑邮箱
  - name: setpwd
    description: 设置密码

# 导入语句
imports:
  - "import android.os.CountDownTimer;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.openapi.CaptchaType;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 检查是否存在 RXSDK.getInstance().sendCaptcha 或 verifyCaptcha 方法调用
  - 验证 CaptchaType 参数是否正确（PHONE 或 EMAIL）
  - 验证 purpose 参数是否为有效的用途值
  - 验证回调是否实现了 onResponse(JSONObject) 方法
  - 检查是否正确判断 code == 0 表示成功
  - 建议添加发送验证码后的倒计时逻辑

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "添加验证码功能"
    - "发送验证码"
    - "验证验证码"
    - "手机验证码"
    - "邮箱验证码"
  actions:
    - 根据用户需求选择发送或验证验证码的代码片段
    - 询问用户验证码类型（手机还是邮箱）
    - 询问用户验证码用途
    - 确保必要的 import 语句已添加
    - 建议添加倒计时逻辑
