# 瑞雪 SDK 账号注销 UI 功能
# Generated by MCP
# 包含：申请注销UI、撤销注销UI

# ==================== 申请注销 UI ====================
applyForDeregisterUI:
  method_name: "RXSdkUI.getInstance().applyForDeregisterUI"
  description: 申请注销账号 UI（H5 页面）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: rxUserCenterConfig
      type: RXUserCenterConfig
      required: true
      description: 注销配置
    - name: callback
      type: RXUICallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 申请注销 UI ==========
    // 注意：需要添加 UI 模块依赖 implementation 'com.ruixue:rxsdk_base_ui:${version}'
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.openapi.RXUserCenterConfig;
    import com.ruixue.callback.RXUICallback;
    
    // 创建注销配置
    RXUserCenterConfig config = new RXUserCenterConfig();
    config.setGame_user_id("游戏用户ID");      // 游戏用户 ID
    config.setNickname("用户昵称");            // 用户昵称
    config.setHead_img_url("头像URL");         // 用户头像 URL
    config.setQueue_name("default");           // 队列名称
    
    RXSdkUI.getInstance().applyForDeregisterUI(activity, config, new RXUICallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "注销申请成功: " + data);
            // TODO: 处理注销申请成功逻辑
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "注销申请失败: " + cause);
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "注销申请错误: " + e.getMessage());
        }
    }).show();

# ==================== 撤销注销 UI ====================
destroyAccountStatusView:
  method_name: "RXSdkUI.getInstance().destroyAccountStatusView"
  description: 撤销注销弹窗
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: isLoginContinue
      type: boolean
      required: true
      description: true 继续登录，false 退出登录
    - name: callback
      type: RXJSONCallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 撤销注销弹窗 ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.RXJSONCallback;
    
    // isLoginContinue: true 表示撤销后继续登录，false 表示撤销后退出登录
    boolean isLoginContinue = true;
    
    RXSdkUI.getInstance().destroyAccountStatusView(activity, isLoginContinue, new RXJSONCallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "撤销注销成功");
            // TODO: 处理撤销注销成功逻辑
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "撤销注销失败");
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "撤销注销错误: " + e.getMessage());
        }
    }).show();

# ==================== 撤销注销 UI（自定义按钮文本） ====================
destroyAccountStatusViewWithText:
  method_name: "RXSdkUI.getInstance().destroyAccountStatusView"
  description: 撤销注销弹窗（自定义按钮文本）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: okButtonText
      type: String
      required: true
      description: 右侧按钮文本
    - name: callback
      type: RXJSONCallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 撤销注销弹窗（自定义按钮） ==========
    
    RXSdkUI.getInstance().destroyAccountStatusView(activity, "继续使用", callback).show();

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSdkUI;"
  - "import com.ruixue.openapi.RXUserCenterConfig;"
  - "import com.ruixue.callback.RXUICallback;"
  - "import com.ruixue.RXJSONCallback;"
  - "import com.ruixue.error.RXException;"
  - "import org.json.JSONObject;"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    artifact: "com.ruixue:rxsdk_base_ui"
    description: 账号注销 UI 需要添加此依赖
