# 瑞雪 SDK 设备信息功能
# Generated by MCP
# 版本要求：SetGameInfo / SetThirdGameInfo 需要 Android SDK >= 4.0.16

# ==================== 获取设备码 ====================
getDeviceCode:
  method_name: "RXSDK.getInstance().getDeviceCode"
  description: 获取设备唯一标识码
  parameters:
    - name: context
      type: Context
      required: true
      description: 上下文对象
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取设备码 ==========
    String deviceCode = RXSDK.getInstance().getDeviceCode(context);  // 类型 String
    Log.d("RXSDK", "设备码: " + deviceCode);

# ==================== 获取时区偏移 ====================
getTimeZoneOffset:
  method_name: "RXSDK.getInstance().getTimeZoneOffset"
  description: 获取当前时区与 UTC 时差
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取时区偏移 ==========
    String offset = RXSDK.getInstance().getTimeZoneOffset();  // 类型 String，格式如 "+08:00"
    Log.d("RXSDK", "时区偏移: " + offset);

# ==================== 获取系统语言 ====================
getSystemLanguage:
  method_name: "RXSDK.getInstance().getSystemLanguage"
  description: 获取当前系统语言
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取系统语言 ==========
    String language = RXSDK.getInstance().getSystemLanguage();  // 类型 String，如 "zh"、"en"
    Log.d("RXSDK", "系统语言: " + language);

# ==================== 获取 SDK 信息 ====================
getSdkInfo:
  method_name: "RXSDK.getInstance().getSdkInfo"
  description: 获取 SDK 版本信息
  return_type: SdkInfo
  code: |
    // ========== 瑞雪 SDK 获取 SDK 信息 ==========
    SdkInfo sdkInfo = RXSDK.getInstance().getSdkInfo();  // 类型 SdkInfo
    String version = sdkInfo.getVersion();
    String buildType = sdkInfo.getBuildType();
    Log.d("RXSDK", "SDK 版本: " + version + ", 构建类型: " + buildType);

# ==================== 获取渠道信息 ====================
getChannel:
  method_name: "RXSDK.getInstance().getChannel"
  description: 获取当前渠道标识
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取渠道信息 ==========
    String channel = RXSDK.getInstance().getChannel();  // 类型 String
    Log.d("RXSDK", "当前渠道: " + channel);

# ==================== 获取 OpenID ====================
getOpenId:
  method_name: "RXSDK.getInstance().getOpenId"
  description: 获取当前登录用户的 OpenID
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取 OpenID ==========
    String openId = RXSDK.getInstance().getOpenId();  // 类型 String，未登录时返回 null
    if (openId != null) {
        Log.d("RXSDK", "用户 OpenID: " + openId);
    } else {
        Log.d("RXSDK", "用户未登录");
    }

# ==================== 获取 BaseUrl ====================
getFirstBaseUrl:
  method_name: "RXSDK.getInstance().getFirstBaseUrl"
  description: 获取当前请求域名
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取 BaseUrl ==========
    String baseUrl = RXSDK.getInstance().getFirstBaseUrl();  // 类型 String
    Log.d("RXSDK", "当前 BaseUrl: " + baseUrl);

# ==================== 设置当前语言 ====================
setLanguage:
  method_name: "RXSDK.getInstance().setLanguage"
  description: 设置当前语言
  parameters:
    - name: context
      type: Context
      required: true
      description: 上下文对象
    - name: language
      type: String
      required: true
      description: 语言码（如 en、zh-Hans、ja 等）
  code: |
    // ========== 瑞雪 SDK 设置当前语言 ==========
    String language = "zh-Hans";  // 必填，语言码（如 en、zh-Hans、ja 等），类型 String

    RXSDK.getInstance().setLanguage(context, language);
    Log.d("RXSDK", "已设置语言为: " + language);

# ==================== 设置子渠道 ID ====================
setSubChannelId:
  method_name: "RXSDK.getInstance().setSubChannelId"
  description: 设置子渠道 ID
  parameters:
    - name: subChannelId
      type: String
      required: true
      description: 子渠道 ID
  code: |
    // ========== 瑞雪 SDK 设置子渠道 ID ==========
    String subChannelId = "sub_channel_001";  // 必填，子渠道 ID，类型 String

    RXSDK.getInstance().setSubChannelId(subChannelId);
    Log.d("RXSDK", "已设置子渠道 ID: " + subChannelId);

# ==================== 设置密码强度 ====================
setPasswordStrength:
  method_name: "RXSDK.setPasswordStrength"
  description: 设置密码强度（静态方法）
  parameters:
    - name: passwordStrength
      type: PasswordStrength 或 int
      required: true
      description: 密码强度枚举或整数值
  code: |
    // ========== 瑞雪 SDK 设置密码强度 ==========
    // 使用枚举方式
    RXSDK.setPasswordStrength(PasswordStrength.MEDIUM);
    
    // 或使用整数方式
    // RXSDK.setPasswordStrength(2);  // 1=弱, 2=中, 3=强
    Log.d("RXSDK", "已设置密码强度");

# ==================== 设置密码正则 ====================
setPwdPattern:
  method_name: "RXSDK.setPwdPattern"
  description: 设置密码正则表达式（静态方法）
  parameters:
    - name: pwdPattern
      type: String
      required: true
      description: 密码正则表达式
  code: |
    // ========== 瑞雪 SDK 设置密码正则 ==========
    String pattern = "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$";  // 8位以上，含字母和数字
    
    RXSDK.setPwdPattern(pattern);
    Log.d("RXSDK", "已设置密码正则: " + pattern);

# ==================== 设置地区 ====================
setArea:
  method_name: "RXSDK.setArea"
  description: 设置地区码（静态方法）
  parameters:
    - name: area
      type: String
      required: true
      description: 地区码（如 CN、US、JP 等）
  code: |
    // ========== 瑞雪 SDK 设置地区 ==========
    String area = "CN";  // 地区码（如 CN、US、JP、KR、SEA 等）
    
    RXSDK.setArea(area);
    Log.d("RXSDK", "已设置地区: " + area);

# ==================== 设置自定义错误码 ====================
setErrorMsg:
  method_name: "RXSDK.setErrorMsg"
  description: 设置自定义错误码信息（静态方法）
  parameters:
    - name: map
      type: Map<String, Map<String, String>>
      required: true
      description: 自定义错误码字典（语言 -> 错误码 -> 消息模板）
  code: |
    // ========== 瑞雪 SDK 设置自定义错误码 ==========
    Map<String, Map<String, String>> map = new HashMap<>();
    
    // 中文错误消息
    Map<String, String> zh = new HashMap<>();
    zh.put("2002", "自定义消息 $code$$thirdcode$$thirdmsg$");
    zh.put("2000", "");
    zh.put("default", "$msg$:$code$");
    
    // 英文错误消息
    Map<String, String> en = new HashMap<>();
    en.put("2002", "custom error $code$$thirdcode$$thirdmsg$");
    en.put("2000", "error demo ");
    en.put("default", "$msg$:$code$");
    
    map.put("zh", zh);
    map.put("en", en);
    
    RXSDK.setErrorMsg(map);
    Log.d("RXSDK", "已设置自定义错误码");

# ==================== 配置埋点上报参数 ====================
trackConfig:
  method_name: "RXSDK.trackConfig"
  description: 配置埋点上报参数（静态方法）
  parameters:
    - name: reportTime
      type: int
      required: true
      description: 上报时间间隔（秒）
    - name: maxCount
      type: int
      required: true
      description: 最大缓存条数
  code: |
    // ========== 瑞雪 SDK 配置埋点上报参数 ==========
    int reportTime = 60;   // 上报时间间隔（秒）
    int maxCount = 100;    // 最大缓存条数
    
    RXSDK.trackConfig(reportTime, maxCount);
    Log.d("RXSDK", "已配置埋点上报参数: 间隔=" + reportTime + "s, 最大条数=" + maxCount);

# ==================== 单独设置埋点上报时间间隔 ====================
setDataTrackFlushInterval:
  method_name: "RXSDK.getInstance().setDataTrackFlushInterval"
  description: 单独设置埋点上报时间间隔（毫秒）；<=0 时忽略并保持默认 60s
  parameters:
    - name: flushInterval
      type: int
      required: true
      description: 上报时间间隔（毫秒）
  code: |
    // ========== 瑞雪 SDK 单独设置埋点上报时间间隔 ==========
    int flushInterval = 60000;   // 上报时间间隔（毫秒），默认 60s

    RXSDK.getInstance().setDataTrackFlushInterval(flushInterval);
    Log.d("RXSDK", "已设置埋点上报间隔: " + flushInterval + "ms");

# ==================== 单独设置埋点最大缓存条数 ====================
setDataTrackMaxCacheCount:
  method_name: "RXSDK.getInstance().setDataTrackMaxCacheCount"
  description: 单独设置埋点最大缓存条数；<=0 时忽略并保持默认 100
  parameters:
    - name: maxCacheCount
      type: int
      required: true
      description: 最大缓存条数
  code: |
    // ========== 瑞雪 SDK 单独设置埋点最大缓存条数 ==========
    int maxCacheCount = 100;   // 最大缓存条数，默认 100

    RXSDK.getInstance().setDataTrackMaxCacheCount(maxCacheCount);
    Log.d("RXSDK", "已设置埋点最大缓存条数: " + maxCacheCount);

# ==================== 获取产品ID ====================
getProductId:
  method_name: "RXSDK.getProductId"
  description: 获取产品 ID（静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取产品 ID ==========
    String productId = RXSDK.getProductId();  // 类型 String
    Log.d("RXSDK", "产品 ID: " + productId);

# ==================== 获取渠道ID ====================
getChannelId:
  method_name: "RXSDK.getChannelId"
  description: 获取渠道 ID（静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取渠道 ID ==========
    String channelId = RXSDK.getChannelId();  // 类型 String
    Log.d("RXSDK", "渠道 ID: " + channelId);

# ==================== 获取子渠道ID ====================
getSubChannelId:
  method_name: "RXSDK.getSubChannelId"
  description: 获取子渠道 ID（静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取子渠道 ID ==========
    String subChannelId = RXSDK.getSubChannelId();  // 类型 String，可能为 null
    Log.d("RXSDK", "子渠道 ID: " + subChannelId);

# ==================== 获取CPID ====================
getCpId:
  method_name: "RXSDK.getCpId"
  description: 获取 CP ID（商户 ID，静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取 CP ID ==========
    String cpId = RXSDK.getCpId();  // 类型 String
    Log.d("RXSDK", "CP ID: " + cpId);

# ==================== 获取SDK版本号 ====================
getSdkVersion:
  method_name: "RXSDK.getSdkVersion"
  description: 获取 SDK 版本号（静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取版本号 ==========
    String sdkVersion = RXSDK.getSdkVersion();  // 类型 String
    Log.d("RXSDK", "SDK 版本: " + sdkVersion);

# ==================== 获取当前语言 ====================
getLanguage:
  method_name: "RXSDK.getLanguage"
  description: 获取当前语言（静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取当前语言 ==========
    String language = RXSDK.getLanguage();  // 类型 String
    Log.d("RXSDK", "当前语言: " + language);

# ==================== 获取SDK日志 ====================
getSDKLog:
  method_name: "RXSDK.getSDKLog"
  description: 获取 SDK 日志（静态方法）
  return_type: List<String>
  code: |
    // ========== 瑞雪 SDK 获取日志 ==========
    List<String> logs = RXSDK.getSDKLog();  // 类型 List<String>
    for (String log : logs) {
        Log.d("RXSDK", "日志: " + log);
    }

# ==================== 获取distinctId ====================
getDistinctId:
  method_name: "RXSDK.getDistinctId"
  description: 获取客户端随机生成的唯一 ID（静态方法）
  return_type: String
  code: |
    // ========== 瑞雪 SDK 获取 distinctId ==========
    String distinctId = RXSDK.getDistinctId();  // 类型 String
    Log.d("RXSDK", "Distinct ID: " + distinctId);

# ==================== 设置游戏信息（简化版） ====================
setGameInfo:
  method_name: "RXSDK.getInstance().setGameInfo"
  description: 上报到瑞雪的当前角色 ID 和区服 ID
  parameters:
    - name: roleId
      type: String
      required: true
      description: 游戏角色 ID
    - name: regionTag
      type: String
      required: true
      description: 区服/服务器 ID
  code: |
    // ========== 瑞雪 SDK 设置游戏信息（简化版） ==========
    String roleId = "role_001";     // 必填，游戏角色 ID，类型 String
    String regionTag = "server_001"; // 必填，区服/服务器 ID，类型 String

    RXSDK.getInstance().setGameInfo(roleId, regionTag);
    Log.d("RXSDK", "已设置游戏信息: roleId=" + roleId + ", regionTag=" + regionTag);

# ==================== 上报区服角色（对象版） ====================
setGameInfoWithObject:
  method_name: "void RXSDK.getInstance().setGameInfo(GameInfo gameInfo)"
  unity_api: "RuiXueSdk.SetThirdGameInfo(GameInfo gameInfo)"
  description: 上报完整用户/角色信息到当前三方渠道；Android 原生入口仍为 setGameInfo(GameInfo)
  min_version:
    android: "4.0.16"
  parameters:
    - name: gameInfo
      type: GameInfo
      required: true
      description: 区服角色信息对象
  game_info_fields:
    required:
      - roleId: 角色 ID，String
      - roleName: 角色名称，String，构造时未传则默认等于 roleId
      - serverId: 服务器 ID，String，构造时为空会被设为 "default"
      - serverName: 服务器名称，String，构造时未传则默认等于 serverId
      - gameRoleLevel: 角色等级，String，默认 "1"
      - type: 操作类型，int，不同渠道取值不同
    conditional:
      - roleCreateTime: 角色创建时间，long，创角时必传；使用 type=1 构造时会自动填当前时间
    optional:
      - partyId: 公会 ID，String
      - partyName: 公会名称，String
      - vipLevel: VIP 等级，int
      - gameRolePower: 角色战力，int
      - experience: 经验值，String
      - balance: 角色余额，String
      - attach: 业务自定义透传字段，String
  type_mapping:
    xuteng:
      1: 选服页面
      2: 创建角色
      3: 进入游戏
      4: 等级提升
    quick:
      1: 创建角色
      2: 进入游戏
      3: 角色升级
      4: 角色退出
  code: |
    // ========== 瑞雪 SDK 上报区服角色（对象版） ==========
    // 必须在登录成功后调用；不同渠道的 type 定义不同，请按接入渠道选择取值。
    int type = 2;                   // 栩腾：2=创建角色；quick：2=进入游戏
    String roleId = "role_001";     // 必填，角色 ID
    String serverId = "server_001"; // 必填，服务器 ID

    GameInfo gameInfo = new GameInfo(type, roleId, serverId);
    gameInfo.setRoleName("角色名");
    gameInfo.setServerName("服务器名");
    gameInfo.setGameRoleLevel("50");

    // 创角事件必须传角色创建时间。只有 type=1 构造时 SDK 会自动填当前时间；
    // 若当前渠道的“创建角色”不是 type=1（如栩腾 type=2），请显式设置。
    gameInfo.setRoleCreateTime(System.currentTimeMillis());

    // 可选字段
    gameInfo.setPartyId("guild_001");
    gameInfo.setPartyName("瑞雪公会");
    gameInfo.setVipLevel(5);
    gameInfo.setGameRolePower(100000);
    gameInfo.setExperience("1000");
    gameInfo.setBalance("100");
    gameInfo.setAttach("{\"scene\":\"enter_game\"}");

    RXSDK.getInstance().setGameInfo(gameInfo);
    Log.d("RXSDK", "已上报区服角色: roleId=" + roleId + ", serverId=" + serverId + ", type=" + type);

# ==================== 判断用户是否已登录 ====================
isLogin:
  method_name: "RXSDK.getInstance().isLogin"
  description: 判断用户是否已登录
  return_type: boolean
  code: |
    // ========== 瑞雪 SDK 判断登录状态 ==========
    boolean isLoggedIn = RXSDK.getInstance().isLogin();  // 类型 boolean
    if (isLoggedIn) {
        Log.d("RXSDK", "用户已登录");
    } else {
        Log.d("RXSDK", "用户未登录");
    }

# ==================== 获取当前登录数据 ====================
getLoginData:
  method_name: "RXSDK.getInstance().getLoginData"
  description: 获取当前登录数据
  return_type: LoginData
  code: |
    // ========== 瑞雪 SDK 获取登录数据 ==========
    LoginData loginData = RXSDK.getInstance().getLoginData();  // 类型 LoginData
    if (loginData != null) {
        String openId = loginData.getOpenId();
        String token = loginData.getToken();
        Log.d("RXSDK", "登录数据: openId=" + openId);
    } else {
        Log.d("RXSDK", "未获取到登录数据");
    }

# ==================== 检查登录是否失效 ====================
loginOpenidExpireInvalid:
  method_name: "RXSDK.getInstance().loginOpenidExpireInvalid"
  description: 检查 login_openid 是否失效
  return_type: boolean
  code: |
    // ========== 瑞雪 SDK 检查登录是否失效 ==========
    boolean isExpired = RXSDK.getInstance().loginOpenidExpireInvalid();  // 类型 boolean
    if (isExpired) {
        Log.d("RXSDK", "登录已失效，需要重新登录");
        // TODO: 提示用户重新登录
    } else {
        Log.d("RXSDK", "登录有效");
    }

# ==================== 检查隐私协议状态 ====================
isAgreedPrivacy:
  method_name: "RXSDK.getInstance().isAgreedPrivacy"
  description: 检查用户是否已同意隐私协议
  return_type: boolean
  code: |
    // ========== 瑞雪 SDK 检查隐私协议状态 ==========
    boolean isAgreed = RXSDK.getInstance().isAgreedPrivacy();  // 类型 boolean
    if (isAgreed) {
        Log.d("RXSDK", "用户已同意隐私协议");
    } else {
        Log.d("RXSDK", "用户未同意隐私协议");
    }

# ==================== 跳转到应用商店 ====================
jumpToAppStore:
  method_name: "RXSDK.getInstance().jumpToAppStore"
  description: 跳转到应用商店
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
  return_type: boolean
  code: |
    // ========== 瑞雪 SDK 跳转到应用商店 ==========
    boolean success = RXSDK.getInstance().jumpToAppStore(activity);  // 类型 boolean
    if (success) {
        Log.d("RXSDK", "已跳转到应用商店");
    } else {
        Log.e("RXSDK", "跳转应用商店失败");
    }

# ==================== 创建自定义请求 ====================
createRequest:
  method_name: "RXSDK.getInstance().createRequest"
  description: 创建自定义接口请求
  parameters:
    - name: api
      type: String
      required: true
      description: 接口路径
    - name: bodyMap
      type: Map<String, Object>
      required: true
      description: 接口参数
  return_type: IRXRequest
  code: |
    // ========== 瑞雪 SDK 创建自定义请求 ==========
    String api = "/api/custom/endpoint";  // 必填，接口路径，类型 String
    Map<String, Object> bodyMap = new HashMap<>();
    bodyMap.put("param1", "value1");
    bodyMap.put("param2", 123);

    IRXRequest request = RXSDK.getInstance().createRequest(api, bodyMap);

    // 发起异步请求（避免主线程阻塞）
    request.postAsync(new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                Log.d("RXSDK", "自定义请求成功: " + data);
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "自定义请求失败: " + msg);
            }
        }
    });

# ==================== 设置防沉迷代理 ====================
setupAddictDelegate:
  method_name: "RXSDK.getInstance().setupAddictDelegate"
  description: 设置防沉迷代理
  parameters:
    - name: antiAddictDelegate
      type: AntiAddictDelegate
      required: false
      description: 防沉迷代理（可选）
  code: |
    // ========== 瑞雪 SDK 设置防沉迷代理 ==========
    RXSDK.getInstance().setupAddictDelegate(new AntiAddictDelegate() {
        @Override
        public void onAntiAddictResult(int result, String message) {
            // result: 0 = 通过, 其他 = 受限
            if (result == 0) {
                Log.d("RXSDK", "防沉迷检查通过");
            } else {
                Log.w("RXSDK", "防沉迷受限: " + message);
                // TODO: 处理防沉迷限制逻辑
            }
        }
    });

# ==================== 媒体平台自定义行为上报 ====================
addAttribution:
  method_name: "RXSDK.getInstance().addAttribution"
  description: 媒体平台自定义行为上报
  parameters:
    - name: params
      type: Map<String, Object>
      required: true
      description: 上报数据
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 媒体平台自定义行为上报 ==========
    Map<String, Object> params = new HashMap<>();
    params.put("event_type", "custom_event");
    params.put("event_value", "some_value");

    RXSDK.getInstance().addAttribution(params, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "归因上报成功");
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "归因上报失败: " + msg);
            }
        }
    });

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.content.Context;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.openapi.IRXRequest;"
  - "import com.ruixue.openapi.GameInfo;"
  - "import com.ruixue.openapi.PasswordStrength;"
  - "import com.ruixue.base.SdkInfo;"
  - "import com.ruixue.passport.LoginData;"
  - "import com.ruixue.legal.AntiAddictDelegate;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"
  - "import java.util.List;"
