# 瑞雪 SDK Android Firebase 组件接入规范
# Generated by MCP
# 包含：Analytics、Crashlytics、FCM 推送、瑞雪推送封装

# ==================== 占位符说明 ====================
placeholder_note:
  description: "@test 是占位符，接入时必须替换为真实业务参数。"

# ==================== 概述 ====================
overview:
  description: Firebase Android 组件封装，提供 Analytics 事件、Crashlytics 崩溃统计、FCM 消息和瑞雪推送封装。
  keywords:
    - Firebase
    - Analytics
    - Crashlytics
    - FCM
    - Push
  note: |
    1. 海外渠道引用 com.ruixue:rxsdk_firebase:${version}
    2. google-services.json 必须放在 app 模块或对应 flavor 目录
    3. app 模块必须 apply com.google.gms.google-services 插件
    4. 需要 Crashlytics 时同时 apply com.google.firebase.crashlytics 插件
    5. Google 登录场景需确保 Firebase 控制台登记的 SHA-1 与打包 keystore 一致

# ==================== 接入前检查 ====================
preflight_check:
  required:
    - app/build.gradle 或 app/build.gradle.kts 已添加 com.ruixue:rxsdk_firebase:${version}
    - app 模块已应用 com.google.gms.google-services 插件
    - app 模块或 src/<flavor>/ 下存在 google-services.json
    - 需要 Crashlytics 时，根 build.gradle classpath 或 plugins 中包含 firebase-crashlytics-gradle，并在 app 模块应用 com.google.firebase.crashlytics
  failure_action: "缺少依赖、google-services.json 或 google-services 插件时，先补齐 Firebase 基础接入，再插入业务代码。"
  diagnostics:
    - "./gradlew :app:processReleaseGoogleServices --info"
    - "adb logcat -d | grep -iE 'FirebaseApp|FirebaseInitProvider|rxpush'"

# ==================== Gradle 依赖 ====================
dependency:
  artifact: "com.ruixue:rxsdk_firebase:${version}"
  google_services_plugin: "com.google.gms.google-services"
  crashlytics_plugin: "com.google.firebase.crashlytics"
  groovy: |
    // 根 build.gradle
    buildscript {
        dependencies {
            classpath 'com.google.gms:google-services:4.3.10'
            classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.2' // 需要 Crashlytics 时
        }
    }

    // app/build.gradle
    plugins {
        id 'com.android.application'
        id 'com.google.gms.google-services'
        id 'com.google.firebase.crashlytics' // 需要 Crashlytics 时
    }

    dependencies {
        implementation 'com.ruixue:rxsdk_firebase:${version}'
    }

# ==================== google-services.json ====================
google_services_json:
  path:
    - "app/google-services.json"
    - "app/src/<flavor>/google-services.json"
  requirement: "client[].client_info.android_client_info.package_name 必须与宿主 applicationId 完全一致"
  common_error: "No matching client found for package name"

# ==================== Analytics ====================
analytics:
  imports:
    - "import android.os.Bundle;"
    - "import com.ruixue.sdk.firebase.FirebaseSdkWrapper;"
    - "import com.ruixue.sdk.firebase.config.RxFirebaseAnalytics;"
  init:
    method_name: "FirebaseSdkWrapper.getInstance().initFirebaseAnalytics"
    code: |
      // 初始化 Firebase Analytics
      FirebaseSdkWrapper.getInstance().initFirebaseAnalytics(this);
  log_event:
    method_name: "FirebaseSdkWrapper.getInstance().getFirebaseAnalytics().logEvent"
    code: |
      Bundle bundle = new Bundle();
      bundle.putString(RxFirebaseAnalytics.Param.ITEM_ID, "@test");
      bundle.putString(RxFirebaseAnalytics.Param.ITEM_NAME, "@test");
      bundle.putString(RxFirebaseAnalytics.Param.CONTENT_TYPE, "@test");
      FirebaseSdkWrapper.getInstance().getFirebaseAnalytics()
              .logEvent(RxFirebaseAnalytics.Event.SELECT_CONTENT, bundle);
  default_event_parameters:
    method_name: "setDefaultEventParameters"
    code: |
      Bundle parameters = new Bundle();
      parameters.putString("@test", "@test");
      parameters.putInt("@test", 4);
      FirebaseSdkWrapper.getInstance().getFirebaseAnalytics().setDefaultEventParameters(parameters);
  user_property:
    method_name: "setUserProperty"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseAnalytics().setUserProperty("@test", "@test");
  user_id:
    method_name: "setAnalyticsUserId"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseAnalytics().setAnalyticsUserId("@test");
  collection_enabled:
    method_name: "setAnalyticsCollectionEnabled"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseAnalytics().setAnalyticsCollectionEnabled(true);

# ==================== Crashlytics ====================
crashlytics:
  imports:
    - "import com.ruixue.sdk.firebase.FirebaseSdkWrapper;"
    - "import com.ruixue.sdk.firebase.data.RxCustomKeysAndValues;"
  custom_key:
    method_name: "FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().setCustomKey"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().setCustomKey("@test", "@test");
  custom_keys:
    method_name: "setCustomKeys"
    code: |
      RxCustomKeysAndValues keysAndValues = new RxCustomKeysAndValues.Builder()
              .putString("@test", "@test")
              .putBoolean("@test", true)
              .putFloat("@test", 1.01f)
              .build();
      FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().setCustomKeys(keysAndValues);
  log:
    method_name: "log"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().log("@test");
  user_id:
    method_name: "setCrashUserId"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().setCrashUserId("@test");
  record_exception:
    method_name: "recordException"
    code: |
      try {
          throw new RuntimeException("@test");
      } catch (Exception e) {
          FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().recordException(e);
      }
  collection_enabled:
    method_name: "setCrashlyticsCollectionEnabled"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().setCrashlyticsCollectionEnabled(true);

# ==================== FCM / 瑞雪推送封装 ====================
push:
  imports:
    - "import android.Manifest;"
    - "import android.content.Intent;"
    - "import android.os.Build;"
    - "import com.google.android.gms.tasks.OnCompleteListener;"
    - "import com.google.firebase.messaging.RemoteMessage;"
    - "import com.ruixue.push.RxPushManager;"
    - "import com.ruixue.push.core.DeviceResultCallback;"
    - "import com.ruixue.sdk.firebase.FirebaseSdkWrapper;"
  manifest_auto_init_off: |
    <meta-data
        android:name="firebase_messaging_auto_init_enabled"
        android:value="false" />
    <meta-data
        android:name="firebase_analytics_collection_enabled"
        android:value="false" />
  android_13_permission: "Android 13+ 需要运行时请求 android.permission.POST_NOTIFICATIONS"
  rx_push_init:
    method_name: "RxPushManager.init / openAppCallback"
    code: |
      // 建议在 LAUNCHER Activity 的 onCreate 中调用
      boolean support = RxPushManager.init(this);
      RxPushManager.openAppCallback(getIntent());
  rx_push_register:
    method_name: "RxPushManager.registerToken"
    code: |
      // 瑞雪登录成功后注册 token
      RxPushManager.registerToken(new DeviceResultCallback() {
          @Override
          public void onResult(String result) {
              Log.d("rxpush", "registerToken: " + result + ", token=" + RxPushManager.getDeviceToken());
          }
      });
  rx_push_unregister:
    method_name: "RxPushManager.unRegisterToken"
    code: |
      // 瑞雪登出账号时反注册 token
      RxPushManager.unRegisterToken();
  rx_push_token_status:
    method_name: "RxPushManager.getDeviceToken / isSupport / getBrandName"
    code: |
      boolean support = RxPushManager.isSupport();
      String brand = RxPushManager.getBrandName();
      String token = RxPushManager.getDeviceToken();
      Log.d("rxpush", "support=" + support + ", brand=" + brand + ", token=" + token);
  rx_push_alias:
    method_name: "RxPushManager.bindAlias / unBindAlias"
    code: |
      RxPushManager.bindAlias("@test");
      RxPushManager.unBindAlias("@test");
  rx_push_on_new_intent:
    method_name: "RxPushManager.openAppCallback"
    code: |
      @Override
      protected void onNewIntent(Intent intent) {
          super.onNewIntent(intent);
          setIntent(intent);
          RxPushManager.openAppCallback(intent);
      }
  fcm_get_token:
    method_name: "FirebaseSdkWrapper.getInstance().getFirebaseMessaging().getToken"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseMessaging().getToken(task -> {
          Log.d("firebase-message", "getToken: " + task);
      });
  fcm_on_new_token:
    description: 扩展 FirebaseMessagingService / RxFirebaseMessagingService 并重写 onNewToken，可监听令牌变更
    code: |
      @Override
      public void onNewToken(@NonNull String token) {
          super.onNewToken(token);
          Log.d("firebase-message", "onNewToken: " + token);
      }
  fcm_auto_init:
    method_name: "setAutoInitEnabled"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseMessaging().setAutoInitEnabled(true);
  fcm_subscribe_topic:
    method_name: "subscribeToTopic"
    code: |
      FirebaseSdkWrapper.getInstance().getFirebaseMessaging().subscribeToTopic("@test", task -> {
          Log.d("firebase-message", "subscribe: " + task);
      });
  fcm_send_upstream:
    method_name: "send"
    code: |
      RemoteMessage remoteMessage = new RemoteMessage.Builder(SENDER_ID + "@fcm.googleapis.com")
              .setMessageId("@test")
              .addData("@test", "@test")
              .addData("@test", "@test")
              .build();
      FirebaseSdkWrapper.getInstance().getFirebaseMessaging().send(remoteMessage);

# ==================== 完整示例 ====================
code: |
  // ========== Android Firebase Analytics / Crashlytics / FCM ==========
  FirebaseSdkWrapper.getInstance().initFirebaseAnalytics(this);

  Bundle bundle = new Bundle();
  bundle.putString(RxFirebaseAnalytics.Param.ITEM_ID, "@test");
  bundle.putString(RxFirebaseAnalytics.Param.ITEM_NAME, "@test");
  FirebaseSdkWrapper.getInstance().getFirebaseAnalytics()
          .logEvent(RxFirebaseAnalytics.Event.SELECT_CONTENT, bundle);

  FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().setCustomKey("@test", "@test");
  FirebaseSdkWrapper.getInstance().getFirebaseCrashlytics().log("@test");

  RxPushManager.init(this);
  RxPushManager.openAppCallback(getIntent());
  RxPushManager.registerToken(result -> Log.d("rxpush", "registerToken: " + result));
  Log.d("rxpush", "token=" + RxPushManager.getDeviceToken());

# ==================== 注意事项 ====================
notes:
  - title: Firebase 配置文件
    content: google-services.json 必须放在 app 模块或 flavor 目录，且 package_name 与 applicationId 一致。
  - title: Gradle 插件
    content: app 模块必须 apply com.google.gms.google-services；Crashlytics 需要同时 apply com.google.firebase.crashlytics。
  - title: 默认 FirebaseApp
    content: Analytics、Crashlytics 和 FCM 都依赖默认 FirebaseApp，google-services 插件未生效时会初始化失败或静默不上报。
  - title: 推送
    content: Android 13+ 需要申请 POST_NOTIFICATIONS 运行时权限；瑞雪登录成功后再调用 RxPushManager.registerToken。
