# 瑞雪 SDK 好友管理功能
# Generated by MCP
# 包含：添加好友、删除好友、更新好友备注、判断是否好友、获取好友列表

# ==================== 添加好友 ====================
addFriends:
  method_name: "RXSDK.getInstance().addFriends"
  description: 添加好友
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: targetRemarks
      type: String
      required: false
      description: 用户给对方设置的备注
    - name: userRemarks
      type: String
      required: false
      description: 对方给用户设置的备注
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 添加好友 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String
    String remarks = "我的好友";                  // 可选，备注，类型 String

    RXSDK.getInstance().addFriends(targetOpenId, remarks, null, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "好友添加成功");
                // TODO: 更新好友列表 UI
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "好友添加失败: " + msg);
                // 常见错误：对方已是好友、对方不存在
            }
        }
    });

# ==================== 删除好友 ====================
removeFriends:
  method_name: "RXSDK.getInstance().removeFriends"
  description: 删除好友
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 删除好友 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String

    RXSDK.getInstance().removeFriends(targetOpenId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "好友删除成功");
                // TODO: 从好友列表中移除该好友
            } else {
                Log.e("RXSDK", "好友删除失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 更新好友备注 ====================
updateFriendRemarks:
  method_name: "RXSDK.getInstance().updateFriendRemarks"
  description: 更新好友备注
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: targetRemarks
      type: String
      required: false
      description: 备注信息
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 更新好友备注 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String
    String remarks = "新备注名称";                 // 必填，新备注，类型 String

    RXSDK.getInstance().updateFriendRemarks(targetOpenId, remarks, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "备注更新成功");
            } else {
                Log.e("RXSDK", "备注更新失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 判断是否为好友 ====================
isFriend:
  method_name: "RXSDK.getInstance().isFriend"
  description: 判断两用户是否为好友
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 判断是否为好友 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String

    RXSDK.getInstance().isFriend(targetOpenId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                boolean isFriend = data != null && data.optBoolean("is_friend", false);
                Log.d("RXSDK", "是否为好友: " + isFriend);
                // TODO: 根据结果更新 UI（如显示"添加好友"或"发送消息"按钮）
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取好友列表 ====================
relationFriends:
  method_name: "RXSDK.getInstance().relationFriends"
  description: 获取好友列表
  parameters:
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取好友列表 ==========
    RXSDK.getInstance().relationFriends(new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray friends = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "好友列表: " + friends);

                // 解析好友列表
                if (friends != null) {
                    for (int i = 0; i < friends.length(); i++) {
                        JSONObject friend = friends.optJSONObject(i);
                        String openid = friend.optString("openid");
                        String nickname = friend.optString("nickname");
                        String avatar = friend.optString("avatar");
                        String remarks = friend.optString("remarks");
                        Log.d("RXSDK", "好友: " + nickname + " (" + remarks + ")");
                    }
                }
                // TODO: 更新好友列表 UI
            } else {
                Log.e("RXSDK", "获取好友列表失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import org.json.JSONArray;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 检查 target 参数是否为有效的 OpenID
  - 验证回调是否实现了 onResponse(JSONObject) 方法
  - 建议在删除好友前显示确认对话框

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "添加好友"
    - "删除好友"
    - "好友列表"
    - "好友管理"
    - "判断好友"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
