# 瑞雪 SDK 游戏区服功能
# Generated by MCP
# 包含：查询区服、创建区服、更新区服、删除区服

# ==================== 查询游戏区服信息 ====================
searchGameAreaInfo:
  method_name: "RXSDK.getInstance().searchGameAreaInfo"
  description: 查询游戏区服信息
  parameters:
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 查询区服信息 ==========
    String areaId = "server_001";  // 必填，区服 ID，类型 String

    RXSDK.getInstance().searchGameAreaInfo(areaId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    String areaName = data.optString("area_name");
                    String areaStatus = data.optString("area_status");
                    String areaType = data.optString("area_type");
                    Log.d("RXSDK", "区服: " + areaName + ", 状态: " + areaStatus);
                }
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 查询区服列表 ====================
searchGameAreaListInfo:
  method_name: "RXSDK.getInstance().searchGameAreaListInfo"
  description: 查询区服列表信息
  parameters:
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 查询区服列表 ==========
    RXSDK.getInstance().searchGameAreaListInfo(new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray list = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "区服列表: " + list);

                if (list != null) {
                    for (int i = 0; i < list.length(); i++) {
                        JSONObject area = list.optJSONObject(i);
                        String areaId = area.optString("area_id");
                        String areaName = area.optString("area_name");
                        String areaStatus = area.optString("area_status");
                        Log.d("RXSDK", "区服: " + areaId + " - " + areaName + " [" + areaStatus + "]");
                    }
                }
                // TODO: 更新区服列表 UI
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 创建游戏区服 ====================
createGameArea:
  method_name: "RXSDK.getInstance().createGameArea"
  description: 创建游戏区服
  parameters:
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: areaName
      type: String
      required: true
      description: 区服名称
    - name: areaStatus
      type: String
      required: true
      description: 区服状态（如 "normal", "hot", "new", "maintain"）
    - name: areaType
      type: String
      required: true
      description: 区服类型
    - name: extension
      type: Map<String, Object>
      required: false
      description: 扩展字段
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 创建区服 ==========
    String areaId = "server_001";      // 必填，区服 ID，类型 String
    String areaName = "风云一区";       // 必填，区服名称，类型 String
    String areaStatus = "new";         // 必填，状态: normal/hot/new/maintain/full，类型 String
    String areaType = "pve";           // 必填，区服类型，类型 String

    // 扩展字段（可选）
    Map<String, Object> extension = new HashMap<>();
    extension.put("max_players", 10000);
    extension.put("open_time", "2024-01-01 00:00:00");

    RXSDK.getInstance().createGameArea(areaId, areaName, areaStatus, areaType, extension,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "区服创建成功");
                    } else {
                        Log.e("RXSDK", "区服创建失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 更新游戏区服信息 ====================
updateGameAreaInfo:
  method_name: "RXSDK.getInstance().updateGameAreaInfo"
  description: 修改游戏区服信息
  parameters:
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: areaName
      type: String
      required: false
      description: 区服名称
    - name: areaStatus
      type: String
      required: false
      description: 区服状态
    - name: areaType
      type: String
      required: false
      description: 区服类型
    - name: extension
      type: Map<String, Object>
      required: false
      description: 扩展字段
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 更新区服信息 ==========
    String areaId = "server_001";   // 必填，区服 ID，类型 String
    String areaStatus = "hot";       // 要更新的状态，类型 String

    RXSDK.getInstance().updateGameAreaInfo(areaId, null, areaStatus, null, null,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "区服信息更新成功");
                    } else {
                        Log.e("RXSDK", "更新失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 删除游戏区服 ====================
deleteGameArea:
  method_name: "RXSDK.getInstance().deleteGameArea"
  description: 删除游戏区服
  parameters:
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 删除区服 ==========
    String areaId = "server_001";  // 必填，区服 ID，类型 String

    RXSDK.getInstance().deleteGameArea(areaId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "区服删除成功");
            } else {
                Log.e("RXSDK", "删除失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 区服状态常量
area_status:
  - name: normal
    description: 正常
  - name: hot
    description: 火爆
  - name: new
    description: 新服
  - name: maintain
    description: 维护中
  - name: full
    description: 已满

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONArray;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 验证 areaId 参数是否有效
  - 验证 areaStatus 是否为有效的状态值
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "游戏区服"
    - "创建区服"
    - "查询区服"
    - "区服列表"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
