# 瑞雪 SDK 游戏角色功能
# Generated by MCP
# 包含：上报瑞雪游戏信息、上报三方渠道用户信息、创建角色、更新角色、删除角色、查询角色
# 版本要求：双游戏信息接口需要 Android SDK >= 4.0.16

preflight_check:
  min_version:
    android: "4.0.16"
  requirements:
    - "已完成 RXSDK.initialize / RXSdkInitConfig 初始化"
    - "Gradle 依赖中 com.ruixue:* 版本 >= 4.0.16"
  failure_action: "如果缺少瑞雪 SDK 依赖或版本低于 4.0.16，先执行 android feature=setup version=4.0.16 或 android feature=dependency version=4.0.16，再执行 Gradle Sync。"

# ==================== 上报到瑞雪的游戏信息 ====================
setGameInfo:
  method_name: "void RXSDK.getInstance().setGameInfo(String roleId, String regionTag)"
  unity_api: "RuiXueSdk.SetGameInfo(roleId, regionTag)"
  description: 上报到瑞雪的当前游戏角色 ID 和区服标识，供瑞雪请求头、日志及业务接口使用
  parameters:
    - name: roleId
      type: String
      required: true
      description: 游戏角色 ID
    - name: regionTag
      type: String
      required: true
      description: 区服/服务器标识
  code: |
    // ========== 上报到瑞雪的游戏信息 ==========
    String roleId = "role_001";
    String regionTag = "server_001";
    RXSDK.getInstance().setGameInfo(roleId, regionTag);

# ==================== 上报到三方渠道的用户信息 ====================
setThirdGameInfo:
  method_name: "void RXSDK.getInstance().setGameInfo(GameInfo gameInfo)"
  unity_api: "RuiXueSdk.SetThirdGameInfo(GameInfo gameInfo)"
  description: 上报完整用户/角色信息到当前三方渠道；Android 原生入口仍为 setGameInfo(GameInfo)
  parameters:
    - name: gameInfo
      type: GameInfo
      required: true
      description: 区服角色信息对象
  game_info_fields:
    - name: roleId
      type: String
      required: true
      description: 角色 ID
    - name: roleName
      type: String
      required: true
      description: 角色名称，构造时未单独设置则默认等于 roleId
    - name: serverId
      type: String
      required: true
      description: 服务器 ID，构造时为空会被设为 "default"
    - name: serverName
      type: String
      required: true
      description: 服务器名称，构造时未单独设置则默认等于 serverId
    - name: gameRoleLevel
      type: String
      required: true
      description: 角色等级，默认 "1"
    - name: type
      type: int
      required: true
      description: 操作类型，不同渠道取值不同，见 type_mapping
    - name: roleCreateTime
      type: long
      required: conditional
      description: 角色创建时间（毫秒），创角时必传；使用 type=1 构造时会自动填 System.currentTimeMillis()
    - name: partyId
      type: String
      required: false
      description: 公会 ID
    - name: partyName
      type: String
      required: false
      description: 公会名称
    - name: vipLevel
      type: int
      required: false
      description: VIP 等级
    - name: gameRolePower
      type: int
      required: false
      description: 角色战力
    - name: experience
      type: String
      required: false
      description: 经验值
    - name: balance
      type: String
      required: false
      description: 角色余额
    - name: attach
      type: String
      required: false
      description: 业务自定义透传字段
  type_mapping:
    xuteng:
      1: 选服页面
      2: 创建角色
      3: 进入游戏
      4: 等级提升
    quick:
      1: 创建角色
      2: 进入游戏
      3: 角色升级
      4: 角色退出
    mumu:
      1: 创角成功
      2: 登录成功
      3: 角色升级
  code: |
    // ========== 上报到三方渠道的用户信息 ==========
    // 必须在登录成功后调用；不同渠道的 type 定义不同，请按接入渠道选择取值。
    int type = 2;                 // 栩腾：2=创建角色；quick：2=进入游戏
    String roleId = "role_001";   // 必填，角色 ID
    String serverId = "server_001"; // 必填，服务器 ID

    GameInfo gameInfo = new GameInfo(type, roleId, serverId);
    gameInfo.setRoleName("勇者小明");          // 必填，角色名称
    gameInfo.setServerName("一区");            // 必填，服务器名称
    gameInfo.setGameRoleLevel("10");          // 必填，角色等级，默认 "1"

    // 创角事件必须传角色创建时间。注意：只有 type=1 构造时 SDK 会自动填当前时间；
    // 若当前渠道的“创建角色”不是 type=1（如栩腾 type=2），请显式设置。
    gameInfo.setRoleCreateTime(System.currentTimeMillis());

    // 可选字段
    gameInfo.setPartyId("guild_001");
    gameInfo.setPartyName("瑞雪公会");
    gameInfo.setVipLevel(5);
    gameInfo.setGameRolePower(100000);
    gameInfo.setExperience("1000");
    gameInfo.setBalance("100");
    gameInfo.setAttach("{\"scene\":\"create_role\"}");

    // Android 原生通过对象重载分发到当前渠道；Unity 对应 RuiXueSdk.SetThirdGameInfo(gameInfo)
    RXSDK.getInstance().setGameInfo(gameInfo);
    Log.d("RXSDK", "已上报三方渠道用户信息: roleId=" + roleId + ", serverId=" + serverId + ", type=" + type);

# ==================== 创建游戏角色 ====================
createGameCharacter:
  method_name: "RXSDK.getInstance().createGameCharacter"
  description: 创建游戏角色
  parameters:
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: characterName
      type: String
      required: true
      description: 角色名称
    - name: characterLevel
      type: String
      required: true
      description: 角色等级
    - name: cpUserId
      type: String
      required: true
      description: CP 用户 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 创建游戏角色 ==========
    String areaId = "server_001";            // 必填，区服 ID，类型 String
    String characterName = "勇者小明";        // 必填，角色名称，类型 String
    String characterLevel = "1";             // 必填，角色等级，类型 String
    String characterFaction = "联盟";         // 可选，阵营，类型 String
    String characterProfession = "战士";      // 可选，职业，类型 String
    String characterStatus = "normal";       // 可选，状态，类型 String
    String characterType = "main";           // 可选，类型，类型 String
    String characterVipLevel = "0";          // 可选，VIP 等级，类型 String
    String cpUserId = "cp_user_12345";       // 必填，CP 用户 ID，类型 String

    // 扩展字段（可选）
    Map<String, Object> extension = new HashMap<>();
    extension.put("combat_power", 1000);
    extension.put("create_time", System.currentTimeMillis());

    RXSDK.getInstance().createGameCharacter(
            areaId, characterName, characterLevel,
            characterFaction, characterProfession, characterStatus,
            characterType, characterVipLevel, cpUserId, extension,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        JSONObject data = jsonObject.optJSONObject("data");
                        String characterId = data != null ? data.optString("character_id") : "";
                        Log.d("RXSDK", "角色创建成功，ID: " + characterId);
                    } else {
                        Log.e("RXSDK", "角色创建失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 更新游戏角色信息 ====================
updateGameCharacterInfo:
  method_name: "RXSDK.getInstance().updateGameCharacterInfo"
  description: 更新游戏角色信息
  parameters:
    - name: characterId
      type: String
      required: true
      description: 角色 ID
    - name: cpUserId
      type: String
      required: true
      description: CP 用户 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 更新角色信息 ==========
    String characterId = "char_001";   // 必填，角色 ID，类型 String
    String newLevel = "50";            // 新等级，类型 String
    String cpUserId = "cp_user_12345"; // 必填，CP 用户 ID，类型 String

    // 扩展字段
    Map<String, Object> extension = new HashMap<>();
    extension.put("combat_power", 5000);
    extension.put("last_login", System.currentTimeMillis());

    RXSDK.getInstance().updateGameCharacterInfo(
            characterId,
            null,          // areaId（不修改传 null）
            null,          // characterFaction
            newLevel,      // characterLevel
            null,          // characterName
            null,          // characterProfession
            null,          // characterStatus
            null,          // characterType
            null,          // characterVipLevel
            cpUserId,
            extension,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "角色信息更新成功");
                    } else {
                        Log.e("RXSDK", "更新失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 删除游戏角色 ====================
deleteGameCharacter:
  method_name: "RXSDK.getInstance().deleteGameCharacter"
  description: 删除游戏角色
  parameters:
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: characterId
      type: String
      required: true
      description: 角色 ID
    - name: cpUserId
      type: String
      required: true
      description: CP 用户 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 删除角色 ==========
    String areaId = "server_001";       // 必填，区服 ID，类型 String
    String characterId = "char_001";    // 必填，角色 ID，类型 String
    String cpUserId = "cp_user_12345";  // 必填，CP 用户 ID，类型 String

    RXSDK.getInstance().deleteGameCharacter(areaId, characterId, cpUserId,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "角色删除成功");
                    } else {
                        Log.e("RXSDK", "删除失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 查询角色列表 ====================
searchGameCharacterListInfo:
  method_name: "RXSDK.getInstance().searchGameCharacterListInfo"
  description: 查询账号下角色信息列表
  parameters:
    - name: cpUserId
      type: String
      required: true
      description: CP 用户 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 查询角色列表 ==========
    String cpUserId = "cp_user_12345";  // 必填，CP 用户 ID，类型 String

    RXSDK.getInstance().searchGameCharacterListInfo(cpUserId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray list = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "角色列表: " + list);

                if (list != null) {
                    for (int i = 0; i < list.length(); i++) {
                        JSONObject character = list.optJSONObject(i);
                        String charId = character.optString("character_id");
                        String charName = character.optString("character_name");
                        String charLevel = character.optString("character_level");
                        String areaId = character.optString("area_id");
                        Log.d("RXSDK", "角色: " + charName + " Lv." + charLevel + " [" + areaId + "]");
                    }
                }
                // TODO: 更新角色列表 UI
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 查询账号在指定区服下的角色列表 ====================
searchGameCharacterListInArea:
  method_name: "RXSDK.getInstance().searchGameCharacterListInArea"
  description: 查询账号下某个区服中的角色信息列表
  parameters:
    - name: cpUserId
      type: String
      required: true
      description: CP 用户 ID
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 查询指定区服角色列表 ==========
    String cpUserId = "cp_user_12345";  // 必填，CP 用户 ID，类型 String
    String areaId = "server_001";       // 必填，区服 ID，类型 String

    RXSDK.getInstance().searchGameCharacterListInArea(cpUserId, areaId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray list = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "指定区服角色列表: " + list);
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 查询具体角色信息 ====================
searchGameCharacterInfo:
  method_name: "RXSDK.getInstance().searchGameCharacterInfo"
  description: 查询具体角色信息
  parameters:
    - name: cpUserId
      type: String
      required: true
      description: CP 用户 ID
    - name: areaId
      type: String
      required: true
      description: 区服 ID
    - name: characterId
      type: String
      required: true
      description: 角色 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 查询角色详情 ==========
    String cpUserId = "cp_user_12345";   // 必填，CP 用户 ID，类型 String
    String areaId = "server_001";        // 必填，区服 ID，类型 String
    String characterId = "char_001";     // 必填，角色 ID，类型 String

    RXSDK.getInstance().searchGameCharacterInfo(cpUserId, areaId, characterId,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        JSONObject data = jsonObject.optJSONObject("data");
                        if (data != null) {
                            String name = data.optString("character_name");
                            String level = data.optString("character_level");
                            String profession = data.optString("character_profession");
                            String vipLevel = data.optString("character_vip_level");
                            Log.d("RXSDK", "角色: " + name + " Lv." + level
                                    + " 职业: " + profession + " VIP: " + vipLevel);
                        }
                    } else {
                        Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.openapi.GameInfo;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONArray;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 检查指南 (给 AI 的指令)
check_guide:
  - SetGameInfo(roleId, regionTag) 上报到瑞雪；SetThirdGameInfo(GameInfo) 上报到三方渠道，禁止混淆用途
  - Android 原生对象版入口为 RXSDK.getInstance().setGameInfo(GameInfo)，Unity 对外名称为 SetThirdGameInfo
  - 按渠道确认 type 取值；栩腾与 quick 的 type 含义不同
  - 创角事件必须设置 roleCreateTime；若渠道创角 type 不是 1，需要显式调用 setRoleCreateTime
  - 验证必填参数是否正确传递
  - 验证 cpUserId 是否为有效的 CP 用户 ID
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "上报区服角色"
    - "上报角色"
    - "setGameInfo"
    - "setThirdGameInfo"
    - "上报三方渠道用户信息"
    - "创建角色"
    - "更新角色"
    - "删除角色"
    - "角色列表"
    - "游戏角色"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
