# 瑞雪 SDK Android GDT（腾讯广告/广点通）接入规范
# Generated by MCP

overview:
  feature: gdt
  minimum_version: "4.0.16"
  dependency: "com.ruixue:rxsdk_gdt:4.0.16"
  note: |
    MCP preflight 会检查基础初始化、GDT 依赖、自动/手动初始化和目标上报 API。
    同一 Gradle 文件内低于 4.0.16 的 com.ruixue:* 依赖会一并升级，高版本保持不变。

dependency:
  groovy: "implementation 'com.ruixue:rxsdk_gdt:4.0.16'"
  kotlin: "implementation(\"com.ruixue:rxsdk_gdt:4.0.16\")"
  proguard: |
    -dontwarn com.qq.gdt.action.**
    -keep class com.qq.gdt.action.** { *; }
    -keepclassmembers class com.qq.gdt.action.** { *; }
    -keep public class com.tencent.turingfd.sdk.**
    -keepclasseswithmembers class * { native <methods>; }

automatic_mode:
  description: |
    后台 advertise_channel.gdt 下发 tm=1、sid、sk、ch、chid 后，
    GDTSdkWrapper 会随瑞雪 SDK ACTIVATED/REGISTER/LOGIN 生命周期自动初始化并上报。

manual_initialization:
  code_java: |
    import com.ruixue.sdk.gdt.GDTSdkWrapper;

    GDTSdkWrapper gdt = GDTSdkWrapper.getInstance();
    gdt.init(context, "YOUR_ACTION_SET_ID", "YOUR_SECRET_KEY", "tencent", "tencent");

required_events:
  code_java: |
    GDTSdkWrapper gdt = GDTSdkWrapper.getInstance();
    gdt.reportCreateRole("role-id");
    gdt.reportCheckout("item", "礼包", "sku-1", 1, false, "", "CNY", true);
    // value 的金额单位为分；600 表示 6.00 CNY。
    gdt.reportPurchase("item", "礼包", "sku-1", 1, "wechat", "CNY", 600, true);

other_events:
  methods:
    - reportRegister(String, boolean)
    - reportLogin(String, boolean)
    - reportQuestFinish(String, String, String, int, String, boolean)
    - reportShare(String, boolean)
    - reportUpdateLevel(int)
    - reportRateApp(float)
    - reportViewContent(String, String, String)
    - reportAddToCart(String, String, String, int, boolean)

preflight_check:
  required:
    - Gradle 包含 com.ruixue:rxsdk_gdt >= 4.0.16
    - 存在 RXSdkInitConfig / RXSDK.initialize / RuiXueSdk.initialize
    - 存在自动生命周期配置或 GDTSdkWrapper 手动初始化
    - 构建目标包含 GDTSdkWrapper 创角、下单、支付 API
