# 瑞雪 SDK 法务条款功能
# Generated by MCP
# 包含：法务接口、法务条款查询

# ==================== 法务接口（带参数） ====================
legal:
  method_name: "RXSDK.getInstance().legal"
  description: 法务接口
  parameters:
    - name: hashMap
      type: Map<String, Object>
      required: true
      description: 参数
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 法务接口 ==========
    Map<String, Object> params = new HashMap<>();
    params.put("type", "privacy");  // 类型
    params.put("region", "CN");     // 地区

    RXSDK.getInstance().legal(params, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    String content = data.optString("content");
                    String url = data.optString("url");
                    Log.d("RXSDK", "法务内容 URL: " + url);
                    // TODO: 显示法务内容
                }
            } else {
                Log.e("RXSDK", "获取法务信息失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 法务接口（无参数） ====================
legalSimple:
  method_name: "RXSDK.getInstance().legal"
  description: 法务接口（无参数版本）
  parameters:
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 法务接口（简化版） ==========
    RXSDK.getInstance().legal(new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                Log.d("RXSDK", "法务信息: " + data);
            }
        }
    });

# ==================== 法务条款接口 ====================
legalTerms:
  method_name: "RXSDK.getInstance().legalTerms"
  description: 法务条款接口
  parameters:
    - name: keys
      type: String
      required: true
      description: 条款 key，多个用逗号分隔
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 法务条款 ==========
    // 常用 key: user_agreement(用户协议), privacy_policy(隐私政策), third_party_sdk(第三方SDK信息)
    String keys = "user_agreement,privacy_policy";  // 必填，条款 key，类型 String

    RXSDK.getInstance().legalTerms(keys, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    // 用户协议
                    JSONObject userAgreement = data.optJSONObject("user_agreement");
                    if (userAgreement != null) {
                        String title = userAgreement.optString("title");
                        String url = userAgreement.optString("url");
                        Log.d("RXSDK", "用户协议: " + title + " - " + url);
                    }

                    // 隐私政策
                    JSONObject privacyPolicy = data.optJSONObject("privacy_policy");
                    if (privacyPolicy != null) {
                        String title = privacyPolicy.optString("title");
                        String url = privacyPolicy.optString("url");
                        Log.d("RXSDK", "隐私政策: " + title + " - " + url);
                    }
                }
                // TODO: 用 WebView 显示法务条款
            } else {
                Log.e("RXSDK", "获取法务条款失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 常用法务条款 key
legal_term_keys:
  - name: user_agreement
    description: 用户协议
  - name: privacy_policy
    description: 隐私政策
  - name: children_privacy
    description: 儿童隐私政策
  - name: third_party_sdk
    description: 第三方 SDK 信息共享清单
  - name: personal_info
    description: 个人信息收集清单

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 验证条款 key 是否正确
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "法务条款"
    - "用户协议"
    - "隐私政策"
    - "隐私协议"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
