# 瑞雪 SDK 法务 UI 功能
# Generated by MCP
# 包含：协议声明、隐私政策弹窗

# ==================== 协议声明弹窗 ====================
statementUI:
  method_name: "RXSdkUI.getInstance().statementUI"
  description: 打开协议声明界面（全屏 H5 样式）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: legalData
      type: LegalData
      required: true
      description: 法务数据（从 legal() 接口获取）
    - name: key
      type: String
      required: true
      description: 条款 key
  code: |
    // ========== 瑞雪 SDK 协议声明弹窗 ==========
    // 注意：需要先调用 legal() 接口获取 LegalData
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.legal.LegalData;
    
    // 常用 key 值:
    // "00001" - 服务协议
    // "00002" - 隐私政策
    String key = "00001";  // 服务协议
    
    // 需要先获取法务数据
    RXSDK.getInstance().legal(new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject response) {
            int code = response.optInt("code", -1);
            if (code == 0) {
                // 解析 LegalData（实际项目中需要正确解析）
                // LegalData legalData = parseLegalData(response);
                // RXSdkUI.getInstance().statementUI(activity, legalData, key).show();
            }
        }
    });

# ==================== 隐私政策弹窗 ====================
userPrivacyPolicy:
  method_name: "RXSdkUI.getInstance().userPrivacyPolicy"
  description: 用户协议和隐私政策弹窗
  parameters:
    - name: activity
      type: Context
      required: true
      description: 当前 Context
    - name: title
      type: String
      required: true
      description: 弹窗标题
    - name: content
      type: String
      required: true
      description: 协议内容（HTML 格式）
    - name: callback
      type: RXJSONCallback
      required: true
      description: 点击回调
  code: |
    // ========== 瑞雪 SDK 隐私政策弹窗 ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.RXJSONCallback;
    
    String title = "用户协议和隐私政策";
    String content = "<p>请仔细阅读以下协议...</p>";  // HTML 格式内容
    
    RXSdkUI.getInstance().userPrivacyPolicy(activity, title, content, new RXJSONCallback() {
        @Override
        public void onSuccess(JSONObject data) {
            // 用户点击同意
            Log.d("RXSDK", "用户同意协议");
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            // 用户点击拒绝
            Log.d("RXSDK", "用户拒绝协议");
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "协议弹窗错误: " + e.getMessage());
        }
    }).show();

# ==================== 隐私政策弹窗（使用 LegalData） ====================
userPrivacyPolicyWithLegalData:
  method_name: "RXSdkUI.getInstance().userPrivacyPolicy"
  description: 使用 LegalData 显示隐私政策弹窗
  parameters:
    - name: activity
      type: Context
      required: true
      description: 当前 Context
    - name: legalData
      type: LegalData
      required: true
      description: 法务数据
    - name: key
      type: String
      required: true
      description: 条款 key
    - name: callback
      type: RXJSONCallback
      required: true
      description: 点击回调
  code: |
    // ========== 瑞雪 SDK 隐私政策弹窗（使用 LegalData） ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.legal.LegalData;
    
    // key 值: "00001" - 服务协议, "00002" - 隐私政策
    RXSdkUI.getInstance().userPrivacyPolicy(activity, legalData, "00001", new RXJSONCallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "用户同意协议");
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.d("RXSDK", "用户拒绝协议");
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "错误: " + e.getMessage());
        }
    }).show();

# ==================== 协议视图 ====================
protocolView:
  method_name: "RXSdkUI.getInstance().protocolView"
  description: 协议视图（全屏展示）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: key
      type: String
      required: true
      description: 默认展示的条款 key
    - name: keyList
      type: List<String>
      required: true
      description: 要展示的协议列表
  code: |
    // ========== 瑞雪 SDK 协议视图 ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import java.util.Arrays;
    import java.util.List;
    
    // 要展示的协议 key 列表
    List<String> keyList = Arrays.asList("00001", "00002");  // 服务协议、隐私政策
    String defaultKey = "00001";  // 默认展示服务协议
    
    RXSdkUI.getInstance().protocolView(activity, defaultKey, keyList).show();

# 常用协议 key
legal_keys:
  - name: "00001"
    description: 服务协议
  - name: "00002"
    description: 隐私政策
  - name: "00003"
    description: 儿童隐私政策
  - name: "00004"
    description: 第三方SDK信息共享清单

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.content.Context;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSdkUI;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.legal.LegalData;"
  - "import com.ruixue.RXJSONCallback;"
  - "import com.ruixue.RXRequestCallback;"
  - "import com.ruixue.error.RXException;"
  - "import org.json.JSONObject;"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    artifact: "com.ruixue:rxsdk_base_ui"
    description: 法务 UI 需要添加此依赖

# AI 行为指南
check_guide: |
  插入法务 UI 代码前必须执行以下检查:
  1. 读取项目的 app/build.gradle 文件
  2. 搜索是否存在 'com.ruixue:rxsdk_base_ui' 依赖
  3. 如果不存在该依赖:
     - 【必须】自动添加依赖到 app/build.gradle，无需询问用户
  4. 添加完依赖后，继续插入法务 UI 代码

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "协议声明"
    - "隐私政策弹窗"
    - "法务弹窗"
    - "用户协议弹窗"
  actions:
    - 检查是否有 rxsdk_base_ui 依赖
    - 如果没有，自动添加依赖
    - 插入对应的法务 UI 代码
