# 瑞雪 SDK API 登录功能 (非 UI 方式)
# Generated by MCP

# 方法签名规范 (用于代码检查)
signature:
  method_name: "RXSDK.getInstance().login"
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: loginType
      type: String
      required: true
      description: 登录类型 (LoginType.USERNAME/CAPTCHACODE/GUEST/GOOGLE 等)
    - name: username
      type: String
      required: false
      description: 用户名/手机号，账号密码登录和验证码登录时必填
    - name: password
      type: String
      required: false
      description: 密码，仅账号密码登录时必填
    - name: captchaCode
      type: String
      required: false
      description: 验证码，仅验证码登录时必填
    - name: loginOpenId
      type: String
      required: false
      description: 上次登录返回的 login_openid，用于二次登录
    - name: ext
      type: Map<String, Object>
      required: false
      description: 扩展参数，可包含 custom_ext、bigdata_ext 等透传参数
    - name: signFields
      type: String[]
      required: false
      description: 需要签名的字段
    - name: migrateArgs
      type: Object
      required: false
      description: 迁移参数
    - name: callback
      type: RXRequestCallback
      required: true
      description: 登录回调

# 登录类型常量
login_types:
  - name: USERNAME
    value: LoginType.USERNAME
    description: 账号密码登录
  - name: CAPTCHACODE
    value: LoginType.CAPTCHACODE
    description: 验证码登录
  - name: GUEST
    value: LoginType.GUEST
    description: 游客登录
  - name: GOOGLE
    value: LoginType.GOOGLE
    description: Google 登录
  - name: WECHAT
    value: LoginType.WECHAT
    description: 微信登录
  - name: YSDK
    value: LoginMethod.YSDK
    description: 应用宝 YSDK 登录（须配合 ext 传 platform_type 或 ysdk_login_type）

# 样板代码 - 应用宝 YSDK（指定 QQ 平台）
code_ysdk: |
  // ========== 瑞雪 SDK API 登录 - 应用宝 YSDK ==========
  /**
   * 应用宝 YSDK 登录（指定平台）
   * @param activity 当前 Activity
   * @param platformType YSDK ePlatform 整型，如 PLATFORM_ID_QQ / PLATFORM_ID_WX / PLATFORM_ID_GUEST
   */
  private void loginByYsdk(Activity activity, int platformType) {
      Map<String, Object> ext = new HashMap<>();
      ext.put("platform_type", platformType);

      LoginParams params = new LoginParams.Builder()
              .setLoginType(LoginMethod.YSDK)
              .setExt(ext)
              .build();

      RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
          @Override
          public void onResponse(JSONObject jsonObject) {
              handleLoginResponse(jsonObject);
          }
      });
  }

# 样板代码 - 应用宝 YSDK（内置登录 UI）
code_ysdk_ui: |
  // ========== 瑞雪 SDK API 登录 - 应用宝 YSDK UI ==========
  private void loginByYsdkUi(Activity activity) {
      Map<String, Object> ext = new HashMap<>();
      ext.put("ysdk_login_type", "ysdk_login_ui");
      // 可选：ext.put("ysdk_login_ui_config", config.toMap());

      LoginParams params = new LoginParams.Builder()
              .setLoginType(LoginMethod.YSDK)
              .setExt(ext)
              .build();

      RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
          @Override
          public void onResponse(JSONObject jsonObject) {
              handleLoginResponse(jsonObject);
          }
      });
  }

  ysdk_notes:
    - "未传 platform_type 且未传 ysdk_login_type=ysdk_login_ui 时，日志会出现 required for platform_type params，并回调 code=3000"
    - "依赖 implementation 'com.ruixue:rxsdk_ysdk:${version}'；Manifest 配置 YSDK_KEY、QQ_APP_ID、WX_APP_ID、OFFER_ID"
    - "使用 RXSdkUI 海外/国内登录页时需额外引入 rxsdk_base_ui，与 YSDK API 登录无关"

# 样板代码 - 账号密码登录
code_username: |
  // ========== 瑞雪 SDK API 登录 - 账号密码 ==========
  /**
   * 账号密码登录
   * @param activity 当前 Activity
   * @param username 用户名
   * @param password 密码
   */
  private void loginByUsername(Activity activity, String username, String password) {
      String loginType = LoginType.USERNAME;
      String captchaCode = null;
      String loginOpenId = null;
      Map<String, Object> ext = null;
      String[] signFields = new String[]{"openid"};
      Object migrateArgs = null;

      // 【可选】构造透传参数
      // Map<String, Object> bigdataExt = new HashMap<>();
      // bigdataExt.put("event_name", "user_login");
      // bigdataExt.put("event_value", "success");
      // Map<String, Object> customExt = new HashMap<>();
      // customExt.put("bigdata_ext", bigdataExt);
      // ext = new HashMap<>();
      // ext.put("custom_ext", customExt);

      RXSDK.getInstance().login(activity, loginParams, new RXRequestCallback() {
          // 注意：使用 LoginParams.Builder 构造登录参数
          @Override
          public void onResponse(JSONObject jsonObject) {
              handleLoginResponse(jsonObject);
          }
      });
  }

# 样板代码 - 验证码登录
code_captcha: |
  // ========== 瑞雪 SDK API 登录 - 验证码 ==========
  /**
   * 验证码登录
   * @param activity 当前 Activity
   * @param phoneNumber 手机号
   * @param captchaCode 验证码
   */
  private void loginByCaptcha(Activity activity, String phoneNumber, String captchaCode) {
      LoginParams params = new LoginParams.Builder()
              .setLoginType(LoginType.CAPTCHACODE)
              .setUsername(phoneNumber)
              .setCaptchaCode(captchaCode)
              .build();

      RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
          @Override
          public void onResponse(JSONObject jsonObject) {
              handleLoginResponse(jsonObject);
          }
      });
  }

# 样板代码 - 游客登录
code_guest: |
  // ========== 瑞雪 SDK API 登录 - 游客 ==========
  /**
   * 游客登录
   * @param activity 当前 Activity
   */
  private void loginAsGuest(Activity activity) {
      String loginType = LoginType.GUEST;
      String username = null;
      String password = null;
      String captchaCode = null;
      String loginOpenId = null;
      Map<String, Object> ext = null;
      String[] signFields = new String[]{"openid"};
      Object migrateArgs = null;

      RXSDK.getInstance().login(activity, loginParams, new RXRequestCallback() {
          // 注意：使用 LoginParams.Builder 构造登录参数
          @Override
          public void onResponse(JSONObject jsonObject) {
              handleLoginResponse(jsonObject);
          }
      });
  }

# 样板代码 - Google 登录
code_google: |
  // ========== 瑞雪 SDK API 登录 - Google ==========
  /**
   * Google 登录
   * @param activity 当前 Activity
   * @param googleClientId Google Web Client ID
   */
  private void loginByGoogle(Activity activity, String googleClientId) {
      String loginType = LoginType.GOOGLE;
      String username = null;
      String password = null;
      String captchaCode = null;
      String loginOpenId = null;
      String[] signFields = new String[]{"openid"};
      Object migrateArgs = null;

      Map<String, Object> ext = new HashMap<>();
      ext.put("clientId", googleClientId);

      RXSDK.getInstance().login(activity, loginParams, new RXRequestCallback() {
          // 注意：使用 LoginParams.Builder 构造登录参数
          @Override
          public void onResponse(JSONObject jsonObject) {
              handleLoginResponse(jsonObject);
          }
      });
  }

# 通用回调处理代码
code_callback: |
  // ========== 登录回调处理 ==========
  /**
   * 处理登录响应
   * @param jsonObject 响应数据
   */
  private void handleLoginResponse(JSONObject jsonObject) {
      int code = jsonObject.optInt("code", -1);
      if (code == 0) {
          JSONObject data = jsonObject.optJSONObject("data");
          if (data != null) {
              // 登录成功
              String openid = data.optString("openid");
              String token = data.optString("token");
              Log.d("RXSDK", "登录成功: openid=" + openid);
              
              // TODO: 处理登录成功逻辑
          }
      } else {
          // 登录失败
          String msg = jsonObject.optString("msg");
          String thirdcode = String.valueOf(jsonObject.opt("thirdcode"));
          String thirdmsg = String.valueOf(jsonObject.opt("thirdmsg"));
          Log.e("RXSDK", "登录失败: code=" + code + ", msg=" + msg 
                  + ", thirdcode=" + thirdcode + ", thirdmsg=" + thirdmsg);
          
          // TODO: 根据错误码处理失败逻辑
      }
  }

# 完整示例代码 (包含所有登录方式)
code_full: |
  // ========== 瑞雪 SDK API 登录 ==========
  import android.app.Activity;
  import android.util.Log;
  import com.ruixue.openapi.RXSDK;
  import com.ruixue.RXRequestCallback;
  import com.ruixue.passport.LoginType;
  import org.json.JSONObject;
  import java.util.HashMap;
  import java.util.Map;

  public class LoginApiManager {

      /**
       * 账号密码登录
       */
      public static void loginByUsername(Activity activity, String username, String password) {
          Map<String, Object> ext = buildExtParams();
          String[] signFields = new String[]{"openid"};
          
          LoginParams params = new LoginParams.Builder()
                  .setLoginType(LoginType.USERNAME)
                  .setUsername(username)
                  .setPassword(password)
                  .build();
          RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
              @Override
              public void onResponse(JSONObject jsonObject) {
                  handleLoginResponse(jsonObject);
              }
          });
      }

      /**
       * 验证码登录
       */
      public static void loginByCaptcha(Activity activity, String phoneNumber, String captchaCode) {
          String[] signFields = new String[]{"openid"};
          
          LoginParams params = new LoginParams.Builder()
                  .setLoginType(LoginType.CAPTCHACODE)
                  .setUsername(phoneNumber)
                  .setCaptchaCode(captchaCode)
                  .build();
          RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
              @Override
              public void onResponse(JSONObject jsonObject) {
                  handleLoginResponse(jsonObject);
              }
          });
      }

      /**
       * 游客登录
       */
      public static void loginAsGuest(Activity activity) {
          String[] signFields = new String[]{"openid"};
          
          LoginParams params = new LoginParams.Builder()
                  .setLoginType(LoginType.GUEST)
                  .build();
          RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
              @Override
              public void onResponse(JSONObject jsonObject) {
                  handleLoginResponse(jsonObject);
              }
          });
      }

      /**
       * Google 登录
       */
      public static void loginByGoogle(Activity activity, String googleClientId) {
          Map<String, Object> ext = new HashMap<>();
          ext.put("clientId", googleClientId);
          String[] signFields = new String[]{"openid"};
          
          LoginParams params = new LoginParams.Builder()
                  .setLoginType(LoginType.GOOGLE)
                  .setExt(ext)
                  .build();
          RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
              @Override
              public void onResponse(JSONObject jsonObject) {
                  handleLoginResponse(jsonObject);
              }
          });
      }

      /**
       * 二次无感登录 (使用上次登录的 loginOpenId)
       */
      public static void loginByOpenId(Activity activity, String loginType, String loginOpenId) {
          String[] signFields = new String[]{"openid"};
          
          LoginParams params = new LoginParams.Builder()
                  .setLoginType(loginType)
                  .setLoginOpenid(loginOpenId)
                  .build();
          RXSDK.getInstance().login(activity, params, new RXRequestCallback() {
              @Override
              public void onResponse(JSONObject jsonObject) {
                  handleLoginResponse(jsonObject);
              }
          });
      }

      /**
       * 构造扩展参数 (可选)
       */
      private static Map<String, Object> buildExtParams() {
          // 构造大数据透传参数
          Map<String, Object> bigdataExt = new HashMap<>();
          bigdataExt.put("event_name", "user_login");
          bigdataExt.put("event_value", "success");

          // 构造自定义透传参数
          Map<String, Object> customExt = new HashMap<>();
          customExt.put("bigdata_ext", bigdataExt);
          customExt.put("user_agent", "Android");

          // 构造 ext 参数
          Map<String, Object> ext = new HashMap<>();
          ext.put("custom_ext", customExt);
          return ext;
      }

      /**
       * 处理登录响应
       */
      private static void handleLoginResponse(JSONObject jsonObject) {
          int code = jsonObject.optInt("code", -1);
          if (code == 0) {
              JSONObject data = jsonObject.optJSONObject("data");
              if (data != null) {
                  String openid = data.optString("openid");
                  String token = data.optString("token");
                  Log.d("RXSDK", "登录成功: openid=" + openid);
                  // TODO: 处理登录成功逻辑
              }
          } else {
              String msg = jsonObject.optString("msg");
              String thirdcode = String.valueOf(jsonObject.opt("thirdcode"));
              String thirdmsg = String.valueOf(jsonObject.opt("thirdmsg"));
              Log.e("RXSDK", "登录失败: code=" + code + ", msg=" + msg);
              // TODO: 根据错误码处理失败逻辑
          }
      }
  }

# 检查指南 (给 AI 的指令)
check_guide:
  - 检查是否存在 RXSDK.getInstance().login 方法调用
  - 验证参数数量是否为 10 个
  - 验证 loginType 是否为有效的 LoginType 常量
  - 验证回调是否实现了 onResponse(JSONObject) 方法
  - 如果参数类型不匹配，提示修复建议

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.passport.LoginParams;"
  - "import com.ruixue.RXRequestCallback;"
  - "import com.ruixue.passport.LoginType;"
  - "import com.ruixue.passport.LoginMethod;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "添加 API 登录代码"
    - "插入 API 登录"
    - "添加账号密码登录"
    - "添加验证码登录"
    - "添加游客登录"
    - "添加 Google 登录"
    - "添加应用宝 YSDK 登录"
  actions:
    - 根据用户指定的登录类型选择对应的代码片段
    - 检查当前文件是否已存在 RXSDK.getInstance().login 调用
    - 如果不存在，在光标位置插入样板代码
    - 如果存在，校验参数是否正确
    - 确保必要的 import 语句已添加

# 与 UI 登录的区别
difference_from_ui_login:
  ui_login:
    method: "RXSdkUI.getInstance().showLoginUI"
    description: 使用 SDK 内置登录界面，用户交互友好
    use_case: 推荐用于大多数场景
  api_login:
    method: "RXSDK.getInstance().login"
    description: 直接 API 调用，无 UI 界面，适合自定义登录界面
    use_case: 适合需要自定义登录 UI 的场景
