# 瑞雪 SDK Android MuMu/Yofun 渠道
# Generated by MCP
# 最低版本：Android SDK 4.0.19

preflight_check:
  min_version:
    android: "4.0.19"
  requirements:
    - "Gradle 已接入 com.ruixue:rxsdk_yofun:4.0.19 或更高固定版本"
    - "包名以 .yofun.mumu 结尾"
    - "Manifest application 节点已配置 YOFUN_APP_ID"
    - "已启用 MultiDex"
    - "已完成 RXSDK.initialize、带 debugMode 的 initThirdSdk 与 invokeChannelAction"

dependency:
  repository: 'maven { url "https://maven-release.webapp.163.com/repository/maven-releases/" }'
  gradle: "implementation 'com.ruixue:rxsdk_yofun:4.0.19'"
  default_config: "multiDexEnabled true"

manifest:
  placeholder: |
    manifestPlaceholders = [
        app_id: "从网易 Yofun 后台获取的 APP_ID"
    ]
  meta_data: |
    <meta-data
        android:name="YOFUN_APP_ID"
        android:value="${app_id}" />

application_lifecycle:
  note: "使用标准 com.ruixue.openapi.RXApplication；其已自动处理 applicationAttach/applicationCreate，宿主不要重复转发"

initialization_and_splash:
  code_java: |
    Map<String, Object> initParams = new HashMap<>();
    initParams.put("debugMode", BuildConfig.DEBUG);
    RuiXueSdk.getApi().initThirdSdk(activity, initParams, new RXJSONCallback() {
        @Override
        public void onSuccess(JSONObject result) {
            Map<String, Object> splashParams = new HashMap<>();
            splashParams.put("splashType", 0); // 0/1/2
            RuiXueSdk.invokeChannelAction(
                activity, RuiXueSdk.CHANNEL_ACTION_SHOW_SPLASH,
                splashParams, splashCallback);
        }

        @Override
        public void onFailed(JSONObject error) {
            // 处理初始化失败
        }
    });

login:
  method: "LoginMethod.MUMU"
  description: MuMu 登录必须使用 mumu 登录类型

game_events:
  method: "RXSDK.getInstance().setGameInfo(GameInfo gameInfo)"
  description: 上报三方渠道用户信息；Unity 对应 RuiXueSdk.SetThirdGameInfo
  type_mapping:
    1: 创角成功
    2: 登录成功
    3: 角色升级

notes:
  - "正式发版必须将 InitThirdSdk 参数 debugMode 设为 false"
  - "渠道 UI 展示回调 type=1 时需确保游戏继续运行；type=2 表示渠道 UI 隐藏"
  - "支付、登录、闪屏和角色事件必须使用真实 APP_ID、包名及签名在 MuMu 环境验收"
