# 瑞雪 SDK 其他 UI 功能
# Generated by MCP
# 包含：邮件中心、绑定手机/邮箱 UI、公告 UI

# ==================== 邮件中心 ====================
showMailCenter:
  method_name: "RXSdkUI.getInstance().showMailCenter"
  description: 展示邮件中心
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: userId
      type: String
      required: true
      description: 游戏用户 ID
  code: |
    // ========== 瑞雪 SDK 展示邮件中心 ==========
    
    import com.ruixue.openapi.RXSdkUI;
    
    String userId = "demo_user_001";  // 游戏用户 ID
    
    RXSdkUI.getInstance().showMailCenter(activity, userId).show();

# ==================== 绑定手机 UI ====================
bindPhoneUI:
  method_name: "RXSdkUI.getInstance().bindPhoneUI"
  description: 绑定手机 UI（H5 页面）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: callback
      type: RXUICallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 绑定手机 UI ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.callback.RXUICallback;
    
    RXSdkUI.getInstance().bindPhoneUI(activity, new RXUICallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "绑定手机成功: " + data);
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "绑定手机失败或取消");
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "绑定手机错误: " + e.getMessage());
        }
    }).show();

# ==================== 绑定邮箱 UI ====================
bindEmailUI:
  method_name: "RXSdkUI.getInstance().bindEmailUI"
  description: 绑定邮箱 UI（H5 页面）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: callback
      type: RXUICallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 绑定邮箱 UI ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.callback.RXUICallback;
    
    RXSdkUI.getInstance().bindEmailUI(activity, new RXUICallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "绑定邮箱成功: " + data);
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "绑定邮箱失败或取消");
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "绑定邮箱错误: " + e.getMessage());
        }
    }).show();

# ==================== 展示公告 UI ====================
showAnnounceView:
  method_name: "RXSdkUI.getInstance().showAnnounceView"
  description: 展示公告 UI
  parameters:
    - name: context
      type: Context
      required: true
      description: Context
    - name: limit
      type: int
      required: true
      description: 读取条数（limit > 0）
    - name: linkCallback
      type: NoticeCallback
      required: true
      description: 回调
  code: |
    // ========== 瑞雪 SDK 展示公告 UI ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.view.notice.NoticeCallback;
    
    int limit = 10;  // 读取公告条数
    
    RXSdkUI.getInstance().showAnnounceView(context, limit, new NoticeCallback() {
        @Override
        public void onLink(String link) {
            Log.d("RXSDK", "用户点击链接: " + link);
            // TODO: 处理链接跳转
        }
        
        @Override
        public void hasAnnounceUI(boolean isHas) {
            if (isHas) {
                Log.d("RXSDK", "有公告展示");
            } else {
                Log.d("RXSDK", "没有公告");
            }
        }
    });

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.content.Context;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSdkUI;"
  - "import com.ruixue.callback.RXUICallback;"
  - "import com.ruixue.error.RXException;"
  - "import com.ruixue.view.notice.NoticeCallback;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    artifact: "com.ruixue:rxsdk_base_ui"
    description: 其他 UI 功能需要添加此依赖
