# 瑞雪 SDK 排行榜功能
# Generated by MCP
# 包含：增加分数、设置分数、查询排名、获取排行榜、好友排行榜

# ==================== 增加用户分数 ====================
addScore:
  method_name: "RXSDK.getInstance().addScore"
  description: 增加用户分数（累加）
  parameters:
    - name: rankId
      type: String
      required: true
      description: 榜单 ID
    - name: score
      type: int
      required: true
      description: 增加的分数值
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 增加分数 ==========
    String rankId = "daily_rank";  // 必填，榜单 ID，类型 String
    int score = 100;               // 必填，增加的分数，类型 int

    RXSDK.getInstance().addScore(rankId, score, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                int newScore = data != null ? data.optInt("score") : 0;
                Log.d("RXSDK", "分数增加成功，当前分数: " + newScore);
            } else {
                Log.e("RXSDK", "分数增加失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 设置用户分数 ====================
setScore:
  method_name: "RXSDK.getInstance().setScore"
  description: 设置用户分数（覆盖原有分数）
  parameters:
    - name: rankId
      type: String
      required: true
      description: 榜单 ID
    - name: score
      type: int
      required: true
      description: 分数值
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 设置分数 ==========
    String rankId = "high_score";  // 必填，榜单 ID，类型 String
    int score = 9999;              // 必填，分数，类型 int

    RXSDK.getInstance().setScore(rankId, score, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "分数设置成功");
            } else {
                Log.e("RXSDK", "分数设置失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 查询用户排名 ====================
queryUserRank:
  method_name: "RXSDK.getInstance().queryUserRank"
  description: 查询用户排名
  parameters:
    - name: rankId
      type: String
      required: true
      description: 榜单 ID
    - name: openId
      type: String
      required: true
      description: 目标用户 OpenID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 查询用户排名 ==========
    String rankId = "daily_rank";       // 必填，榜单 ID，类型 String
    String openId = "user_openid";      // 必填，用户 OpenID（查自己可用当前用户 OpenID），类型 String

    RXSDK.getInstance().queryUserRank(rankId, openId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    int rank = data.optInt("rank", -1);
                    int score = data.optInt("score", 0);

                    if (rank > 0) {
                        Log.d("RXSDK", "排名: 第" + rank + "名, 分数: " + score);
                    } else {
                        Log.d("RXSDK", "暂无排名，分数: " + score);
                    }
                }
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取排行榜列表 ====================
getRankList:
  method_name: "RXSDK.getInstance().getRankList"
  description: 获取排行榜列表
  parameters:
    - name: rankId
      type: String
      required: true
      description: 榜单 ID
    - name: startRank
      type: int
      required: true
      description: 开始排名（从 1 开始）
    - name: endRank
      type: int
      required: true
      description: 结束排名
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取排行榜 ==========
    String rankId = "daily_rank";  // 必填，榜单 ID，类型 String
    int startRank = 1;             // 必填，开始排名，类型 int
    int endRank = 100;             // 必填，结束排名，类型 int

    RXSDK.getInstance().getRankList(rankId, startRank, endRank, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray list = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "排行榜数据: " + list);

                // 解析排行榜
                if (list != null) {
                    for (int i = 0; i < list.length(); i++) {
                        JSONObject item = list.optJSONObject(i);
                        int rank = item.optInt("rank");
                        String nickname = item.optString("nickname");
                        String avatar = item.optString("avatar");
                        int score = item.optInt("score");

                        Log.d("RXSDK", "第" + rank + "名: " + nickname + " - " + score + "分");
                    }
                }
                // TODO: 更新排行榜 UI
            } else {
                Log.e("RXSDK", "获取排行榜失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取好友排行榜 ====================
friendsRank:
  method_name: "RXSDK.getInstance().friendsRank"
  description: 获取好友排行榜列表
  parameters:
    - name: rankId
      type: String
      required: true
      description: 榜单 ID
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 好友排行榜 ==========
    String rankId = "daily_rank";  // 必填，榜单 ID，类型 String

    RXSDK.getInstance().friendsRank(rankId, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray list = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "好友排行榜: " + list);

                // 解析好友排行榜
                if (list != null) {
                    for (int i = 0; i < list.length(); i++) {
                        JSONObject item = list.optJSONObject(i);
                        int rank = item.optInt("rank");
                        String nickname = item.optString("nickname");
                        int score = item.optInt("score");

                        Log.d("RXSDK", "好友第" + rank + "名: " + nickname + " - " + score + "分");
                    }
                }
                // TODO: 更新好友排行榜 UI
            } else {
                Log.e("RXSDK", "获取好友排行榜失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 榜单类型说明
rank_types:
  - 日榜: 每日 0 点重置
  - 周榜: 每周一 0 点重置
  - 总榜: 不重置，累计分数

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONArray;"
  - "import org.json.JSONObject;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 验证 rankId 参数是否为有效的榜单 ID
  - 验证 startRank 和 endRank 参数的范围
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "排行榜"
    - "增加分数"
    - "设置分数"
    - "查询排名"
    - "好友排行榜"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
