# 瑞雪 SDK 实名认证功能
# Generated by MCP
# 包含：实名认证、快速实名认证、支付宝 IIFAA 实名认证
#
# 接入前必须先询问用户:
# - 是否使用瑞雪实名认证 UI？
# - 使用：调用 android feature=real_auth_ui 接入 RXSdkUI.getInstance().realAuthUI
# - 不使用：接入获取 IIFAA 支付宝授权跳转地址和查询 IIFAA 认证结果
#
# 版本要求:
# - IIFAA 支付宝实名认证需要 Android SDK 4.0.14 及以上
# - 如果当前 SDK 版本过低，MCP/Agent 应自动修改 Gradle 中 com.ruixue:* 依赖版本到 4.0.14 或更高

decision_prompt:
  question: "是否使用瑞雪实名认证 UI？"
  use_ruixue_ui: "使用瑞雪实名认证 UI 时，请调用 android feature=real_auth_ui 接入 realAuthUI。"
  custom_ui: "不使用瑞雪实名认证 UI 时，请使用 iifaa_alipay_real_auth 示例。"

iifaa_config_notice:
  message: "请按照文档确认配置"
  document_url: "https://doc.ruixueyun.com/main/#/view?path=ba910252-aff4-440d-8f78-31f25d19c271"
  response_rule: "用户询问 IIFAA 配置文档时，只返回 document_url，不解析文档内容。"

# ==================== 实名认证 ====================
realAuth:
  method_name: "RXSDK.getInstance().realAuth"
  description: 实名认证
  parameters:
    - name: realname
      type: String
      required: true
      description: 真实姓名
    - name: idcard
      type: String
      required: true
      description: 身份证号码
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 实名认证 ==========
    String realname = "xxxxxx";               // 必填，真实姓名，类型 String
    String idcard = "xxxxxx";                 // 必填，身份证号码，类型 String

    RXSDK.getInstance().realAuth(realname, idcard, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "实名认证成功");
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    int age = data.optInt("age", 0);
                    boolean isAdult = age >= 18;
                    Log.d("RXSDK", "用户年龄: " + age + ", 是否成年: " + isAdult);
                    // TODO: 如果是未成年人，需要进入防沉迷流程
                }
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "实名认证失败: " + msg);
            }
        }
    });

# ==================== 快速实名认证 ====================
realAuthFast:
  method_name: "RXSDK.getInstance().realAuth"
  description: 快速实名认证（带 isFastRealAuth 参数）
  parameters:
    - name: realname
      type: String
      required: true
      description: 真实姓名
    - name: idcard
      type: String
      required: true
      description: 身份证号码
    - name: isFastRealAuth
      type: boolean
      required: true
      description: 是否使用快速认证
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 快速实名认证 ==========
    String realname = "xxxxxx";               // 必填，真实姓名，类型 String
    String idcard = "xxxxxx";                 // 必填，身份证号码，类型 String
    boolean isFastRealAuth = true;            // 是否使用快速认证，类型 boolean

    RXSDK.getInstance().realAuth(realname, idcard, isFastRealAuth, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "快速实名认证成功");
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    int age = data.optInt("age", 0);
                    String pi = data.optString("pi");  // 防沉迷编码
                    Log.d("RXSDK", "用户年龄: " + age + ", PI: " + pi);
                }
            } else {
                Log.e("RXSDK", "快速实名认证失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== IIFAA 支付宝实名认证（自定义 UI） ====================
iifaa_alipay_real_auth:
  method_name: "RXSdkApi.getInstance().getIIFAARedirectURL / getIIFAAResultWithSource"
  description: 获取 IIFAA 支付宝授权跳转地址并查询认证结果
  min_android_sdk: "4.0.14"
  code: |
    // ========== 瑞雪 SDK IIFAA 支付宝实名认证 ==========
    // 版本要求：Android SDK >= 4.0.14；低版本请先自动升级 Gradle 中 com.ruixue:* 依赖版本
    //
    // 关键要求：
    // 1. 获取授权地址后读取 data["url"] 并通过 scheme 跳转
    // 2. retryCount 固定传 3
    // 3. 监听 App 进入前台时查询认证结果
    // 4. 必须用 isIifaaRealAuthInProgress 标记，只在实名流程中回到前台才查询
    private boolean isIifaaRealAuthInProgress = false;

    private void startIifaaRealAuth(Activity activity) {
        String appName = "游戏名称";
        String thirdPartSchema = "yourapp://iifaa"; // 与 AndroidManifest / 渠道配置中的 scheme 保持一致

        RXSdkApi.getInstance().getIIFAARedirectURL(appName, thirdPartSchema, new RXRequestCallback() {
            @Override
            public void onResponse(JSONObject jsonObject) {
                int code = jsonObject.optInt("code", -1);
                if (code != 0) {
                    Log.e("RXSDK", "获取 IIFAA 授权地址失败: " + jsonObject.optString("msg"));
                    return;
                }

                JSONObject data = jsonObject.optJSONObject("data");
                String url = data == null ? "" : data.optString("url");
                if (TextUtils.isEmpty(url)) {
                    Log.e("RXSDK", "IIFAA 授权地址为空: " + jsonObject);
                    return;
                }

                isIifaaRealAuthInProgress = true;
                activity.startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url)));
            }
        });
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (!isIifaaRealAuthInProgress) {
            return;
        }

        queryIifaaResult();
    }

    private void queryIifaaResult() {
        // source 传 deregister 表示注销场景，传空表示正常认证逻辑
        RXSdkApi.getInstance().getIIFAAResultWithSource("", 3, new RXRequestCallback() {
            @Override
            public void onResponse(JSONObject jsonObject) {
                int code = jsonObject.optInt("code", -1);
                if (code == 0) {
                    isIifaaRealAuthInProgress = false;
                    Log.d("RXSDK", "IIFAA 认证成功: " + jsonObject);
                } else {
                    Log.e("RXSDK", "IIFAA 认证结果查询失败: " + jsonObject.optString("msg"));
                }
            }
        });
    }

# 身份证号校验规则
idcard_validation:
  description: 身份证号码校验规则
  rules:
    - 非空即可

# 响应数据说明
response_data:
  fields:
    - name: age
      type: int
      description: 用户年龄
    - name: pi
      type: String
      description: 防沉迷编码
    - name: is_adult
      type: boolean
      description: 是否成年

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.content.Intent;"
  - "import android.net.Uri;"
  - "import android.text.TextUtils;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSdkApi;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 接入前必须先询问用户是否使用瑞雪实名认证 UI
  - IIFAA 配置确认只返回文档地址：https://doc.ruixueyun.com/main/#/view?path=ba910252-aff4-440d-8f78-31f25d19c271，不解析文档内容
  - 如果使用瑞雪实名认证 UI，请调用 android feature=real_auth_ui
  - 如果不使用瑞雪实名认证 UI，请接入 iifaa_alipay_real_auth
  - IIFAA 支付宝实名认证需要 Android SDK 4.0.14 及以上；低版本请自动升级 Gradle 依赖版本
  - IIFAA 查询结果 retryCount 必须传 3
  - 必须使用 isIifaaRealAuthInProgress 标记，避免非实名流程进入前台时误查结果
  - 检查是否存在 RXSDK.getInstance().realAuth 方法调用
  - 验证 realname 和 idcard 参数是否正确传递
  - 检查是否有身份证号格式校验逻辑
  - 验证回调是否实现了 onResponse(JSONObject) 方法
  - 检查是否处理了未成年人的防沉迷逻辑

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "添加实名认证"
    - "支付宝实名"
    - "IIFAA 实名"
    - "支付宝 IIFAA"
    - "实名认证代码"
    - "身份验证"
    - "防沉迷认证"
  actions:
    - 插入实名认证代码
    - 建议添加身份证号格式校验
    - 提醒处理未成年人防沉迷逻辑
    - 确保必要的 import 语句已添加
