# 瑞雪 SDK 分享功能
# Generated by MCP
# 包含：分享、自定义分享、获取分享信息、分享上报

# ==================== 分享 ====================
share:
  method_name: "RXSDK.getInstance().share"
  description: 一键分享
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: shareConfig
      type: RXShareConfig
      required: true
      description: 分享配置
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 一键分享 ==========
    Activity activity = this;  // 当前 Activity，类型 Activity

    RXShareConfig config = new RXShareConfig();
    config.setFunc("share_func_id");       // 必填，埋点标识，类型 String
    config.setPlatform("wechat");          // 必填，分享平台：wechat/system/facebook/messenger/line/tiktok/zalo，类型 String
    config.setRegion("CN");                // 可选，地区码，类型 String
    config.setTransmits("custom_data");    // 可选，透传参数，类型 String
    config.setShareScene(0);               // 可选，0 好友，1 朋友圈，类型 int
    config.setUseShortUrl(true);           // 可选，是否使用短链接，类型 boolean
    config.setAutoReport(true);            // 可选，是否自动上报，默认 true，类型 boolean
    config.setiOSScheme("yourapp://");     // 可选，iOS 唤醒协议，类型 String
    config.setAndroidScheme("yourapp://"); // 可选，Android 唤醒协议，类型 String
    config.setUseScheme("1");              // 可选，是否使用游戏协议，类型 String

    RXSDK.getInstance().share(activity, config, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "分享成功");
                // TODO: 处理分享成功逻辑（如发放奖励）
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "分享失败: " + msg);
            }
        }
    });

# ==================== 自定义分享 ====================
shareCustom:
  method_name: "RXSDK.getInstance().shareCustom"
  description: 自定义配置分享
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: config
      type: RXCustomShareConfig
      required: true
      description: 自定义分享配置
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 自定义分享 ==========
    Activity activity = this;  // 当前 Activity，类型 Activity

    RXCustomShareConfig config = new RXCustomShareConfig();
    config.setPlatform("wechat");                      // 必填，分享平台，类型 String
    config.setType("link");                            // 必填，分享类型：text/image/link/url，类型 String
    config.setTitle("分享标题");                        // 可选，分享标题，类型 String
    config.setDescription("分享描述");                  // 可选，分享描述，类型 String
    config.setUrl("https://example.com/share");        // 可选，分享链接，类型 String
    config.setImage("https://example.com/image.png");  // 可选，图片 url 或本地路径，类型 String
    config.setShareScene(0);                           // 可选，0 好友，1 朋友圈，类型 int
    config.setThirdAppid("wx1234567890");              // 可选，三方 appid，类型 String
    config.setIOSProtocol("yourapp://");               // 可选，iOS 唤醒协议，类型 String
    config.setAndroidProtocol("yourapp://");           // 可选，Android 唤醒协议，类型 String
    config.setUseScheme("1");                          // 可选，是否使用游戏协议，类型 String

    RXSDK.getInstance().shareCustom(activity, config, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "自定义分享成功");
            } else {
                Log.e("RXSDK", "分享失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取分享信息 ====================
getShareInfo:
  method_name: "RXSDK.getInstance().getShareInfo"
  description: 获取分享信息
  parameters:
    - name: shareConfig
      type: RXShareConfig
      required: true
      description: 分享配置
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取分享信息 ==========
    RXShareConfig config = new RXShareConfig.Builder()
            .setShareId("share_001")   // 分享 ID
            .build();

    RXSDK.getInstance().getShareInfo(config, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    String title = data.optString("title");
                    String description = data.optString("description");
                    String webUrl = data.optString("web_url");
                    String thumbUrl = data.optString("thumb_url");
                    Log.d("RXSDK", "分享信息: " + title);
                }
            } else {
                Log.e("RXSDK", "获取分享信息失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取分享埋点数据 ====================
getShareData:
  method_name: "RXSDK.getInstance().getShareData"
  description: 获取分享埋点数据
  parameters:
    - name: hashMap
      type: Map<String, Object>
      required: true
      description: 参数 Map
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取分享埋点数据 ==========
    Map<String, Object> params = new HashMap<>();
    params.put("share_type", "web");
    params.put("platform", "wechat");

    RXSDK.getInstance().getShareData(params, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                Log.d("RXSDK", "分享埋点数据: " + data);
            }
        }
    });

# ==================== 分享上报 ====================
shareReport:
  method_name: "RXSDK.getInstance().shareReport"
  description: 分享上报
  parameters:
    - name: distinctId
      type: String
      required: true
      description: 用户唯一标识
    - name: properties
      type: Map<String, Object>
      required: true
      description: 属性
  code: |
    // ========== 瑞雪 SDK 分享上报 ==========
    String distinctId = "user_openid";  // 用户唯一标识，类型 String

    Map<String, Object> properties = new HashMap<>();
    properties.put("share_platform", "wechat");
    properties.put("share_type", "web");
    properties.put("share_content", "游戏邀请");

    RXSDK.getInstance().shareReport(distinctId, properties);
    Log.d("RXSDK", "分享上报完成");

# ==================== 获取短链接 ====================
getShortUrl:
  method_name: "RXSDK.getInstance().getShortUrl"
  description: 获取短链接
  parameters:
    - name: url
      type: String
      required: true
      description: 原始 URL
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取短链接 ==========
    String longUrl = "https://example.com/share?user_id=123&game_id=456";  // 原始长链接，类型 String

    RXSDK.getInstance().getShortUrl(longUrl, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                String shortUrl = data != null ? data.optString("short_url") : "";
                Log.d("RXSDK", "短链接: " + shortUrl);
                // TODO: 使用短链接进行分享
            } else {
                Log.e("RXSDK", "获取短链接失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 分享调度初始化 ====================
shareSchedulingInit:
  method_name: "RXSDK.getInstance().shareSchedulingInit"
  description: 分享调度初始化
  parameters:
    - name: funcs
      type: String[]
      required: true
      description: 分享功能标识数组
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 分享调度初始化 ==========
    String[] funcs = new String[] { "invite_friend", "daily_share" };

    RXSDK.getInstance().shareSchedulingInit(funcs, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "分享调度初始化成功");
            } else {
                Log.e("RXSDK", "分享调度初始化失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取分享调度 ====================
getShareScheduling:
  method_name: "RXSDK.getInstance().getShareScheduling"
  description: 获取分享调度结果
  return_type: Map<String, Object>
  parameters:
    - name: func
      type: String...
      required: true
      description: 分享功能标识，可传多个
  code: |
    // ========== 瑞雪 SDK 获取分享调度 ==========
    Map<String, Object> scheduling = RXSDK.getInstance().getShareScheduling(
            "invite_friend", "daily_share"
    );
    Log.d("RXSDK", "分享调度: " + scheduling);

# ==================== 分享调度上报 ====================
shareSchedulingReport:
  method_name: "RXSDK.getInstance().shareSchedulingReport"
  description: 分享调度结果上报
  parameters:
    - name: func
      type: String
      required: true
      description: 分享功能标识
    - name: platform
      type: String
      required: true
      description: 分享平台
    - name: region
      type: String
      required: false
      description: 地区码
    - name: scheduling_event
      type: boolean
      required: true
      description: true 表示完成，false 表示失败
    - name: scheduling_type
      type: String
      required: true
      description: 调度类型
    - name: transmits
      type: String
      required: false
      description: 透传参数
    - name: properties
      type: Map<String, Object>
      required: true
      description: 自定义属性
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 分享调度上报 ==========
    Map<String, Object> properties = new HashMap<>();
    properties.put("reward_id", "reward_001");

    RXSDK.getInstance().shareSchedulingReport(
            "invite_friend",
            "wechat",
            "CN",
            true,
            "share",
            "透传参数",
            properties,
            new RXRequestCallback() {
                @Override
                public void onResponse(JSONObject jsonObject) {
                    int code = jsonObject.optInt("code", -1);
                    if (code == 0) {
                        Log.d("RXSDK", "分享调度上报成功");
                    } else {
                        Log.e("RXSDK", "分享调度上报失败: " + jsonObject.optString("msg"));
                    }
                }
            }
    );

# ==================== 获取分享平台配置 ====================
getSharePlatforms:
  method_name: "RXSDK.getInstance().getSharePlatforms"
  description: 获取分享通路配置
  parameters:
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取分享平台配置 ==========
    RXSDK.getInstance().getSharePlatforms(new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "分享平台配置: " + jsonObject.optJSONObject("data"));
            } else {
                Log.e("RXSDK", "获取分享平台配置失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 分享类型
share_types:
  - name: WEB
    description: 网页分享
  - name: IMAGE
    description: 图片分享
  - name: TEXT
    description: 文本分享
  - name: VIDEO
    description: 视频分享
  - name: MINI_PROGRAM
    description: 小程序分享

# 分享平台
share_platforms:
  - name: WECHAT
    description: 微信好友
  - name: WECHAT_MOMENTS
    description: 微信朋友圈
  - name: QQ
    description: QQ 好友
  - name: QZONE
    description: QQ 空间
  - name: WEIBO
    description: 微博

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.openapi.RXShareConfig;"
  - "import com.ruixue.openapi.RXCustomShareConfig;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 验证分享配置是否正确构建
  - 验证分享平台是否已配置相关依赖
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "分享功能"
    - "微信分享"
    - "QQ 分享"
    - "获取短链接"
    - "分享上报"
  actions:
    - 根据用户需求选择对应的代码片段
    - 提醒用户配置相关分享平台依赖
    - 确保必要的 import 语句已添加
