# 瑞雪 SDK 社交关系功能
# Generated by MCP
# 包含：添加关系、删除关系、更新备注、判断关系、获取关系列表

# ==================== 设置用户自定义信息 ====================
userSetCustom:
  method_name: "RXSDK.getInstance().userSetCustom"
  description: 设置用户自定义信息
  parameters:
    - name: custom
      type: String
      required: true
      description: 自定义信息（JSON 字符串）
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 设置用户自定义信息 ==========
    String custom = "{\"level\":50,\"vip\":3,\"title\":\"王者\"}";  // 自定义信息（JSON 字符串），类型 String

    RXSDK.getInstance().userSetCustom(custom, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "自定义信息设置成功");
            } else {
                Log.e("RXSDK", "设置失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 添加自定义关系 ====================
relationAdd:
  method_name: "RXSDK.getInstance().relationAdd"
  description: 添加自定义关系
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: types
      type: Map<String, Object>
      required: true
      description: 关系类型 Map
    - name: targetRemarks
      type: String
      required: false
      description: 备注信息
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 添加自定义关系 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String
    String relationType = "follow";               // 关系类型: follow/block/mute 等，类型 String
    String remarks = "好友A";                     // 可选，备注，类型 String

    Map<String, Object> types = new HashMap<>();
    types.put(relationType, true);

    RXSDK.getInstance().relationAdd(targetOpenId, types, remarks, null, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "关系添加成功");
            } else {
                Log.e("RXSDK", "关系添加失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 删除自定义关系 ====================
relationDelete:
  method_name: "RXSDK.getInstance().relationDelete"
  description: 删除自定义关系
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: types
      type: Map<String, Object>
      required: true
      description: 关系类型 Map
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 删除自定义关系 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String
    String relationType = "follow";               // 关系类型，类型 String

    Map<String, Object> types = new HashMap<>();
    types.put(relationType, true);

    RXSDK.getInstance().relationDelete(targetOpenId, types, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "关系删除成功");
            } else {
                Log.e("RXSDK", "关系删除失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 更新关系备注 ====================
updateRemarks:
  method_name: "RXSDK.getInstance().updateRemarks"
  description: 更新自定义关系备注
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: type
      type: String
      required: true
      description: 关系类型
    - name: targetRemarks
      type: String
      required: false
      description: 备注信息
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 更新关系备注 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String
    String relationType = "follow";               // 必填，关系类型，类型 String
    String remarks = "新备注名称";                 // 新备注，类型 String

    RXSDK.getInstance().updateRemarks(targetOpenId, relationType, remarks, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "备注更新成功");
            } else {
                Log.e("RXSDK", "备注更新失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 判断是否存在关系 ====================
hasRelation:
  method_name: "RXSDK.getInstance().hasRelation"
  description: 判断两用户是否存在某自定义关系
  parameters:
    - name: target
      type: String
      required: true
      description: 对方 OpenID
    - name: type
      type: String
      required: true
      description: 关系类型
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 判断是否存在关系 ==========
    String targetOpenId = "target_user_openid";  // 必填，对方 OpenID，类型 String
    String relationType = "follow";               // 必填，关系类型，类型 String

    RXSDK.getInstance().hasRelation(targetOpenId, relationType, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONObject data = jsonObject.optJSONObject("data");
                boolean hasRelation = data != null && data.optBoolean("has_relation", false);
                Log.d("RXSDK", "是否存在关系: " + hasRelation);
                // TODO: 根据结果更新 UI
            } else {
                Log.e("RXSDK", "查询失败: " + jsonObject.optString("msg"));
            }
        }
    });

# ==================== 获取关系列表 ====================
relationList:
  method_name: "RXSDK.getInstance().relationList"
  description: 获取自定义关系列表
  parameters:
    - name: type
      type: String
      required: true
      description: 关系类型
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取关系列表 ==========
    String relationType = "follow";  // 必填，关系类型，类型 String

    RXSDK.getInstance().relationList(relationType, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                JSONArray list = jsonObject.optJSONArray("data");
                Log.d("RXSDK", "关系列表: " + list);

                if (list != null) {
                    for (int i = 0; i < list.length(); i++) {
                        JSONObject item = list.optJSONObject(i);
                        String openid = item.optString("openid");
                        String nickname = item.optString("nickname");
                        String remarks = item.optString("remarks");
                        Log.d("RXSDK", "用户: " + nickname + ", 备注: " + remarks);
                    }
                }
                // TODO: 更新关系列表 UI
            } else {
                Log.e("RXSDK", "获取列表失败: " + jsonObject.optString("msg"));
            }
        }
    });

# 常用关系类型
relation_types:
  - name: follow
    description: 关注
  - name: block
    description: 拉黑
  - name: mute
    description: 屏蔽
  - name: team
    description: 战队/团队
  - name: guild
    description: 公会

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import org.json.JSONArray;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 检查 target 参数是否为有效的 OpenID
  - 验证 types Map 是否正确构造
  - 验证回调是否实现了 onResponse(JSONObject) 方法

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "添加关系"
    - "删除关系"
    - "关注用户"
    - "拉黑用户"
    - "社交关系"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
