# 瑞雪 SDK Android TopOn 广告聚合接入规范
# Generated by MCP
# 包含：初始化、激励视频、插屏、开屏、横幅、原生广告

# ==================== 概述 ====================
overview:
  description: TopOn（AnyThink）广告聚合 SDK 封装，提供激励视频、插屏、开屏、横幅、原生广告
  keywords:
    - TopOn
    - AnyThink
    - 广告聚合
    - 激励视频
    - 插屏广告
    - 开屏广告
    - 横幅广告
    - 原生广告
  note: |
    1. TopOn 组件是可选组件，需要根据业务需求选择接入
    2. 必须先完成瑞雪 SDK 初始化，再通过 initThirdSdk 初始化 TopOn
    3. 广告位 ID（placementId）需在 TopOn 后台创建并配置广告源
    4. 官方文档：https://help.toponad.com/cn/docs/Android

# ==================== 组件信息 ====================
component:
  name: TopOn
  module: rxsdk_topon
  package: com.ruixue.topon
  plugin_key: RX_PLUGIN_TOPON
  description: TopOn 广告聚合组件，提供多种广告形式的加载与展示

# ==================== Gradle 依赖 ====================
dependency: |
  # 在 app/build.gradle 的 dependencies 中添加：
  implementation 'com.ruixue:rxsdk_topon:${version}'
  # ${version} 请向瑞雪技术支持获取最新版本号

# ==================== AndroidManifest 配置 ====================
manifest_config: |
  <!-- 如果聚合了 Admob，则必须在 AndroidManifest.xml 中添加以下配置 -->
  <!-- value 值需配置 Admob 后台创建的应用 ID -->
  <manifest>
      <application>
          <!-- Sample AdMob App ID: ca-app-pub-3940256099942544~3347511713 -->
          <meta-data
              android:name="com.google.android.gms.ads.APPLICATION_ID"
              android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
      </application>
  </manifest>

# ==================== 初始化 ====================
init:
  method_name: "RuiXueSdk.getApi().initThirdSdk"
  description: 初始化 TopOn（需在瑞雪 SDK 初始化成功后调用）
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: map
      type: HashMap<String, Object>
      required: true
      description: 初始化参数，必须包含 topon_app_id、topon_app_key
    - name: callback
      type: RXJSONCallback
      required: true
      description: 初始化结果回调
  code: |
    // ========== TopOn 初始化 ==========
    HashMap<String, Object> map = new HashMap<>();
    map.put("topon_app_id", "你的 TopOn AppId");
    map.put("topon_app_key", "你的 TopOn AppKey");

    RuiXueSdk.getApi().initThirdSdk(activity, map, new RXJSONCallback() {
        @Override
        public void onSuccess(@Nullable JSONObject data) {
            RXLogger.e("rx third init success: " + data.toString());
        }

        @Override
        public void onFailed(@NonNull JSONObject cause) {
            RXLogger.e("rx third init failed: " + cause);
        }
    });

# ==================== 辅助方法 ====================
helper_methods:
  - method_name: "TopOnHelper.setNetworkLogDebug"
    description: SDK 日志开关，集成测试阶段建议开启，上线前必须关闭
    code: "TopOnHelper.setNetworkLogDebug(true);"
  - method_name: "TopOnHelper.getSDKVersionName"
    description: 获取 TopOn SDK 版本
    code: 'Log.i(TAG, "TopOn SDK version: " + TopOnHelper.getSDKVersionName());'
  - method_name: "TopOnHelper.integrationChecking"
    description: 检查广告平台集成状态，提交审核时需注释此 API
    code: "TopOnHelper.integrationChecking(activity);"
  - method_name: "TopOnHelper.testModeDeviceInfo"
    description: 打印当前设备信息（IMEI、OAID、GAID、AndroidID 等）
    code: |
      TopOnHelper.testModeDeviceInfo(activity, new DeviceInfoCallback() {
          @Override
          public void deviceInfo(String deviceInfo) {
              Log.i(TAG, "deviceInfo: " + deviceInfo);
          }
      });

# ==================== 激励视频 ====================
reward_video:
  description: 激励视频广告，支持手动加载和全自动加载两种模式
  manual:
    classes:
      - RxATRewardVideoAd
    api:
      - "new RxATRewardVideoAd(Context context, String placementId)"
      - "void setAdListener(ATRewardVideoListener listener)"
      - "void load()"
      - "boolean isAdReady()"
      - "void show(Activity activity)"
      - "static void entryAdScenario(String placementId, String scenarioId)"
    code: |
      // ========== 激励视频 - 手动加载 ==========
      RxATRewardVideoAd rxATRewardVideoAd;
      private void rewardLoadAd() {
          if (rxATRewardVideoAd == null) {
              rxATRewardVideoAd = new RxATRewardVideoAd(this, placementId);
              rxATRewardVideoAd.setAdListener(new ATRewardVideoListener() {
                  @Override
                  public void onRewardedVideoAdLoaded() { Log.d(TAG, "onRewardedVideoAdLoaded"); }
                  @Override
                  public void onRewardedVideoAdFailed(AdError adError) {
                      // 禁止在此回调中执行广告加载方法重试
                      Log.e(TAG, "onRewardedVideoAdFailed:" + adError.getFullErrorInfo());
                  }
                  @Override
                  public void onRewardedVideoAdPlayStart(ATAdInfo adInfo) {
                      // 建议在此回调中调用 load 进行预加载
                      rxATRewardVideoAd.load();
                  }
                  @Override
                  public void onRewardedVideoAdPlayEnd(ATAdInfo atAdInfo) {}
                  @Override
                  public void onRewardedVideoAdPlayFailed(AdError adError, ATAdInfo atAdInfo) {}
                  @Override
                  public void onRewardedVideoAdClosed(ATAdInfo atAdInfo) {}
                  @Override
                  public void onReward(ATAdInfo atAdInfo) {
                      // 建议在此回调中下发奖励
                  }
                  @Override
                  public void onRewardedVideoAdPlayClicked(ATAdInfo atAdInfo) {}
              });
          }
          rxATRewardVideoAd.load();
      }

      private void rewardShowAd() {
          // 1. 进入场景统计  2. 判断 ready  3. 展示
          RxATRewardVideoAd.entryAdScenario("your rv placementID", "your scenarioID");
          if (rxATRewardVideoAd.isAdReady()) {
              rxATRewardVideoAd.show(this);
          }
      }
  auto:
    classes:
      - RxATRewardVideoAutoAd
    api:
      - "static void rxInit(Context context, String[] placementIds, ATRewardVideoAutoLoadListener loadListener)"
      - "static void rxEntryAdScenario(String placementId, String scenarioId)"
      - "static boolean rxIsAdReady(String placementId)"
      - "static void rxShow(Activity activity, String placementId, String scenario, ATRewardVideoAutoEventListener eventListener)"
    code: |
      // ========== 激励视频 - 全自动加载 ==========
      RxATRewardVideoAutoAd.rxInit(this, new String[]{"b62b420ba3c661"},
          new ATRewardVideoAutoLoadListener() {
              @Override
              public void onRewardVideoAutoLoaded(String s) {}
              @Override
              public void onRewardVideoAutoLoadFail(String s, AdError adError) {}
          });

      RxATRewardVideoAd.rxEntryAdScenario("b62b420ba3c661", null);
      if (RxATRewardVideoAutoAd.rxIsAdReady("b62b420ba3c661")) {
          RxATRewardVideoAutoAd.rxShow(this, "b62b420ba3c661", "",
              new ATRewardVideoAutoEventListener() {
                  @Override public void onRewardedVideoAdPlayStart(ATAdInfo atAdInfo) {}
                  @Override public void onRewardedVideoAdPlayEnd(ATAdInfo atAdInfo) {}
                  @Override public void onRewardedVideoAdPlayFailed(AdError adError, ATAdInfo atAdInfo) {}
                  @Override public void onRewardedVideoAdClosed(ATAdInfo atAdInfo) {}
                  @Override public void onRewardedVideoAdPlayClicked(ATAdInfo atAdInfo) {}
                  @Override public void onReward(ATAdInfo atAdInfo) {}
              });
      }

# ==================== 插屏广告 ====================
interstitial:
  description: 插屏广告，支持手动加载和全自动加载两种模式
  manual:
    classes:
      - RxATInterstitial
    api:
      - "new RxATInterstitial(Context context, String placementId)"
      - "void setAdListener(ATInterstitialListener listener)"
      - "void load()"
      - "boolean isAdReady()"
      - "void show(Activity activity)"
      - "static void entryAdScenario(String placementId, String scenarioId)"
    code: |
      // ========== 插屏广告 - 手动加载 ==========
      RxATInterstitial mInterstitialAd;
      private void interLoadAd() {
          if (mInterstitialAd == null) {
              mInterstitialAd = new RxATInterstitial(this, "b62b41f080cfc5");
              mInterstitialAd.setAdListener(new ATInterstitialListener() {
                  @Override public void onInterstitialAdLoaded() {}
                  @Override public void onInterstitialAdLoadFail(AdError adError) {
                      Log.e(TAG, "onInterstitialAdLoadFail:" + adError.getFullErrorInfo());
                  }
                  @Override public void onInterstitialAdClicked(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdShow(ATAdInfo atAdInfo) {
                      // 建议在此回调中调用 load 进行预加载
                      mInterstitialAd.load();
                  }
                  @Override public void onInterstitialAdClose(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdVideoStart(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdVideoEnd(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdVideoError(AdError adError) {}
              });
              mInterstitialAd.load();
          }
      }

      private void interShowAd() {
          RxATInterstitial.entryAdScenario("b62b41f080cfc5", "");
          if (mInterstitialAd.isAdReady()) {
              mInterstitialAd.show(this);
          }
      }
  auto:
    classes:
      - RxATInterstitialAutoAd
    api:
      - "static void rxInit(Context context, String[] placementIds, ATInterstitialAutoLoadListener loadListener)"
      - "static void rxEntryAdScenario(String placementId, String scenarioId)"
      - "static boolean rxIsAdReady(String placementId)"
      - "static void rxShow(Activity activity, String placementId, ATInterstitialAutoEventListener eventListener)"
    code: |
      // ========== 插屏广告 - 全自动加载 ==========
      RxATInterstitial.rxEntryAdScenario("b62b41f080cfc5", "");
      if (RxATInterstitialAutoAd.rxIsAdReady("b62b41f080cfc5")) {
          RxATInterstitialAutoAd.rxShow(this, "b62b41f080cfc5",
              new ATInterstitialAutoEventListener() {
                  @Override public void onInterstitialAdClicked(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdShow(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdClose(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdVideoStart(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdVideoEnd(ATAdInfo atAdInfo) {}
                  @Override public void onInterstitialAdVideoError(AdError adError) {}
              });
      }

# ==================== 开屏广告 ====================
splash:
  description: 开屏广告，展示区域至少占屏幕 75%
  classes:
    - RxATSplashAd
    - RxATSplashAdListener
  api:
    - "new RxATSplashAd(Context context, String placementId, RxATSplashAdListener listener, int fetchAdTimeout, String defaultAdSourceConfig)"
    - "boolean isAdReady()"
    - "void rxShow(Activity activity, ViewGroup container)"
    - "void loadAd()"
  code: |
    // ========== 开屏广告 ==========
    public void showSplash() {
        FrameLayout container = findViewById(R.id.splash_ad_container);
        RxATSplashAdListener listener = new RxATSplashAdListener() {
            @Override public void onAdLoaded(boolean isTimeout) {}
            @Override public void onAdLoadTimeout() {}
            @Override public void onNoAdError(AdError var1) {}
            @Override public void onAdShow(ATAdInfo var1) {}
            @Override public void onAdClick(ATAdInfo var1) {}
            @Override public void onAdDismiss(ATAdInfo var1, RxATSplashAdExtraInfo info) {}
        };

        // 首次开屏广告源配置，请从 TopOn 后台兜底开屏广告源导出
        String defaultConfig = "{\"unit_id\":1333176,\"nw_firm_id\":8,...}";

        RxATSplashAd splashAd = new RxATSplashAd(this, "b62b41521d52d1", listener, 5000, defaultConfig);
        if (splashAd.isAdReady()) {
            // container 大小至少占屏幕 75%
            splashAd.rxShow(this, container);
        } else {
            splashAd.loadAd();
        }
    }

# ==================== 横幅广告 ====================
banner:
  description: 横幅广告，ATBannerView 对象可重复使用
  classes:
    - RxATBannerView
  api:
    - "new RxATBannerView(Context context)"
    - "void setPlacementId(String placementId)"
    - "void setBannerAdListener(ATBannerListener listener)"
    - "void loadAd()"
  code: |
    // ========== 横幅广告 ==========
    RxATBannerView mBannerView;
    FrameLayout mBannerViewContainer;
    private void initBannerView() {
        mBannerView = new RxATBannerView(this);
        mBannerView.setPlacementId("b62b420ae05bb4");
        mBannerView.setVisibility(View.VISIBLE);
        mBannerView.setBannerAdListener(new ATBannerExListener() {
            @Override public void onBannerLoaded() {}
            @Override public void onBannerFailed(AdError adError) {}
            @Override public void onBannerClicked(ATAdInfo entity) {}
            @Override public void onBannerShow(ATAdInfo entity) {}
            @Override public void onBannerClose(ATAdInfo entity) { mBannerView.setVisibility(View.GONE); }
            @Override public void onBannerAutoRefreshed(ATAdInfo entity) {}
            @Override public void onBannerAutoRefreshFail(AdError adError) {}
            @Override public void onDeeplinkCallback(boolean isRefresh, ATAdInfo adInfo, boolean isSuccess) {}
            @Override public void onDownloadConfirm(Context context, ATAdInfo adInfo, ATNetworkConfirmInfo info) {}
        });
    }

    private void addBannerViewToContainer() {
        if (mBannerViewContainer != null && mBannerView != null) {
            mBannerViewContainer.addView(mBannerView, new FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT,
                mBannerViewContainer.getLayoutParams().height));
        }
    }

    private void loadBannerAd() {
        mBannerView.setVisibility(View.VISIBLE);
        mBannerViewContainer.setVisibility(View.VISIBLE);
        mBannerView.loadAd();
    }

# ==================== 原生广告 ====================
native:
  description: 原生广告，根据获取到的广告数据自定义 view
  classes:
    - RxATNative
    - RxNativeAd
  api:
    - "new RxATNative(Context context, String placementId, ATNativeNetworkListener listener)"
    - "void makeAdRequest()"
    - "RxNativeAd rxGetNativeAd()"
    - "void setNativeEventListener(ATNativeEventListener listener)"
    - "ATAdInfo getAdInfo()"
  code: |
    // ========== 原生广告 ==========
    RxATNative atNative;
    public void loadNativeAd() {
        if (atNative == null) {
            atNative = new RxATNative(this, "b62b420bf038e3", new ATNativeNetworkListener() {
                @Override public void onNativeAdLoaded() { Log.i(TAG, "onNativeAdLoaded"); }
                @Override public void onNativeAdLoadFail(AdError adError) {
                    Log.i(TAG, "onNativeAdLoadFail:" + adError.getFullErrorInfo());
                }
            });
        }
        atNative.makeAdRequest();
    }

    public void showNativeAd() {
        RxNativeAd rxNativeAd = atNative.rxGetNativeAd();
        rxNativeAd.setNativeEventListener(new ATNativeEventListener() {
            @Override public void onAdImpressed(ATNativeAdView adView, ATAdInfo atAdInfo) {}
            @Override public void onAdClicked(ATNativeAdView adView, ATAdInfo atAdInfo) {}
            @Override public void onAdVideoStart(ATNativeAdView adView) {}
            @Override public void onAdVideoEnd(ATNativeAdView adView) {}
            @Override public void onAdVideoProgress(ATNativeAdView adView, int i) {}
        });
        // 根据获取到的广告数据自定义 view
        Log.d(TAG, "getAdInfo: " + rxNativeAd.getAdInfo().toString());
    }

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RuiXueSdk;"
  - "import com.ruixue.RXJSONCallback;"
  - "import com.ruixue.topon.TopOnHelper;"
  - "import com.ruixue.topon.adtype.RxATRewardVideoAd;"
  - "import com.ruixue.topon.adtype.RxATRewardVideoAutoAd;"
  - "import com.ruixue.topon.adtype.RxATInterstitial;"
  - "import com.ruixue.topon.adtype.RxATInterstitialAutoAd;"
  - "import com.ruixue.topon.adtype.RxATSplashAd;"
  - "import com.ruixue.topon.adtype.RxATBannerView;"
  - "import com.ruixue.topon.adtype.RxATNative;"
  - "import com.ruixue.topon.bean.RxNativeAd;"
  - "import com.ruixue.topon.listener.RxATSplashAdListener;"

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: 必须先完成瑞雪 SDK 初始化，再调用 initThirdSdk 初始化 TopOn
  - title: 初始化参数
    content: initThirdSdk 的 map 必须包含 topon_app_id 和 topon_app_key，从 TopOn 后台获取
  - title: 加载失败重试
    content: 禁止在广告加载失败回调（onXxxAdFailed）中执行加载方法重试，否则会引起无用请求与卡顿
  - title: 预加载
    content: 建议在广告展示/播放开始回调中调用 load 进行下一次预加载
  - title: 开屏区域
    content: 开屏广告展示区域至少占屏幕 75%，跳过秒数超过 3 秒，否则可能展示无效
  - title: Admob 配置
    content: 若聚合 Admob，必须在 AndroidManifest.xml 中配置 com.google.android.gms.ads.APPLICATION_ID
  - title: 上线前
    content: 提交审核/上线前需关闭 setNetworkLogDebug 并注释 integrationChecking
