# 瑞雪 SDK 数据埋点功能
# Generated by MCP
# 包含：埋点数据上报、用户行为上报

# ==================== 埋点数据上报 ====================
dataTrack:
  method_name: "RXSDK.getInstance().dataTrack"
  description: 埋点数据上报
  parameters:
    - name: eventName
      type: String
      required: true
      description: 埋点标识事件
    - name: distinctId
      type: String
      required: true
      description: 用户唯一标识
    - name: properties
      type: Map<String, Object>
      required: false
      description: 自定义属性
  return_type: boolean
  return_description: 是否成功
  code: |
    // ========== 瑞雪 SDK 埋点数据上报 ==========
    String eventName = "level_pass";        // 必填，事件名称，类型 String
    String distinctId = "user_openid";      // 必填，用户唯一标识，类型 String

    Map<String, Object> properties = new HashMap<>();
    properties.put("level", 10);
    properties.put("score", 9999);
    properties.put("duration", 120);        // 耗时（秒）
    properties.put("timestamp", System.currentTimeMillis());

    boolean result = RXSDK.getInstance().dataTrack(eventName, distinctId, properties);
    if (result) {
        Log.d("RXSDK", "埋点上报成功: " + eventName);
    } else {
        Log.e("RXSDK", "埋点上报失败: " + eventName);
    }

# ==================== 上报用户行为 ====================
trackUserAction:
  method_name: "RXSDK.getInstance().trackUserAction"
  description: 上报用户行为
  parameters:
    - name: distinctId
      type: String
      required: true
      description: 用户唯一标识
    - name: properties
      type: Map<String, Object>
      required: false
      description: 属性
  code: |
    // ========== 瑞雪 SDK 用户行为上报 ==========
    String userId = "user_openid";   // 必填，用户 ID，类型 String
    String action = "button_click";   // 行为类型，类型 String

    Map<String, Object> properties = new HashMap<>();
    properties.put("action", action);
    properties.put("button_name", "start_game");
    properties.put("page", "game_hall");
    properties.put("action_time", System.currentTimeMillis());

    RXSDK.getInstance().trackUserAction(userId, properties);
    Log.d("RXSDK", "用户行为已上报: " + action);

# ==================== 停止用户行为上报 ====================
stopTrackUserAction:
  method_name: "RXSDK.getInstance().stopTrackUserAction"
  description: 停止用户行为上报
  code: |
    // ========== 瑞雪 SDK 停止用户行为上报 ==========
    // 在用户退出游戏或进入后台时调用

    RXSDK.getInstance().stopTrackUserAction();
    Log.d("RXSDK", "用户行为上报已停止");

# ==================== 窗口曝光上报 ====================
reportWindowExposure:
  method_name: "RXSDK.getInstance().reportWindowExposure"
  description: 上报商业化窗口曝光
  parameters:
    - name: properties
      type: Map<String, Object>
      required: true
      description: 窗口曝光属性
  code: |
    // ========== 瑞雪 SDK 窗口曝光上报 ==========
    Map<String, Object> properties = new HashMap<>();
    properties.put("window_id", "popup_001");
    properties.put("window_name", "限时礼包弹窗");
    properties.put("scene_identifier", "home");

    RXSDK.getInstance().reportWindowExposure(properties);
    Log.d("RXSDK", "窗口曝光已上报");

# ==================== 获取运营场景 ====================
getOperationScene:
  method_name: "RXSDK.getInstance().getOperationScene"
  description: 获取运营场景配置
  parameters:
    - name: callback
      type: RXJSONCallback
      required: true
      description: 回调接口
  code: |
    // ========== 瑞雪 SDK 获取运营场景 ==========
    RXSDK.getInstance().getOperationScene(new RXJSONCallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "运营场景: " + data);
        }

        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "获取运营场景失败: " + cause);
        }
    });

# 常用埋点事件
common_events:
  - name: game_login
    description: 游戏登录
  - name: game_logout
    description: 游戏登出
  - name: level_start
    description: 关卡开始
  - name: level_pass
    description: 关卡通过
  - name: level_fail
    description: 关卡失败
  - name: purchase
    description: 购买
  - name: share
    description: 分享
  - name: invite
    description: 邀请
  - name: tutorial_complete
    description: 新手教程完成

# 导入语句
imports:
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSDK;"
  - "import com.ruixue.RXJSONCallback;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 检查指南 (给 AI 的指令)
check_guide:
  - 验证 eventName 是否为有效的事件名称
  - 验证 distinctId 是否为有效的用户标识
  - 验证 properties 是否正确构造

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "埋点上报"
    - "数据埋点"
    - "事件上报"
    - "用户行为"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
