# 瑞雪 SDK 用户中心 UI 功能
# Generated by MCP
# 包含：用户中心、帮助中心、客服

# ==================== 用户中心弹窗 ====================
userCenterUI:
  method_name: "RXSdkUI.getInstance().userCenterUI"
  description: 用户中心界面
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: rxUserCenterConfig
      type: RXUserCenterConfig
      required: true
      description: 用户中心配置
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 用户中心弹窗 ==========
    // 注意：需要添加 UI 模块依赖 implementation 'com.ruixue:rxsdk_base_ui:${version}'
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.openapi.RXUserCenterConfig;
    import com.ruixue.RXRequestCallback;
    import org.json.JSONObject;
    import java.util.HashMap;
    import java.util.Map;
    
    // 配置用户中心显示的按钮
    Map<String, Object> ucMap = new HashMap<>();
    ucMap.put("btns", new String[]{
        "real_name",           // 实名认证
        "privacy_policy",      // 隐私政策
        "acount_cancel",       // 账号注销
        "phone_management",    // 手机管理
        "change_pwd"           // 修改密码
    });
    
    // 创建用户中心配置
    RXUserCenterConfig rxUserCenterConfig = new RXUserCenterConfig();
    rxUserCenterConfig.setTransmit_args("透传参数");           // 透传数据，使用 jsonString 形式
    rxUserCenterConfig.setGame_user_id(1000);                  // 用户的游戏 ID
    rxUserCenterConfig.setNickname("用户昵称");                // 用户昵称
    rxUserCenterConfig.setHead_img_url("用户头像URL");         // 用户头像 URL
    rxUserCenterConfig.setQueue_name("default");               // 在瑞雪客服系统设置的接入点名称，不填写默认为 default
    rxUserCenterConfig.setConfigParams(ucMap);                 // 用户中心按钮配置
    // rxUserCenterConfig.setLightTheme(true);                 // 是否使用浅色主题，默认 false
    // rxUserCenterConfig.setSyncInfoEnable(false);            // 是否展示同步信息按钮，默认 false
    
    RXSdkUI.getInstance().userCenterUI(activity, rxUserCenterConfig, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                // 处理成功逻辑
                JSONObject data = jsonObject.optJSONObject("data");
                if (data != null) {
                    String type = data.optString("type");
                    // type 可能的值：
                    // - "real_name": 实名认证
                    // - "logout": 退出登录
                    // - "cancel_account": 注销账号
                    Log.d("RXSDK", "用户中心操作类型: " + type);
                }
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "用户中心操作失败: " + msg);
                // TODO: 根据错误码处理失败逻辑
            }
        }
    }).show();

# ==================== 帮助中心弹窗 ====================
helperCenterUI:
  method_name: "RXSdkUI.getInstance().helperCenterUI"
  description: 帮助中心界面
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: rxUserCenterConfig
      type: RXUserCenterConfig
      required: true
      description: 帮助中心配置
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 帮助中心弹窗 ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.openapi.RXUserCenterConfig;
    import com.ruixue.RXRequestCallback;
    
    RXUserCenterConfig config = new RXUserCenterConfig();
    config.setGame_user_id("游戏用户ID");
    config.setNickname("用户昵称");
    config.setQueue_name("default");
    // config.setLightTheme(true);  // 是否使用浅色主题
    
    RXSdkUI.getInstance().helperCenterUI(activity, config, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "帮助中心操作成功");
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "帮助中心操作失败: " + msg);
            }
        }
    }).show();

# ==================== 客服弹窗 ====================
chatServiceUI:
  method_name: "RXSdkUI.getInstance().chatServiceUI"
  description: 客服界面
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: rxUserCenterConfig
      type: RXUserCenterConfig
      required: true
      description: 客服配置
    - name: callback
      type: RXRequestCallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 客服弹窗 ==========
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.openapi.RXUserCenterConfig;
    import com.ruixue.RXRequestCallback;
    
    RXUserCenterConfig config = new RXUserCenterConfig();
    config.setGame_user_id("游戏用户ID");
    config.setNickname("用户昵称");
    config.setQueue_name("default");  // 客服接入节点
    
    RXSdkUI.getInstance().chatServiceUI(activity, config, new RXRequestCallback() {
        @Override
        public void onResponse(JSONObject jsonObject) {
            int code = jsonObject.optInt("code", -1);
            if (code == 0) {
                Log.d("RXSDK", "客服操作成功");
            } else {
                String msg = jsonObject.optString("msg");
                Log.e("RXSDK", "客服操作失败: " + msg);
            }
        }
    }).show();

# ==================== 绑定手机 UI ====================
bindPhoneUI:
  method_name: "RXSdkUI.getInstance().bindPhoneUI"
  description: 绑定手机 UI（H5 页面）
  note: 如果已绑定手机会跳转到换绑页面
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: callback
      type: RXUICallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 绑定手机 UI ==========
    // 注意：如果已绑定手机会跳转到换绑页面
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.callback.RXUICallback;
    import com.ruixue.error.RXException;
    
    RXSdkUI.getInstance().bindPhoneUI(activity, new RXUICallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "绑定手机成功: " + data);
            // TODO: 处理绑定成功逻辑
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "绑定手机失败或取消: " + cause);
            // TODO: 处理绑定失败逻辑
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "绑定手机错误: " + e.getMessage());
        }
    }).show();

# ==================== 绑定邮箱 UI ====================
bindEmailUI:
  method_name: "RXSdkUI.getInstance().bindEmailUI"
  description: 绑定邮箱 UI（H5 页面）
  note: 如果已绑定邮箱会跳转到换绑页面
  parameters:
    - name: activity
      type: Activity
      required: true
      description: 当前 Activity
    - name: callback
      type: RXUICallback
      required: true
      description: 回调函数
  code: |
    // ========== 瑞雪 SDK 绑定邮箱 UI ==========
    // 注意：如果已绑定邮箱会跳转到换绑页面
    
    import com.ruixue.openapi.RXSdkUI;
    import com.ruixue.callback.RXUICallback;
    import com.ruixue.error.RXException;
    
    RXSdkUI.getInstance().bindEmailUI(activity, new RXUICallback() {
        @Override
        public void onSuccess(JSONObject data) {
            Log.d("RXSDK", "绑定邮箱成功: " + data);
            // TODO: 处理绑定成功逻辑
        }
        
        @Override
        public void onFailed(JSONObject cause) {
            Log.e("RXSDK", "绑定邮箱失败或取消: " + cause);
            // TODO: 处理绑定失败逻辑
        }
        
        @Override
        public void onError(RXException e) {
            Log.e("RXSDK", "绑定邮箱错误: " + e.getMessage());
        }
    }).show();

# RXUserCenterConfig 配置参数
user_center_config:
  class_name: RXUserCenterConfig
  import_path: com.ruixue.openapi.RXUserCenterConfig
  description: 用户中心/帮助中心/客服配置对象
  fields:
    - name: transmit_args
      type: String
      setter: setTransmit_args
      description: 透传数据，使用 jsonString 形式
    - name: game_user_id
      type: Object
      setter: setGame_user_id
      description: 用户的游戏 ID，不传则在瑞雪后台账号注销页面不显示游戏侧的用户 ID
    - name: nickname
      type: String
      setter: setNickname
      description: 用户昵称
    - name: head_img_url
      type: String
      setter: setHead_img_url
      description: 用户头像 URL
    - name: queue_name
      type: String
      setter: setQueue_name
      description: 在瑞雪客服系统设置的接入点名称，不填写默认为 default
    - name: lightTheme
      type: boolean
      setter: setLightTheme
      description: 是否使用浅色主题，默认 false
    - name: syncInfoEnable
      type: boolean
      setter: setSyncInfoEnable
      description: 是否展示同步信息按钮，用于同步三方信息，默认 false
    - name: configParams
      type: Map<String, Object>
      setter: setConfigParams
      description: 用户中心按钮配置

# 用户中心按钮配置
user_center_btns:
  - name: real_name
    description: 实名认证
  - name: privacy_policy
    description: 隐私政策
  - name: acount_cancel
    description: 账号注销
  - name: phone_management
    description: 手机管理（账号管理）
  - name: change_pwd
    description: 修改密码

# 导入语句
imports:
  - "import android.app.Activity;"
  - "import android.util.Log;"
  - "import com.ruixue.openapi.RXSdkUI;"
  - "import com.ruixue.openapi.RXUserCenterConfig;"
  - "import com.ruixue.RXRequestCallback;"
  - "import org.json.JSONObject;"
  - "import java.util.HashMap;"
  - "import java.util.Map;"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    artifact: "com.ruixue:rxsdk_base_ui"
    description: 用户中心 UI 需要添加此依赖
