# 瑞雪 SDK Android 微信配置
# Generated by MCP
# 包含：微信登录配置、微信支付配置、AndroidManifest 配置

# ==================== 功能说明 ====================
description: |
  微信登录和微信支付需要在 AndroidManifest.xml 中配置回调 Activity，
  以便接收微信客户端的回调结果。

# ==================== AndroidManifest 配置 ====================
manifest_config:
  description: 微信回调 Activity 配置
  
  # 微信登录配置（必需）
  wechat_login:
    title: 微信登录 Manifest 配置
    description: 使用微信登录功能时，必须添加此配置
    code: |
      <!-- ========== 微信回调配置（微信登录必需） ========== -->
      
      <!-- 微信回调 Activity，可继承重写 -->
      <!-- android:taskAffinity 设置 Activity 归属，默认使用应用包名 -->
      <activity
          android:name="com.ruixue.wechat.WXEntryActivity"
          android:enabled="true"
          android:exported="true"
          android:taskAffinity="${applicationId}"
          android:launchMode="singleTask"
          android:theme="@android:style/Theme.Translucent.NoTitleBar" />
      
      <!-- 微信回调 Activity 别名类 -->
      <!-- 微信需要回调到指定包名指定类名，所以设置别名指向实际的 Activity -->
      <activity-alias
          android:name="${applicationId}.wxapi.WXEntryActivity"
          android:enabled="true"
          android:exported="true"
          android:targetActivity="com.ruixue.wechat.WXEntryActivity" />

  # 微信支付配置（微信支付必需）
  wechat_pay:
    title: 微信支付 Manifest 配置
    description: 使用微信支付功能时，需要额外添加支付回调配置
    code: |
      <!-- ========== 微信支付回调配置（微信支付必需） ========== -->
      
      <!-- 微信支付回调 Activity 别名，用于接收支付结果回调 -->
      <activity-alias
          android:name="${applicationId}.wxapi.WXPayEntryActivity"
          android:enabled="true"
          android:exported="true"
          android:targetActivity="com.ruixue.wechat.WXEntryActivity" />

  # 完整配置（微信登录 + 微信支付）
  wechat_full:
    title: 微信完整配置（登录 + 支付）
    description: 同时使用微信登录和微信支付时的完整配置
    code: |
      <!-- ========== 微信配置（登录 + 支付） ========== -->
      
      <!-- 微信回调 Activity，可继承重写 -->
      <!-- android:taskAffinity 设置 Activity 归属，默认使用应用包名 -->
      <activity
          android:name="com.ruixue.wechat.WXEntryActivity"
          android:enabled="true"
          android:exported="true"
          android:taskAffinity="${applicationId}"
          android:launchMode="singleTask"
          android:theme="@android:style/Theme.Translucent.NoTitleBar" />
      
      <!-- 微信登录回调 Activity 别名 -->
      <!-- 微信需要回调到指定包名指定类名，所以设置别名指向实际的 Activity -->
      <activity-alias
          android:name="${applicationId}.wxapi.WXEntryActivity"
          android:enabled="true"
          android:exported="true"
          android:targetActivity="com.ruixue.wechat.WXEntryActivity" />
      
      <!-- 微信支付回调 Activity 别名，用于接收支付结果回调 -->
      <activity-alias
          android:name="${applicationId}.wxapi.WXPayEntryActivity"
          android:enabled="true"
          android:exported="true"
          android:targetActivity="com.ruixue.wechat.WXEntryActivity" />

# ==================== 配置说明 ====================
config_notes:
  - title: taskAffinity 说明
    content: |
      android:taskAffinity 用于指定 Activity 所属的任务栈。
      建议设置为 ${applicationId}，即应用的包名。
      如果需要自定义，请确保与应用包名一致。
  
  - title: WXEntryActivity 说明
    content: |
      com.ruixue.wechat.WXEntryActivity 是 SDK 内置的微信回调处理类。
      如需自定义回调处理逻辑，可以继承该类并重写相关方法。
  
  - title: activity-alias 说明
    content: |
      微信 SDK 要求回调 Activity 必须位于 ${applicationId}.wxapi 包下，
      且类名必须为 WXEntryActivity（登录）或 WXPayEntryActivity（支付）。
      使用 activity-alias 可以将回调转发到 SDK 内置的处理类。
  
  - title: exported 说明
    content: |
      android:exported="true" 是必需的，允许微信客户端启动该 Activity。
      Android 12+ 要求显式声明 exported 属性。

# ==================== 依赖配置 ====================
dependencies:
  wechat_login:
    title: 微信登录依赖
    description: 使用微信登录需要添加微信 SDK 依赖（通常已包含在基础 SDK 中）
    code: |
      // 微信登录依赖（如果未包含在基础 SDK 中）
      // implementation 'com.ruixue:rxsdk_weixin:${version}'
  
  wechat_pay:
    title: 微信支付依赖
    description: 使用微信支付必须添加此依赖
    code: |
      // 微信支付依赖（必需）
      implementation 'com.ruixue:rxsdk_weixin_withpay:${version}'

# ==================== AI 行为指南 ====================
check_guide: |
  当用户请求微信登录或微信支付功能时，必须执行以下检查：
  
  1. 检查 AndroidManifest.xml 是否已配置微信回调：
     - 搜索 "WXEntryActivity" 判断是否已配置
     - 如果未配置，自动添加对应的 Manifest 配置
  
  2. 微信登录时：
     - 添加 WXEntryActivity 和 activity-alias（WXEntryActivity）
  
  3. 微信支付时：
     - 检查是否已有微信登录配置，如果没有则一并添加
     - 添加 activity-alias（WXPayEntryActivity）
     - 检查 build.gradle 是否有 rxsdk_weixin_withpay 依赖
  
  4. 配置位置：
     - Manifest 配置添加在 <application> 标签内
     - 建议放在其他 <activity> 声明之后

# ==================== 完整示例 ====================
full_example:
  title: AndroidManifest.xml 完整示例
  code: |
    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools">
    
        <uses-permission android:name="android.permission.INTERNET" />
    
        <application
            android:name=".DemoApplication"
            android:allowBackup="true"
            android:icon="@mipmap/ic_launcher"
            android:label="@string/app_name"
            android:theme="@style/Theme.App"
            tools:targetApi="31">
            
            <!-- 主 Activity -->
            <activity
                android:name=".MainActivity"
                android:exported="true">
                <intent-filter>
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
            
            <!-- ========== 微信配置（登录 + 支付） ========== -->
            
            <!-- 微信回调 Activity，可继承重写 -->
            <activity
                android:name="com.ruixue.wechat.WXEntryActivity"
                android:enabled="true"
                android:exported="true"
                android:taskAffinity="${applicationId}"
                android:launchMode="singleTask"
                android:theme="@android:style/Theme.Translucent.NoTitleBar" />
            
            <!-- 微信登录回调 Activity 别名 -->
            <activity-alias
                android:name="${applicationId}.wxapi.WXEntryActivity"
                android:enabled="true"
                android:exported="true"
                android:targetActivity="com.ruixue.wechat.WXEntryActivity" />
            
            <!-- 微信支付回调 Activity 别名 -->
            <activity-alias
                android:name="${applicationId}.wxapi.WXPayEntryActivity"
                android:enabled="true"
                android:exported="true"
                android:targetActivity="com.ruixue.wechat.WXEntryActivity" />
            
        </application>
    
    </manifest>

# ==================== MCP 交互 ====================
mcp_interaction:
  trigger_phrases:
    - "微信登录"
    - "微信支付"
    - "接入微信"
    - "配置微信"
    - "WXEntryActivity"
  
  actions:
    wechat_login:
      - check_manifest_for_wxentry
      - add_manifest_config_if_missing
      - show_login_code
    
    wechat_pay:
      - check_manifest_for_wxentry
      - check_manifest_for_wxpayentry
      - add_manifest_config_if_missing
      - check_gradle_dependency
      - add_dependency_if_missing
      - show_pay_code
