platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'


workspace 'RXOpeninstallSDK.xcworkspace'

def commonPods
  
  use_frameworks!
  
  pod 'RXLanguageKit'
#  pod 'libOpenInstallSDK'
  pod 'WechatOpenSDK'
  pod 'RXAuthSDK_official'

end

target 'RXOpeninstallSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

#  commonPods

end

target 'RXOpeninstallSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXOpeninstallSDKDemo/RXOpeninstallSDKDemo.xcodeproj'
    commonPods

end
