platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'RXAliCloudDNSSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    pod 'RXAliDNSSDK_official'
#    pod 'RXLanguageKit'
end

target 'RXAliCloudDNSSDKDemo' do
  project 'RXAliCloudDNSSDKDemo/RXAliCloudDNSSDKDemo.xcodeproj'
  commonPods
end

target 'RXAliCloudDNSSDK' do
  project 'RXAliCloudDNSSDK.xcodeproj'
  commonPods
end
