# 瑞雪 SDK iOS 公告/邮件功能
# Generated by MCP
# 包含：获取公告、临时公告、邮件列表、领取道具

# ==================== 获取公告列表 ====================
get_announcement:
  method_name: "[[RXSDK sharedSDK] getAnnouncementWithLimit:complete:]"
  description: 获取公告列表
  parameters:
    - name: limit
      type: int
      required: true
      description: 返回公告条数（1-100）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取公告列表 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    int limit = 10;  // 必填，返回公告条数（1-100），类型 int
    
    [[RXSDK sharedSDK] getAnnouncementWithLimit:limit
                                       complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取公告失败: %@", error.responesObject);
        } else {
            NSArray *list = response[@"data"][@"list"];  // 类型 NSArray *
            for (NSDictionary *announcement in list) {
                NSString *title = announcement[@"title"];      // 公告标题，类型 NSString *
                NSString *content = announcement[@"content"];  // 公告内容，类型 NSString *
                NSLog(@"公告: title=%@, content=%@", title, content);
            }
        }
    }];

# ==================== 获取临时公告 ====================
get_temp_notice:
  method_name: "[[RXSDK sharedSDK] getTempNotice:]"
  description: 获取临时公告
  parameters:
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取临时公告 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    [[RXSDK sharedSDK] getTempNotice:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取临时公告失败: %@", error.responesObject);
        } else {
            NSDictionary *data = response[@"data"];  // 类型 NSDictionary *
            if (data && data.count > 0) {
                NSString *title = data[@"title"];      // 公告标题，类型 NSString *
                NSString *content = data[@"content"];  // 公告内容，类型 NSString *
                NSLog(@"临时公告: %@ - %@", title, content);
                // TODO: 展示临时公告
            }
        }
    }];

# ==================== 获取本地公告缓存 ====================
get_local_announcement:
  method_name: "[[RXSDK sharedSDK] getLocalAnnouncement]"
  description: 获取当前本地保存的全量公告
  return_type: NSArray *
  code_objc: |
    // ========== 瑞雪 SDK 获取本地公告缓存 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSArray *announcements = [[RXSDK sharedSDK] getLocalAnnouncement];
    NSLog(@"本地公告缓存: %@", announcements);

# ==================== 获取本地公告已读记录 ====================
get_local_announcement_read_list:
  method_name: "[[RXSDK sharedSDK] getLocalAnnouncementReadList]"
  description: 获取本地公告是否已读记录
  return_type: NSDictionary *
  code_objc: |
    // ========== 瑞雪 SDK 获取本地公告已读记录 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSDictionary *readList = [[RXSDK sharedSDK] getLocalAnnouncementReadList];
    NSLog(@"本地公告已读记录: %@", readList);

# ==================== 同步公告已读记录到本地 ====================
sync_local_announcement_record:
  method_name: "[[RXSDK sharedSDK] syncLocalAnnouncementRecord:]"
  description: 同步公告是否已读记录到本地
  parameters:
    - name: dict
      type: NSDictionary *
      required: true
      description: 公告已读记录
  code_objc: |
    // ========== 瑞雪 SDK 同步公告已读记录 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSDictionary *record = @{
        @"announcement_id": @(YES)
    };

    [[RXSDK sharedSDK] syncLocalAnnouncementRecord:record];

# ==================== 保存公告数据与已读记录 ====================
get_local_announcement_and_set_record:
  method_name: "[[RXSDK sharedSDK] getLocalAnnouncementAndSetReadOrNotRecord]"
  description: 保存全量公告数据以及本地是否已读未读记录
  code_objc: |
    // ========== 瑞雪 SDK 保存公告数据与已读记录 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    [[RXSDK sharedSDK] getLocalAnnouncementAndSetReadOrNotRecord];

# ==================== 获取邮件列表 ====================
get_email_list:
  method_name: "[[RXSDK sharedSDK] getEmailListWithCpUserID:complete:]"
  description: 获取邮件列表
  parameters:
    - name: cpUserID
      type: NSString *
      required: true
      description: 游戏用户 ID
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取邮件列表 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *cpUserID = @"cp_user_001";  // 必填，游戏用户 ID，类型 NSString *
    
    [[RXSDK sharedSDK] getEmailListWithCpUserID:cpUserID
                                       complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取邮件列表失败: %@", error.responesObject);
        } else {
            NSArray *list = response[@"data"][@"list"];  // 类型 NSArray *
            for (NSDictionary *email in list) {
                NSString *emailId = email[@"id"];       // 邮件 ID，类型 NSString *
                NSString *title = email[@"title"];      // 邮件标题，类型 NSString *
                NSString *hasGift = email[@"has_gift"]; // 是否有礼物，类型 NSString *
                NSLog(@"邮件: id=%@, title=%@, hasGift=%@", emailId, title, hasGift);
            }
        }
    }];

# ==================== 获取邮件详情 ====================
get_email_detail:
  method_name: "[[RXSDK sharedSDK] getEmailDetailWithCpUserID:emailID:complete:]"
  description: 获取邮件详情
  parameters:
    - name: cpUserID
      type: NSString *
      required: true
      description: 游戏用户 ID
    - name: emailID
      type: NSInteger
      required: true
      description: 邮件 ID
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取邮件详情 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *cpUserID = @"cp_user_001";  // 必填，游戏用户 ID，类型 NSString *
    NSInteger emailID = 12345;             // 必填，邮件 ID，类型 NSInteger
    
    [[RXSDK sharedSDK] getEmailDetailWithCpUserID:cpUserID
                                          emailID:emailID
                                         complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取邮件详情失败: %@", error.responesObject);
        } else {
            NSDictionary *data = response[@"data"];  // 类型 NSDictionary *
            NSLog(@"邮件详情: %@", data);
        }
    }];

# ==================== 领取道具 ====================
receive_props:
  method_name: "[[RXSDK sharedSDK] receivePropsWithCpUserID:type:emailID:complete:]"
  description: 领取邮件中的道具
  parameters:
    - name: cpUserID
      type: NSString *
      required: true
      description: 游戏用户 ID
    - name: type
      type: NSInteger
      required: true
      description: 1 领取当前，2 一键领取所有
    - name: emailID
      type: NSInteger
      required: true
      description: 邮件 ID（type=2 时可传 0）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 领取道具 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // ========== 领取单封邮件的道具 ==========
    NSString *cpUserID = @"cp_user_001";  // 必填，游戏用户 ID，类型 NSString *
    NSInteger type = 1;                    // 必填，1 领取当前 2 一键领取所有，类型 NSInteger
    NSInteger emailID = 12345;             // 必填，邮件 ID（type=2 时可传 0），类型 NSInteger
    
    [[RXSDK sharedSDK] receivePropsWithCpUserID:cpUserID
                                           type:type
                                        emailID:emailID
                                       complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"领取道具失败: %@", error.responesObject);
        } else {
            NSLog(@"领取道具成功: %@", response);
        }
    }];
    
    // ========== 一键领取所有道具 ==========
    [[RXSDK sharedSDK] receivePropsWithCpUserID:cpUserID
                                           type:2  // 2 一键领取所有，类型 NSInteger
                                        emailID:0
                                       complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"一键领取失败: %@", error.responesObject);
        } else {
            NSLog(@"一键领取成功: %@", response);
        }
    }];

# ==================== 删除邮件 ====================
delete_email:
  method_name: "[[RXSDK sharedSDK] deleteEmailWithCpUserID:type:emailID:complete:]"
  description: 删除邮件
  parameters:
    - name: cpUserID
      type: NSString *
      required: true
      description: 游戏用户 ID
    - name: type
      type: NSInteger
      required: true
      description: 1 删除当前，2 一键删除所有
    - name: emailID
      type: NSInteger
      required: true
      description: 邮件 ID（type=2 时可传 0）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 删除邮件 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *cpUserID = @"cp_user_001";  // 必填，游戏用户 ID，类型 NSString *
    NSInteger type = 1;                    // 必填，1 删除当前 2 一键删除所有，类型 NSInteger
    NSInteger emailID = 12345;             // 必填，邮件 ID（type=2 时可传 0），类型 NSInteger
    
    [[RXSDK sharedSDK] deleteEmailWithCpUserID:cpUserID
                                          type:type
                                       emailID:emailID
                                      complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"删除邮件失败: %@", error.responesObject);
        } else {
            NSLog(@"删除邮件成功");
        }
    }];
