# 瑞雪 SDK iOS RXASAKit（Apple Search Ads）组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: Apple Search Ads 归因数据获取组件
  keywords:
    - ASA
  note: |
    1. ASA 组件是可选组件，需要根据业务需求选择接入
    2. 组件初始化必须在瑞雪 SDK 初始化之前执行
    3. 用于获取 Apple Search Ads 广告归因数据

# ==================== 组件信息 ====================
component:
  name: RXASAKit（Apple Search Ads）
  pod_name: RXASAKit
  service_class: RXASAService
  singleton: sharedSDK
  import: "#import <RXASAKit/RXASAService.h>"
  description: Apple Search Ads 归因数据获取组件

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== RXASAKit（Apple Search Ads）组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXASAKit'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 接入步骤 ====================
setup_steps:
  - step: 1
    title: 添加 Pod 依赖
    description: 在 Podfile 中添加 ASA 组件
    code: |
      # Podfile
      target 'YourApp' do
        use_frameworks!
        
        # 瑞雪 SDK ASA 组件（Apple Search Ads）
        pod 'RXASAKit'
      end
  
  - step: 2
    title: 执行 Pod Install
    description: 在终端中执行 pod install
    code: |
      cd /path/to/your/project
      pod install
  
  - step: 3
    title: 初始化配置
    description: 在瑞雪 SDK 初始化之前调用注册方法

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXASAService sharedSDK] regist]"
  description: 注册 ASA 组件
  parameters: []
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - ASA（Apple Search Ads）接入 ==========
  #import <RXASAKit/RXASAService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  #import <RXUIKit/RXUIKitService.h>  // 国内 UI 组件（或 RXOSUIKit 海外版）
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】注册 ASA 组件
      [[RXASAService sharedSDK] regist];
      
      // 2. 创建瑞雪 SDK 初始化配置
      RXSdkInitConfig *config = [[RXSdkInitConfig alloc] init];
      config.cpId = @"YOUR_CP_ID";
      config.productId = @"YOUR_PRODUCT_ID";
      config.channelId = @"YOUR_CHANNEL_ID";
      config.baseUrlList = @[@"https://api.example.com/"];
      config.launchOptions = launchOptions;
      
      // 3. 初始化瑞雪 SDK
      [[RXSDK sharedSDK] initWithConfig:config complete:^(NSDictionary *response, RX_CommonRequestError *error) {
          if (error) {
              NSLog(@"SDK 初始化失败: %@", error.responesObject);
              return;
          }
          NSLog(@"SDK 初始化成功: %@", response);
          
          // 4. 初始化 UI 组件（在 SDK 初始化成功后）
          [[RXUIKitService sharedSDK] regist];
      }];
      
      return YES;
  }

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: ASA 组件初始化代码必须放在瑞雪 SDK 初始化之前
  - title: 调用时机
    content: 在 application:didFinishLaunchingWithOptions: 中尽早调用
  - title: 组件独立
    content: ASA 组件独立运行，无需额外配置参数
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
  - title: 平台限制
    content: Apple Search Ads 归因仅适用于 iOS 平台
