# 瑞雪 SDK iOS 广告投放（字节/巨量广告）组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: 广告投放组件，用于对接字节跳动/巨量引擎广告归因和转化追踪
  keywords:
    - 广告投放
    - 头条
    - 字节
    - 巨量广告
  note: |
    1. 广告投放组件是可选组件，需要根据业务需求选择接入
    2. 组件初始化必须在瑞雪 SDK 初始化之前执行
    3. 用于广告归因、转化事件上报等功能

# ==================== 组件信息 ====================
component:
  name: 广告投放（字节/巨量广告）
  pod_name: RXBDASignalSDK
  service_class: RXBDAsignalService
  singleton: sharedSDK
  import: "#import <RXBDASignalSDK/RXBDAsignalService.h>"
  description: 字节跳动/巨量引擎广告投放组件，提供广告归因和转化追踪功能

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== 广告投放（字节/巨量广告）组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXBDASignalSDK'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 接入步骤 ====================
setup_steps:
  - step: 1
    title: 添加 Pod 依赖
    description: 在 Podfile 中添加广告投放组件
    code: |
      # Podfile
      target 'YourApp' do
        use_frameworks!
        
        # 瑞雪 SDK 广告投放组件（字节/巨量广告）
        pod 'RXBDASignalSDK'
      end
  
  - step: 2
    title: 执行 Pod Install
    description: 在终端中执行 pod install
    code: |
      cd /path/to/your/project
      pod install
  
  - step: 3
    title: 初始化配置
    description: 在瑞雪 SDK 初始化之前调用注册方法

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXBDAsignalService sharedSDK] regist]"
  description: 注册广告投放组件
  parameters: []
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - 广告投放（字节/巨量广告）接入 ==========
  #import <RXBDASignalSDK/RXBDAsignalService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  #import <RXUIKit/RXUIKitService.h>  // 国内 UI 组件（或 RXOSUIKit 海外版）
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】注册广告投放组件
      [[RXBDAsignalService sharedSDK] regist];
      
      // 2. 【必须在瑞雪 SDK 初始化之前】初始化 UI 组件
      [[RXUIKitService sharedSDK] regist];
      
      // 3. 创建瑞雪 SDK 初始化配置
      RXSdkInitConfig *config = [[RXSdkInitConfig alloc] init];
      config.cpId = @"YOUR_CP_ID";
      config.productId = @"YOUR_PRODUCT_ID";
      config.channelId = @"YOUR_CHANNEL_ID";
      config.baseUrlList = @[@"https://api.example.com/"];
      config.launchOptions = launchOptions;
      
      // 4. 初始化瑞雪 SDK
      [[RXSDK sharedSDK] initWithConfig:config complete:^(NSDictionary *response, RX_CommonRequestError *error) {
          if (error) {
              NSLog(@"SDK 初始化失败: %@", error.responesObject);
          } else {
              NSLog(@"SDK 初始化成功: %@", response);
          }
      }];
      
      return YES;
  }

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: 广告投放组件初始化代码必须放在瑞雪 SDK 初始化之前
  - title: 调用时机
    content: 在 application:didFinishLaunchingWithOptions: 中尽早调用
  - title: 组件独立
    content: 广告投放组件独立运行，无需额外配置参数
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
  - title: 广告平台
    content: 此组件对接字节跳动/巨量引擎广告平台，用于广告归因和转化追踪
