# 瑞雪 SDK iOS 验证码功能
# Generated by MCP
# 包含：发送验证码、校验验证码、图形验证

# ==================== 发送验证码 ====================
send_captcha:
  method_name: "[[RXSDK sharedSDK] sendCaptchaWithType:target:purpose:complete:]"
  description: 发送验证码（手机或邮箱）
  parameters:
    - name: type
      type: CaptchaType
      required: true
      description: 验证码类型（CaptchaType_email 邮箱、CaptchaType_phone 手机）
    - name: target
      type: NSString *
      required: true
      description: 发送目标（手机号或邮箱）
    - name: purpose
      type: NSString *
      required: true
      description: 用途（register/login/bindphone/unbindphone/resetpwd/changepwd/bindemail/unbindemail）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 发送验证码 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // ========== 发送手机验证码 ==========
    // purpose 用途说明:
    //   - register: 注册
    //   - login: 登录
    //   - bindphone: 绑定手机
    //   - unbindphone: 解绑手机
    //   - resetpwd: 重置密码
    //   - changepwd: 修改密码
    //   - setpwd: 设置密码
    
    NSString *phone = @"xxxxxx";         // 必填，手机号，类型 NSString *
    NSString *purpose = @"login";        // 必填，用途，类型 NSString *
    
    [[RXSDK sharedSDK] sendCaptchaWithType:CaptchaType_phone  // 类型 CaptchaType
                                    target:phone
                                   purpose:purpose
                                  complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"发送验证码失败: %@", error.responesObject);
        } else {
            NSLog(@"发送验证码成功: %@", response);
            // TODO: 开始倒计时
        }
    }];
    
    // ========== 发送邮箱验证码 ==========
    // purpose 用途说明:
    //   - bindemail: 绑定邮箱
    //   - unbindemail: 解绑邮箱
    
    NSString *email = @"xxxxxx";   // 必填，邮箱地址，类型 NSString *
    NSString *emailPurpose = @"bindemail";   // 必填，用途，类型 NSString *
    
    [[RXSDK sharedSDK] sendCaptchaWithType:CaptchaType_email  // 类型 CaptchaType
                                    target:email
                                   purpose:emailPurpose
                                  complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"发送邮箱验证码失败: %@", error.responesObject);
        } else {
            NSLog(@"发送邮箱验证码成功: %@", response);
        }
    }];

# ==================== 发送验证码（带图形验证） ====================
send_captcha_with_ticket:
  method_name: "[[RXSDK sharedSDK] sendCaptchaWithType:target:purpose:ticket:randstr:complete:]"
  description: 发送验证码（带图形验证凭证）
  parameters:
    - name: type
      type: CaptchaType
      required: true
      description: 验证码类型
    - name: target
      type: NSString *
      required: true
      description: 发送目标
    - name: purpose
      type: NSString *
      required: true
      description: 用途
    - name: ticket
      type: NSString *
      required: false
      description: 图形验证凭证
    - name: randstr
      type: NSString *
      required: false
      description: 图形验证随机串
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 发送验证码（带图形验证） ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *phone = @"xxxxxx";   // 必填，手机号，类型 NSString *
    NSString *purpose = @"login";        // 必填，用途，类型 NSString *
    NSString *ticket = @"图形验证凭证";  // 可选，图形验证凭证，类型 NSString *
    NSString *randstr = @"随机串";       // 可选，图形验证随机串，类型 NSString *
    
    [[RXSDK sharedSDK] sendCaptchaWithType:CaptchaType_phone
                                    target:phone
                                   purpose:purpose
                                    ticket:ticket
                                   randstr:randstr
                                  complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"发送验证码失败: %@", error.responesObject);
        } else {
            NSLog(@"发送验证码成功: %@", response);
        }
    }];

# ==================== 校验验证码 ====================
verify_captcha:
  method_name: "[[RXSDK sharedSDK] verifyCaptchaWithType:target:purpose:captchaCode:complete:]"
  description: 校验验证码
  parameters:
    - name: type
      type: CaptchaType
      required: true
      description: 验证码类型
    - name: target
      type: NSString *
      required: true
      description: 发送目标
    - name: purpose
      type: NSString *
      required: true
      description: 用途
    - name: captchaCode
      type: NSString *
      required: true
      description: 用户输入的验证码
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 校验验证码 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // ========== 校验手机验证码 ==========
    // purpose 用途说明:
    //   - register: 注册
    //   - login: 登录
    //   - bindphone: 绑定手机
    //   - unbindphone: 解绑手机
    //   - resetpwd: 重置密码
    //   - changepwd: 修改密码
    //   - setpwd: 设置密码
    
    NSString *phone = @"xxxxxx";         // 必填，手机号，类型 NSString *
    NSString *captchaCode = @"xxxxxx";   // 必填，用户输入的验证码，类型 NSString *
    NSString *purpose = @"login";        // 必填，用途，类型 NSString *
    
    [[RXSDK sharedSDK] verifyCaptchaWithType:CaptchaType_phone
                                      target:phone
                                     purpose:purpose
                                 captchaCode:captchaCode
                                    complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"验证码校验失败: %@", error.responesObject);
        } else {
            NSLog(@"验证码校验成功: %@", response);
            // TODO: 继续后续操作（注册、重置密码等）
        }
    }];
    
    // ========== 校验邮箱验证码 ==========
    // purpose 用途说明:
    //   - bindemail: 绑定邮箱
    //   - unbindemail: 解绑邮箱
    
    NSString *email = @"xxxxxx";             // 必填，邮箱，类型 NSString *
    NSString *emailCaptcha = @"xxxxxx";      // 必填，验证码，类型 NSString *
    NSString *emailPurpose = @"bindemail";   // 必填，用途，类型 NSString *
    
    [[RXSDK sharedSDK] verifyCaptchaWithType:CaptchaType_email
                                      target:email
                                     purpose:emailPurpose
                                 captchaCode:emailCaptcha
                                    complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"邮箱验证码校验失败: %@", error.responesObject);
        } else {
            NSLog(@"邮箱验证码校验成功: %@", response);
        }
    }];

# ==================== 图形验证 UI ====================
captcha_verify_ui:
  method_name: "[[RXSDK sharedSDK] captchaVerifyUIWithAppid:complete:]"
  description: 弹出图形验证 UI
  parameters:
    - name: appid
      type: NSString *
      required: true
      description: 图形验证码 appid
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调（返回 ticket 和 randstr）
  code_objc: |
    // ========== 瑞雪 SDK 图形验证 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *appid = @"图形验证码 appid";  // 必填，从后台获取，类型 NSString *
    
    [[RXSDK sharedSDK] captchaVerifyUIWithAppid:appid
                                       complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"图形验证失败: %@", error.responesObject);
        } else {
            // 获取图形验证凭证
            NSString *ticket = response[@"ticket"];    // 类型 NSString *
            NSString *randstr = response[@"randstr"];  // 类型 NSString *
            
            NSLog(@"图形验证成功: ticket=%@, randstr=%@", ticket, randstr);
            
            // TODO: 使用 ticket 和 randstr 发送短信验证码
        }
    }];
