# 瑞雪 SDK 账号注销 UI 功能
# Generated by MCP
# 包含：申请注销UI、撤销注销UI

# ==================== 申请注销 UI ====================
# 注意：iOS 申请注销使用 API 接口，不是 UI 组件
# 参见 deregister.tpl 中的 deregisterWithConfig

# ==================== 撤销注销 UI ====================
destroyAccountStatusViewWithDeregisterType:
  method_name: "[[RXUIKitService sharedSDK] destroyAccountStatusViewWithDeregisterType:complete:]"
  description: 撤销注销弹窗
  parameters:
    - name: deregisterType
      type: NSString *
      required: true
      description: 注销类型（login 继续登录，logout 退出登录）
    - name: complete
      type: void(^)(DestroyClickType clickType)
      required: true
      description: 点击回调
  code: |
    // ========== 瑞雪 SDK 撤销注销弹窗 ==========
    // 注意：需要添加 pod 依赖 pod 'RXUIKit'
    
    #import <RXUIKit/RXUIKitService.h>
    
    // deregisterType: @"login" 继续登录，@"logout" 退出登录
    NSString *deregisterType = @"login";
    
    [[RXUIKitService sharedSDK] destroyAccountStatusViewWithDeregisterType:deregisterType complete:^(DestroyClickType clickType) {
        if (clickType == DestroyClickType_login) {
            NSLog(@"用户选择继续登录");
            // TODO: 处理继续登录逻辑
        } else if (clickType == DestroyClickType_logout) {
            NSLog(@"用户选择退出登录");
            // TODO: 处理退出登录逻辑
        }
    }];

# ==================== 撤销注销 UI（自定义按钮文本） ====================
destroyAccountStatusViewWithBtnTitle:
  method_name: "[[RXUIKitService sharedSDK] destroyAccountStatusViewWithBtnTitle:complete:]"
  description: 撤销注销弹窗（自定义按钮文本）
  parameters:
    - name: btnTitle
      type: NSString *
      required: true
      description: 按钮标题
    - name: complete
      type: void(^)(NSString *btnTitle)
      required: true
      description: 点击回调
  code: |
    // ========== 瑞雪 SDK 撤销注销弹窗（自定义按钮） ==========
    
    NSString *btnTitle = @"继续使用";
    
    [[RXUIKitService sharedSDK] destroyAccountStatusViewWithBtnTitle:btnTitle complete:^(NSString *btnTitle) {
        if ([btnTitle isEqualToString:@"撤销注销"]) {
            NSLog(@"撤销注销成功");
        } else {
            NSLog(@"用户点击: %@", btnTitle);
        }
    }];

# DestroyClickType 枚举
destroy_click_type:
  - name: DestroyClickType_login
    description: 继续登录
  - name: DestroyClickType_logout
    description: 退出登录

# 导入语句
imports:
  - "#import <RXUIKit/RXUIKitService.h>"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    pod_name: "RXUIKit"
    description: 账号注销 UI 需要添加此 pod 依赖
