# 瑞雪 SDK iOS 设备信息功能
# Generated by MCP
# 包含：设备码、时区、语言、IDFA

# ==================== 获取设备码 ====================
get_device_code:
  method_name: "[[RXSDK sharedSDK] getDeviceCode]"
  description: 获取设备码
  code_objc: |
    // ========== 瑞雪 SDK 获取设备码 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *deviceCode = [[RXSDK sharedSDK] getDeviceCode];  // 类型 NSString *
    NSLog(@"设备码: %@", deviceCode);

# ==================== 获取时区偏移 ====================
get_timezone_offset:
  method_name: "[[RXSDK sharedSDK] getTimeZoneOffset]"
  description: 获取当前时区与 UTC 时差
  code_objc: |
    // ========== 瑞雪 SDK 获取时区偏移 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *offset = [[RXSDK sharedSDK] getTimeZoneOffset];  // 类型 NSString *
    NSLog(@"时区偏移: %@", offset);

# ==================== 获取系统语言 ====================
get_system_language:
  method_name: "[[RXSDK sharedSDK] getSystemLanguage]"
  description: 获取当前手机语言
  code_objc: |
    // ========== 瑞雪 SDK 获取系统语言 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *language = [[RXSDK sharedSDK] getSystemLanguage];  // 类型 NSString *
    NSLog(@"系统语言: %@", language);

# ==================== 获取 IDFA ====================
get_idfa:
  method_name: "[RXSDK getIDFA]"
  description: 获取 IDFA（广告标识符）
  code_objc: |
    // ========== 瑞雪 SDK 获取 IDFA ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 注意：iOS 14+ 需要用户授权 ATT
    
    NSString *idfa = [RXSDK getIDFA];  // 类型 NSString *
    NSLog(@"IDFA: %@", idfa);

# ==================== 获取当前请求域名 ====================
get_api_domain:
  method_name: "[[RXSDK sharedSDK] getApiDomain]"
  description: 获取当前请求域名
  code_objc: |
    // ========== 瑞雪 SDK 获取当前请求域名 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *domain = [[RXSDK sharedSDK] getApiDomain];  // 类型 NSString *
    NSLog(@"当前请求域名: %@", domain);

# ==================== 获取配置数据 ====================
get_config_data:
  method_name: "[[RXSDK sharedSDK] getConfigData]"
  description: 获取配置数据
  code_objc: |
    // ========== 瑞雪 SDK 获取配置数据 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSDictionary *config = [[RXSDK sharedSDK] getConfigData];  // 类型 NSDictionary *
    NSLog(@"配置数据: %@", config);

# ==================== 获取广告信息 ====================
get_ad_info:
  method_name: "[[RXSDK sharedSDK] getAdInfo]"
  description: 获取广告信息
  code_objc: |
    // ========== 瑞雪 SDK 获取广告信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSDictionary *adInfo = [[RXSDK sharedSDK] getAdInfo];  // 类型 NSDictionary *
    NSLog(@"广告信息: %@", adInfo);

# ==================== 清空广告信息 ====================
delete_ad_info:
  method_name: "[[RXSDK sharedSDK] deleteAdInfo]"
  description: 清空广告信息
  code_objc: |
    // ========== 瑞雪 SDK 清空广告信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    [[RXSDK sharedSDK] deleteAdInfo];
    NSLog(@"广告信息已清空");

# ==================== 设置当前语言 ====================
set_language:
  method_name: "[[RXSDK sharedSDK] setLanguage:]"
  description: 设置当前语言
  parameters:
    - name: language
      type: NSString *
      required: true
      description: 语言码（如 en、zh-Hans）
  code_objc: |
    // ========== 瑞雪 SDK 设置当前语言 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *language = @"zh-Hans";  // 必填，语言码（如 en、zh-Hans、ja 等），类型 NSString *
    [[RXSDK sharedSDK] setLanguage:language];
    NSLog(@"已设置语言: %@", language);

# ==================== 设置当前地区 ====================
set_area:
  method_name: "[[RXSDK sharedSDK] setArea:]"
  description: 设置当前地区
  parameters:
    - name: area
      type: NSString *
      required: true
      description: 地区码
  code_objc: |
    // ========== 瑞雪 SDK 设置当前地区 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *area = @"CN";  // 必填，地区码（如 CN、US、JP 等），类型 NSString *
    [[RXSDK sharedSDK] setArea:area];
    NSLog(@"已设置地区: %@", area);

# ==================== 设置子渠道 ID ====================
set_sub_channel_id:
  method_name: "[[RXSDK sharedSDK] setSubChannelId:]"
  description: 设置子渠道 ID
  parameters:
    - name: subChannelId
      type: NSString *
      required: true
      description: 子渠道 ID
  code_objc: |
    // ========== 瑞雪 SDK 设置子渠道 ID ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *subChannelId = @"sub_channel_001";  // 必填，子渠道 ID，类型 NSString *
    [[RXSDK sharedSDK] setSubChannelId:subChannelId];
    NSLog(@"已设置子渠道 ID: %@", subChannelId);

# ==================== 设置游戏角色信息 ====================
set_game_info:
  method_name: "[[RXSDK sharedSDK] setGameInfoWithRoleId:regionTag:]"
  description: 设置游戏角色信息
  parameters:
    - name: roleId
      type: NSString *
      required: true
      description: 游戏角色 ID
    - name: regionTag
      type: NSString *
      required: true
      description: 区服信息
  code_objc: |
    // ========== 瑞雪 SDK 设置游戏角色信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *roleId = @"role_001";     // 必填，游戏角色 ID，类型 NSString *
    NSString *regionTag = @"server_1";  // 必填，区服信息，类型 NSString *
    
    [[RXSDK sharedSDK] setGameInfoWithRoleId:roleId regionTag:regionTag];
    NSLog(@"已设置游戏信息: roleId=%@, regionTag=%@", roleId, regionTag);

# ==================== 获取 OpenID ====================
get_openid:
  method_name: "[[RXSDK sharedSDK] getOpenID]"
  description: 获取当前登录用户的 OpenID
  code_objc: |
    // ========== 瑞雪 SDK 获取 OpenID ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *openId = [[RXSDK sharedSDK] getOpenID];  // 类型 NSString *
    NSLog(@"当前 OpenID: %@", openId);

# ==================== 获取当前 baseUrl ====================
get_first_base_url:
  method_name: "[[RXSDK sharedSDK] getFirstBaseUrl]"
  description: 获取当前 baseUrl
  code_objc: |
    // ========== 瑞雪 SDK 获取当前 baseUrl ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *baseUrl = [[RXSDK sharedSDK] getFirstBaseUrl];  // 类型 NSString *
    NSLog(@"当前 baseUrl: %@", baseUrl);

# ==================== 获取启动参数 ====================
get_launch_options:
  method_name: "[[RXSDK sharedSDK] getLaunchOptions]"
  description: 获取启动参数
  code_objc: |
    // ========== 瑞雪 SDK 获取启动参数 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSDictionary *launchOptions = [[RXSDK sharedSDK] getLaunchOptions];  // 类型 NSDictionary *
    NSLog(@"启动参数: %@", launchOptions);

# ==================== 获取启动参数（SceneDelegate） ====================
get_connect_options:
  method_name: "[[RXSDK sharedSDK] getConnectOptions]"
  description: 获取启动参数（SceneDelegate）
  code_objc: |
    // ========== 瑞雪 SDK 获取启动参数（SceneDelegate） ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 注意：用于 iOS 13+ 的 SceneDelegate 场景
    
    UISceneConnectionOptions *connectOptions = [[RXSDK sharedSDK] getConnectOptions];  // 类型 UISceneConnectionOptions *
    NSLog(@"SceneDelegate 启动参数: %@", connectOptions);

# ==================== 设置自定义错误码信息 ====================
config_error_msg:
  method_name: "[[RXSDK sharedSDK] configErrorMsg:]"
  description: 设置自定义错误码信息
  parameters:
    - name: msgDic
      type: NSDictionary *
      required: true
      description: 错误码字典（语言 -> 错误码 -> 消息模板）
  code_objc: |
    // ========== 瑞雪 SDK 设置自定义错误码 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 中文错误消息
    NSDictionary *zh = @{
        @"2002": @"自定义消息 $code$$thirdcode$$thirdmsg$",
        @"2000": @"",
        @"default": @"$msg$:$code$"
    };
    
    // 英文错误消息
    NSDictionary *en = @{
        @"2002": @"custom error $code$$thirdcode$$thirdmsg$",
        @"2000": @"error demo ",
        @"default": @"$msg$:$code$"
    };
    
    NSDictionary *errorMsgDic = @{
        @"zh": zh,
        @"en": en
    };
    
    [[RXSDK sharedSDK] configErrorMsg:errorMsgDic];
    NSLog(@"已设置自定义错误码");

# ==================== 设置商品 ID 和超时时间 ====================
set_iap_product_id:
  method_name: "[[RXSDK sharedSDK] setIAPProductId:timeout:]"
  description: 设置商品 ID 和超时时间
  parameters:
    - name: productId
      type: NSString *
      required: true
      description: 商品 ID
    - name: timeout
      type: NSInteger
      required: true
      description: 超时时间
  code_objc: |
    // ========== 瑞雪 SDK 设置商品 ID 和超时时间 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *productId = @"com.game.product001";  // 必填，商品 ID，类型 NSString *
    NSInteger timeout = 30;                         // 必填，超时时间（秒），类型 NSInteger
    
    [[RXSDK sharedSDK] setIAPProductId:productId timeout:timeout];
    NSLog(@"已设置商品 ID: %@, 超时时间: %ld", productId, (long)timeout);
