# 瑞雪 SDK iOS Facebook 组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: Facebook 登录和分享组件
  keywords:
    - facebook
    - Facebook 登录
    - Facebook 分享
  note: |
    1. Facebook 组件是可选组件，需要根据业务需求选择接入
    2. 需要在 Info.plist 中配置 FacebookAppID、FacebookClientToken、LSApplicationQueriesSchemes、URL Types
    3. 组件注册必须在瑞雪 SDK 初始化之前执行
    4. 提供 Facebook 登录和分享功能

# ==================== 组件信息 ====================
component:
  name: Facebook
  pod_name: RXFacebookSDK
  service_class: RXFacebookService
  singleton: sharedSDK
  import: "#import <RXFacebookSDK/RXFacebookService.h>"
  description: Facebook 登录和分享组件

# ==================== 工程配置 ====================
project_config:
  info_plist:
    - key: FacebookAppID
      type: String
      required: true
      description: Facebook App ID，从 Facebook 开发者后台获取
    - key: FacebookClientToken
      type: String
      required: true
      description: Facebook Client Token，从 Facebook 开发者后台获取
  ls_application_queries_schemes:
    - fbapi
    - fb-messenger-share-api
  url_types:
    - scheme: fb{FacebookAppID}
      required: true
      description: Facebook URL Scheme，格式为 fb + App ID

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== Facebook 组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXFacebookSDK'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 接入步骤 ====================
setup_steps:
  - step: 1
    title: 添加 Pod 依赖
    description: 在 Podfile 中添加 Facebook 组件
    code: |
      # Podfile
      target 'YourApp' do
        use_frameworks!
        
        # 瑞雪 SDK Facebook 组件
        pod 'RXFacebookSDK'
      end
  
  - step: 2
    title: 执行 Pod Install
    description: 在终端中执行 pod install
    code: |
      cd /path/to/your/project
      pod install

  - step: 3
    title: 配置 Info.plist
    description: 添加 FacebookAppID、FacebookClientToken、LSApplicationQueriesSchemes、URL Types（自动完成）

  - step: 4
    title: 初始化代码
    description: 在瑞雪 SDK 初始化之前调用注册方法

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXFacebookService sharedSDK] FBRegistWithApplication:launchOptions:]"
  description: 注册 Facebook 组件
  parameters:
    - name: application
      type: UIApplication *
      required: true
      description: UIApplication 实例
    - name: launchOptions
      type: NSDictionary *
      required: true
      description: 启动参数
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 方法签名 ====================

# --- 注册 ---
FBRegistWithApplication:
  method_name: "[[RXFacebookService sharedSDK] FBRegistWithApplication:launchOptions:]"
  description: 注册 Facebook（在 AppDelegate 中调用）
  parameters:
    - name: application
      type: UIApplication *
      required: true
    - name: launchOptions
      type: NSDictionary *
      required: true

# --- 登录 ---
FBLoginWithPermissions:
  method_name: "[[RXFacebookService sharedSDK] FBLoginWithPermissions:extDic:migrate_args:sign_fields:]"
  description: Facebook 登录
  parameters:
    - name: permissions
      type: NSArray *
      required: true
      description: 权限列表（如 public_profile、email）
    - name: extDic
      type: NSMutableDictionary *
      required: false
      description: 扩展字段
    - name: migrate_args
      type: id
      required: false
      description: 账号迁移参数
    - name: sign_fields
      type: NSArray *
      required: false
      description: 签名字段
  code_objc: |
    [[RXFacebookService sharedSDK] FBLoginWithPermissions:@[@"public_profile", @"email"]
                                                   extDic:nil
                                             migrate_args:nil
                                              sign_fields:@[@"nickname", @"avatar"]];

# --- 退出登录 ---
FBLogout:
  method_name: "[[RXFacebookService sharedSDK] FBLogout]"
  description: Facebook 退出登录
  parameters: []

# --- 分享 ---
FBShareWithContent:
  method_name: "[[RXFacebookService sharedSDK] FBShareWithContent:mode:complete:]"
  description: Facebook 分享
  parameters:
    - name: content
      type: id
      required: true
      description: 分享内容
    - name: mode
      type: NSInteger
      required: true
      description: 分享样式（0-弹框 1-跳转 FB app）
    - name: complete
      type: block
      required: true
      description: 结果回调
  code_objc: |
    [[RXFacebookService sharedSDK] FBShareWithContent:shareContent
                                                 mode:0
                                             complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        NSLog(@"分享结果: %@", response);
    }];

# --- URL 处理 ---
FBApplication:
  method_name: "[[RXFacebookService sharedSDK] FBApplication:openURL:options:]"
  description: 处理 Facebook URL 回调
  parameters:
    - name: application
      type: UIApplication *
      required: true
    - name: url
      type: NSURL *
      required: true
    - name: options
      type: NSDictionary *
      required: true

# ==================== 完整代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - Facebook 接入 ==========
  #import <RXFacebookSDK/RXFacebookService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】注册 Facebook
      [[RXFacebookService sharedSDK] FBRegistWithApplication:application
                                               launchOptions:launchOptions];
      
      // 2. 初始化瑞雪 SDK...
      // [[RXSDK sharedSDK] initWithConfig:config complete:...];
      
      return YES;
  }
  
  // ========== URL Scheme 回调 ==========
  - (BOOL)application:(UIApplication *)app 
              openURL:(NSURL *)url 
              options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
      // 处理 Facebook 回调
      [[RXFacebookService sharedSDK] FBApplication:app openURL:url options:options];
      [[RXSDK sharedSDK] application:app openURL:url options:options];
      return YES;
  }
  
  // ========== Facebook 登录 ==========
  [[RXFacebookService sharedSDK] FBLoginWithPermissions:@[@"public_profile", @"email"]
                                                 extDic:nil
                                           migrate_args:nil
                                            sign_fields:@[@"nickname", @"avatar"]];
  
  // ========== Facebook 退出登录 ==========
  [[RXFacebookService sharedSDK] FBLogout];
  
  // ========== Facebook 分享 ==========
  [[RXFacebookService sharedSDK] FBShareWithContent:shareContent
                                               mode:0
                                           complete:^(NSDictionary *response, RX_CommonRequestError *error) {
      NSLog(@"分享结果: %@", response);
  }];

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: FBRegistWithApplication 必须在瑞雪 SDK 初始化之前调用
  - title: FacebookAppID
    content: 必须在 Info.plist 中配置 FacebookAppID，值从 Facebook 开发者后台获取
  - title: FacebookClientToken
    content: 必须在 Info.plist 中配置 FacebookClientToken，值从 Facebook 开发者后台获取
  - title: URL Types
    content: URL Types 中添加 fb{AppID} 格式的 Scheme
  - title: LSApplicationQueriesSchemes
    content: 必须添加 fbapi 和 fb-messenger-share-api
  - title: URL 回调
    content: 必须在 application:openURL:options: 中调用 FBApplication:openURL:options:
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
