# 瑞雪 SDK iOS 好友管理功能
# Generated by MCP
# 包含：添加好友、删除好友、更新好友备注、判断是否好友、获取好友列表

# ==================== 添加好友 ====================
addFriend:
  method_name: "[[RXSDK sharedSDK] addFriendWithTarget:target_remarks:user_remarks:complete:]"
  description: 添加好友
  parameters:
    - name: target
      type: NSString *
      required: true
      description: 对方 OpenID
    - name: target_remarks
      type: NSString *
      required: false
      description: 用户给对方设置的备注（最长 512 字符）
    - name: user_remarks
      type: NSString *
      required: false
      description: 对方给用户设置的备注（最长 512 字符）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 回调
  code_objc: |
    // ========== 瑞雪 SDK 添加好友 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *targetOpenId = @"target_user_openid";  // 必填，对方 OpenID，类型 NSString *
    NSString *remarks = @"我的好友";                  // 可选，备注，类型 NSString *
    
    [[RXSDK sharedSDK] addFriendWithTarget:targetOpenId
                            target_remarks:remarks
                              user_remarks:nil
                                  complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"好友添加失败: %@", error.responesObject);
            // 常见错误：对方已是好友、对方不存在
        } else {
            NSLog(@"好友添加成功: %@", response);
            // TODO: 更新好友列表 UI
        }
    }];

# ==================== 删除好友 ====================
deleteFriend:
  method_name: "[[RXSDK sharedSDK] deleteFriendWithTarget:complete:]"
  description: 删除好友
  parameters:
    - name: target
      type: NSString *
      required: true
      description: 对方 OpenID
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 回调
  code_objc: |
    // ========== 瑞雪 SDK 删除好友 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *targetOpenId = @"target_user_openid";  // 必填，对方 OpenID，类型 NSString *
    
    [[RXSDK sharedSDK] deleteFriendWithTarget:targetOpenId
                                     complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"好友删除失败: %@", error.responesObject);
        } else {
            NSLog(@"好友删除成功");
            // TODO: 从好友列表中移除该好友
        }
    }];

# ==================== 更新好友备注 ====================
updateFriendRemark:
  method_name: "[[RXSDK sharedSDK] updateFriendRemarkWithTarget:target_remarks:complete:]"
  description: 更新好友备注
  parameters:
    - name: target
      type: NSString *
      required: true
      description: 对方 OpenID
    - name: target_remarks
      type: NSString *
      required: true
      description: 备注信息（最长 512 字符）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 回调
  code_objc: |
    // ========== 瑞雪 SDK 更新好友备注 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *targetOpenId = @"target_user_openid";  // 必填，对方 OpenID，类型 NSString *
    NSString *remarks = @"新备注名称";                 // 必填，新备注，类型 NSString *
    
    [[RXSDK sharedSDK] updateFriendRemarkWithTarget:targetOpenId
                                     target_remarks:remarks
                                           complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"备注更新失败: %@", error.responesObject);
        } else {
            NSLog(@"备注更新成功");
        }
    }];

# ==================== 判断是否为好友 ====================
isFriend:
  method_name: "[[RXSDK sharedSDK] requestIsFriendWithTarget:complete:]"
  description: 判断两用户是否为好友
  parameters:
    - name: target
      type: NSString *
      required: true
      description: 对方 OpenID
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 回调
  code_objc: |
    // ========== 瑞雪 SDK 判断是否为好友 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *targetOpenId = @"target_user_openid";  // 必填，对方 OpenID，类型 NSString *
    
    [[RXSDK sharedSDK] requestIsFriendWithTarget:targetOpenId
                                        complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"查询失败: %@", error.responesObject);
        } else {
            NSDictionary *data = response[@"data"];  // 类型 NSDictionary *
            BOOL isFriend = [data[@"is_friend"] boolValue];  // 类型 BOOL
            NSLog(@"是否为好友: %@", isFriend ? @"是" : @"否");
            // TODO: 根据结果更新 UI（如显示"添加好友"或"发送消息"按钮）
        }
    }];

# ==================== 获取好友列表 ====================
getFriendList:
  method_name: "[[RXSDK sharedSDK] getFriendListWithComplete:]"
  description: 获取好友列表
  parameters:
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 回调
  code_objc: |
    // ========== 瑞雪 SDK 获取好友列表 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    [[RXSDK sharedSDK] getFriendListWithComplete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取好友列表失败: %@", error.responesObject);
        } else {
            NSArray *friends = response[@"data"];  // 类型 NSArray *
            NSLog(@"好友列表: %@", friends);
            
            // 解析好友列表
            for (NSDictionary *friend in friends) {
                NSString *openid = friend[@"openid"];      // 类型 NSString *
                NSString *nickname = friend[@"nickname"];  // 类型 NSString *
                NSString *avatar = friend[@"avatar"];      // 类型 NSString *
                NSString *remarks = friend[@"remarks"];    // 类型 NSString *
                NSLog(@"好友: %@ (%@)", nickname, remarks);
            }
            // TODO: 更新好友列表 UI
        }
    }];

# 导入语句
imports:
  - "#import <RXSDK_Pure/RXSDK_Pure.h>"

# 检查指南 (给 AI 的指令)
check_guide:
  - 检查 target 参数是否为有效的 OpenID
  - 建议在删除好友前显示确认对话框

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "添加好友"
    - "删除好友"
    - "好友列表"
    - "好友管理"
    - "判断好友"
  actions:
    - 根据用户需求选择对应的代码片段
    - 确保必要的 import 语句已添加
