# 瑞雪 SDK iOS 性能分析（GPM）组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: GPM（Game Performance Monitor）性能分析组件，用于游戏性能监控和分析
  note: |
    1. GPM 组件是可选组件，需要根据业务需求选择接入
    2. GPM 初始化必须在瑞雪 SDK 初始化之前执行
    3. 关键词：性能分析、gpm

# ==================== 组件信息 ====================
component:
  name: 性能分析（GPM）
  pod_name: RXGPMSDK
  service_class: RXGPMService
  singleton: sharedSDK
  import: "#import <RXGPMSDK/RXGPMService.h>"
  description: 游戏性能监控分析组件，提供 FPS、内存、CPU 等性能数据采集和分析

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== 性能分析（GPM）组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXGPMSDK'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 接入步骤 ====================
setup_steps:
  - step: 1
    title: 添加 Pod 依赖
    description: 在 Podfile 中添加 GPM 组件
    code: |
      # Podfile
      target 'YourApp' do
        use_frameworks!
        
        # 瑞雪 SDK 性能分析组件
        pod 'RXGPMSDK'
      end
  
  - step: 2
    title: 执行 Pod Install
    description: 在终端中执行 pod install
    code: |
      cd /path/to/your/project
      pod install
  
  - step: 3
    title: 初始化配置
    description: 在瑞雪 SDK 初始化之前调用 GPM 注册方法

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXGPMService sharedSDK] regist]"
  description: 注册性能分析组件
  parameters: []
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - 性能分析（GPM）接入 ==========
  #import <RXGPMSDK/RXGPMService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  #import <RXUIKit/RXUIKitService.h>  // 国内 UI 组件（或 RXOSUIKit 海外版）
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】注册性能分析组件
      [[RXGPMService sharedSDK] regist];
      
      // 2. 【必须在瑞雪 SDK 初始化之前】初始化 UI 组件
      [[RXUIKitService sharedSDK] regist];
      
      // 3. 创建瑞雪 SDK 初始化配置
      RXSdkInitConfig *config = [[RXSdkInitConfig alloc] init];
      config.cpId = @"YOUR_CP_ID";
      config.productId = @"YOUR_PRODUCT_ID";
      config.channelId = @"YOUR_CHANNEL_ID";
      config.baseUrlList = @[@"https://api.example.com/"];
      config.launchOptions = launchOptions;
      
      // 4. 初始化瑞雪 SDK
      [[RXSDK sharedSDK] initWithConfig:config complete:^(NSDictionary *response, RX_CommonRequestError *error) {
          if (error) {
              NSLog(@"SDK 初始化失败: %@", error.responesObject);
          } else {
              NSLog(@"SDK 初始化成功: %@", response);
          }
      }];
      
      return YES;
  }

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: GPM 初始化代码必须放在瑞雪 SDK 初始化之前
  - title: 调用时机
    content: 在 application:didFinishLaunchingWithOptions: 中尽早调用
  - title: 组件独立
    content: GPM 组件独立运行，无需额外配置参数
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
