# 瑞雪 SDK iOS 内购支付功能
# Generated by MCP
# 包含：IAP 支付、补单、商品信息查询

# ==================== IAP 支付 ====================
iap:
  method_name: "[[RXSDK sharedSDK] iap:complete:]"
  description: 内购支付
  parameters:
    - name: dict
      type: NSDictionary *
      required: true
      description: 订单参数字典
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK IAP 内购支付 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *tradeNo = @"订单号从服务端获取";    // 必填，订单号，类型 NSString *
    NSString *productId = @"com.game.product001"; // 必填，商品 ID，类型 NSString *
    NSString *currency = @"CNY";                   // 可选，币种，类型 NSString *
    
    NSDictionary *orderDict = @{
        @"trade_no": tradeNo,              // 必填，订单号，类型 NSString
        @"currency": currency,             // 币种，默认 CNY，类型 NSString
        @"goods_tag": productId,           // 商品标签，类型 NSString
        @"env": @(0),                      // 0 正式 1 沙盒，类型 NSNumber
        @"indulge_auth": @(0),             // 0 不验证防沉迷 1 验证，类型 NSNumber
        @"is_debug": @(0),                 // 0 正式订单 1 测试订单，类型 NSNumber
        @"notify_url": @"https://your-server.com/pay/notify",  // 发货回调地址，类型 NSString
        @"ext": @{                         // 扩展字段，类型 NSDictionary
            @"custom_field": @"自定义值"
        },
        @"transmit_args": @"透传参数"       // 可选，透传参数，类型 NSString
    };  // 类型 NSDictionary *
    
    [[RXSDK sharedSDK] iap:orderDict complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"支付失败: %@", error.responesObject);
        } else {
            NSInteger code = [response[@"code"] integerValue];  // 类型 NSInteger
            if (code == 0) {
                NSLog(@"支付成功: %@", response);
                // TODO: 处理支付成功逻辑
            } else {
                NSLog(@"支付业务失败: %@", response[@"msg"]);
            }
        }
    }];

# ==================== 检查补单 ====================
check_failed_order:
  method_name: "[[RXSDK sharedSDK] checkHasFailedOrder]"
  description: 检查是否需要补单
  code_objc: |
    // ========== 瑞雪 SDK 检查补单 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    BOOL needReFailOrder = [[RXSDK sharedSDK] checkHasFailedOrder];  // 类型 BOOL
    if (needReFailOrder) {
        NSLog(@"有需要补单的订单");
        // TODO: 调用补单接口
    }

# ==================== 补单 ====================
re_fail_order:
  method_name: "[[RXSDK sharedSDK] reFailOrderWithMaxCount:complete:]"
  description: 执行补单
  parameters:
    - name: maxCount
      type: NSInteger
      required: true
      description: 最大重试次数
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 补单 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSInteger maxCount = 5;  // 必填，最大重试次数，类型 NSInteger
    
    [[RXSDK sharedSDK] reFailOrderWithMaxCount:maxCount
                                      complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"补单失败: %@", error.responesObject);
        } else {
            NSLog(@"补单成功: %@", response);
        }
    }];

# ==================== 查询商品信息 ====================
get_product_info:
  method_name: "[[RXSDK sharedSDK] getProductInfoWithProductIdArr:complete:]"
  description: 查询 App Store 商品信息
  parameters:
    - name: productIdArr
      type: NSArray *
      required: true
      description: 商品 ID 数组
    - name: complete
      type: void(^)(NSArray<SKProduct *> *)
      required: true
      description: 结果回调（返回 SKProduct 数组）
  code_objc: |
    // ========== 瑞雪 SDK 查询商品信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    #import <StoreKit/StoreKit.h>
    
    NSArray *productIds = @[@"com.game.product001", @"com.game.product002"];  // 必填，商品 ID 数组，类型 NSArray *
    
    [[RXSDK sharedSDK] getProductInfoWithProductIdArr:productIds
                                             complete:^(NSArray<SKProduct *> *productInfoList) {  // 类型 NSArray<SKProduct *> *
        for (SKProduct *product in productInfoList) {
            NSString *productId = product.productIdentifier;  // 商品 ID，类型 NSString *
            NSString *title = product.localizedTitle;          // 商品标题，类型 NSString *
            NSDecimalNumber *price = product.price;            // 商品价格，类型 NSDecimalNumber *
            NSLog(@"商品: id=%@, title=%@, price=%@", productId, title, price);
        }
    }];

# ==================== 获取货币符号 ====================
get_locale_identifier:
  method_name: "[[RXSDK sharedSDK] getLocaleIdentifierWithProductId:timeout:complete:]"
  description: 获取地区货币符号
  parameters:
    - name: productId
      type: NSString *
      required: true
      description: 商品 ID
    - name: timeout
      type: NSInteger
      required: true
      description: 超时时间（秒）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取货币符号 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *productId = @"com.game.product001";  // 必填，商品 ID，类型 NSString *
    NSInteger timeout = 2;                          // 必填，超时时间（秒），类型 NSInteger
    
    [[RXSDK sharedSDK] getLocaleIdentifierWithProductId:productId
                                                timeout:timeout
                                               complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取货币符号失败: %@", error.responesObject);
        } else {
            NSString *symbol = response[@"data"][@"symbol"];  // 类型 NSString *
            NSLog(@"货币符号: %@", symbol);
        }
    }];

# ==================== 设置重复下单间隔 ====================
set_iap_interval:
  method_name: "[[RXSDK sharedSDK] setIAPInterval:]"
  description: 设置重复下单间隔
  parameters:
    - name: interval
      type: NSInteger
      required: true
      description: 间隔时间（秒）
  code_objc: |
    // ========== 瑞雪 SDK 设置下单间隔 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 注意：防止结果回调前重复下单导致订单验证错误
    
    NSInteger interval = 300;  // 间隔时间（秒），默认 300s，类型 NSInteger
    [[RXSDK sharedSDK] setIAPInterval:interval];

# ==================== 查询订单状态 ====================
trade_query:
  method_name: "[[RXSDK sharedSDK] tradeQueryWithOrderNo:complete:]"
  description: 查询订单状态
  parameters:
    - name: orderNo
      type: NSString *
      required: true
      description: 订单号
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 查询订单状态 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *orderNo = @"订单号";  // 必填，订单号，类型 NSString *
    
    [[RXSDK sharedSDK] tradeQueryWithOrderNo:orderNo
                                    complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"查询订单失败: %@", error.responesObject);
        } else {
            NSDictionary *data = response[@"data"];           // 类型 NSDictionary *
            NSInteger status = [data[@"status"] integerValue]; // 订单状态，类型 NSInteger
            NSLog(@"订单状态: %ld", (long)status);
        }
    }];

# ==================== 获取初始化保存的计费点 ====================
get_product_info_saved:
  method_name: "[[RXSDK sharedSDK] getProductInfo]"
  description: 获取初始化保存的计费点
  code_objc: |
    // ========== 瑞雪 SDK 获取保存的计费点 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSDictionary *productInfo = [[RXSDK sharedSDK] getProductInfo];  // 类型 NSDictionary *
    NSLog(@"保存的计费点信息: %@", productInfo);

# ==================== StoreKit2 查询未完成交易 ====================
sk2_unfinished_transactions:
  method_name: "[[RXSDK sharedSDK] sk2UnfinishUncompletedTransactionsWithOrderInfo:completeHandle:]"
  description: StoreKit2 查询未完成交易
  parameters:
    - name: orderInfo
      type: NSDictionary *
      required: true
      description: 订单信息
    - name: handle
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK StoreKit2 查询未完成交易 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 注意：需要 iOS 15+ 使用 StoreKit2
    
    NSDictionary *orderInfo = @{
        @"trade_no": @"订单号",              // 类型 NSString
        @"product_id": @"com.game.product001" // 类型 NSString
    };  // 类型 NSDictionary *
    
    [[RXSDK sharedSDK] sk2UnfinishUncompletedTransactionsWithOrderInfo:orderInfo
                                                        completeHandle:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"查询未完成交易失败: %@", error.responesObject);
        } else {
            NSLog(@"查询未完成交易成功: %@", response);
        }
    }];
