# 瑞雪 SDK iOS Instagram 组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: Instagram 登录和分享组件
  keywords:
    - Instagram
    - Instagram 登录
    - Instagram 分享
  note: |
    1. Instagram 组件是可选组件，需要根据业务需求选择接入
    2. 无需额外工程配置
    3. 组件初始化必须在瑞雪 SDK 初始化之前执行
    4. 需要用户提供 Client ID 和 Redirect URI

# ==================== 组件信息 ====================
component:
  name: Instagram
  pod_name: RXInstagramSDK
  service_class: RXInstagramService
  singleton: sharedSDK
  import: "#import <RXInstagramSDK/RXInstagramService.h>"
  description: Instagram 登录和分享组件

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== Instagram 组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXInstagramSDK'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXInstagramService sharedSDK] initWithClientID:redirectURI:]"
  description: 初始化 Instagram 组件
  parameters:
    - name: clientID
      type: NSString *
      required: true
      description: Instagram Client ID，从 Instagram/Meta 开发者后台获取
    - name: redirectURI
      type: NSString *
      required: true
      description: Instagram Redirect URI，在 Instagram/Meta 开发者后台配置
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - Instagram 接入 ==========
  #import <RXInstagramSDK/RXInstagramService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】初始化 Instagram
      [[RXInstagramService sharedSDK] initWithClientID:@"your_client_id"
                                           redirectURI:@"your_redirect_uri"];
      
      // 2. 初始化瑞雪 SDK...
      return YES;
  }

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: initWithClientID:redirectURI: 必须在瑞雪 SDK 初始化之前调用
  - title: Client ID
    content: 从 Instagram/Meta 开发者后台获取
  - title: Redirect URI
    content: 必须与 Instagram/Meta 开发者后台配置的 Redirect URI 一致
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
