# 瑞雪 SDK 法务 UI 功能
# Generated by MCP
# 包含：协议声明、隐私政策弹窗

# ==================== 协议声明弹窗 ====================
setProtocolViewWithKey:
  method_name: "[[RXUIKitService sharedSDK] setProtocolViewWithKey:keyList:]"
  description: 协议声明视图（全屏 H5 样式）
  parameters:
    - name: key
      type: NSString *
      required: true
      description: 默认展示的条款 key
    - name: keyList
      type: NSArray *
      required: true
      description: 要展示的协议列表
  code: |
    // ========== 瑞雪 SDK 协议声明弹窗 ==========
    // 注意：需要添加 pod 依赖 pod 'RXUIKit'
    
    #import <RXUIKit/RXUIKitService.h>
    
    // 要展示的协议 key 列表
    // 常用 key: @"00001" - 服务协议, @"00002" - 隐私政策
    NSArray *keyList = @[@"00001", @"00002"];
    NSString *defaultKey = @"00001";  // 默认展示服务协议
    
    [[RXUIKitService sharedSDK] setProtocolViewWithKey:defaultKey keyList:keyList];

# ==================== 隐私政策弹窗 ====================
userPrivacyPolicyWithComplete:
  method_name: "[[RXUIKitService sharedSDK] userPrivacyPolicyWithComplete:]"
  description: 隐私政策弹窗
  parameters:
    - name: complete
      type: void(^)(BOOL agree)
      required: true
      description: 点击回调（agree: 是否同意）
  code: |
    // ========== 瑞雪 SDK 隐私政策弹窗 ==========
    // 注意：需要添加 pod 依赖 pod 'RXUIKit'
    
    #import <RXUIKit/RXUIKitService.h>
    
    [[RXUIKitService sharedSDK] userPrivacyPolicyWithComplete:^(BOOL agree) {
        if (agree) {
            NSLog(@"用户同意隐私政策");
            // TODO: 处理同意逻辑
        } else {
            NSLog(@"用户拒绝隐私政策");
            // TODO: 处理拒绝逻辑
        }
    }];

# 常用协议 key
legal_keys:
  - name: "00001"
    description: 服务协议
  - name: "00002"
    description: 隐私政策
  - name: "00003"
    description: 儿童隐私政策

# 导入语句
imports:
  - "#import <RXUIKit/RXUIKitService.h>"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    pod_name: "RXUIKit"
    description: 法务 UI 需要添加此 pod 依赖

# AI 行为指南
check_guide: |
  插入法务 UI 代码前必须执行以下检查:
  1. 读取项目的 Podfile 文件
  2. 搜索是否存在 'RXUIKit' 依赖
  3. 如果不存在该依赖:
     - 【必须】自动添加依赖到 Podfile，无需询问用户
  4. 添加完依赖后，提示用户执行 pod install
  5. 继续插入法务 UI 代码

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "协议声明"
    - "隐私政策弹窗"
    - "法务弹窗"
  actions:
    - 检查是否有 RXUIKit 依赖
    - 如果没有，自动添加依赖
    - 插入对应的法务 UI 代码
