# 瑞雪 SDK 登录 UI 功能
# Generated by MCP
# 包含：登录弹窗 UI

# ==================== 登录弹窗 UI ====================
showLoginViewWithConfig:
  method_name: "[[RXUIKitService sharedSDK] showLoginViewWithConfig:complete:]"
  description: 显示登录弹窗 UI（国内版）
  parameters:
    - name: config
      type: RXLoginUIModel *
      required: true
      description: 登录 UI 配置
    - name: complete
      type: void(^)(NSDictionary *response, RX_CommonRequestError *error)
      required: true
      description: 登录回调
  return_type: BOOL
  return_description: 是否成功展示
  code: |
    // ========== 瑞雪 SDK 登录弹窗 UI ==========
    // 注意：需要添加 pod 依赖 pod 'RXUIKit'
    
    #import <RXUIKit/RXUIKitService.h>
    
    // 构造登录 UI 配置
    RXLoginUIModel *config = [[RXLoginUIModel alloc] init];
    // config.loginTypes = @[@"phone", @"wechat"];  // 可选，登录方式
    // config.logoImage = [UIImage imageNamed:@"logo"];  // 可选，Logo 图片
    
    // 显示登录弹窗
    [[RXUIKitService sharedSDK] showLoginViewWithConfig:config complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"登录失败: %@", error.responesObject[@"msg"]);
            // TODO: 处理登录失败逻辑
        } else {
            NSString *openid = response[@"data"][@"openid"];
            NSLog(@"登录成功: openid=%@", openid);
            // TODO: 处理登录成功逻辑
        }
    }];

# ==================== 关闭登录弹窗 ====================
closeLoginView:
  method_name: "[[RXUIKitService sharedSDK] closeLoginView]"
  description: 关闭登录弹窗
  code: |
    [[RXUIKitService sharedSDK] closeLoginView];

# RXLoginUIModel 配置参数
login_ui_config:
  class_name: RXLoginUIModel
  description: 登录 UI 配置对象
  fields:
    - name: loginTypes
      type: NSArray<NSString *> *
      required: false
      description: 登录方式列表，如 @[@"phone", @"wechat", @"apple"]
    - name: logoImage
      type: UIImage *
      required: false
      description: 自定义 Logo 图片
    - name: titleImage
      type: UIImage *
      required: false
      description: 标题图片

# 导入语句
imports:
  - "#import <RXUIKit/RXUIKitService.h>"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    pod_name: "RXUIKit"
    description: 登录 UI 需要添加此 pod 依赖

# AI 行为指南
check_guide: |
  插入登录 UI 代码前必须执行以下检查:
  1. 读取项目的 Podfile 文件
  2. 搜索是否存在 'RXUIKit' 依赖
  3. 如果不存在该依赖:
     - 【必须】自动添加依赖到 Podfile，无需询问用户
     - 依赖格式: pod 'RXUIKit'
  4. 添加完依赖后，提示用户执行 pod install
  5. 继续插入登录 UI 代码
  
  ⚠️ 重要：UI 模块依赖是必须的，不要询问用户，直接添加！

# AI 插入行为指南
insert_behavior:
  trigger_phrases:
    - "登录弹窗"
    - "登录 UI"
    - "显示登录界面"
  actions:
    - 检查是否有 RXUIKit 依赖
    - 如果没有，自动添加依赖
    - 插入登录 UI 代码
    - 确保必要的 import 语句已添加
