# 瑞雪 SDK 其他 UI 功能
# Generated by MCP
# 包含：邮件中心、绑定手机/邮箱 UI、公告 UI

# ==================== 邮件中心 ====================
showEmailViewWithCpUserId:
  method_name: "[[RXUIKitService sharedSDK] showEmailViewWithCpUserId:withComplete:]"
  description: 展示邮件中心
  parameters:
    - name: cpUserId
      type: NSString *
      required: true
      description: CP 方 userID
    - name: complete
      type: void(^)(NSDictionary *response, RX_CommonRequestError *error)
      required: true
      description: 结果回调
  code: |
    // ========== 瑞雪 SDK 展示邮件中心 ==========
    
    #import <RXUIKit/RXUIKitService.h>
    
    NSString *cpUserId = @"demo_user_001";  // 游戏用户 ID
    
    [[RXUIKitService sharedSDK] showEmailViewWithCpUserId:cpUserId withComplete:^(NSDictionary *response, RX_CommonRequestError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (error) {
                NSLog(@"邮件中心错误: %@", error.msg);
            } else {
                NSLog(@"邮件中心操作完成");
            }
        });
    }];

# ==================== 绑定手机 UI ====================
bindPhoneWithComplete:
  method_name: "[[RXUIKitService sharedSDK] bindPhoneWithComplete:]"
  description: 绑定手机 UI
  note: 如果已绑定手机会跳转到换绑页面
  parameters:
    - name: complete
      type: void(^)(NSDictionary *response, RX_CommonRequestError *error)
      required: true
      description: 绑定或换绑手机操作完成回调
  code: |
    // ========== 瑞雪 SDK 绑定手机 UI ==========
    // 注意：如果已绑定手机会跳转到换绑页面
    
    #import <RXUIKit/RXUIKitService.h>
    
    [[RXUIKitService sharedSDK] bindPhoneWithComplete:^(NSDictionary *response, RX_CommonRequestError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (error) {
                NSLog(@"绑定手机失败: %@", error.msg);
            } else {
                NSLog(@"绑定手机成功");
            }
        });
    }];

# ==================== 绑定邮箱 UI ====================
bindEmailWithComplete:
  method_name: "[[RXUIKitService sharedSDK] bindEmailWithComplete:]"
  description: 绑定邮箱 UI
  note: 如果已绑定邮箱会跳转到换绑页面
  parameters:
    - name: complete
      type: void(^)(NSDictionary *response, RX_CommonRequestError *error)
      required: true
      description: 绑定或换绑邮箱操作完成回调
  code: |
    // ========== 瑞雪 SDK 绑定邮箱 UI ==========
    // 注意：如果已绑定邮箱会跳转到换绑页面
    
    #import <RXUIKit/RXUIKitService.h>
    
    [[RXUIKitService sharedSDK] bindEmailWithComplete:^(NSDictionary *response, RX_CommonRequestError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (error) {
                NSLog(@"绑定邮箱失败: %@", error.msg);
            } else {
                NSLog(@"绑定邮箱成功");
            }
        });
    }];

# ==================== 展示公告 UI ====================
showAnnounceViewWithLimit:
  method_name: "[[RXUIKitService sharedSDK] showAnnounceViewWithLimit:linkCallBack:isHasCallBack:]"
  description: 展示公告 UI
  parameters:
    - name: limit
      type: int
      required: true
      description: 展示公告条数
    - name: linkCallBack
      type: void(^)(NSString *link)
      required: true
      description: 用户点击链接回调
    - name: ishasCallBack
      type: void(^)(BOOL isHas)
      required: true
      description: 是否有公告回调
  code: |
    // ========== 瑞雪 SDK 展示公告 UI ==========
    
    #import <RXUIKit/RXUIKitService.h>
    
    int limit = 10;  // 展示公告条数
    
    [[RXUIKitService sharedSDK] showAnnounceViewWithLimit:limit linkCallBack:^(NSString *link) {
        NSLog(@"用户点击链接: %@", link);
        // TODO: 处理链接跳转
    } isHasCallBack:^(BOOL isHas) {
        if (isHas) {
            NSLog(@"有公告展示");
        } else {
            NSLog(@"没有公告");
        }
    }];

# 导入语句
imports:
  - "#import <RXUIKit/RXUIKitService.h>"

# 依赖检查
dependency_check:
  ui_module:
    required: true
    pod_name: "RXUIKit"
    description: 其他 UI 功能需要添加此 pod 依赖
