# 瑞雪 SDK iOS 密码管理功能
# Generated by MCP
# 包含：修改密码、重置密码

# ==================== 修改密码 ====================
change_password:
  method_name: "[[RXSDK sharedSDK] changePasswordWithNewPwd:oldPwd:complete:]"
  description: 修改密码（需要知道旧密码）
  parameters:
    - name: newPwd
      type: NSString *
      required: true
      description: 新密码
    - name: oldPwd
      type: NSString *
      required: true
      description: 旧密码
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 修改密码 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *oldPwd = @"旧密码";   // 必填，旧密码，类型 NSString *
    NSString *newPwd = @"新密码";   // 必填，新密码，类型 NSString *
    
    [[RXSDK sharedSDK] changePasswordWithNewPwd:newPwd
                                         oldPwd:oldPwd
                                       complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"修改密码失败: %@", error.responesObject);
        } else {
            NSLog(@"修改密码成功: %@", response);
            // TODO: 提示用户重新登录
        }
    }];

# ==================== 重置密码 ====================
reset_password:
  method_name: "[[RXSDK sharedSDK] resetPasswordWithUsername:password:captchaCode:migrateArgs:complete:]"
  description: 重置密码（忘记密码，通过验证码重置）
  parameters:
    - name: username
      type: NSString *
      required: true
      description: 用户名/手机号/邮箱
    - name: password
      type: NSString *
      required: true
      description: 新密码
    - name: captchaCode
      type: NSString *
      required: true
      description: 验证码（purpose 为 resetpwd）
    - name: migrateArgs
      type: id
      required: false
      description: 账号迁移参数
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 重置密码 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *username = @"xxxxxx";     // 必填，用户名/手机号/邮箱，类型 NSString *
    NSString *newPassword = @"xxxxxx"; // 必填，新密码，类型 NSString *
    NSString *captchaCode = @"xxxxxx";       // 必填，验证码（purpose 为 resetpwd），类型 NSString *
    
    [[RXSDK sharedSDK] resetPasswordWithUsername:username
                                        password:newPassword
                                     captchaCode:captchaCode
                                     migrateArgs:nil  // 可选，账号迁移参数，类型 id
                                        complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"重置密码失败: %@", error.responesObject);
        } else {
            NSLog(@"重置密码成功: %@", response);
            // TODO: 跳转到登录页面
        }
    }];

# ==================== 设置密码强度 ====================
set_password_strength:
  method_name: "[[RXSDK sharedSDK] setPasswordStrength:]"
  description: 设置密码强度等级
  parameters:
    - name: type
      type: RXPasswordStrength
      required: true
      description: 密码强度等级枚举
  code_objc: |
    // ========== 瑞雪 SDK 设置密码强度 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // RXPasswordStrength 枚举值：
    //   - RXPasswordStrengthWeak: 弱
    //   - RXPasswordStrengthMedium: 中
    //   - RXPasswordStrengthStrong: 强
    //   - RXPasswordStrengthCustom: 自定义（需配合 setPwdPattern 使用）
    
    RXPasswordStrength strength = RXPasswordStrengthMedium;  // 密码强度等级，类型 RXPasswordStrength
    [[RXSDK sharedSDK] setPasswordStrength:strength];

# ==================== 设置密码正则 ====================
set_password_pattern:
  method_name: "[[RXSDK sharedSDK] setPwdPattern:]"
  description: 设置自定义密码正则表达式
  parameters:
    - name: pattern
      type: NSString *
      required: true
      description: 密码正则表达式
  code_objc: |
    // ========== 瑞雪 SDK 设置密码正则 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 注意：需要先将密码强度设置为自定义
    
    // 1. 先设置密码强度为自定义
    [[RXSDK sharedSDK] setPasswordStrength:RXPasswordStrengthCustom];
    
    // 2. 设置密码正则：至少8位，包含大小写字母和数字
    NSString *pattern = @"^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$";  // 密码正则表达式，类型 NSString *
    [[RXSDK sharedSDK] setPwdPattern:pattern];
