# 瑞雪 SDK iOS 用户通行证功能
# Generated by MCP
# 包含：登录、注册、登出、指定用户信息查询、用户信息管理
# 版本要求：RXSDK_Pure >= 4.0.4

# ==================== 接入前强制检查 ====================
preflight_check:
  must_do_before_insert_code: true
  description: 在生成 getUserInfoByFieldWithParams 业务代码前，必须先确认宿主工程已完成瑞雪 SDK 基础接入和版本要求。
  checks:
    - name: "检查 Podfile 基础依赖"
      target: "Podfile"
      required:
        RXSDK_Pure: ">= 4.0.4"
      failure_action: "如果缺少 RXSDK_Pure 或版本低于 4.0.4，先引导执行 ios feature=setup 或手动将 Podfile 中 RXSDK_Pure 升级到 4.0.4 后执行 pod install / pod update RXSDK_Pure。"
    - name: "检查 SDK 初始化代码"
      target: "AppDelegate / 初始化管理类"
      required:
        - "存在 RXSdkInitConfig 配置"
        - "存在 [[RXSDK sharedSDK] initWithConfig:complete:] 调用"
        - "cpId / productId / channelId / baseUrlList 已配置"
      failure_action: "如果未初始化，不要只插入 getUserInfoByFieldWithParams 调用；先生成并接入 ios feature=init 初始化代码。"
    - name: "检查调用时机"
      required:
        - "必须在 SDK 初始化成功后调用"
        - "AccessToken 调用场景需要用户已登录"
      failure_action: "若调用位置早于初始化或登录成功回调，先调整调用链。"
  agent_rule: |
    当用户要求“接入瑞雪查询用户绑定信息 / 查询绑定登录方式 / 获取实名信息”等 passport 能力时，
    先执行上述基础接入和版本检查；未满足时先补基础配置或升级依赖，再插入业务接口代码。

# ==================== RXLoginConfig 配置类 ====================
RXLoginConfig:
  description: API 登录配置类
  properties:
    # 必须参数
    - name: loginType
      type: LoginType
      required: true
      description: 登录类型枚举
    # 条件必须参数
    - name: username
      type: NSString *
      required: conditional
      description: 账号密码/验证码登录时必传
    - name: password
      type: NSString *
      required: conditional
      description: 账号密码登录时必传
    - name: captchaCode
      type: NSString *
      required: conditional
      description: 验证码登录时必传
    - name: permissions
      type: NSArray *
      required: conditional
      description: Facebook、Line 登录时必传
    # 可选参数
    - name: loginOpenId
      type: NSString *
      required: false
      description: 二次登录 openId
    - name: extDic
      type: NSMutableDictionary *
      required: false
      description: 扩展字段，断线重连时传 reconnect_login:YES
    - name: signFields
      type: NSArray *
      required: false
      description: 签名字段数组，如 @[@"nickname", @"avatar"]
    - name: migrateArgs
      type: id
      required: false
      description: 账号迁移参数

# LoginType 枚举值
LoginType:
  - LoginTypeVisitor    # 游客登录
  - LoginTypeAccount    # 账号密码登录
  - LoginTypeCapCode    # 验证码登录
  - LoginTypeApple      # 苹果登录
  - LoginTypeW          # 微信登录
  - LoginTypeGoogle     # Google 登录
  - LoginTypeFacebook   # Facebook 登录
  - LoginTypeLine       # Line 登录
  - LoginTypeAuth       # 一键登录
  - LoginTypeZalo       # Zalo 登录
  - LoginTypeTikTok     # TikTok 登录
  - LoginTypeSnapChat   # SnapChat 登录

# ==================== SDK 单例获取 ====================
sharedSDK:
  method_name: "[RXSDK sharedSDK]"
  description: 获取 SDK 单例实例
  code_objc: |
    // ========== 获取 SDK 单例实例 ==========
    RXSDK *sdk = [RXSDK sharedSDK];

# ==================== 登录（RXLoginConfig 配置） ====================
login_with_config:
  method_name: "[[RXSDK sharedSDK] loginWithConfig:complete:]"
  description: 使用 RXLoginConfig 配置对象登录（推荐方式）
  parameters:
    - name: config
      type: RXLoginConfig *
      required: true
      description: 登录配置对象
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 登录结果回调
  code_objc: |
    // ========== 瑞雪 SDK 用户登录（RXLoginConfig 配置） ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // ========== 游客登录示例 ==========
    RXLoginConfig *config = [[RXLoginConfig alloc] init];
    config.loginType = LoginTypeVisitor;  // 必填，登录类型
    
    [[RXSDK sharedSDK] loginWithConfig:config complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"登录失败: %@", error.responesObject);
        } else {
            NSLog(@"登录成功: %@", response);
            // TODO: 处理登录成功逻辑
        }
    }];
    
    // ========== 账号密码登录示例 ==========
    RXLoginConfig *accountConfig = [[RXLoginConfig alloc] init];
    accountConfig.loginType = LoginTypeAccount;  // 必填
    accountConfig.username = @"user@example.com";  // 必填
    accountConfig.password = @"password123";  // 必填
    // accountConfig.signFields = @[@"nickname", @"avatar"];  // 可选，签名字段
    // accountConfig.migrateArgs = @"migrate_data";  // 可选，账号迁移参数
    
    [[RXSDK sharedSDK] loginWithConfig:accountConfig complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"登录失败: %@", error.responesObject);
        } else {
            NSLog(@"登录成功: %@", response);
        }
    }];
    
    // ========== 验证码登录示例 ==========
    RXLoginConfig *captchaConfig = [[RXLoginConfig alloc] init];
    captchaConfig.loginType = LoginTypeCapCode;  // 必填
    captchaConfig.username = @"13800138000";  // 必填，手机号或邮箱
    captchaConfig.captchaCode = @"123456";  // 必填，验证码
    
    [[RXSDK sharedSDK] loginWithConfig:captchaConfig complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"登录失败: %@", error.responesObject);
        } else {
            NSLog(@"登录成功: %@", response);
        }
    }];
    
    // ========== Apple 登录示例 ==========
    RXLoginConfig *appleConfig = [[RXLoginConfig alloc] init];
    appleConfig.loginType = LoginTypeApple;  // 必填
    
    [[RXSDK sharedSDK] loginWithConfig:appleConfig complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"登录失败: %@", error.responesObject);
        } else {
            NSLog(@"Apple 登录成功: %@", response);
        }
    }];
    
    // ========== 二次登录示例（使用 loginOpenId） ==========
    RXLoginConfig *secondConfig = [[RXLoginConfig alloc] init];
    secondConfig.loginType = LoginTypeApple;  // 必填
    secondConfig.loginOpenId = @"上次登录返回的 login_openid";  // 必填
    
    [[RXSDK sharedSDK] loginWithConfig:secondConfig complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"二次登录失败: %@", error.responesObject);
        } else {
            NSLog(@"二次登录成功: %@", response);
        }
    }];

# ==================== 用户注册 ====================
register:
  method_name: "[[RXSDK sharedSDK] registerWithUsername:password:captchaCode:ext:complete:]"
  description: 用户注册
  parameters:
    - name: username
      type: NSString *
      required: true
      description: 用户名/手机号/邮箱
    - name: password
      type: NSString *
      required: true
      description: 密码
    - name: captchaCode
      type: NSString *
      required: false
      description: 验证码（手机或邮箱注册必须）
    - name: ext
      type: NSDictionary *
      required: false
      description: 扩展字段（nickname/avatarUrl/sex）
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 注册结果回调
  code_objc: |
    // ========== 瑞雪 SDK 用户注册 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // 前置条件：需要先调用 sendCaptcha 发送验证码（purpose: register）
    
    // ========== 手机号注册示例 ==========
    NSString *phone = @"xxxxxx";         // 必填，手机号
    NSString *password = @"xxxxxx";      // 必填，密码
    NSString *captchaCode = @"xxxxxx";   // 必填，验证码
    
    NSDictionary *ext = @{
        @"nickname": @"昵称",    // 可选
        @"avatarUrl": @"",       // 可选
        @"sex": @"1"             // 可选，1 男 0 女
    };
    
    [[RXSDK sharedSDK] registerWithUsername:phone
                                   password:password
                                captchaCode:captchaCode
                                        ext:ext
                                   complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"注册失败: %@", error.responesObject);
        } else {
            NSLog(@"注册成功: %@", response);
        }
    }];

# ==================== 获取指定用户信息 ====================
get_user_info_by_field:
  method_name: "[[RXSDK sharedSDK] getUserInfoByFieldWithParams:complete:]"
  api: "/v1/passport/user/info_by_field"
  request_method: "POST"
  min_version:
    RXSDK_Pure: "4.0.4"
  description: 按指定字段获取用户注册信息、登录信息、本次请求信息、防沉迷信息或账号凭证信息
  prompt_guidance: |
    当用户提出“获取用户信息、查询用户资料、查询实名信息、查询绑定信息、查询登录方式、查询防沉迷信息”等需求时，优先使用 getUserInfoByFieldWithParams:complete:。
    根据用户问题组合字段，不要固定只查默认字段：
    - 用户实名信息：使用 user 分组，字段通常为 real_auth_id、real_auth_name、real_auth_id_card、real_auth_time、real_auth_ip、real_auth_device_code、age、birthday、sex。
    - 用户基础资料：使用 user 分组，字段通常为 openid、cp_user_id、nickname、avatar、phone、email、flag、regtime。
    - 用户绑定信息 / 用户绑定的登录方式 / 查询用户绑定了哪些账号 / 接入瑞雪查询用户绑定信息：使用 account 分组；如果只问“绑定的登录方式”，参数必须是 account: ["method"]。
    - 当前登录凭证信息：使用 current_account 分组，字段通常为 method、username、user_id、add_time。
    - 上次登录信息：使用 login 分组，字段通常为 method、login_time、last_login_time、devicecode、login_ip。
    - 本次请求环境：使用 current 分组，字段通常为 product_id、channel_id、devicecode、ip、os、os_version。
    - 防沉迷信息：使用 aas 分组，字段通常为 limit、aas、flag、suitable_age、trip。
    - 用户可能要求任意组合，例如“实名信息 + 绑定登录方式”：传 user 的实名字段，同时传 account: ["method"]。
  parameters:
    - name: params
      type: NSDictionary *
      required: true
      description: 请求参数 map；user/login/current/aas/current_account/account 至少传一个字段分组，openid 与 cp_user_id 用于服务端签名调用时定位用户
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取指定用户信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSDictionary *params = @{
        // user/login/current/aas/current_account/account 六个分组均为可选，至少传一个
        @"user": @[@"openid", @"cp_user_id", @"nickname", @"avatar", @"phone", @"email", @"real_auth_name"],
        @"login": @[@"product_id", @"channel_id", @"login_time", @"last_login_time", @"method"],
        @"current": @[@"product_id", @"channel_id", @"devicecode", @"ip", @"os", @"os_version"],
        @"aas": @[@"flag", @"limit", @"aas", @"suitable_age", @"trip"],
        @"current_account": @[@"user_id", @"method", @"username", @"add_time"],
        @"account": @[@"user_id", @"method", @"username", @"add_time"],
        // Accesstoken 调用时无需传 openid/cp_user_id；服务端签名调用时二选一
        // @"openid": @"rxuxxxx",
        // @"cp_user_id": @"10001"
    };

    [[RXSDK sharedSDK] getUserInfoByFieldWithParams:params complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取指定用户信息失败: %@", error.responesObject);
        } else {
            NSDictionary *data = response[@"data"];
            NSDictionary *user = data[@"user"];
            NSDictionary *login = data[@"login"];
            NSDictionary *current = data[@"current"];
            NSDictionary *aas = data[@"aas"];
            NSDictionary *currentAccount = data[@"current_account"];
            NSArray *accounts = data[@"account"];

            NSLog(@"指定用户信息: user=%@, login=%@, current=%@, aas=%@, currentAccount=%@, accounts=%@",
                  user, login, current, aas, currentAccount, accounts);
        }
    }];

  supported_fields:
    user: [openid, cp_user_id, product_id, channel_id, custom, source, promoter, devicecode, subchannelid, platformid, attr, nickname, avatar, regtime, regip, birthday, age, sex, user_state, phone, email, flag, topinviter_platformid, topinviter_openid, topinviter_subchannelid, inviter_level, inviter_subchannelid, inviter_openid, inviter_platformid, realauthid, realauth_time, real_auth_id, real_auth_name, real_auth_id_card, real_auth_time, real_auth_ip, real_auth_device_code]
    login: [devicecode, product_id, channel_id, login_ip, login_time, last_login_time, method]
    current: [product_id, channel_id, devicecode, ip, os, os_version]
    aas: [flag, limit, aas, suitable_age, trip]
    account: [user_id, add_time, product_id, channel_id, username, method, devicecode]
  examples:
    real_auth_and_bound_methods:
      description: 获取用户实名信息和用户绑定的登录方式信息
      params_objc: |
        NSDictionary *params = @{
            @"user": @[@"real_auth_id", @"real_auth_name", @"real_auth_id_card", @"real_auth_time", @"age", @"sex"],
            @"account": @[@"method"]
        };
    bound_login_methods_only:
      description: 接入瑞雪查询用户绑定信息 / 查询用户绑定的登录方式
      params_objc: |
        NSDictionary *params = @{
            @"account": @[@"method"]
        };
    profile_and_current_request:
      description: 获取用户基础资料和本次请求环境
      params_objc: |
        NSDictionary *params = @{
            @"user": @[@"openid", @"nickname", @"avatar", @"phone", @"email"],
            @"current": @[@"ip", @"os", @"os_version"]
        };

# ==================== 更新用户信息 ====================
update_user_info:
  method_name: "[[RXSDK sharedSDK] updateUserInfo:nickname:sex:region:ext:complete:]"
  description: 修改用户信息
  parameters:
    - name: avatarUrl
      type: NSString *
      required: false
      description: 头像 URL
    - name: nickname
      type: NSString *
      required: false
      description: 用户昵称
    - name: sex
      type: NSString *
      required: false
      description: 性别（1 男 0 女）
    - name: region
      type: NSString *
      required: false
      description: 地区码
    - name: ext
      type: NSDictionary *
      required: false
      description: 扩展参数
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 更新用户信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *avatarUrl = @"https://example.com/avatar.png";  // 可选
    NSString *nickname = @"新昵称";  // 可选
    NSString *sex = @"1";  // 可选，1 男 0 女
    NSString *region = @"CN";  // 可选
    
    NSDictionary *ext = @{
        @"custom_field": @"自定义值"  // 可选
    };
    
    [[RXSDK sharedSDK] updateUserInfo:avatarUrl
                             nickname:nickname
                                  sex:sex
                               region:region
                                  ext:ext
                             complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"更新用户信息失败: %@", error.responesObject);
        } else {
            NSLog(@"更新用户信息成功: %@", response);
        }
    }];

# ==================== 获取 OpenID ====================
get_openid:
  method_name: "[[RXSDK sharedSDK] getOpenID]"
  description: 获取当前登录用户的 OpenID
  code_objc: |
    // ========== 瑞雪 SDK 获取 OpenID ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *openId = [[RXSDK sharedSDK] getOpenID];
    NSLog(@"当前 OpenID: %@", openId);

# ==================== Token 刷新 ====================
refresh_token:
  method_name: "[[RXSDK sharedSDK] refreshTokenWithComplete:]"
  description: 刷新登录 Token
  parameters:
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 刷新 Token ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    [[RXSDK sharedSDK] refreshTokenWithComplete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"Token 刷新失败: %@", error.responesObject);
            // Token 刷新失败，需要重新登录
        } else {
            NSLog(@"Token 刷新成功: %@", response);
        }
    }];

# ==================== 检查 login_openid 是否失效 ====================
check_login_openid:
  method_name: "[[RXSDK sharedSDK] loginOpenidExpireInvalid]"
  description: 检查 login_openid 是否失效
  code_objc: |
    // ========== 瑞雪 SDK 检查登录状态 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    BOOL isExpired = [[RXSDK sharedSDK] loginOpenidExpireInvalid];
    if (isExpired) {
        NSLog(@"login_openid 已失效，需要重新登录");
        // TODO: 跳转登录页面
    } else {
        NSLog(@"login_openid 有效");
    }

# ==================== 查询用户拥有的账号 ====================
search_has_accounts:
  method_name: "[[RXSDK sharedSDK] searchHasAccountsWithMethod:devicecode:states:complete:]"
  description: 查询用户拥有的账号
  parameters:
    - name: method
      type: NSString *
      required: true
      description: 登录方式，对应登录/绑定三方账号接口参数中的 method 字段
    - name: devicecode
      type: NSString *
      required: false
      description: 设备码，不传默认取当前设备码
    - name: states
      type: NSInteger
      required: true
      description: 账号状态位标记
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 查询用户拥有的账号 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSString *method = @"phone";     // 必填，登录方式
    NSString *devicecode = nil;      // 可选，传 nil 默认取当前设备码
    NSInteger states = 1;            // 必填，账号状态位标记

    [[RXSDK sharedSDK] searchHasAccountsWithMethod:method
                                        devicecode:devicecode
                                            states:states
                                          complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"查询账号失败: %@", error.responesObject);
        } else {
            NSLog(@"查询账号成功: %@", response);
        }
    }];

# ==================== 同步三方授权信息 ====================
sync_info:
  method_name: "[[RXSDK sharedSDK] syncInfoWithParams:complete:]"
  description: 同步三方授权信息
  parameters:
    - name: params
      type: NSDictionary *
      required: true
      description: 与登录 ext 结构相同的三方授权参数
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 同步三方授权信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSDictionary *params = @{
        @"method": @"wechat",
        @"openid": @"third_openid",
        @"access_token": @"third_access_token"
    };

    [[RXSDK sharedSDK] syncInfoWithParams:params complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"同步三方授权信息失败: %@", error.responesObject);
        } else {
            NSLog(@"同步三方授权信息成功: %@", response);
        }
    }];

# ==================== 法务信息获取 ====================
get_legal_info:
  method_name: "[[RXSDK sharedSDK] getLegalInfo:]"
  description: 获取法务配置信息（用户协议、隐私政策等）
  parameters:
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取法务信息 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    [[RXSDK sharedSDK] getLegalInfo:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取法务信息失败: %@", error.responesObject);
        } else {
            // 解析法务条款
            NSDictionary *data = response[@"data"];
            NSString *userAgreement = data[@"user_agreement"];  // 用户协议
            NSString *privacyPolicy = data[@"privacy_policy"];  // 隐私政策
            NSString *thirdPartySDK = data[@"third_party_sdk"];  // 第三方 SDK
            
            NSLog(@"法务信息: %@", data);
        }
    }];

# ==================== 自定义请求 ====================
custom_request:
  method_name: "[[RXSDK sharedSDK] createRequestWithUrl:header:body:method:needLogin:complete:]"
  description: 自定义网络请求
  parameters:
    - name: url
      type: NSString *
      required: true
      description: 接口地址（可传路径或完整 URL）
    - name: header
      type: NSMutableDictionary *
      required: false
      description: 请求头
    - name: body
      type: NSMutableDictionary *
      required: false
      description: 请求参数
    - name: method
      type: NSInteger
      required: true
      description: 请求类型（1 POST，2 GET）
    - name: needLogin
      type: BOOL
      required: true
      description: 是否需要登录态
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 自定义请求 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    // ========== 自定义 POST 请求 ==========
    NSString *url = @"/api/custom/endpoint";  // 必填
    NSInteger method = 1;  // 必填，1=POST 2=GET
    BOOL needLogin = YES;  // 必填
    
    NSMutableDictionary *header = [NSMutableDictionary dictionary];
    header[@"Custom-Header"] = @"value";
    
    NSMutableDictionary *body = [NSMutableDictionary dictionary];
    body[@"param1"] = @"value1";
    body[@"param2"] = @"value2";
    
    [[RXSDK sharedSDK] createRequestWithUrl:url
                                     header:header
                                       body:body
                                     method:method
                                  needLogin:needLogin
                                   complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"请求失败: %@", error.responesObject);
        } else {
            NSLog(@"请求成功: %@", response);
        }
    }];
