# 瑞雪 SDK iOS 实名认证功能
# Generated by MCP
# 包含：实名认证、支付宝 IIFAA 实名认证
#
# 接入前必须先询问用户:
# - 是否使用瑞雪实名认证 UI？
# - 使用：调用 ios feature=real_auth_ui 接入 RXUIKitService setRealauthViewWithCanClose / setRealauthViewWithComplete
# - 不使用：接入获取 IIFAA 支付宝授权跳转地址和查询 IIFAA 认证结果
#
# 版本要求:
# - IIFAA 支付宝实名认证需要 RXSDK_Pure 4.0.6 及以上
# - 使用瑞雪实名认证 UI 需要 RXUIKit 4.0.4 及以上
# - 如果当前 SDK 版本过低，MCP/Agent 应自动修改 Podfile 版本并执行 pod update

decision_prompt:
  question: "是否使用瑞雪实名认证 UI？"
  use_ruixue_ui: "使用瑞雪实名认证 UI 时，请调用 ios feature=real_auth_ui 接入 RXUIKit。"
  custom_ui: "不使用瑞雪实名认证 UI 时，请使用 iifaa_alipay_real_auth 示例。"

iifaa_config_notice:
  message: "请按照文档确认配置"
  document_url: "https://doc.ruixueyun.com/main/#/view?path=ba910252-aff4-440d-8f78-31f25d19c271"
  response_rule: "用户询问 IIFAA 配置文档时，只返回 document_url，不解析文档内容。"

# ==================== 实名认证 ====================
real_auth:
  method_name: "[[RXSDK sharedSDK] realAuthWithRealName:idCard:complete:]"
  description: 实名认证
  parameters:
    - name: realName
      type: NSString *
      required: true
      description: 真实姓名
    - name: idCard
      type: NSString *
      required: true
      description: 身份证号码
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 实名认证 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>
    
    NSString *realName = @"xxxxxx";            // 必填，真实姓名，类型 NSString *
        NSString *idCard = @"xxxxxx";              // 必填，身份证号码，类型 NSString *
    
    [[RXSDK sharedSDK] realAuthWithRealName:realName
                                     idCard:idCard
                                   complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"实名认证失败: %@", error.responesObject);
        } else {
            // 解析认证结果
            NSDictionary *data = response[@"data"];          // 类型 NSDictionary *
            NSInteger age = [data[@"age"] integerValue];     // 年龄，类型 NSInteger
            BOOL isAdult = age >= 18;                        // 是否成年，类型 BOOL
            
            NSLog(@"实名认证成功: 年龄=%ld, 是否成年=%@", (long)age, isAdult ? @"是" : @"否");
            
            if (!isAdult) {
                // TODO: 处理未成年人防沉迷逻辑
            }
        }
    }];

# ==================== 实名认证（快速认证） ====================
real_auth_fast:
  method_name: "[[RXSDK sharedSDK] realAuthWithRealName:idCard:isFastAuth:complete:]"
  description: 实名认证，可选择快速认证
  parameters:
    - name: realName
      type: NSString *
      required: true
      description: 真实姓名
    - name: idCard
      type: NSString *
      required: true
      description: 身份证号码
    - name: isFastAuth
      type: BOOL
      required: true
      description: YES 快速认证，NO 普通认证
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 快速实名认证 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSString *realName = @"xxxxxx";  // 必填，真实姓名
    NSString *idCard = @"xxxxxx";    // 必填，身份证号码
    BOOL isFastAuth = YES;           // YES 快速认证，NO 普通认证

    [[RXSDK sharedSDK] realAuthWithRealName:realName
                                     idCard:idCard
                                 isFastAuth:isFastAuth
                                   complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"实名认证失败: %@", error.responesObject);
        } else {
            NSLog(@"实名认证成功: %@", response);
        }
    }];

# ==================== IIFAA 授权跳转地址 ====================
iifaa_redirect_url:
  method_name: "[[RXSDK sharedSDK] getIIFAARedirectURLWithAppName:thirdPartSchema:complete:]"
  description: 获取 IIFAA 支付宝授权跳转地址（快速实名）
  min_versions:
    RXSDK_Pure: "4.0.3"
  parameters:
    - name: appName
      type: NSString *
      required: true
      description: 应用名称
    - name: thirdPartSchema
      type: NSString *
      required: true
      description: 第三方回调 Schema
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 获取 IIFAA 授权跳转地址 ==========
    #import <RXSDK_Pure/RXSDK_Pure.h>

    NSString *appName = @"游戏名称";              // 必填，应用名称
    NSString *schema = @"yourapp://iifaa";       // 必填，第三方回调 Schema

    [[RXSDK sharedSDK] getIIFAARedirectURLWithAppName:appName
                                      thirdPartSchema:schema
                                             complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"获取 IIFAA 授权地址失败: %@", error.responesObject);
        } else {
            NSString *redirectURL = response[@"data"][@"url"];
            NSLog(@"IIFAA 授权地址: %@", redirectURL);
            // TODO: 使用 UIApplication 打开授权地址
        }
    }];

# ==================== IIFAA 认证结果查询 ====================
iifaa_result:
  method_name: "[[RXSDK sharedSDK] getIIFAAResultWithSource:retryCount:complete:]"
  description: 查询 IIFAA 快速认证结果
  min_versions:
    RXSDK_Pure: "4.0.6"
  parameters:
    - name: source
      type: NSString
      required: false
      description: 业务场景，deregister 表示注销场景，传空表示正常认证逻辑
    - name: retryCount
      type: NSInteger
      required: false
      description: 310039 错误重试次数，传 0 不重试；不传时默认重试 3 次
    - name: complete
      type: RXSDKRequestComplete
      required: true
      description: 结果回调
  code_objc: |
    // ========== 瑞雪 SDK 查询 IIFAA 认证结果 ==========
    // 版本要求：RXSDK_Pure >= 4.0.6
    #import <RXSDK_Pure/RXSDK_Pure.h>

    // source 传 deregister 表示注销场景，传空字符串表示正常认证逻辑
    [[RXSDK sharedSDK] getIIFAAResultWithSource:@"" retryCount:3 complete:^(NSDictionary *response, RX_CommonRequestError *error) {
        if (error) {
            NSLog(@"IIFAA 认证结果查询失败: %@", error.responesObject);
        } else {
            NSLog(@"IIFAA 认证结果: %@", response);
        }
    }];

# ==================== IIFAA 支付宝实名认证完整流程（自定义 UI） ====================
iifaa_alipay_real_auth:
  method_name: "[[RXSDK sharedSDK] getIIFAARedirectURLWithAppName:thirdPartSchema:complete:] + getIIFAAResultWithSource:retryCount:complete:"
  description: 获取 IIFAA 支付宝授权跳转地址并在 App 回到前台后查询认证结果
  min_versions:
    RXSDK_Pure: "4.0.6"
    RXUIKit: "4.0.4"
  code_objc: |
    // ========== 瑞雪 SDK IIFAA 支付宝实名认证 ==========
    // 版本要求：
    // - RXSDK_Pure >= 4.0.6
    // - 使用瑞雪实名认证 UI 时 RXUIKit >= 4.0.4
    // - SDK 版本过低时请自动修改 Podfile 并执行 pod update
    //
    // 关键要求：
    // 1. 获取授权地址后读取 data["url"] 并通过 scheme 跳转
    // 2. retryCount 固定传 3
    // 3. 监听 App 进入前台时查询认证结果
    // 4. 必须用 isIifaaRealAuthInProgress 标记，只在实名流程中回到前台才查询
    #import <RXSDK_Pure/RXSDK_Pure.h>
    #import <UIKit/UIKit.h>
    
    @interface IifaaRealAuthHandler : NSObject
    @property (nonatomic, assign) BOOL isIifaaRealAuthInProgress;
    @end
    
    @implementation IifaaRealAuthHandler
    
    - (instancetype)init {
        self = [super init];
        if (self) {
            [[NSNotificationCenter defaultCenter] addObserver:self
                                                     selector:@selector(applicationDidBecomeActive)
                                                         name:UIApplicationDidBecomeActiveNotification
                                                       object:nil];
        }
        return self;
    }
    
    - (void)startIifaaRealAuth {
        NSString *appName = @"游戏名称";
        NSString *scheme = @"yourapp://iifaa"; // 与 URL Scheme / 后台配置保持一致
        [[RXSDK sharedSDK] getIIFAARedirectURLWithAppName:appName
                                          thirdPartSchema:scheme
                                                 complete:^(NSDictionary *response, RX_CommonRequestError *error) {
            if (error) {
                NSLog(@"获取 IIFAA 授权地址失败: %@", error.responesObject);
                return;
            }
            
            NSString *url = response[@"data"][@"url"];
            if (![url isKindOfClass:[NSString class]] || url.length <= 0) {
                NSLog(@"IIFAA 授权地址为空: %@", response);
                return;
            }
            
            self.isIifaaRealAuthInProgress = YES;
            NSURL *openURL = [NSURL URLWithString:url];
            if (@available(iOS 10.0, *)) {
                [[UIApplication sharedApplication] openURL:openURL options:@{} completionHandler:nil];
            } else {
                [[UIApplication sharedApplication] openURL:openURL];
            }
        }];
    }
    
    - (void)applicationDidBecomeActive {
        if (!self.isIifaaRealAuthInProgress) {
            return;
        }
        [self queryIifaaResult];
    }
    
    - (void)queryIifaaResult {
        // source 传 deregister 表示注销场景，传空字符串表示正常认证逻辑
        [[RXSDK sharedSDK] getIIFAAResultWithSource:@"" retryCount:3 complete:^(NSDictionary *response, RX_CommonRequestError *error) {
            if (error) {
                NSLog(@"IIFAA 认证结果查询失败: %@", error.responesObject);
            } else {
                self.isIifaaRealAuthInProgress = NO;
                NSLog(@"IIFAA 认证成功: %@", response);
            }
        }];
    }
    
    @end
