# 瑞雪 SDK iOS Reddit 组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: Reddit 登录组件
  keywords:
    - reddit
    - reddit 登录
  note: |
    1. Reddit 组件是可选组件，需要根据业务需求选择接入
    2. 无需额外工程配置
    3. 组件初始化必须在瑞雪 SDK 初始化之前执行
    4. 需要用户提供 Client ID 和 Redirect URI

# ==================== 组件信息 ====================
component:
  name: Reddit
  pod_name: RXRedditKit
  service_class: RXRedditService
  singleton: sharedSDK
  import: "#import <RXRedditKit/RXRedditService.h>"
  description: Reddit 登录组件

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== Reddit 组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXRedditKit'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXRedditService sharedSDK] initWithClientID:redirectURI:]"
  description: 初始化 Reddit 组件
  parameters:
    - name: clientID
      type: NSString *
      required: true
      description: Reddit Client ID，从 Reddit 开发者后台获取
    - name: redirectURI
      type: NSString *
      required: true
      description: Reddit Redirect URI，在 Reddit 开发者后台配置
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - Reddit 接入 ==========
  #import <RXRedditKit/RXRedditService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】初始化 Reddit
      [[RXRedditService sharedSDK] initWithClientID:@"your_client_id"
                                        redirectURI:@"your_redirect_uri"];
      
      // 2. 初始化瑞雪 SDK...
      return YES;
  }

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: initWithClientID:redirectURI: 必须在瑞雪 SDK 初始化之前调用
  - title: Client ID
    content: 从 Reddit 开发者后台获取
  - title: Redirect URI
    content: 必须与 Reddit 开发者后台配置的 Redirect URI 一致
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
