# 瑞雪 SDK iOS 自动化接入步骤
# Generated by ruixue-sdk-mcp

platform: ios

# AI Agent 执行指南
agent_guide: |
  【iOS SDK 自动化接入流程】
  
  请严格按以下步骤执行，每个步骤都必须完成：
  
  步骤 1: 检测 Podfile
  - 检查项目根目录是否存在 Podfile 文件
  - 如果存在 → 跳到步骤 3
  - 如果不存在 → 执行步骤 2
  
  步骤 2: 创建 Podfile
  - 在项目根目录创建 Podfile 文件
  - 使用 podfile_example 中的内容
  - 提醒用户修改 'YourAppTarget' 为实际的 target 名称
  
  步骤 3: 检查是否已有 SDK
  - 读取 Podfile 内容，检查是否包含 'RXSDK_Pure'
  - 如果已包含 → 提示用户已集成
  - 如果未包含 → 执行步骤 4
  
  步骤 4: 添加 SDK 依赖
  - 在 Podfile 的 target 块中添加: pod 'RXSDK_Pure'
  
  步骤 5: 执行 pod install【必须执行】
  - 在项目目录执行命令: pod install
  - 如果失败，尝试: pod install --repo-update
  
  步骤 6: 完成提示
  - 告知用户使用 .xcworkspace 打开项目

# 给用户的提示信息
user_message: |
  即将为您的 iOS 项目接入瑞雪 SDK。
  接入过程需要执行以下操作：
  1. 检测/创建 Podfile
  2. 添加 SDK 依赖配置
  3. 执行 pod install
  
  完成后请使用 .xcworkspace 文件打开项目。

# 执行步骤
steps:
  - id: check_podfile
    type: check_file
    description: 检测 Podfile 是否存在
    target: "{{.WorkspacePath}}/Podfile"
    required: true
    onSuccess: check_existing_sdk
    onFailure: create_podfile
    note: 检查项目是否已使用 CocoaPods 管理依赖

  - id: create_podfile
    type: create_file
    description: 创建 Podfile 文件
    target: "{{.WorkspacePath}}/Podfile"
    content: |
      platform :ios, '12.0'
      source 'https://github.com/CocoaPods/Specs.git'
      
      target 'YourAppTarget' do
        use_frameworks!
        # 瑞雪 SDK 核心库
        pod 'RXSDK_Pure'
        
      end
    required: true
    onSuccess: remind_edit_target
    note: 创建包含瑞雪 SDK 依赖的 Podfile

  - id: remind_edit_target
    type: user_input
    description: 提醒修改 target 名称
    content: |
      已创建 Podfile，请将 'YourAppTarget' 修改为您的实际 target 名称。
      target 名称可以在 Xcode 项目中查看。
      修改完成后，将执行 pod install。
    required: true
    onSuccess: pod_install
    note: 用户需要确认 target 名称正确

  - id: check_existing_sdk
    type: check_file
    description: 检查是否已集成瑞雪 SDK
    target: "{{.WorkspacePath}}/Podfile"
    condition: 文件内容包含 RXSDK_Pure
    required: true
    onSuccess: already_integrated
    onFailure: edit_podfile
    note: 避免重复添加依赖

  - id: already_integrated
    type: user_input
    description: 检测到已集成瑞雪 SDK
    content: |
      项目中已存在瑞雪 SDK 依赖 (RXSDK_Pure)。
      如需重新安装，请执行: pod install --repo-update
    required: false
    note: 提示用户已有 SDK，避免重复操作

  - id: edit_podfile
    type: edit_file
    description: 添加瑞雪 SDK 依赖到 Podfile
    target: "{{.WorkspacePath}}/Podfile"
    insertAfter: "use_frameworks!"
    content: |
      # 瑞雪 SDK 核心库
      pod 'RXSDK_Pure'
    required: true
    onSuccess: pod_install
    note: 在 use_frameworks! 后添加 SDK 依赖

  - id: pod_install
    type: run_command
    description: 执行 pod install 安装依赖【必须执行】
    target: pod install
    workingDir: "{{.WorkspacePath}}"
    required: true
    onSuccess: setup_complete
    onFailure: pod_install_retry
    note: 【重要】必须执行此命令下载并安装 SDK

  - id: pod_install_retry
    type: run_command
    description: 重试安装（更新仓库索引）
    target: pod install --repo-update
    workingDir: "{{.WorkspacePath}}"
    required: true
    onSuccess: setup_complete
    note: 如果首次安装失败，尝试更新仓库索引后重新安装

  - id: setup_complete
    type: user_input
    description: SDK 依赖安装完成
    content: |
      瑞雪 SDK 依赖已成功安装！
      
      【重要】后续步骤：
      1. 关闭 .xcodeproj，使用 .xcworkspace 文件打开项目
      2. 在 AppDelegate 中添加 SDK 初始化代码
      
      提示：执行 ios_passport 可获取 SDK 初始化代码示例
    required: false
    note: 依赖安装完成后的提示信息

# Podfile 完整示例
podfile_example: |
  platform :ios, '12.0'
  source 'https://github.com/CocoaPods/Specs.git'
  
  target 'YourAppTarget' do
    use_frameworks!
    # 瑞雪 SDK 核心库
    pod 'RXSDK_Pure'
    
    # 其他依赖...
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
