# 银联综合支付（iOS）
# Generated by MCP

feature: unifypay
supported: false
platform: ios
message: "当前银联综合支付插件 rxsdk_unifypay 及 UPPaySdkWrapper 仅支持 Android；iOS 不生成伪接口。"
android_api: "UPPaySdkWrapper.getInstance().doPay(activity, payParams, callback)"
next_step: "请在 Android 端调用 android feature=unifypay，并传入 workspacePath 完成依赖与初始化检查。"
