# 瑞雪 SDK iOS Zalo 组件接入规范
# Generated by MCP

# ==================== 概述 ====================
overview:
  description: Zalo 登录和分享组件
  keywords:
    - zalo
    - zalo 登录
    - zalo 分享
  note: |
    1. Zalo 组件是可选组件，需要根据业务需求选择接入
    2. 需要在 Info.plist 中配置 LSApplicationQueriesSchemes 和 URL Types
    3. 组件初始化必须在瑞雪 SDK 初始化之前执行

# ==================== 组件信息 ====================
component:
  name: Zalo
  pod_name: RXZaloSDK
  service_class: RXZaloService
  singleton: sharedSDK
  import: "#import <RXZaloSDK/RXZaloService.h>"
  description: Zalo 登录和分享组件

# ==================== 工程配置 ====================
project_config:
  ls_application_queries_schemes:
    - zalosdk
    - zaloshareext
  url_types:
    - scheme: "zalo-{AppID}"
      required: true
      description: Zalo URL Scheme，格式为 zalo- + App ID

# ==================== Pod 依赖 ====================
pod_install: |
  # ========== Zalo 组件接入 ==========
  # 在 Podfile 中添加以下依赖：
  
  pod 'RXZaloSDK'
  
  # 然后执行：
  # cd 项目目录
  # pod install

# ==================== 初始化方法 ====================
init_method:
  method_name: "[[RXZaloService sharedSDK] initWithAppId:]"
  description: 初始化 Zalo 组件
  parameters:
    - name: appId
      type: NSString *
      required: true
      description: Zalo App ID（纯数字，不含 zalo- 前缀）
  note: 必须在瑞雪 SDK 初始化之前调用

# ==================== 代码示例 ====================
code_objc: |
  // ========== AppDelegate.m - Zalo 接入 ==========
  #import <RXZaloSDK/RXZaloService.h>
  #import <RXSDK_Pure/RXSDK_Pure.h>
  
  - (BOOL)application:(UIApplication *)application 
          didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      
      // 1. 【必须在瑞雪 SDK 初始化之前】初始化 Zalo
      [[RXZaloService sharedSDK] initWithAppId:@"your_zalo_appid"];
      
      // 2. 初始化瑞雪 SDK...
      return YES;
  }

# ==================== 注意事项 ====================
notes:
  - title: 初始化顺序
    content: initWithAppId 必须在瑞雪 SDK 初始化之前调用
  - title: App ID 格式
    content: initWithAppId 中使用纯数字 App ID，不含 zalo- 前缀
  - title: URL Types
    content: URL Types 中的 Scheme 需要 zalo- 前缀，格式为 zalo-{AppID}
  - title: LSApplicationQueriesSchemes
    content: 必须添加 zalosdk 和 zaloshareext
  - title: 依赖安装
    content: 添加 pod 依赖后必须执行 pod install 安装组件
