platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/aliyun/aliyun-specs.git'


##工作台名称
workspace 'RXSDK.xcworkspace'

def commonPods
    ##公共Pod项目
    use_frameworks!
    #pod 'RXNetworkingKit'
#    pod 'AFNetworking'
#    pod 'YYModel'
#    pod 'MBProgressHUD'
#    pod 'GoogleSignIn'
#    pod 'FBSDKLoginKit'
#    pod 'FBSDKShareKit'
#    pod 'RXAuthLoginKit'
#    pod 'RXAdjustSDK'
#    pod 'RXWXSDK'
#    pod 'RXASAKit'
    
    ##海外
#    pod 'Google-Mobile-Ads-Sdk'

end

##SDK
#target 'RXSDK' do
#    ##项目在工作台下的目录名称
#    project 'RXSDK.xcodeproj'
#
#    commonPods
#end

target 'RXSDK-Pure' do
    ##项目在工作台下的目录名称
    project 'RXSDK.xcodeproj'

    use_frameworks!
#    pod 'GZIP'
    #pod 'RXNetworkingKit'
#    pod 'AFNetworking'
#    pod 'YYModel'
#    pod 'MBProgressHUD'
pod 'RXLanguageKit'
#pod 'RXAliDNSSDK_official'
#pod 'SocketRocket'
#pod 'RXAdjustSDK'
#pod 'Adjust'
#pod 'AliyunOSSiOS'
#pod 'RXASAKit'
end


target 'RuiXueDemo' do
    ##项目在工作台下的目录名称
    project 'RuiXueDemo/RuiXueDemo.xcodeproj'
    
    use_frameworks!

#pod 'RXGDTSDK'
pod 'RXLBSKit'
#pod 'RXPublicToolKit'
pod 'WechatOpenSDK'
pod 'RXLanguageKit'
#pod 'RXAliDNSSDK_official'
#pod 'SocketRocket'
#pod  'BDASignalSDK'
#pod  'Protobuf'
#pod 'ZaloSDK'
#pod 'RXLineSDK'
#pod 'RXAdjustSDK'
#pod 'RXFirebaseSDK'
#pod 'FirebaseAnalytics'
#pod 'FirebaseMessaging'
#pod 'Adjust'
#pod 'RXAdjustSigSDK'
#pod 'RXAddressBookSDK'
#pod 'RXLineSDK_official'
#pod 'RXAppListSDK'
#pod 'FBSDKLoginKit', '17.0.0'
#pod 'FBSDKShareKit', '17.0.0'

#pod 'AliyunOSSiOS'
pod 'RXASAKit'
#pod 'RXLineSDK'
#pod 'RXFacebookSDK'
#pod 'AFNetworking'
#pod 'RXLineSDK'
#pod 'RXTecentCloudDNSSDK'
#pod 'RXAliCloudDNSSDK'
end



#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#          config.build_settings['OTHER_LDFLAGS'] = '-Wl,-weak-lswiftCoreGraphics'
#        end
#    end
#end
