platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'




workspace 'RXGoogleSDK.xcworkspace'

def commonPods

  use_frameworks!
  
  pod 'GoogleSignIn', '7.1.0'
#  pod 'GoogleAPIClientForREST/YouTube'
#  pod 'RXSDK_Pure'
#  pod 'RXFirebaseSDK'
  
end

target 'RXGoogleSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

  commonPods

end

target 'RXGoogleSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXGoogleSDKDemo/RXGoogleSDKDemo.xcodeproj'
    commonPods

end
