platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'


workspace 'RXGDTSDK.xcworkspace'

def commonPods
  
  use_frameworks!
  
  pod 'RXLanguageKit'
  pod 'WechatOpenSDK'
  pod 'RXAuthSDK_official'

end

target 'RXGDTSDK' do
  # Comment the next line if you don't want to use dynamic frameworks

  commonPods

end

target 'RXGDTSDKDemo' do
    ##项目在工作台下的目录名称
    project 'RXGDTSDKDemo/RXGDTSDKDemo.xcodeproj'
    commonPods

end
