platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'


workspace 'RXUIKit-OS.xcworkspace'

def commonPods
  
  use_frameworks!
  
#  pod 'MBOSProgressHUD'
#  pod 'WebViewJavascriptBridge'
#  pod 'GoogleSignIn', '7.1.0'
#  pod 'GoogleSignIn'
#  pod 'RXLineSDK_official'
#  pod 'FBSDKLoginKit', '14.1.0'
#  pod 'FBSDKShareKit', '14.1.0'
#  pod 'RXLanguageKit'
#  pod 'RXSDK_Pure'
#  pod 'GoogleAPIClientForREST/YouTube'
  
#  pod 'FBSDKCoreKit', '14.1.0'
#  pod 'FBSDKCoreKit_Basics', '14.1.0'
end

target 'RXUIKit-OS' do
  # Comment the next line if you don't want to use dynamic frameworks

  commonPods

end

target 'RXUIKit-OSDemo' do
    ##项目在工作台下的目录名称
    project 'RXUIKit-OSDemo/RXUIKit-OSDemo.xcodeproj'
    commonPods
#    pod 'RXZaloSDK'
#  pod 'RXTikTokSDK'
#pod 'TikTokOpenSDK', '~> 5.0.15'
#pod 'SnapSDK'
#pod 'SocketRocket'
#pod 'RXPublicToolKit'


#pod 'RXFirebaseSDK'
#
#pod 'TikTokOpenSDKCore'
#pod 'TikTokOpenAuthSDK'
#pod 'TikTokOpenShareSDK'
  pod 'GoogleSignIn', '7.1.0'
  pod 'GoogleSignIn'
#  pod 'RXLineSDK_official'
  pod 'FBSDKLoginKit', '17.0.0'
  pod 'FBSDKShareKit', '17.0.0'
  
#  pod 'FirebaseAnalytics', '10.24.0'
#  pod 'FirebaseMessaging', '10.24.0'
#  pod 'FirebaseAnalyticsOnDeviceConversion', '10.28.0'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
